const AUTH_BASE={production:"https://oauth2.quran.foundation",prelive:"https://prelive-oauth2.quran.foundation"};
const API_BASE={production:"https://apis.quran.foundation",prelive:"https://apis-prelive.quran.foundation"};
let tokenCache={token:null,expiresAt:0};
function env(){return process.env.QF_ENV==="prelive"?"prelive":"production"}
async function token(){const clientId=process.env.QF_CLIENT_ID,secret=process.env.QF_CLIENT_SECRET;if(!clientId||!secret)throw new Error("Quran Foundation credentials missing");if(tokenCache.token&&Date.now()<tokenCache.expiresAt-60000)return tokenCache.token;const basic=Buffer.from(`${clientId}:${secret}`).toString("base64");const r=await fetch(`${AUTH_BASE[env()]}/oauth2/token`,{method:"POST",headers:{Authorization:`Basic ${basic}`,"Content-Type":"application/x-www-form-urlencoded"},body:"grant_type=client_credentials&scope=content"});if(!r.ok)throw new Error(`QF token ${r.status}`);const x=await r.json();tokenCache={token:x.access_token,expiresAt:Date.now()+(Number(x.expires_in||3600)*1000)};return tokenCache.token}
export async function qfGet(path,search={}){const clientId=process.env.QF_CLIENT_ID;if(!clientId)throw new Error("Quran Foundation client id missing");const u=new URL(`${API_BASE[env()]}${path}`);Object.entries(search).forEach(([k,v])=>{if(v!==undefined&&v!==null&&v!=="")u.searchParams.set(k,String(v))});const access=await token();let r=await fetch(u,{headers:{"x-auth-token":access,"x-client-id":clientId}});if(r.status===401){tokenCache={token:null,expiresAt:0};const retry=await token();r=await fetch(u,{headers:{"x-auth-token":retry,"x-client-id":clientId}})}if(!r.ok)throw new Error(`QF content ${r.status}`);return r.json()}
export async function listHadithResources(){return qfGet("/content/api/v4/resources/hadiths")}
export async function listTafsirs(language="ar"){return qfGet("/content/api/v4/resources/tafsirs",{language})}
export async function tafsirByVerse(tafsirId,verseKey){return qfGet(`/content/api/v4/tafsirs/${tafsirId}`,{verse_key:verseKey,per_page:"all"})}
export async function versesByChapter(chapter,{translations,tafsirs}={}){return qfGet(`/content/api/v4/verses/by_chapter/${chapter}`,{translations,tafsirs,per_page:50})}
