import React,{useEffect,useMemo,useState} from "react";

const C={ivory:"#F6F3EC",ink:"#10100F",lapis:"#173B57",gold:"#B59A62",green:"#4F915C",red:"#A44D3C"};
const profile=()=>{try{return localStorage.getItem("sakinah-active-profile")||"me"}catch{return "me"}};
const read=(k,d)=>{try{const v=localStorage.getItem(k);return v==null?d:JSON.parse(v)}catch{return d}};
const write=(k,v)=>{try{localStorage.setItem(k,JSON.stringify(v))}catch{}};
const key=n=>`sakinah-${n}-${profile()}`;
const btn={border:"1px solid rgba(16,16,15,.09)",borderRadius:14,padding:11,background:"transparent",fontFamily:"inherit",color:"inherit"};
function Shell({lang,go,titleAr,titleEn,subAr,subEn,children,back="my-day"}){return <div style={{position:"absolute",inset:0,background:C.ivory,color:C.ink,display:"flex",flexDirection:"column"}}><div style={{padding:"22px 22px 0"}}><button onClick={()=>go(back)} style={{...btn,border:0,padding:0}}>{lang==="ar"?"← رجوع":"← Back"}</button></div><div style={{flex:1,overflowY:"auto",padding:"15px 22px 130px"}}><div style={{fontFamily:"Fraunces,serif",fontSize:29,lineHeight:1.25}}>{lang==="ar"?titleAr:titleEn}</div><div style={{fontSize:11.5,opacity:.48,lineHeight:1.75,marginTop:7}}>{lang==="ar"?subAr:subEn}</div>{children}</div></div>}
function Toggle({on,setOn,label}){return <button onClick={()=>setOn(!on)} style={{...btn,display:"flex",justifyContent:"space-between",alignItems:"center",width:"100%"}}><span>{label}</span><span style={{width:34,height:20,borderRadius:20,padding:2,background:on?C.green:"rgba(16,16,15,.12)",display:"flex",justifyContent:on?"flex-end":"flex-start"}}><i style={{width:16,height:16,borderRadius:"50%",background:"white"}}/></span></button>}
function Progress({value}){return <div style={{height:8,borderRadius:8,background:"rgba(16,16,15,.07)",overflow:"hidden"}}><div style={{height:"100%",width:`${Math.max(0,Math.min(100,value))}%`,background:C.gold}}/></div>}

export function MyDayCenter({lang,go}){
 const today=new Date();const date=today.toLocaleDateString(lang==="ar"?"ar-IQ":"en-GB",{weekday:"long",day:"numeric",month:"long"});
 const items=[["daily-reflection","تأمّل اليوم","Today's reflection","◌"],["smart-khatmah","ورد القرآن","Quran portion","◈"],["smart-quranic-adhkar","ذكر مناسب الآن","Remembrance now","✦"],["fasting-center","الصيام","Fasting","☾"],["jumuah-center","الجمعة","Jumu'ah","⌁"],["worship-times","أوقات العبادة","Worship times","◷"],["daily-tools","كل الأدوات اليومية","All daily tools","＋"]];
 const [done,setDone]=useState(()=>read(key("myday"),{}));const mark=id=>{const x={...done,[id]:!done[id]};setDone(x);write(key("myday"),x)};
 return <Shell lang={lang} go={go} back="app" titleAr="يومي مع سكينة" titleEn="My Day with Sakinah" subAr={date} subEn={date}><div style={{marginTop:18,borderRadius:25,padding:19,background:"linear-gradient(135deg,rgba(181,154,98,.18),rgba(255,255,255,.55))"}}><div style={{fontSize:10,opacity:.45}}>{lang==="ar"?"خطتك الهادئة لليوم":"A calm plan for today"}</div><div style={{fontFamily:"Fraunces,serif",fontSize:24,marginTop:6}}>{lang==="ar"?"خطوة صغيرة، كل يوم":"One small step, every day"}</div><div style={{marginTop:14}}><Progress value={(Object.values(done).filter(Boolean).length/Math.max(1,items.length-1))*100}/></div></div><div style={{marginTop:12}}>{items.map(([id,ar,en,icon])=><div key={id} style={{display:"grid",gridTemplateColumns:"42px 1fr auto",gap:10,alignItems:"center",padding:"12px 0",borderTop:"1px solid rgba(16,16,15,.07)"}}><button onClick={()=>mark(id)} style={{width:36,height:36,borderRadius:13,border:"1px solid rgba(16,16,15,.08)",background:done[id]?"rgba(79,145,92,.14)":"transparent",fontFamily:"inherit"}}>{done[id]?"✓":icon}</button><button onClick={()=>go(id)} style={{border:0,background:"transparent",fontFamily:"inherit",textAlign:lang==="ar"?"right":"left",color:"inherit",fontSize:13,fontWeight:650}}>{lang==="ar"?ar:en}</button><span style={{opacity:.28}}>›</span></div>)}</div></Shell>}

export function DailyToolsHub({lang,go}){const cards=[["islamic-calendar","التقويم الهجري","Islamic Calendar"],["fasting-center","الصيام","Fasting"],["ramadan-center","رمضان","Ramadan"],["smart-khatmah","الختمة الذكية","Smart Khatmah"],["memorization-center","الحفظ والمراجعة","Memorization"],["names-live","أسماء الله الحسنى","99 Names"],["hisn-center","حصن المسلم","Hisn al-Muslim"],["jumuah-center","يوم الجمعة","Jumu'ah"],["worship-times","أوقات العبادة","Worship Times"],["parental-controls","الرقابة الأبوية","Parental Controls"],["privacy-lock","قفل الخصوصية","Privacy Lock"],["card-maker","صانع البطاقات","Card Maker"]];return <Shell lang={lang} go={go} titleAr="أدوات سكينة اليومية" titleEn="Sakinah Daily Tools" subAr="إضافات عملية مرتبطة ببروفايل المستخدم" subEn="Practical tools tied to the active profile"><div style={{marginTop:16,display:"grid",gridTemplateColumns:"1fr 1fr",gap:9}}>{cards.map(([id,ar,en])=><button key={id} onClick={()=>go(id)} style={{...btn,minHeight:96,textAlign:lang==="ar"?"right":"left",background:"rgba(255,255,255,.42)"}}><div style={{fontSize:20,color:C.gold}}>◌</div><div style={{fontSize:12.5,fontWeight:650,marginTop:8}}>{lang==="ar"?ar:en}</div></button>)}</div></Shell>}

export function IslamicCalendar({lang,go}){const [now]=useState(new Date());let hijri="";try{hijri=new Intl.DateTimeFormat(lang==="ar"?"ar-SA-u-ca-islamic":"en-u-ca-islamic",{day:"numeric",month:"long",year:"numeric",weekday:"long"}).format(now)}catch{hijri=now.toDateString()}const events=lang==="ar"?["رمضان","ليلة القدر","عيد الفطر","يوم عرفة","عيد الأضحى","عاشوراء","الأيام البيض"]:["Ramadan","Laylat al-Qadr","Eid al-Fitr","Day of Arafah","Eid al-Adha","Ashura","White Days"];return <Shell lang={lang} go={go} titleAr="التقويم الهجري" titleEn="Islamic Calendar" subAr="عرض هجري من تقويم الجهاز مع المناسبات الرئيسية" subEn="Device Islamic calendar with key observances"><div style={{marginTop:20,padding:22,borderRadius:24,background:"rgba(181,154,98,.12)",textAlign:"center"}}><div style={{fontSize:12,opacity:.5}}>{lang==="ar"?"اليوم":"Today"}</div><div style={{fontFamily:"Fraunces,serif",fontSize:25,marginTop:8}}>{hijri}</div></div><div style={{marginTop:14}}>{events.map(x=><div key={x} style={{padding:"12px 2px",borderTop:"1px solid rgba(16,16,15,.07)",fontSize:12.5}}>{x}</div>)}</div><div style={{fontSize:9.8,opacity:.42,lineHeight:1.7,marginTop:14}}>{lang==="ar"?"قد يختلف بدء الشهر الهجري حسب رؤية الهلال والبلد؛ لذلك يبقى التقويم المحلي قابلاً للتصحيح لاحقاً.":"Hijri month starts can vary by local moon sighting; local correction can be added later."}</div></Shell>}

export function FastingCenter({lang,go}){const [cfg,setCfg]=useState(()=>read(key("fasting"),{mon:true,thu:true,white:true,owed:0,logged:0}));const save=x=>{setCfg(x);write(key("fasting"),x)};return <Shell lang={lang} go={go} titleAr="الصيام" titleEn="Fasting" subAr="تذكير وتتبع الصيام المستحب وقضاء رمضان" subEn="Track voluntary fasting and Ramadan make-up days"><div style={{marginTop:18,display:"grid",gap:8}}><Toggle on={cfg.mon} setOn={v=>save({...cfg,mon:v})} label={lang==="ar"?"تذكير الاثنين":"Monday reminder"}/><Toggle on={cfg.thu} setOn={v=>save({...cfg,thu:v})} label={lang==="ar"?"تذكير الخميس":"Thursday reminder"}/><Toggle on={cfg.white} setOn={v=>save({...cfg,white:v})} label={lang==="ar"?"الأيام البيض 13–15":"White Days 13–15"}/></div><div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:9,marginTop:15}}><div style={{...btn}}><small style={{opacity:.45}}>{lang==="ar"?"أيام القضاء":"Make-up days"}</small><input type="number" min="0" value={cfg.owed} onChange={e=>save({...cfg,owed:Number(e.target.value)||0})} style={{width:"100%",border:0,background:"transparent",fontSize:24,marginTop:5,fontFamily:"inherit"}}/></div><button onClick={()=>save({...cfg,logged:cfg.logged+1})} style={{...btn,background:"rgba(79,145,92,.10)"}}><small style={{opacity:.45}}>{lang==="ar"?"صمت اليوم":"Fasted today"}</small><div style={{fontSize:23,marginTop:5}}>{cfg.logged} ✓</div></button></div></Shell>}

export function RamadanCenter({lang,go}){const labels=lang==="ar"?["الصلاة في وقتها","ورد القرآن","أذكار الصباح والمساء","صدقة","قيام/تراويح","دعاء","صلة رحم"]:["Prayers on time","Quran portion","Morning/evening adhkar","Charity","Qiyam/Tarawih","Dua","Family ties"];const [done,setDone]=useState(()=>read(key("ramadan"),{}));const mark=i=>{const x={...done,[i]:!done[i]};setDone(x);write(key("ramadan"),x)};return <Shell lang={lang} go={go} titleAr="وضع رمضان" titleEn="Ramadan Mode" subAr="لوحة يومية هادئة لأهداف رمضان" subEn="A calm daily Ramadan goals board"><div style={{marginTop:18}}><Progress value={(Object.values(done).filter(Boolean).length/labels.length)*100}/></div><div style={{marginTop:12}}>{labels.map((x,i)=><button key={x} onClick={()=>mark(i)} style={{...btn,width:"100%",marginTop:7,textAlign:lang==="ar"?"right":"left",background:done[i]?"rgba(79,145,92,.10)":"transparent"}}>{done[i]?"✓ ":"○ "}{x}</button>)}</div></Shell>}

export function SmartKhatmah({lang,go}){const [days,setDays]=useState(()=>read(key("khatmah-days"),30));const [page,setPage]=useState(()=>read(key("khatmah-page"),1));const per=Math.max(1,Math.ceil((604-page+1)/Math.max(1,days)));const savePage=n=>{const v=Math.max(1,Math.min(604,n));setPage(v);write(key("khatmah-page"),v)};return <Shell lang={lang} go={go} titleAr="الختمة الذكية" titleEn="Smart Khatmah" subAr="قسّم ما تبقى من المصحف على المدة التي تختارها" subEn="Divide the remaining Mushaf across your chosen timeframe"><div style={{marginTop:18,padding:18,borderRadius:22,background:"rgba(181,154,98,.11)"}}><div style={{fontSize:10,opacity:.45}}>{lang==="ar"?"وردك المقترح يومياً":"Suggested daily portion"}</div><div style={{fontFamily:"Fraunces,serif",fontSize:28,marginTop:6}}>{per} {lang==="ar"?"صفحة":"pages"}</div><div style={{marginTop:12}}><Progress value={(page/604)*100}/></div></div><label style={{display:"block",marginTop:14,fontSize:11}}>{lang==="ar"?"مدة الختمة بالأيام":"Khatmah duration (days)"}<input type="number" min="1" value={days} onChange={e=>{const v=Math.max(1,Number(e.target.value)||1);setDays(v);write(key("khatmah-days"),v)}} style={{...btn,width:"100%",boxSizing:"border-box",marginTop:6}}/></label><label style={{display:"block",marginTop:10,fontSize:11}}>{lang==="ar"?"آخر صفحة وصلت إليها":"Last page reached"}<input type="number" min="1" max="604" value={page} onChange={e=>savePage(Number(e.target.value)||1)} style={{...btn,width:"100%",boxSizing:"border-box",marginTop:6}}/></label><button onClick={()=>savePage(page+per)} style={{...btn,width:"100%",marginTop:12,background:C.lapis,color:"white",border:0}}>{lang==="ar"?"أنهيت ورد اليوم":"Finished today's portion"}</button></Shell>}

export function MemorizationCenter({lang,go}){const [plan,setPlan]=useState(()=>read(key("memorization"),{surah:"",from:"",to:"",repeat:5,reviews:0}));const save=x=>{setPlan(x);write(key("memorization"),x)};return <Shell lang={lang} go={go} titleAr="الحفظ والمراجعة" titleEn="Memorization & Review" subAr="خطة بسيطة تحفظ موضعك وعدد مرات التكرار والمراجعة" subEn="A simple saved plan for repetition and review"><div style={{display:"grid",gap:9,marginTop:18}}><input value={plan.surah} onChange={e=>save({...plan,surah:e.target.value})} placeholder={lang==="ar"?"اسم السورة":"Surah name"} style={btn}/><div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:8}}><input value={plan.from} onChange={e=>save({...plan,from:e.target.value})} placeholder={lang==="ar"?"من آية":"From ayah"} style={btn}/><input value={plan.to} onChange={e=>save({...plan,to:e.target.value})} placeholder={lang==="ar"?"إلى آية":"To ayah"} style={btn}/></div><div style={{fontSize:11}}>{lang==="ar"?"التكرار":"Repeat"}</div><div style={{display:"flex",gap:7}}>{[3,5,7,10,20].map(n=><button key={n} onClick={()=>save({...plan,repeat:n})} style={{...btn,flex:1,background:plan.repeat===n?"rgba(181,154,98,.12)":"transparent"}}>{n}×</button>)}</div><button onClick={()=>save({...plan,reviews:plan.reviews+1})} style={{...btn,background:"rgba(79,145,92,.10)"}}>{lang==="ar"?`تمت مراجعة اليوم · ${plan.reviews}`:`Reviewed today · ${plan.reviews}`}</button></div></Shell>}

export function HisnCenter({lang,go}){const sections=lang==="ar"?["أذكار الصباح","أذكار المساء","النوم والاستيقاظ","المنزل","المسجد","السفر","الطعام والشراب","الكرب والحزن"]:["Morning","Evening","Sleep & waking","Home","Mosque","Travel","Food & drink","Distress & grief"];return <Shell lang={lang} go={go} titleAr="حصن المسلم" titleEn="Hisn al-Muslim" subAr="فهرس جاهز للربط بالنص الموثق الكامل؛ لا نعرض نصاً غير موثّق" subEn="A structured index ready for a verified full-text source; no unverified text is shown"><div style={{marginTop:16}}>{sections.map(x=><div key={x} style={{padding:"13px 2px",borderTop:"1px solid rgba(16,16,15,.07)",display:"flex",justifyContent:"space-between",fontSize:12.5}}><span>{x}</span><span style={{opacity:.3}}>›</span></div>)}</div></Shell>}

export function JumuahCenter({lang,go}){const tasks=lang==="ar"?["الاغتسال والتطيب","التبكير إلى الصلاة","سورة الكهف","الإكثار من الصلاة على النبي ﷺ","تحرّي ساعة الإجابة","الدعاء"]:["Ghusl and fragrance","Go early to prayer","Surah Al-Kahf","More salawat","Seek the response hour","Dua"];const [done,setDone]=useState(()=>read(key("jumuah"),{}));const mark=i=>{const x={...done,[i]:!done[i]};setDone(x);write(key("jumuah"),x)};return <Shell lang={lang} go={go} titleAr="يوم الجمعة" titleEn="Jumu'ah" subAr="قائمة تذكير شخصية لسنن وأعمال الجمعة" subEn="A personal Friday reminder checklist"><div style={{marginTop:16}}>{tasks.map((x,i)=><button key={x} onClick={()=>mark(i)} style={{...btn,width:"100%",marginTop:7,textAlign:lang==="ar"?"right":"left",background:done[i]?"rgba(79,145,92,.10)":"transparent"}}>{done[i]?"✓ ":"○ "}{x}</button>)}</div></Shell>}

export function WorshipTimes({lang,go}){const rows=lang==="ar"?[["الشروق","بعد انتهاء وقت الفجر"],["الضحى","بعد ارتفاع الشمس وقبل الزوال"],["أوقات النهي","تُعرض بدقة بعد ربط مواقيت الموقع"],["قيام الليل","من بعد العشاء إلى الفجر؛ والثلث الأخير يُحسب من الليل"]]:[["Sunrise","After Fajr time ends"],["Duha","After sunrise until before zenith"],["Prohibited times","Calculated precisely after location prayer-time binding"],["Night prayer","After Isha until Fajr; last third calculated from the night"]];return <Shell lang={lang} go={go} titleAr="أوقات العبادة" titleEn="Worship Times" subAr="مركز لأوقات الشروق والضحى وقيام الليل وأوقات النهي" subEn="Sunrise, Duha, night prayer and prohibited-time center"><div style={{marginTop:16}}>{rows.map(([a,b])=><div key={a} style={{padding:"13px 2px",borderTop:"1px solid rgba(16,16,15,.07)"}}><b style={{fontSize:12.5}}>{a}</b><div style={{fontSize:10.5,opacity:.48,marginTop:5}}>{b}</div></div>)}</div><button onClick={()=>go("app")} style={{...btn,width:"100%",marginTop:12,background:C.lapis,color:"white",border:0}}>{lang==="ar"?"فتح مواقيت الصلاة":"Open prayer times"}</button></Shell>}

export function ParentalControls({lang,go}){const [cfg,setCfg]=useState(()=>read(key("parental"),{minutes:60,quran:true,stories:true,quiz:true,nasheed:true,external:false}));const save=x=>{setCfg(x);write(key("parental"),x)};const rows=[["quran",lang==="ar"?"معلّم القرآن":"Quran teacher"],["stories",lang==="ar"?"القصص":"Stories"],["quiz",lang==="ar"?"المسابقات":"Quizzes"],["nasheed",lang==="ar"?"الأناشيد":"Nasheeds"],["external",lang==="ar"?"الروابط الخارجية":"External links"]];return <Shell lang={lang} go={go} titleAr="الرقابة الأبوية" titleEn="Parental Controls" subAr="إعدادات مستقلة لبروفايل الطفل" subEn="Per-child profile controls"><label style={{display:"block",marginTop:18,fontSize:11}}>{lang==="ar"?"وقت الاستخدام اليومي بالدقائق":"Daily usage minutes"}<input type="number" min="5" value={cfg.minutes} onChange={e=>save({...cfg,minutes:Math.max(5,Number(e.target.value)||5)})} style={{...btn,width:"100%",boxSizing:"border-box",marginTop:6}}/></label><div style={{display:"grid",gap:8,marginTop:13}}>{rows.map(([id,label])=><Toggle key={id} on={cfg[id]} setOn={v=>save({...cfg,[id]:v})} label={label}/>)}</div></Shell>}

async function hashPin(v){const b=new TextEncoder().encode(v);const h=await crypto.subtle.digest("SHA-256",b);return Array.from(new Uint8Array(h)).map(x=>x.toString(16).padStart(2,"0")).join("")}
export function PrivacyLock({lang,go}){const storage=key("privacy-pin");const [has,setHas]=useState(()=>!!localStorage.getItem(storage));const [pin,setPin]=useState("");const [msg,setMsg]=useState("");const save=async()=>{if(!/^\d{4,8}$/.test(pin)){setMsg(lang==="ar"?"اختر PIN من 4 إلى 8 أرقام":"Use a 4–8 digit PIN");return}localStorage.setItem(storage,await hashPin(pin));setHas(true);setPin("");setMsg(lang==="ar"?"تم تفعيل القفل":"Lock enabled")};const remove=async()=>{if(await hashPin(pin)===localStorage.getItem(storage)){localStorage.removeItem(storage);setHas(false);setPin("");setMsg(lang==="ar"?"تم إلغاء القفل":"Lock removed")}else setMsg(lang==="ar"?"PIN غير صحيح":"Incorrect PIN")};return <Shell lang={lang} go={go} titleAr="قفل الخصوصية" titleEn="Privacy Lock" subAr="قفل محلي للبروفايل؛ نخزن بصمة SHA-256 للـPIN وليس الرقم نفسه" subEn="Local profile lock; the PIN itself is not stored"><div style={{marginTop:18,padding:16,borderRadius:18,background:has?"rgba(79,145,92,.10)":"rgba(181,154,98,.10)"}}>{has?(lang==="ar"?"القفل مفعّل":"Lock enabled"):(lang==="ar"?"القفل غير مفعّل":"Lock disabled")}</div><input inputMode="numeric" type="password" value={pin} onChange={e=>setPin(e.target.value.replace(/\D/g,"").slice(0,8))} placeholder="PIN" style={{...btn,width:"100%",boxSizing:"border-box",marginTop:12,textAlign:"center",fontSize:20,letterSpacing:5}}/><button onClick={has?remove:save} style={{...btn,width:"100%",marginTop:9,background:C.lapis,color:"white",border:0}}>{has?(lang==="ar"?"إلغاء القفل":"Disable lock"):(lang==="ar"?"تفعيل القفل":"Enable lock")}</button>{msg&&<div style={{fontSize:10.5,color:C.gold,marginTop:10}}>{msg}</div>}</Shell>}

export function CardMaker({lang,go}){const [text,setText]=useState(lang==="ar"?"فَإِنَّ مَعَ الْعُسْرِ يُسْرًا":"Indeed, with hardship comes ease"),[size,setSize]=useState(28),[theme,setTheme]=useState(0);const themes=[["#F6F3EC","#173B57"],["#173B57","#F6F3EC"],["#F2E6D0","#10100F"]];const [bg,fg]=themes[theme];const download=()=>{const safe=text.replace(/[&<>]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;"}[c]));const svg=`<svg xmlns="http://www.w3.org/2000/svg" width="1080" height="1080"><rect width="100%" height="100%" fill="${bg}"/><text x="540" y="540" fill="${fg}" text-anchor="middle" dominant-baseline="middle" font-family="serif" font-size="${size*2}" direction="rtl">${safe}</text><text x="540" y="970" fill="${fg}" opacity=".45" text-anchor="middle" font-family="sans-serif" font-size="24">SAKINAH</text></svg>`;const u=URL.createObjectURL(new Blob([svg],{type:"image/svg+xml"}));const a=document.createElement("a");a.href=u;a.download="sakinah-card.svg";a.click();URL.revokeObjectURL(u)};return <Shell lang={lang} go={go} titleAr="صانع البطاقات الإسلامية" titleEn="Islamic Card Maker" subAr="معاينة مباشرة ثم حفظ بطاقة SVG عالية الدقة" subEn="Live preview and high-resolution SVG export"><div style={{marginTop:17,aspectRatio:"1",borderRadius:26,background:bg,color:fg,padding:28,display:"grid",placeItems:"center",textAlign:"center",boxShadow:"0 16px 40px rgba(0,0,0,.10)"}}><div style={{fontFamily:"'Noto Naskh Arabic','Amiri',serif",fontSize:size,lineHeight:1.8,direction:lang==="ar"?"rtl":"ltr"}}>{text}</div></div><textarea value={text} onChange={e=>setText(e.target.value)} style={{...btn,width:"100%",boxSizing:"border-box",minHeight:90,marginTop:12,resize:"vertical"}}/><label style={{display:"block",fontSize:10.5,marginTop:9}}>{lang==="ar"?"حجم الخط":"Font size"}<input type="range" min="18" max="48" value={size} onChange={e=>setSize(Number(e.target.value))} style={{width:"100%"}}/></label><div style={{display:"flex",gap:8,marginTop:9}}>{themes.map((t,i)=><button key={i} onClick={()=>setTheme(i)} style={{...btn,flex:1,background:t[0],color:t[1]}}>{i+1}</button>)}</div><button onClick={download} style={{...btn,width:"100%",marginTop:10,background:C.lapis,color:"white",border:0}}>{lang==="ar"?"حفظ البطاقة":"Save card"}</button></Shell>}
