import React,{useEffect,useMemo,useRef,useState} from "react";

const C={ivory:"#F6F3EC",ink:"#10100F",lapis:"#173B57",gold:"#B59A62",green:"#4F915C",red:"#A44D3C"};
const btn={border:"1px solid rgba(16,16,15,.09)",borderRadius:15,padding:11,background:"rgba(255,255,255,.48)",fontFamily:"inherit",color:"inherit"};
const read=(k,d)=>{try{return JSON.parse(localStorage.getItem(k)||JSON.stringify(d))}catch{return d}};
const write=(k,v)=>{try{localStorage.setItem(k,JSON.stringify(v))}catch{}};
const activeProfile=()=>{try{return localStorage.getItem("sakinah-active-profile")||"me"}catch{return "me"}};
const pkey=n=>`sakinah-${n}-${activeProfile()}`;
function Shell({lang,go,titleAr,titleEn,subAr,subEn,children}){return <div style={{position:"fixed",inset:0,zIndex:50000,background:C.ivory,color:C.ink,overflowY:"auto",padding:"25px 22px 130px"}} dir={lang==="ar"?"rtl":"ltr"}><button onClick={go} style={{...btn,border:0,padding:0,background:"transparent"}}>{lang==="ar"?"رجوع ←":"← Back"}</button><div style={{fontFamily:"Fraunces,serif",fontSize:31,marginTop:16}}>{lang==="ar"?titleAr:titleEn}</div><div style={{fontSize:11.5,opacity:.48,lineHeight:1.8,marginTop:6}}>{lang==="ar"?subAr:subEn}</div>{children}</div>}

export function UnifiedProfiles({lang,go}){
 const [profiles,setProfiles]=useState(()=>read("sakinah-profiles",[{id:"me",nameAr:"أنا",nameEn:"Me",kind:"adult",age:""}]));
 const [active,setActive]=useState(activeProfile());const [name,setName]=useState("");const [kind,setKind]=useState("adult");const [age,setAge]=useState("");
 const save=x=>{setProfiles(x);write("sakinah-profiles",x)};
 const choose=id=>{localStorage.setItem("sakinah-active-profile",id);setActive(id);window.dispatchEvent(new Event("sakinah-profile-change"))};
 const add=()=>{const n=name.trim();if(!n)return;const id=`p-${Date.now()}`;save([...profiles,{id,nameAr:n,nameEn:n,kind,age:age?Number(age):""}]);setName("");setAge("")};
 return <Shell lang={lang} go={go} titleAr="البروفايلات" titleEn="Profiles" subAr="كل بروفايل له ملاحظاته، حساباته، مكتبته، مسبحته وتقدمه بشكل مستقل." subEn="Each profile keeps its own notes, accounts, library, tasbeeh and progress."><div style={{marginTop:18,display:"grid",gap:8}}>{profiles.map(p=><button key={p.id} onClick={()=>choose(p.id)} style={{...btn,display:"grid",gridTemplateColumns:"48px 1fr auto",gap:11,alignItems:"center",textAlign:lang==="ar"?"right":"left",background:active===p.id?"rgba(181,154,98,.13)":"rgba(255,255,255,.48)"}}><span style={{width:42,height:42,borderRadius:14,display:"grid",placeItems:"center",background:p.kind==="child"?"#FFF0C9":"rgba(23,59,87,.08)",fontSize:19}}>{p.kind==="child"?"☀":"◌"}</span><span><b style={{fontSize:13}}>{lang==="ar"?p.nameAr:p.nameEn}</b><small style={{display:"block",opacity:.45,marginTop:3}}>{p.kind==="child"?(lang==="ar"?`طفل${p.age?` · ${p.age} سنة`:""}`:`Child${p.age?` · ${p.age}`:""}`):(lang==="ar"?"بروفايل بالغ":"Adult profile")}</small></span><span>{active===p.id?"✓":""}</span></button>)}</div><div style={{marginTop:18,padding:15,borderRadius:20,border:"1px solid rgba(16,16,15,.08)",background:"rgba(255,255,255,.42)"}}><div style={{fontWeight:700,fontSize:12.5}}>{lang==="ar"?"إضافة بروفايل":"Add profile"}</div><input value={name} onChange={e=>setName(e.target.value)} placeholder={lang==="ar"?"الاسم":"Name"} style={{...btn,width:"100%",boxSizing:"border-box",marginTop:9}}/><div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:8,marginTop:8}}><select value={kind} onChange={e=>setKind(e.target.value)} style={btn}><option value="adult">{lang==="ar"?"بالغ":"Adult"}</option><option value="child">{lang==="ar"?"طفل":"Child"}</option></select><input type="number" min="1" max="17" value={age} onChange={e=>setAge(e.target.value)} disabled={kind!=="child"} placeholder={lang==="ar"?"العمر":"Age"} style={btn}/></div><button onClick={add} style={{...btn,width:"100%",marginTop:9,background:C.lapis,color:"white",border:0}}>{lang==="ar"?"إضافة":"Add"}</button></div></Shell>;
}

const DHIKR=[
 ["سبحان الله","SubhanAllah",33],["الحمد لله","Alhamdulillah",33],["الله أكبر","Allahu Akbar",34],["أستغفر الله","Astaghfirullah",100],["لا إله إلا الله","La ilaha illa Allah",100],["اللهم صل على محمد","Salawat",100]
];
export function SmartTasbeeh({lang,go}){
 const [idx,setIdx]=useState(()=>read(pkey("tasbeeh-dhikr"),0));const [count,setCount]=useState(()=>read(pkey("tasbeeh-count"),0));const [target,setTarget]=useState(()=>read(pkey("tasbeeh-target"),33));const [vibrate,setVibrate]=useState(()=>read(pkey("tasbeeh-vibrate"),true));
 const item=DHIKR[idx]||DHIKR[0];useEffect(()=>{write(pkey("tasbeeh-dhikr"),idx);write(pkey("tasbeeh-count"),count);write(pkey("tasbeeh-target"),target);write(pkey("tasbeeh-vibrate"),vibrate)},[idx,count,target,vibrate]);
 const tap=()=>{const n=count+1;setCount(n);const today=new Date().toISOString().slice(0,10);const hist=read(pkey("tasbeeh-history"),{});hist[today]=(hist[today]||0)+1;write(pkey("tasbeeh-history"),hist);if(vibrate&&navigator.vibrate)navigator.vibrate(n%target===0?[50,50,100]:18)};
 const pct=Math.min(100,(count%target|| (count?target:0))/target*100);
 return <Shell lang={lang} go={go} titleAr="المسبحة الذكية" titleEn="Smart Tasbeeh" subAr="عداد تفاعلي يحفظ تقدم كل بروفايل وسجله اليومي." subEn="Interactive counter with per-profile progress and daily history."><select value={idx} onChange={e=>{const i=Number(e.target.value);setIdx(i);setCount(0);setTarget(DHIKR[i][2])}} style={{...btn,width:"100%",marginTop:18}}>{DHIKR.map((x,i)=><option value={i} key={x[0]}>{lang==="ar"?x[0]:x[1]}</option>)}</select><button onClick={tap} style={{display:"grid",placeItems:"center",width:240,height:240,maxWidth:"72vw",maxHeight:"72vw",margin:"26px auto 0",borderRadius:"50%",border:"1px solid rgba(181,154,98,.25)",background:"radial-gradient(circle at 35% 28%,#fff,#F0E6CF)",boxShadow:"0 24px 60px rgba(16,16,15,.10)",fontFamily:"inherit",color:C.ink}}><span><b style={{display:"block",fontSize:54,fontWeight:500}}>{count}</b><small style={{fontSize:12,opacity:.5}}>{lang==="ar"?item[0]:item[1]}</small></span></button><div style={{height:8,borderRadius:10,background:"rgba(16,16,15,.07)",overflow:"hidden",marginTop:22}}><div style={{height:"100%",width:`${pct}%`,background:C.gold}}/></div><div style={{display:"grid",gridTemplateColumns:"repeat(3,1fr)",gap:7,marginTop:13}}>{[33,100,1000].map(n=><button key={n} onClick={()=>setTarget(n)} style={{...btn,background:target===n?"rgba(181,154,98,.14)":"transparent"}}>{n}</button>)}</div><div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:8,marginTop:8}}><button onClick={()=>setVibrate(v=>!v)} style={btn}>{lang==="ar"?`الاهتزاز ${vibrate?"مفعّل":"متوقف"}`:`Vibration ${vibrate?"on":"off"}`}</button><button onClick={()=>setCount(0)} style={btn}>{lang==="ar"?"تصفير العداد":"Reset"}</button></div></Shell>;
}

const GUIDE={
 ar:{wudu:["النية بالقلب والتسمية.","غسل الكفين.","المضمضة والاستنشاق.","غسل الوجه.","غسل اليدين إلى المرفقين، اليمنى ثم اليسرى.","مسح الرأس والأذنين.","غسل الرجلين إلى الكعبين، اليمنى ثم اليسرى."],prayer:["استقبال القبلة والنية بالقلب.","تكبيرة الإحرام ثم القيام وقراءة الفاتحة وما تيسر.","الركوع مع الطمأنينة ثم الرفع منه.","السجود مرتين مع الجلوس بين السجدتين.","القيام للركعة التالية وإتمام عدد الركعات.","التشهد في موضعه، ثم الصلاة على النبي ﷺ في التشهد الأخير.","التسليم عن اليمين ثم اليسار."]},
 en:{wudu:["Make the intention in the heart and begin with the name of Allah.","Wash both hands.","Rinse the mouth and nose.","Wash the face.","Wash the arms to the elbows, right then left.","Wipe the head and ears.","Wash the feet to the ankles, right then left."],prayer:["Face the qibla and intend the prayer in the heart.","Begin with takbir, stand, and recite al-Fatihah and what is easy.","Bow calmly, then rise from bowing.","Prostrate twice with a sitting between the two prostrations.","Stand for the next rak'ah and complete the required rak'ahs.","Recite tashahhud in its place and salawat in the final sitting.","Finish with salam to the right and left."]},
 tr:{wudu:["Kalben niyet et ve besmele ile başla.","Ellerini yıka.","Ağzını ve burnunu yıka.","Yüzünü yıka.","Kollarını dirseklere kadar sağdan başlayarak yıka.","Başını ve kulaklarını mesh et.","Ayaklarını topuklara kadar sağdan başlayarak yıka."],prayer:["Kıbleye dön ve kalben niyet et.","İftitah tekbiriyle başla; ayakta Fâtiha ve kolayına geleni oku.","Rükûya git, sükûnetle doğrul.","İki secde yap ve aralarında otur.","Sonraki rekâta kalk ve rekâtları tamamla.","Yerinde tahiyyatı, son oturuşta salavatı oku.","Sağa ve sola selam vererek namazı bitir."]},
 ur:{wudu:["دل میں نیت کریں اور بسم اللہ سے آغاز کریں۔","دونوں ہاتھ دھوئیں۔","کلی کریں اور ناک میں پانی ڈالیں۔","چہرہ دھوئیں۔","بازو کہنیوں تک، پہلے دایاں پھر بایاں دھوئیں۔","سر اور کانوں کا مسح کریں۔","پاؤں ٹخنوں تک، پہلے دایاں پھر بایاں دھوئیں۔"],prayer:["قبلہ رخ ہو کر دل میں نیت کریں۔","تکبیر تحریمہ کہیں، قیام میں سورۂ فاتحہ اور آسان قرآن پڑھیں۔","اطمینان سے رکوع کریں اور پھر سیدھے کھڑے ہوں۔","دو سجدے کریں اور درمیان میں بیٹھیں۔","اگلی رکعت کے لیے کھڑے ہوں اور مطلوبہ رکعات مکمل کریں۔","مناسب مقام پر تشہد اور آخری قعدہ میں درود پڑھیں۔","دائیں اور بائیں سلام پھیر کر نماز ختم کریں۔"]}
};
export function PrayerWuduGuide({lang,go}){const [guideLang,setGuideLang]=useState(lang==="ar"?"ar":"en"),[tab,setTab]=useState("wudu");const data=GUIDE[guideLang]||GUIDE.ar;return <Shell lang={lang} go={go} titleAr="تعليم الصلاة والوضوء" titleEn="Prayer & Wudu Guide" subAr="شرح مبسط بعدة لغات، مع التنبيه أن بعض التفاصيل الفقهية قد تختلف بين المذاهب." subEn="A simple multilingual guide; some jurisprudential details may differ by school."><div style={{display:"grid",gridTemplateColumns:"repeat(4,1fr)",gap:6,marginTop:17}}>{[["ar","العربية"],["en","English"],["tr","Türkçe"],["ur","اردو"]].map(([k,n])=><button key={k} onClick={()=>setGuideLang(k)} style={{...btn,padding:9,background:guideLang===k?"rgba(181,154,98,.14)":"transparent"}}>{n}</button>)}</div><div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:8,marginTop:10}}><button onClick={()=>setTab("wudu")} style={{...btn,background:tab==="wudu"?C.lapis:"transparent",color:tab==="wudu"?"white":C.ink}}>{guideLang==="ar"?"الوضوء":"Wudu"}</button><button onClick={()=>setTab("prayer")} style={{...btn,background:tab==="prayer"?C.lapis:"transparent",color:tab==="prayer"?"white":C.ink}}>{guideLang==="ar"?"الصلاة":"Prayer"}</button></div><div style={{marginTop:15}}>{data[tab].map((x,i)=><div key={i} dir={guideLang==="ur"||guideLang==="ar"?"rtl":"ltr"} style={{display:"grid",gridTemplateColumns:"42px 1fr",gap:11,alignItems:"start",padding:"13px 0",borderTop:"1px solid rgba(16,16,15,.07)"}}><span style={{width:34,height:34,borderRadius:12,display:"grid",placeItems:"center",background:"rgba(181,154,98,.12)",color:C.gold,fontWeight:700}}>{i+1}</span><span style={{fontSize:13,lineHeight:1.8}}>{x}</span></div>)}</div></Shell>}

const PRAYERS=[["Fajr","الفجر"],["Dhuhr","الظهر"],["Asr","العصر"],["Maghrib","المغرب"],["Isha","العشاء"]];
export function AdhanReminderCenter({lang,go}){
 const [cfg,setCfg]=useState(()=>read(pkey("adhan-reminders"),{Fajr:true,Dhuhr:true,Asr:true,Maghrib:true,Isha:true,adhkar:true}));const [permission,setPermission]=useState(typeof Notification!=="undefined"?Notification.permission:"unsupported");const [status,setStatus]=useState("");const timer=useRef(null);
 const save=x=>{setCfg(x);write(pkey("adhan-reminders"),x)};
 const request=async()=>{if(typeof Notification==="undefined")return;const p=await Notification.requestPermission();setPermission(p)};
 const schedule=async()=>{setStatus(lang==="ar"?"جاري تحديد الموقع…":"Getting location…");if(!navigator.geolocation){setStatus(lang==="ar"?"الموقع غير متاح":"Location unavailable");return}navigator.geolocation.getCurrentPosition(async pos=>{try{const {latitude,longitude}=pos.coords;const r=await fetch(`https://api.aladhan.com/v1/timings?latitude=${latitude}&longitude=${longitude}&method=3`);const j=await r.json();const times=j?.data?.timings||{};write(pkey("today-prayer-times"),times);setStatus(lang==="ar"?"تم تجهيز تذكيرات اليوم أثناء فتح التطبيق":"Today's in-app reminders are ready");if(timer.current)clearInterval(timer.current);const fired=new Set();timer.current=setInterval(()=>{const now=new Date();const hh=String(now.getHours()).padStart(2,"0"),mm=String(now.getMinutes()).padStart(2,"0"),key=`${hh}:${mm}`;PRAYERS.forEach(([en,ar])=>{if(cfg[en]&&String(times[en]||"").slice(0,5)===key&&!fired.has(en+key)){fired.add(en+key);if(Notification.permission==="granted")new Notification(lang==="ar"?`حان وقت صلاة ${ar}`:`Time for ${en}`,{body:lang==="ar"?"سكينة · تذكير الصلاة":"Sakinah · Prayer reminder"});}})},20000)}catch{setStatus(lang==="ar"?"تعذر تحميل المواقيت":"Could not load prayer times")}},()=>setStatus(lang==="ar"?"لم يتم السماح بالموقع":"Location permission denied"));};
 useEffect(()=>()=>timer.current&&clearInterval(timer.current),[]);
 return <Shell lang={lang} go={go} titleAr="الأذان والتنبيهات" titleEn="Adhan & Reminders" subAr="تخصيص كل صلاة والتذكيرات. في نسخة الويب الحالية تعمل التنبيهات أثناء فتح التطبيق؛ Android سيضيف العمل الحقيقي بالخلفية." subEn="Customize each prayer and reminders. In this web build notifications work while the app is open; Android will add true background scheduling."><button onClick={request} style={{...btn,width:"100%",marginTop:17,background:permission==="granted"?"rgba(79,145,92,.12)":"rgba(181,154,98,.12)"}}>{lang==="ar"?`إذن الإشعارات: ${permission}`:`Notification permission: ${permission}`}</button><div style={{marginTop:10,display:"grid",gap:7}}>{PRAYERS.map(([en,ar])=><button key={en} onClick={()=>save({...cfg,[en]:!cfg[en]})} style={{...btn,display:"flex",justifyContent:"space-between",alignItems:"center"}}><span>{lang==="ar"?ar:en}</span><b style={{color:cfg[en]?C.green:"#999"}}>{cfg[en]?"●":"○"}</b></button>)}</div><button onClick={()=>save({...cfg,adhkar:!cfg.adhkar})} style={{...btn,width:"100%",marginTop:7,display:"flex",justifyContent:"space-between"}}><span>{lang==="ar"?"تذكيرات التسابيح والأذكار":"Dhikr reminders"}</span><b>{cfg.adhkar?"●":"○"}</b></button><button onClick={schedule} style={{...btn,width:"100%",marginTop:10,background:C.lapis,color:"white",border:0}}>{lang==="ar"?"تجهيز تذكيرات اليوم":"Prepare today's reminders"}</button>{status&&<div style={{fontSize:10.5,opacity:.55,marginTop:9}}>{status}</div>}</Shell>;
}

export function DevotionHub({lang,go}){const items=[["adhan","◷","الأذان والتنبيهات","Adhan & Reminders"],["tasbeeh","◎","المسبحة الذكية","Smart Tasbeeh"],["profiles","◌","البروفايلات","Profiles"],["guide","▤","تعليم الصلاة والوضوء","Prayer & Wudu Guide"]];return <Shell lang={lang} go={go} titleAr="العبادة اليومية" titleEn="Daily Devotion" subAr="الأذان، المسبحة، البروفايلات وتعليم الصلاة والوضوء." subEn="Adhan, tasbeeh, profiles, and prayer/wudu learning."><div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:10,marginTop:20}}>{items.map(([id,icon,ar,en],i)=><button key={id} onClick={()=>go(id)} style={{...btn,minHeight:125,textAlign:lang==="ar"?"right":"left",background:i===0?"linear-gradient(145deg,#173B57,#0C293E)":"rgba(255,255,255,.55)",color:i===0?"white":C.ink}}><div style={{fontSize:25,color:i===0?"#E7D29B":C.gold}}>{icon}</div><div style={{fontSize:13.5,fontWeight:700,marginTop:18,lineHeight:1.5}}>{lang==="ar"?ar:en}</div></button>)}</div></Shell>}
