function phase(hour){if(hour<5)return'night';if(hour<7)return'fajr';if(hour<11)return'morning';if(hour<15)return'noon';if(hour<18)return'afternoon';if(hour<20)return'sunset';return'night'}
function ensureLayer(){let layer=document.getElementById('sakinah-atmosphere-overlay');if(layer)return layer;layer=document.createElement('div');layer.id='sakinah-atmosphere-overlay';Object.assign(layer.style,{position:'fixed',left:'0',top:'0',width:'0',height:'0',overflow:'hidden',pointerEvents:'none',zIndex:'2147483540',borderRadius:'inherit'});document.body.appendChild(layer);return layer}
function cloud(x,y,w,o,delay=0){const e=document.createElement('i');Object.assign(e.style,{position:'absolute',left:`${x}%`,top:`${y}%`,width:`${w}px`,height:`${Math.round(w*.22)}px`,borderRadius:'999px',background:'rgba(238,244,248,.78)',opacity:String(o),filter:'blur(3px)',boxShadow:`${Math.round(w*.18)}px -${Math.round(w*.06)}px 0 rgba(238,244,248,.52),${Math.round(w*.34)}px 2px 0 rgba(238,244,248,.30)`,animation:`mmCloudDrift ${18+delay}s ease-in-out ${delay}s infinite alternate`});return e}
function wind(x,y,w,o,delay=0){const e=document.createElement('i');Object.assign(e.style,{position:'absolute',left:`${x}%`,top:`${y}%`,width:`${w}px`,height:'22px',opacity:String(o),borderTop:'1px solid rgba(238,244,248,.55)',borderRadius:'50%',transform:'skewX(-14deg)',animation:`mmWindMove ${8+delay}s ease-in-out ${delay}s infinite alternate`});return e}
function leaf(x,y,o,delay=0){const e=document.createElement('i');Object.assign(e.style,{position:'absolute',left:`${x}%`,top:`${y}%`,width:'9px',height:'5px',borderRadius:'80% 20% 80% 20%',background:'rgba(202,177,76,.72)',opacity:String(o),transform:'rotate(-24deg)',animation:`mmLeafFloat ${9+delay}s linear ${delay}s infinite`});return e}
function sync(layer,hero){const r=hero.getBoundingClientRect();layer.style.left=`${r.left}px`;layer.style.top=`${r.top}px`;layer.style.width=`${r.width}px`;layer.style.height=`${r.height}px`;layer.style.display=r.bottom<0||r.top>innerHeight?'none':'block';layer.style.borderRadius=getComputedStyle(hero).borderRadius}
function paint(layer,p){if(layer.dataset.phase===p)return;layer.dataset.phase=p;layer.replaceChildren();const day=p!=='night';const cloudAlpha=day?.22:.10;layer.append(cloud(-7,22,105,cloudAlpha,0),cloud(64,29,90,cloudAlpha*.72,4),wind(6,30,118,day?.30:.13,0),wind(58,23,100,day?.25:.10,3),leaf(22,26,day?.65:.18,0),leaf(72,32,day?.55:.16,3),leaf(41,20,day?.42:.14,5));if(p==='sunset')layer.append(cloud(52,40,118,.19,2));if(p==='night')layer.append(cloud(8,33,84,.08,1))}
function render(){const hero=document.querySelector('.mm-prayer-hero')||document.querySelector('.sakinah-live-hero');const layer=ensureLayer();if(!hero){layer.style.display='none';return}sync(layer,hero);const d=new Date();paint(layer,phase(d.getHours()+d.getMinutes()/60))}
export function installHeroAtmosphere(){if(!document.getElementById('mm-weather-keyframes')){const s=document.createElement('style');s.id='mm-weather-keyframes';s.textContent='@keyframes mmCloudDrift{from{transform:translateX(-8px)}to{transform:translateX(18px)}}@keyframes mmWindMove{from{transform:translateX(-8px) skewX(-14deg);opacity:.35}to{transform:translateX(20px) skewX(-14deg);opacity:.75}}@keyframes mmLeafFloat{0%{transform:translate(0,0) rotate(-24deg)}50%{transform:translate(34px,12px) rotate(25deg)}100%{transform:translate(70px,3px) rotate(70deg)}}';document.head.appendChild(s)}const start=()=>{render();const root=document.getElementById('root');const mo=new MutationObserver(()=>requestAnimationFrame(render));if(root)mo.observe(root,{subtree:true,childList:true});addEventListener('scroll',render,{passive:true});addEventListener('resize',render,{passive:true});setInterval(render,60000)};requestAnimationFrame(()=>requestAnimationFrame(start))}
