import React,{useMemo,useState} from "react";

const C={ivory:"#F6F3EC",ink:"#10100F",lapis:"#173B57",gold:"#B59A62",soft:"#EEE7D8",green:"#416F5A"};
const ar=n=>String(n).replace(/[0-9]/g,d=>"٠١٢٣٤٥٦٧٨٩"[d]);
const fmt=(d,opts={})=>new Intl.DateTimeFormat("ar-SA-u-ca-islamic",opts).format(d);
const greg=(d,opts={})=>new Intl.DateTimeFormat("ar-IQ",opts).format(d);
function hijriParts(d){try{const p=new Intl.DateTimeFormat("en-u-ca-islamic",{day:"numeric",month:"numeric",year:"numeric"}).formatToParts(d);return Object.fromEntries(p.filter(x=>x.type!=="literal").map(x=>[x.type,Number(x.value)]))}catch{return {day:1,month:1,year:d.getFullYear()}}}
const EVENTS=[
 {m:1,d:1,name:"رأس السنة الهجرية",kind:"مناسبة"},{m:1,d:10,name:"عاشوراء",kind:"صيام"},{m:3,d:12,name:"المولد النبوي",kind:"مناسبة"},{m:7,d:27,name:"الإسراء والمعراج",kind:"مناسبة"},{m:8,d:15,name:"منتصف شعبان",kind:"مناسبة"},{m:9,d:1,name:"بداية رمضان",kind:"رمضان"},{m:9,d:21,name:"العشر الأواخر",kind:"رمضان"},{m:9,d:27,name:"ليلة ٢٧ من رمضان",kind:"رمضان"},{m:10,d:1,name:"عيد الفطر",kind:"عيد"},{m:12,d:9,name:"يوم عرفة",kind:"صيام"},{m:12,d:10,name:"عيد الأضحى",kind:"عيد"}
];
function daysToHijri(targetM,targetD,now){for(let i=0;i<390;i++){const d=new Date(now);d.setDate(d.getDate()+i);const h=hijriParts(d);if(h.month===targetM&&h.day===targetD)return {days:i,date:d,h}}return null}
function monthGrid(now){const current=hijriParts(now),cells=[];for(let off=-current.day+1;off<=35;off++){const d=new Date(now);d.setDate(d.getDate()+off);const h=hijriParts(d);if(h.month===current.month)cells.push({date:d,h,today:off===0,event:EVENTS.find(e=>e.m===h.month&&e.d===h.day)})}return cells}

export default function IslamicCalendarCenter(){
 const[now]=useState(()=>new Date());
 const h=hijriParts(now);
 const cells=useMemo(()=>monthGrid(now),[now]);
 const upcoming=useMemo(()=>EVENTS.map(e=>({...e,next:daysToHijri(e.m,e.d,now)})).filter(e=>e.next).sort((a,b)=>a.next.days-b.next.days).slice(0,6),[now]);
 const monthName=fmt(now,{month:"long",year:"numeric"});
 return <div dir="rtl" style={{position:"absolute",inset:0,overflowY:"auto",background:C.ivory,color:C.ink}}><main style={{maxWidth:760,margin:"0 auto",padding:"30px 16px 140px"}}>
  <header style={{textAlign:"center"}}><h1 style={{fontSize:29,margin:"4px 0 6px"}}>التقويم الهجري</h1><p style={{fontSize:11,opacity:.48,margin:0,lineHeight:1.8}}>تقويم هجري منظم مع التاريخ الميلادي والمناسبات والأيام المهمة القادمة</p></header>
  <section style={{marginTop:20,borderRadius:28,padding:"20px 18px",background:`linear-gradient(145deg,${C.lapis},#244D68)`,color:"white",boxShadow:"0 14px 34px rgba(23,59,87,.12)"}}><div style={{fontSize:10,opacity:.62}}>اليوم</div><div style={{fontSize:28,lineHeight:1.5,marginTop:4}}>{fmt(now,{weekday:"long",day:"numeric",month:"long",year:"numeric"})}</div><div style={{fontSize:11,opacity:.68,marginTop:5}}>{greg(now,{weekday:"long",day:"numeric",month:"long",year:"numeric"})}</div><div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:8,marginTop:16}}><div style={{padding:11,borderRadius:16,background:"rgba(255,255,255,.08)"}}><small style={{opacity:.6}}>الشهر</small><b style={{display:"block",marginTop:3}}>{fmt(now,{month:"long"})}</b></div><div style={{padding:11,borderRadius:16,background:"rgba(255,255,255,.08)"}}><small style={{opacity:.6}}>السنة الهجرية</small><b style={{display:"block",marginTop:3}}>{ar(h.year)} هـ</b></div></div></section>

  <section style={{marginTop:16,padding:14,borderRadius:24,background:"rgba(255,255,255,.58)",border:"1px solid rgba(16,16,15,.06)"}}><div style={{display:"flex",justifyContent:"space-between",alignItems:"center",marginBottom:12}}><b style={{fontSize:14}}>{monthName}</b><span style={{fontSize:10,opacity:.42}}>الشهر الحالي</span></div><div style={{display:"grid",gridTemplateColumns:"repeat(7,1fr)",gap:5,textAlign:"center",fontSize:9,opacity:.45,marginBottom:6}}>{["ح","ن","ث","ر","خ","ج","س"].map(x=><div key={x}>{x}</div>)}</div><div style={{display:"grid",gridTemplateColumns:"repeat(7,1fr)",gap:5}}>{cells.map((x,i)=><div key={i} title={x.event?.name||""} style={{aspectRatio:"1",borderRadius:13,display:"grid",placeItems:"center",position:"relative",fontSize:11,fontWeight:x.today?800:500,background:x.today?C.lapis:x.event?"rgba(181,154,98,.16)":"rgba(16,16,15,.025)",color:x.today?"white":C.ink,border:x.event&&!x.today?"1px solid rgba(181,154,98,.25)":"1px solid transparent"}}>{ar(x.h.day)}{x.event&&<i style={{position:"absolute",bottom:4,width:4,height:4,borderRadius:"50%",background:x.today?"white":C.gold}}/>}</div>)}</div><div style={{display:"flex",gap:14,marginTop:10,fontSize:9,opacity:.55}}><span>● اليوم</span><span style={{color:C.gold}}>● مناسبة</span></div></section>

  <section style={{marginTop:18}}><div style={{display:"flex",justifyContent:"space-between",alignItems:"end",marginBottom:7}}><div><div style={{fontSize:10,color:C.gold}}>القادم</div><h2 style={{fontSize:20,margin:"2px 0"}}>المناسبات الهجرية</h2></div><span style={{fontSize:9,opacity:.4}}>حسب تقويم الجهاز</span></div>{upcoming.map((e,i)=><div key={`${e.m}-${e.d}`} style={{display:"grid",gridTemplateColumns:"52px 1fr auto",gap:10,alignItems:"center",padding:"12px 0",borderTop:"1px solid rgba(16,16,15,.07)"}}><div style={{width:46,height:46,borderRadius:16,background:i===0?"rgba(65,111,90,.12)":C.soft,display:"grid",placeItems:"center",textAlign:"center"}}><b style={{fontSize:14}}>{e.next.days===0?"اليوم":ar(e.next.days)}</b>{e.next.days>0&&<small style={{fontSize:8,opacity:.5}}>يوم</small>}</div><div><b style={{fontSize:12.5}}>{e.name}</b><div style={{fontSize:9.5,opacity:.46,marginTop:3}}>{fmt(e.next.date,{day:"numeric",month:"long"})} · {greg(e.next.date,{day:"numeric",month:"short"})}</div></div><span style={{fontSize:9,padding:"5px 8px",borderRadius:10,background:"rgba(181,154,98,.10)",color:C.gold}}>{e.kind}</span></div>)}</section>

  <section style={{marginTop:16,padding:13,borderRadius:18,background:"rgba(181,154,98,.08)",fontSize:9.5,lineHeight:1.8,opacity:.62}}>التاريخ الهجري هنا يعتمد تقويم الجهاز. بداية الأشهر والمناسبات المرتبطة برؤية الهلال قد تختلف يوماً بحسب البلد والجهة الشرعية المحلية.</section>
 </main></div>
}
