import React,{useState} from "react";

const C={ivory:"#F6F3EC",ink:"#253238",blue:"#173B57",gold:"#B59A62",green:"#6E8B78"};
const STORIES=[
 {id:"adam",icon:"🌿",title:"آدم عليه السلام",ref:"البقرة 30–39 · الأعراف 11–25",tone:["#DDE9D7","#F8F1D9"],intro:"قصة بداية الإنسان، وكيف علّم الله آدم وكرّمه، ثم علّمه طريق التوبة بعد الخطأ.",parts:["خلق الله آدم وعلّمه ما لم يكن يعلم، وأمر الملائكة بالسجود له تكريماً بأمر الله.","عاش آدم وزوجه في الجنة، وحذّرهما الله من شجرة معينة، لكن الشيطان وسوس لهما فوقعا في الخطأ.","لم يُترك آدم في اليأس؛ تعلّم كلمات التوبة، فتاب الله عليه، وبدأت حياة الإنسان على الأرض مع الهداية."],lesson:"إذا أخطأنا لا نيأس؛ نعترف بالخطأ، نستغفر الله، ونحاول أن نصلحه."},
 {id:"nuh",icon:"⛵",title:"نوح عليه السلام والسفينة",ref:"هود 25–49 · نوح 1–28",tone:["#CFE5EA","#E9F2F0"],intro:"قصة نبي دعا قومه زمناً طويلاً، وبقي صابراً حتى أمره الله بصنع السفينة.",parts:["دعا نوح قومه إلى عبادة الله وحده، وكان يتحدث معهم بصبر في أوقات مختلفة.","لما أصرّ كثير منهم على الرفض، أمر الله نوحاً أن يصنع السفينة، فصنعها وهو يثق بوعد الله.","جاء الطوفان، ونجّى الله نوحاً ومن آمن معه، وأصبحت السفينة علامة على النجاة بالإيمان والطاعة."],lesson:"الصبر على الحق مهم، وحتى لو سخر الآخرون من الخير لا نتركه."},
 {id:"ibrahim",icon:"✨",title:"إبراهيم عليه السلام والأصنام",ref:"الأنبياء 51–70",tone:["#F4DDC4","#F8F0DB"],intro:"قصة فتى شجاع رفض عبادة الأصنام وبيّن لقومه أنها لا تملك نفعاً ولا ضراً.",parts:["كان إبراهيم يعرف أن العبادة لا تكون إلا لله، ولم يقتنع بما كان قومه يفعلونه من عبادة الأصنام.","كسر الأصنام وترك الكبير منها، ثم سأل قومه سؤالاً يجعلهم يفكرون: هل هذه الأصنام تستطيع أن تتكلم أو تدافع عن نفسها؟", "غضب قومه وأرادوا إحراقه، لكن الله جعل النار برداً وسلاماً عليه فنجّاه."],lesson:"نسأل ونفكر، ولا نتبع شيئاً فقط لأن الناس اعتادوا عليه."},
 {id:"yusuf",icon:"⭐",title:"يوسف عليه السلام",ref:"سورة يوسف 1–111",tone:["#E8DDF0","#F7EBDD"],intro:"قصة طويلة جميلة عن الصبر والعفة والمغفرة، من الطفولة حتى صار يوسف ذا مكانة كبيرة.",parts:["رأى يوسف رؤيا مميزة وهو صغير، ثم حسده بعض إخوته وألقوه في البئر، لكن الله حفظه.","مرّ يوسف باختبارات صعبة، واختار الطاعة والصدق حتى عندما كان ذلك أصعب عليه.","بعد سنوات، أصبح مسؤولاً مهماً، واجتمع بأهله من جديد، وعفا عن إخوته بدل أن ينتقم منهم."],lesson:"الصبر والصدق قد يكونان صعبين الآن، لكن الله لا يضيّع عمل الخير."},
 {id:"musa",icon:"🌊",title:"موسى عليه السلام وفرعون",ref:"طه 9–79 · الشعراء 10–68",tone:["#D5E7F3","#EAF3E4"],intro:"قصة شجاعة وثقة بالله أمام ظلم فرعون، ثم نجاة موسى ومن معه عند البحر.",parts:["كلّم الله موسى وأرسله إلى فرعون، وأعطاه آيات تؤيده، وطلب منه أن يدعو بالحكمة.","رفض فرعون واستكبر، وجمع السحرة، لكنهم عرفوا أن ما جاء به موسى حق فآمنوا.","خرج موسى ومن معه، فلحق بهم فرعون. وعند البحر أمر الله موسى أن يضرب بعصاه، فانفلق البحر ونجا المؤمنون."],lesson:"عندما نفعل الصواب لا نسمح للخوف أن يمنعنا، ونتوكل على الله."},
 {id:"yunus",icon:"🐋",title:"يونس عليه السلام والحوت",ref:"الأنبياء 87–88 · الصافات 139–148",tone:["#CDE7E3","#E6EFF7"],intro:"قصة دعاء ورجوع إلى الله في لحظة شديدة، وكيف كانت النجاة بعد التسبيح والتوبة.",parts:["غادر يونس قومه وهو غاضب قبل أن يؤذن له، وركب سفينة في البحر.","ابتلعه الحوت، فكان في ظلمات شديدة، وهناك دعا الله واعترف بخطئه وسبّحه.","استجاب الله له ونجّاه، ثم عاد إلى رسالته، وآمن قومه."],lesson:"حتى في أصعب لحظة نستطيع أن نرجع إلى الله بالدعاء والصدق."},
 {id:"cave",icon:"🕯️",title:"أصحاب الكهف",ref:"الكهف 9–26",tone:["#E5DFD2","#EEF0E4"],intro:"قصة شباب آمنوا بالله وحافظوا على إيمانهم، فحماهم الله بطريقة عجيبة.",parts:["كانوا فتياناً آمنوا بربهم، ورفضوا أن يتركوا إيمانهم تحت ضغط قومهم.","لجؤوا إلى كهف، ودعوا الله أن يهيئ لهم رشداً ورحمة.","أنامهم الله سنين طويلة ثم بعثهم، لتكون قصتهم آية على قدرة الله."],lesson:"الصديق الصالح والشجاعة في التمسك بالخير يساعداننا عندما يكون الطريق صعباً."},
 {id:"maryam",icon:"🌸",title:"مريم وعيسى عليه السلام",ref:"مريم 16–36",tone:["#F3DDE5","#F7EFDA"],intro:"قصة مريم الصادقة، وبشارة الملَك لها بعيسى عليه السلام، وآية ميلاده بإذن الله.",parts:["اعتزلت مريم أهلها، فجاءها الملَك وبشّرها بغلام طاهر بأمر الله.","تعجبت مريم، فأخبرها أن ذلك على الله يسير، وأن عيسى سيكون آية للناس.","ولما عادت إلى قومها، أنطق الله عيسى وهو في المهد، فبيّن أنه عبد الله ونبيه."],lesson:"قد تقع أمور لا نفهم كيف ستنتهي، لكن قدرة الله أعظم من توقعاتنا."}
];

function Back({go}){return <button onClick={()=>go("kids-home")} style={{border:0,borderRadius:999,padding:"9px 14px",background:"rgba(255,255,255,.72)",fontFamily:"inherit",color:C.ink,boxShadow:"0 7px 22px rgba(37,50,56,.07)"}}>→ الأطفال</button>}

export default function KidsQuranStories({go}){
 const [selected,setSelected]=useState(null);
 const story=STORIES.find(x=>x.id===selected);
 if(story)return <div dir="rtl" style={{position:"fixed",inset:0,zIndex:50000,overflowY:"auto",background:C.ivory,color:C.ink,fontFamily:"inherit"}}><div style={{maxWidth:680,margin:"0 auto",padding:"28px 18px 120px"}}><button onClick={()=>setSelected(null)} style={{border:0,borderRadius:999,padding:"9px 14px",background:"rgba(255,255,255,.75)",fontFamily:"inherit",color:C.ink}}>→ كل القصص</button><div style={{marginTop:18,borderRadius:34,padding:"26px 22px",background:`linear-gradient(145deg,${story.tone[0]},${story.tone[1]})`,minHeight:210,display:"flex",flexDirection:"column",justifyContent:"space-between"}}><div style={{fontSize:54}}>{story.icon}</div><div><div style={{fontSize:11,opacity:.5}}>قصة حقيقية من القرآن</div><h1 style={{margin:"5px 0 0",fontSize:32,lineHeight:1.5,fontWeight:600}}>{story.title}</h1><div style={{fontSize:11,color:C.gold,marginTop:5}}>{story.ref}</div></div></div><p style={{fontSize:15,lineHeight:2,margin:"20px 4px 14px",opacity:.75}}>{story.intro}</p><div style={{display:"grid",gap:12}}>{story.parts.map((p,i)=><div key={i} style={{display:"grid",gridTemplateColumns:"44px 1fr",gap:12,alignItems:"start",padding:"16px",borderRadius:22,background:"rgba(255,255,255,.68)",border:"1px solid rgba(37,50,56,.055)"}}><div style={{width:40,height:40,borderRadius:15,display:"grid",placeItems:"center",background:"rgba(181,154,98,.13)",color:C.gold,fontWeight:700}}>{i+1}</div><div style={{fontSize:14,lineHeight:1.95}}>{p}</div></div>)}</div><div style={{marginTop:16,padding:18,borderRadius:24,background:C.blue,color:"white"}}><div style={{fontSize:10,opacity:.62}}>ماذا نتعلم؟</div><div style={{fontSize:14.5,lineHeight:1.9,marginTop:6}}>{story.lesson}</div></div><div style={{fontSize:10.5,opacity:.42,lineHeight:1.8,marginTop:14,textAlign:"center"}}>المحتوى مبسّط للأطفال، ومبني على الآيات المذكورة دون إضافة أحداث غير ثابتة في القرآن.</div></div></div>;
 return <div dir="rtl" style={{position:"fixed",inset:0,zIndex:50000,overflowY:"auto",background:"linear-gradient(180deg,#F8F3E8,#F1F4EE)",color:C.ink,fontFamily:"inherit"}}><div style={{maxWidth:720,margin:"0 auto",padding:"26px 18px 120px"}}><Back go={go}/><div style={{marginTop:24,textAlign:"center"}}><div style={{fontSize:11,letterSpacing:.6,color:C.gold}}>سكينة للأطفال</div><h1 style={{fontSize:31,lineHeight:1.5,margin:"4px 0 0"}}>قصص حقيقية من القرآن</h1><p style={{fontSize:12.5,lineHeight:1.8,opacity:.5,margin:"7px auto 0",maxWidth:480}}>نحكي القصة بلغة بسيطة وجميلة، ونذكر مرجعها القرآني بوضوح، ثم نختم بفكرة يتعلمها الطفل.</p></div><div style={{display:"grid",gridTemplateColumns:"repeat(2,minmax(0,1fr))",gap:12,marginTop:22}}>{STORIES.map((s,i)=><button key={s.id} onClick={()=>setSelected(s.id)} style={{border:0,borderRadius:26,padding:0,overflow:"hidden",textAlign:"right",background:"rgba(255,255,255,.68)",boxShadow:"0 12px 34px rgba(37,50,56,.055)",fontFamily:"inherit",color:C.ink,cursor:"pointer"}}><div style={{height:112,padding:"16px",boxSizing:"border-box",background:`linear-gradient(145deg,${s.tone[0]},${s.tone[1]})`,display:"flex",alignItems:"flex-end",justifyContent:"space-between"}}><span style={{fontSize:38}}>{s.icon}</span><span style={{fontSize:9.5,opacity:.46}}>قصة {i+1}</span></div><div style={{padding:"14px 14px 16px"}}><div style={{fontSize:15,fontWeight:650,lineHeight:1.6}}>{s.title}</div><div style={{fontSize:9.5,color:C.gold,marginTop:4}}>{s.ref}</div><div style={{fontSize:10.5,opacity:.48,lineHeight:1.6,marginTop:7}}>{s.intro}</div></div></button>)}</div></div></div>;
}
