import React,{useEffect,useRef,useState} from "react";
const C={ivory:"#F8F5EE",ink:"#26343B",lapis:"#173B57",gold:"#B59A62",sky:"#DCEEFF",lilac:"#EDE3FA",mint:"#DFF3E7",peach:"#FFE6CF",sun:"#FFF2B8"};
const DB="sakinah-kids-audio",STORE="nasheeds";
function openDb(){return new Promise((ok,fail)=>{const r=indexedDB.open(DB,1);r.onupgradeneeded=()=>{const db=r.result;if(!db.objectStoreNames.contains(STORE))db.createObjectStore(STORE,{keyPath:"id",autoIncrement:true})};r.onsuccess=()=>ok(r.result);r.onerror=()=>fail(r.error)})}
async function all(){const db=await openDb();return new Promise((ok,fail)=>{const tx=db.transaction(STORE,"readonly"),r=tx.objectStore(STORE).getAll();r.onsuccess=()=>ok(r.result||[]);r.onerror=()=>fail(r.error)})}
async function addFiles(files){const db=await openDb();return Promise.all([...files].map(file=>new Promise((ok,fail)=>{const tx=db.transaction(STORE,"readwrite"),r=tx.objectStore(STORE).add({name:file.name,type:file.type||"audio/*",size:file.size,blob:file,createdAt:Date.now()});r.onsuccess=()=>ok(r.result);r.onerror=()=>fail(r.error)})))}
async function del(id){const db=await openDb();return new Promise((ok,fail)=>{const tx=db.transaction(STORE,"readwrite"),r=tx.objectStore(STORE).delete(id);r.onsuccess=()=>ok();r.onerror=()=>fail(r.error)})}
export function KidsNasheedsLive({lang="ar",go}){
 const [rows,setRows]=useState([]),[current,setCurrent]=useState(null),[status,setStatus]=useState("");
 const urlRef=useRef(null);
 const reload=()=>all().then(setRows).catch(()=>setStatus(lang==="ar"?"تعذر فتح مكتبة الصوت المحلية":"Could not open local audio library"));
 useEffect(()=>{reload();return()=>{if(urlRef.current)URL.revokeObjectURL(urlRef.current)}},[]);
 const choose=x=>{if(urlRef.current)URL.revokeObjectURL(urlRef.current);const url=URL.createObjectURL(x.blob);urlRef.current=url;setCurrent({...x,url})};
 const upload=async e=>{const files=e.target.files;if(!files?.length)return;try{await addFiles(files);setStatus(lang==="ar"?"تمت إضافة الأناشيد إلى مكتبتك الصغيرة ✨":"Nasheeds added to your little library ✨");await reload()}catch{setStatus(lang==="ar"?"تعذر حفظ الملفات":"Could not save files")}e.target.value=""};
 const remove=async id=>{await del(id);if(current?.id===id){if(urlRef.current)URL.revokeObjectURL(urlRef.current);urlRef.current=null;setCurrent(null)}reload()};
 const tones=[C.sky,C.lilac,C.mint,C.peach];
 return <div style={{position:"absolute",inset:0,background:"linear-gradient(180deg,#FFF9EF,#F3F8F5)",color:C.ink,display:"flex",flexDirection:"column"}} dir={lang==="ar"?"rtl":"ltr"}>
  <div style={{padding:"max(76px,calc(env(safe-area-inset-top) + 48px)) 18px 0"}}><button onClick={()=>go?.("kids-world")} style={{border:0,borderRadius:999,padding:"7px 12px",background:"rgba(255,255,255,.82)",boxShadow:"0 8px 24px rgba(38,52,59,.07)",fontFamily:"inherit",color:"inherit"}}>{lang==="ar"?"→ الأطفال":"← Kids"}</button></div>
  <div style={{flex:1,overflowY:"auto",padding:"16px 18px 130px"}}>
   <div style={{textAlign:"center"}}><div style={{fontSize:10,color:C.gold}}>🎵 سكينة للأطفال</div><div style={{fontSize:30,fontWeight:800,lineHeight:1.5,marginTop:3}}>{lang==="ar"?"أناشيدي الجميلة":"My Nasheeds"}</div><div style={{fontSize:12,opacity:.5,lineHeight:1.8,margin:"6px auto 0",maxWidth:500}}>{lang==="ar"?"مكتبة صوتية صغيرة وآمنة على جهازك. أضف الأناشيد التي تملكها أو المسموح لك باستخدامها.":"A small safe on-device audio library for nasheeds you own or are allowed to use."}</div></div>
   <div style={{marginTop:18,padding:18,borderRadius:28,background:"linear-gradient(135deg,#FFF0C9,#DFF6FF 60%,#F3E7FF)",position:"relative",overflow:"hidden"}}><div style={{position:"absolute",left:15,top:10,fontSize:24}}>☁️</div><div style={{position:"absolute",right:16,bottom:9,fontSize:22}}>🌟</div><div style={{fontSize:11,opacity:.55}}>مكتبتك الخاصة</div><div style={{fontSize:23,fontWeight:800,marginTop:4}}>استمع وردّد وفرح قلبك 🎶</div><div style={{fontSize:11,opacity:.55,marginTop:5}}>الملفات تبقى محفوظة محلياً على هذا الجهاز.</div></div>
   <label style={{display:"block",marginTop:14,padding:14,borderRadius:18,background:C.lapis,color:"white",textAlign:"center",fontSize:12.5,fontWeight:700,cursor:"pointer",boxShadow:"0 12px 28px rgba(23,59,87,.12)"}}>＋ أضف نشيداً جديداً<input type="file" accept="audio/*" multiple hidden onChange={upload}/></label>
   {status&&<div style={{marginTop:10,padding:10,borderRadius:14,background:C.sun,fontSize:10.5,textAlign:"center"}}>{status}</div>}
   {current&&<div style={{marginTop:16,padding:18,borderRadius:26,background:C.lilac,boxShadow:"0 14px 32px rgba(38,52,59,.06)"}}><div style={{display:"flex",alignItems:"center",gap:11}}><div style={{width:48,height:48,borderRadius:18,display:"grid",placeItems:"center",background:"rgba(255,255,255,.66)",fontSize:25}}>🎧</div><div style={{minWidth:0}}><div style={{fontSize:10,opacity:.5}}>يُشغّل الآن</div><div style={{fontSize:13,fontWeight:750,overflow:"hidden",textOverflow:"ellipsis",whiteSpace:"nowrap",marginTop:2}}>{current.name}</div></div></div><audio src={current.url} controls autoPlay style={{width:"100%",marginTop:13}}/></div>}
   <div style={{display:"flex",justifyContent:"space-between",alignItems:"center",marginTop:18}}><div style={{fontSize:14,fontWeight:800}}>أناشيدي</div><div style={{fontSize:10,opacity:.45}}>{rows.length} ملف</div></div>
   <div style={{marginTop:10,display:"grid",gap:9}}>{rows.length===0?<div style={{padding:"30px 16px",borderRadius:24,background:"rgba(255,255,255,.7)",textAlign:"center"}}><div style={{fontSize:34}}>🎼</div><div style={{fontSize:12.5,fontWeight:700,marginTop:8}}>مكتبتك تنتظر أول نشيد</div><div style={{fontSize:10.5,opacity:.45,marginTop:4}}>اضغط «أضف نشيداً جديداً» واختر ملفاً صوتياً من جهازك.</div></div>:rows.map((x,i)=><div key={x.id} style={{display:"grid",gridTemplateColumns:"52px 1fr auto",gap:10,alignItems:"center",padding:11,borderRadius:20,background:tones[i%tones.length],border:"1px solid rgba(38,52,59,.04)"}}><button onClick={()=>choose(x)} style={{width:48,height:48,border:0,borderRadius:17,background:"rgba(255,255,255,.72)",fontSize:20}}>▶</button><button onClick={()=>choose(x)} style={{border:0,background:"transparent",fontFamily:"inherit",textAlign:lang==="ar"?"right":"left",color:"inherit",minWidth:0}}><b style={{fontSize:12.5,display:"block",overflow:"hidden",textOverflow:"ellipsis",whiteSpace:"nowrap"}}>{x.name}</b><small style={{display:"block",opacity:.42,marginTop:3}}>{Math.max(1,Math.round((x.size||0)/1024/1024*10)/10)} MB</small></button><button onClick={()=>remove(x.id)} aria-label="حذف" style={{width:36,height:36,border:"1px solid rgba(164,77,60,.12)",borderRadius:13,background:"rgba(255,255,255,.5)",color:"#A44D3C",fontSize:17}}>×</button></div>)}</div>
  </div>
 </div>
}
