import React,{useEffect,useState} from "react";

const C={ivory:"#F6F3EC",ink:"#253238",blue:"#173B57",gold:"#B59A62"};
const STORIES=[
 {id:"adam",icon:"🌿",title:"آدم عليه السلام",ref:"البقرة 30–39 · الأعراف 11–25",tone:["#DDE9D7","#F8F1D9"],intro:"قصة بداية الإنسان، والتعلّم، والخطأ، ثم التوبة.",story:["في بداية قصة الإنسان خلق الله آدم عليه السلام، وعلّمه من العلم ما لم يكن يعرفه. وكرّمه الله، وأمر الملائكة أن يسجدوا له سجود تكريم وطاعة لأمر الله.","أسكن الله آدم وزوجه الجنة، وأباح لهما نعيمها، وحذرهما من شجرة واحدة. لكن الشيطان وسوس لهما حتى أكلا منها. وحين أدرك آدم وزوجه خطأهما لم يكابرا ولم يهربا من الحقيقة، بل رجعا إلى الله وطلبا منه المغفرة.","فتاب الله عليهما، وعلّمهما أن الإنسان قد يخطئ، لكن باب الرجوع إلى الله مفتوح. ثم بدأت حياة البشر على الأرض، ومعهم هداية الله ووعده بأن من اتبع هدايته فلن يضل."],lesson:"إذا أخطأنا لا نيأس؛ نعترف بالخطأ، نستغفر الله، ونحاول أن نصلحه."},
 {id:"nuh",icon:"⛵",title:"نوح عليه السلام والسفينة",ref:"هود 25–49 · نوح 1–28",tone:["#CFE5EA","#E9F2F0"],intro:"قصة نبي صابر ظل يدعو قومه زمناً طويلاً.",story:["أرسل الله نوحاً عليه السلام إلى قومه ليدعوهم إلى عبادة الله وحده. كان يكلمهم في النهار والليل، سراً وجهراً، ويشرح لهم برفق أن الله هو خالقهم ورازقهم.","لكن أكثر قومه أصروا على الرفض والسخرية. وبعد زمن طويل أوحى الله إلى نوح أن يصنع سفينة. بدأ نوح يصنعها بأمر الله، وكلما مرّ به بعض قومه سخروا منه، لكنه لم يترك ما أمره الله به.","ثم جاء أمر الله، وفار الماء وجاء الطوفان. حمل نوح في السفينة من أمره الله بحملهم، فنجّى الله نوحاً والمؤمنين معه. وبعد انتهاء الطوفان استقرت السفينة، وبقيت القصة درساً في الصبر والثقة بالله."],lesson:"الصبر على الحق مهم، وحتى لو سخر الآخرون من الخير لا نتركه."},
 {id:"ibrahim",icon:"✨",title:"إبراهيم عليه السلام والأصنام",ref:"الأنبياء 51–70",tone:["#F4DDC4","#F8F0DB"],intro:"قصة فتى شجاع دعا قومه إلى التفكير وعبادة الله وحده.",story:["نشأ إبراهيم عليه السلام بين قوم كانوا يعبدون أصناماً من دون الله. كان يفكر ويسأل: كيف نعبد شيئاً لا يسمع ولا يتكلم ولا يستطيع أن ينفع نفسه؟ وكان يعلم أن العبادة لا تكون إلا لله.","وفي يوم غاب فيه قومه، كسر إبراهيم الأصنام وترك كبيرها، حتى يدفع قومه إلى التفكير. وحين عادوا وسألوه، أرشدهم إلى أن يسألوا أصنامهم إن كانت تستطيع الكلام. عندها عرفوا في أنفسهم أن هذه الأصنام لا تملك شيئاً.","غضب القوم وقرروا أن يحرقوا إبراهيم، لكن الله أنجاه، وجعل النار عليه برداً وسلاماً. فكانت نجاته آية عظيمة على قدرة الله."],lesson:"لا نتبع شيئاً فقط لأن الجميع يفعله؛ نسأل ونتعلم ونبحث عن الحق."},
 {id:"yusuf",icon:"⭐",title:"يوسف عليه السلام",ref:"سورة يوسف 1–111",tone:["#E8DDF0","#F7EBDD"],intro:"قصة طويلة عن الصبر والصدق والعفة والمغفرة.",story:["كان يوسف عليه السلام صغيراً حين رأى رؤيا عجيبة، وقصّها على أبيه يعقوب عليه السلام. أحبّه أبوه، لكن بعض إخوته حسدوه، فأخذوه بعيداً وألقوه في بئر، ثم عادوا إلى أبيهم بقصة غير صحيحة.","لم تنته قصة يوسف عند البئر. أخرجه مسافرون وذهب به القدر إلى مصر. مرّ يوسف باختبارات صعبة، لكنه بقي صادقاً عفيفاً، واختار طاعة الله حتى عندما أدى ذلك إلى السجن.","وبعد سنوات أظهر الله براءة يوسف، وأصبح صاحب مكانة ومسؤولية. ثم جاء إخوته إليه وهم لا يعرفونه. وحين عرفوه وندموا، لم ينتقم منهم، بل عفا عنهم، واجتمع بأبيه وأهله من جديد.","وهكذا أراهم الله كيف يمكن أن تتحول أيام الحزن الطويلة إلى خير كبير، إذا صبر الإنسان وتمسك بالحق."],lesson:"الصبر والصدق قد يكونان صعبين الآن، لكن الله لا يضيّع عمل الخير."},
 {id:"musa",icon:"🌊",title:"موسى عليه السلام وفرعون",ref:"طه 9–79 · الشعراء 10–68",tone:["#D5E7F3","#EAF3E4"],intro:"قصة شجاعة وثقة بالله أمام ظلم فرعون.",story:["كلّم الله موسى عليه السلام وأرسله إلى فرعون، الذي كان ظالماً متكبراً. طلب موسى من الله أن يشرح صدره وييسر أمره، وأن يعينه بأخيه هارون.","ذهب موسى وهارون إلى فرعون ودعواه إلى الحق. لكن فرعون رفض واستكبر، ثم جمع السحرة ليواجهوا موسى أمام الناس. فلما رأى السحرة آية الله عرفوا أن ما جاء به موسى ليس سحراً، فآمنوا بالله.","بعد ذلك خرج موسى ومن معه، فلحق بهم فرعون وجنوده. وصل المؤمنون إلى البحر، وخاف بعضهم، لكن موسى قال بثقة إن الله معه وسيهديه. فأمره الله أن يضرب البحر بعصاه، فانفلق البحر طريقاً يابساً، وعبر موسى ومن معه، ثم نجاهم الله من فرعون."],lesson:"عندما نفعل الصواب لا نسمح للخوف أن يمنعنا، ونتوكل على الله."},
 {id:"yunus",icon:"🐋",title:"يونس عليه السلام والحوت",ref:"الأنبياء 87–88 · الصافات 139–148",tone:["#CDE7E3","#E6EFF7"],intro:"قصة دعاء ورجوع إلى الله في لحظة شديدة.",story:["كان يونس عليه السلام نبياً يدعو قومه إلى الله. ولما غضب من إعراضهم خرج قبل أن يؤذن له، ثم ركب سفينة في البحر.","حدث للسفينة ما جعل أهلها يلقون أحد الركاب في البحر، فوقعت القرعة على يونس. فلما صار في الماء ابتلعه الحوت بأمر الله. وكان يونس في ظلمات البحر وبطن الحوت والليل، لكنه لم ينس الله.","دعا يونس ربه واعترف بخطئه وسبّحه. فاستجاب الله له ونجّاه من الكرب، وأخرجه إلى البر، ثم أعاده إلى رسالته، وآمن قومه."],lesson:"حتى في أصعب لحظة نستطيع أن نرجع إلى الله بالدعاء والصدق."},
 {id:"cave",icon:"🕯️",title:"أصحاب الكهف",ref:"الكهف 9–26",tone:["#E5DFD2","#EEF0E4"],intro:"قصة شباب آمنوا بالله وحافظوا على إيمانهم.",story:["كان أصحاب الكهف مجموعة من الفتيان آمنوا بالله في وقت كان قومهم يعبدون غيره. ثبتوا على إيمانهم، وعرفوا أن رضا الله أهم من رضا الناس.","ولما اشتد عليهم الأمر خرجوا من قومهم ولجؤوا إلى كهف، ودعوا الله أن ينشر لهم من رحمته ويهيئ لهم رشداً. فأنامهم الله في الكهف سنين طويلة، وحفظهم طوال تلك المدة.","ثم أيقظهم الله بعد سنين كثيرة. ظنوا أنهم ناموا يوماً أو بعض يوم، لكن قصتهم أصبحت آية للناس على قدرة الله وعلى حقيقة البعث."],lesson:"الصديق الصالح والشجاعة في التمسك بالخير يساعداننا عندما يكون الطريق صعباً."},
 {id:"maryam",icon:"🌸",title:"مريم وعيسى عليه السلام",ref:"مريم 16–36",tone:["#F3DDE5","#F7EFDA"],intro:"قصة مريم الصادقة وبشارة عيسى عليه السلام.",story:["كانت مريم عليها السلام فتاة طاهرة عابدة. ابتعدت عن أهلها إلى مكان شرقي، فأرسل الله إليها الملك في صورة بشر، فخافت واستعاذت بالله.","طمأنها الملك وأخبرها أن الله سيهب لها غلاماً طاهراً. تعجبت مريم، فأخبرها أن ذلك على الله يسير، وأن هذا الطفل سيكون آية ورحمة للناس.","وحين ولدت عيسى عليه السلام وعادت به إلى قومها تعجبوا وسألوها، فلم تدخل معهم في جدال، بل أشارت إلى الطفل. فأنطق الله عيسى وهو في المهد، فأعلن أنه عبد الله، وأن الله آتاه الكتاب وجعله نبياً."],lesson:"قد تقع أمور لا نفهم كيف ستنتهي، لكن قدرة الله أعظم من توقعاتنا."}
];

function Back({go}){return <button onClick={()=>go("kids-home")} style={{border:0,borderRadius:999,padding:"9px 14px",background:"rgba(255,255,255,.72)",fontFamily:"inherit",color:C.ink,boxShadow:"0 7px 22px rgba(37,50,56,.07)"}}>→ الأطفال</button>}

export default function KidsQuranStories({go}){
 const [selected,setSelected]=useState(null),[reading,setReading]=useState(false);
 const story=STORIES.find(x=>x.id===selected);
 useEffect(()=>()=>{try{speechSynthesis.cancel()}catch{}},[]);
 const stop=()=>{try{speechSynthesis.cancel()}catch{}setReading(false)};
 const readStory=()=>{if(!story||!("speechSynthesis" in window))return;stop();const text=[`قصة ${story.title}.`,...story.story,`ماذا نتعلم؟ ${story.lesson}`].join(" ");const u=new SpeechSynthesisUtterance(text);u.lang="ar-SA";u.rate=.88;u.pitch=1.02;const voices=speechSynthesis.getVoices();const voice=voices.find(v=>v.lang?.toLowerCase().startsWith("ar"));if(voice)u.voice=voice;u.onstart=()=>setReading(true);u.onend=()=>setReading(false);u.onerror=()=>setReading(false);speechSynthesis.speak(u)};
 if(story)return <div dir="rtl" style={{position:"fixed",inset:0,zIndex:50000,overflowY:"auto",background:C.ivory,color:C.ink,fontFamily:"inherit"}}><div style={{maxWidth:680,margin:"0 auto",padding:"28px 18px 120px"}}><button onClick={()=>{stop();setSelected(null)}} style={{border:0,borderRadius:999,padding:"9px 14px",background:"rgba(255,255,255,.75)",fontFamily:"inherit",color:C.ink}}>→ كل القصص</button><div style={{marginTop:18,borderRadius:34,padding:"26px 22px",background:`linear-gradient(145deg,${story.tone[0]},${story.tone[1]})`,minHeight:210,display:"flex",flexDirection:"column",justifyContent:"space-between"}}><div style={{fontSize:54}}>{story.icon}</div><div><div style={{fontSize:11,opacity:.5}}>قصة حقيقية من القرآن</div><h1 style={{margin:"5px 0 0",fontSize:32,lineHeight:1.5,fontWeight:600}}>{story.title}</h1><div style={{fontSize:11,color:C.gold,marginTop:5}}>{story.ref}</div></div></div><div style={{display:"flex",gap:9,marginTop:14}}><button onClick={reading?stop:readStory} style={{flex:1,minHeight:52,border:0,borderRadius:18,background:C.blue,color:"white",fontFamily:"inherit",fontSize:13,fontWeight:650}}>{reading?"■ إيقاف القراءة":"▶ اقرأ القصة لي"}</button><div style={{minWidth:94,borderRadius:18,display:"grid",placeItems:"center",background:"rgba(181,154,98,.12)",fontSize:10.5,color:"#876C38"}}>قراءة صوتية</div></div><p style={{fontSize:15,lineHeight:2,margin:"20px 4px 14px",opacity:.72}}>{story.intro}</p><article style={{padding:"22px 20px",borderRadius:28,background:"rgba(255,255,255,.72)",boxShadow:"0 14px 40px rgba(37,50,56,.045)"}}>{story.story.map((p,i)=><p key={i} style={{fontSize:16.5,lineHeight:2.15,margin:i?"18px 0 0":"0"}}>{p}</p>)}</article><div style={{marginTop:16,padding:18,borderRadius:24,background:C.blue,color:"white"}}><div style={{fontSize:10,opacity:.62}}>ماذا نتعلم؟</div><div style={{fontSize:14.5,lineHeight:1.9,marginTop:6}}>{story.lesson}</div></div><div style={{fontSize:10.5,opacity:.42,lineHeight:1.8,marginTop:14,textAlign:"center"}}>هذه صياغة مبسطة للطفل مبنية على الآيات المذكورة، دون إضافة أحداث غير ثابتة في القرآن.</div></div></div>;
 return <div dir="rtl" style={{position:"fixed",inset:0,zIndex:50000,overflowY:"auto",background:"linear-gradient(180deg,#F8F3E8,#F1F4EE)",color:C.ink,fontFamily:"inherit"}}><div style={{maxWidth:720,margin:"0 auto",padding:"26px 18px 120px"}}><Back go={go}/><div style={{marginTop:24,textAlign:"center"}}><div style={{fontSize:11,letterSpacing:.6,color:C.gold}}>سكينة للأطفال</div><h1 style={{fontSize:31,lineHeight:1.5,margin:"4px 0 0"}}>قصص حقيقية من القرآن</h1><p style={{fontSize:12.5,lineHeight:1.8,opacity:.5,margin:"7px auto 0",maxWidth:480}}>اختر قصة واقرأها لطفلك كحكاية متصلة، أو اضغط «اقرأ القصة لي» ليسمعها بصوت الجهاز.</p></div><div style={{display:"grid",gridTemplateColumns:"repeat(2,minmax(0,1fr))",gap:12,marginTop:22}}>{STORIES.map((s,i)=><button key={s.id} onClick={()=>setSelected(s.id)} style={{border:0,borderRadius:26,padding:0,overflow:"hidden",textAlign:"right",background:"rgba(255,255,255,.68)",boxShadow:"0 12px 34px rgba(37,50,56,.055)",fontFamily:"inherit",color:C.ink,cursor:"pointer"}}><div style={{height:112,padding:"16px",boxSizing:"border-box",background:`linear-gradient(145deg,${s.tone[0]},${s.tone[1]})`,display:"flex",alignItems:"flex-end",justifyContent:"space-between"}}><span style={{fontSize:38}}>{s.icon}</span><span style={{fontSize:9.5,opacity:.46}}>قصة {i+1}</span></div><div style={{padding:"14px 14px 16px"}}><div style={{fontSize:15,fontWeight:650,lineHeight:1.6}}>{s.title}</div><div style={{fontSize:9.5,color:C.gold,marginTop:4}}>{s.ref}</div><div style={{fontSize:10.5,opacity:.48,lineHeight:1.6,marginTop:7}}>{s.intro}</div></div></button>)}</div></div></div>;
}