import React,{useEffect,useRef,useState} from "react";
const C={ivory:"#F8F5EE",ink:"#26343B",lapis:"#173B57",gold:"#B59A62",sky:"#DCEEFF",lilac:"#EDE3FA",mint:"#DFF3E7",peach:"#FFE6CF",sun:"#FFF2B8"};
const DB="sakinah-kids-audio",STORE="nasheeds";
const BUILTIN=[
 {id:"bismillah",icon:"🌱",title:"بسم الله نبدأ",tone:C.mint,lines:["بسمِ اللهِ نبدأ يومي","وبذكرِ اللهِ يحلو يومي","قبلَ طعامي، قبلَ كلامي","بسمِ اللهِ نورٌ أمامي"]},
 {id:"hamd",icon:"☀️",title:"الحمد لله",tone:C.sun,lines:["الحمدُ للهِ على النِّعَمِ","على أهلي، صحتي، والهِمَمِ","أشكرُ ربي في كلِّ صباح","وبالحمدِ يمتلئُ القلبُ ارتياح"]},
 {id:"parents",icon:"💗",title:"ربي احفظ والديّ",tone:C.peach,lines:["ربي احفظ أمي وأبي","وازرعْ حبَّهما في قلبي","أحسنُ قولاً، أُهدي سلاماً","وأكونُ لهما طفلاً بسّاماً"]},
 {id:"prayer",icon:"🕌",title:"صلاتي جميلة",tone:C.sky,lines:["حينَ ينادينا الأذان","نمضي للصلاةِ بأمان","نتوضأُ، نقفُ بخشوع","ونعودُ بقلبٍ فيه نور"]},
 {id:"quran",icon:"📖",title:"قرآني نور",tone:C.lilac,lines:["قرآني نورٌ في دربي","وكلامُ اللهِ قريبٌ من قلبي","أقرأُ آياتٍ كلَّ يوم","وأتعلمُ خيرَ العلوم"]},
 {id:"kindness",icon:"🤍",title:"أنا طفل طيب",tone:C.mint,lines:["أبتسمُ دوماً، أقولُ كلاماً طيباً","أساعدُ غيري، وأكونُ حبيباً","لا أؤذي أحداً، لا أسخرُ أبداً","فالخلقُ الحسنُ يجعلُ يومي أسعد"]},
 {id:"salam",icon:"🌈",title:"السلام عليكم",tone:C.sky,lines:["السلامُ عليكم يا أحباب","تحيةُ خيرٍ تفتحُ الأبواب","أبدأُ بها حينَ ألقى صديقي","فتزيدُ محبةً في طريقي"]},
 {id:"sleep",icon:"🌙",title:"قبل أن أنام",tone:C.lilac,lines:["قبلَ النومِ أذكرُ ربي","وأجمعُ بالخيرِ قلبي","أغفو بهدوءٍ حتى الصباح","وأبدأُ يوماً مليئاً بالفلاح"]}
];
function openDb(){return new Promise((ok,fail)=>{const r=indexedDB.open(DB,1);r.onupgradeneeded=()=>{const db=r.result;if(!db.objectStoreNames.contains(STORE))db.createObjectStore(STORE,{keyPath:"id",autoIncrement:true})};r.onsuccess=()=>ok(r.result);r.onerror=()=>fail(r.error)})}
async function all(){const db=await openDb();return new Promise((ok,fail)=>{const tx=db.transaction(STORE,"readonly"),r=tx.objectStore(STORE).getAll();r.onsuccess=()=>ok(r.result||[]);r.onerror=()=>fail(r.error)})}
async function addFiles(files){const db=await openDb();return Promise.all([...files].map(file=>new Promise((ok,fail)=>{const tx=db.transaction(STORE,"readwrite"),r=tx.objectStore(STORE).add({name:file.name,type:file.type||"audio/*",size:file.size,blob:file,createdAt:Date.now()});r.onsuccess=()=>ok(r.result);r.onerror=()=>fail(r.error)})))}
async function del(id){const db=await openDb();return new Promise((ok,fail)=>{const tx=db.transaction(STORE,"readwrite"),r=tx.objectStore(STORE).delete(id);r.onsuccess=()=>ok();r.onerror=()=>fail(r.error)})}
function recite(lines,onDone){if(!window.speechSynthesis)return false;window.speechSynthesis.cancel();let i=0;const next=()=>{if(i>=lines.length){onDone?.();return}const u=new SpeechSynthesisUtterance(lines[i++]);u.lang="ar-SA";u.rate=.74;u.pitch=1.08;u.onend=()=>setTimeout(next,180);window.speechSynthesis.speak(u)};next();return true}
export function KidsNasheedsLive({lang="ar",go}){
 const [rows,setRows]=useState([]),[current,setCurrent]=useState(null),[song,setSong]=useState(null),[speaking,setSpeaking]=useState(false),[status,setStatus]=useState("");
 const urlRef=useRef(null);
 const reload=()=>all().then(setRows).catch(()=>setStatus(lang==="ar"?"تعذر فتح مكتبة الصوت المحلية":"Could not open local audio library"));
 useEffect(()=>{reload();return()=>{if(urlRef.current)URL.revokeObjectURL(urlRef.current);try{window.speechSynthesis?.cancel()}catch{}}},[]);
 const choose=x=>{try{window.speechSynthesis?.cancel()}catch{}setSpeaking(false);setSong(null);if(urlRef.current)URL.revokeObjectURL(urlRef.current);const url=URL.createObjectURL(x.blob);urlRef.current=url;setCurrent({...x,url})};
 const playBuiltin=x=>{if(urlRef.current){URL.revokeObjectURL(urlRef.current);urlRef.current=null}setCurrent(null);setSong(x);setSpeaking(true);if(!recite(x.lines,()=>setSpeaking(false))){setSpeaking(false);setStatus("القراءة الصوتية غير مدعومة في هذا المتصفح")}};
 const stop=()=>{try{window.speechSynthesis?.cancel()}catch{}setSpeaking(false)};
 const upload=async e=>{const files=e.target.files;if(!files?.length)return;try{await addFiles(files);setStatus(lang==="ar"?"تمت إضافة الأناشيد إلى مكتبتك الصغيرة ✨":"Nasheeds added to your little library ✨");await reload()}catch{setStatus(lang==="ar"?"تعذر حفظ الملفات":"Could not save files")}e.target.value=""};
 const remove=async id=>{await del(id);if(current?.id===id){if(urlRef.current)URL.revokeObjectURL(urlRef.current);urlRef.current=null;setCurrent(null)}reload()};
 const tones=[C.sky,C.lilac,C.mint,C.peach];
 return <div style={{position:"absolute",inset:0,background:"linear-gradient(180deg,#FFF9EF,#F3F8F5)",color:C.ink,display:"flex",flexDirection:"column"}} dir={lang==="ar"?"rtl":"ltr"}>
  <div style={{padding:"max(76px,calc(env(safe-area-inset-top) + 48px)) 18px 0"}}><button onClick={()=>go?.("kids-world")} style={{border:0,borderRadius:999,padding:"7px 12px",background:"rgba(255,255,255,.82)",boxShadow:"0 8px 24px rgba(38,52,59,.07)",fontFamily:"inherit",color:"inherit"}}>{lang==="ar"?"→ الأطفال":"← Kids"}</button></div>
  <div style={{flex:1,overflowY:"auto",padding:"16px 18px 130px"}}>
   <div style={{textAlign:"center"}}><div style={{fontSize:10,color:C.gold}}>🎵 سكينة للأطفال</div><div style={{fontSize:30,fontWeight:800,lineHeight:1.5,marginTop:3}}>أناشيدي الجميلة</div><div style={{fontSize:12,opacity:.5,lineHeight:1.8,margin:"6px auto 0",maxWidth:500}}>أناشيد قصيرة ولطيفة بقيم جميلة، ومعها مكتبتك الصوتية الخاصة.</div></div>
   <div style={{marginTop:18,padding:18,borderRadius:28,background:"linear-gradient(135deg,#FFF0C9,#DFF6FF 60%,#F3E7FF)",position:"relative",overflow:"hidden"}}><div style={{position:"absolute",left:15,top:10,fontSize:24}}>☁️</div><div style={{position:"absolute",right:16,bottom:9,fontSize:22}}>🌟</div><div style={{fontSize:11,opacity:.55}}>غنِّ وتعلّم</div><div style={{fontSize:23,fontWeight:800,marginTop:4}}>كلمات صغيرة.. معانٍ كبيرة 🎶</div><div style={{fontSize:11,opacity:.55,marginTop:5}}>اضغط على أي نشيد لقراءته للطفل، ويمكنه متابعة الكلمات على الشاشة.</div></div>
   <div style={{display:"flex",justifyContent:"space-between",alignItems:"end",marginTop:18}}><div><div style={{fontSize:14,fontWeight:800}}>أناشيد سكينة</div><div style={{fontSize:10,opacity:.45,marginTop:2}}>٨ أناشيد أصلية قصيرة للأطفال</div></div><div style={{fontSize:20}}>🎤</div></div>
   <div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:9,marginTop:10}}>{BUILTIN.map(x=><button key={x.id} onClick={()=>playBuiltin(x)} style={{minHeight:116,border:0,borderRadius:23,padding:14,background:x.tone,color:C.ink,fontFamily:"inherit",textAlign:"right",boxShadow:song?.id===x.id?`inset 0 0 0 2px ${C.gold}`:"inset 0 0 0 1px rgba(38,52,59,.035)"}}><span style={{fontSize:27,display:"block"}}>{x.icon}</span><b style={{fontSize:12.5,display:"block",marginTop:10}}>{x.title}</b><small style={{fontSize:9.5,opacity:.48,display:"block",marginTop:4}}>▶ اقرأ وغنِّ معي</small></button>)}</div>
   {song&&<div style={{marginTop:14,padding:18,borderRadius:26,background:song.tone,boxShadow:"0 14px 32px rgba(38,52,59,.06)"}}><div style={{display:"flex",justifyContent:"space-between",alignItems:"center"}}><div><small style={{opacity:.48}}>نشيد سكينة</small><div style={{fontSize:18,fontWeight:800,marginTop:2}}>{song.icon} {song.title}</div></div><button onClick={speaking?stop:()=>playBuiltin(song)} style={{border:0,borderRadius:999,padding:"9px 12px",background:C.lapis,color:"white",fontFamily:"inherit"}}>{speaking?"■ إيقاف":"▶ استمع"}</button></div><div style={{marginTop:15,padding:15,borderRadius:20,background:"rgba(255,255,255,.62)",textAlign:"center",fontSize:16,lineHeight:2.15,fontWeight:650}}>{song.lines.map((l,i)=><div key={i}>{l}</div>)}</div></div>}
   <div style={{marginTop:20,paddingTop:17,borderTop:"1px solid rgba(38,52,59,.07)"}}><div style={{fontSize:14,fontWeight:800}}>مكتبتك الصوتية</div><div style={{fontSize:10,opacity:.45,marginTop:3}}>يمكنك أيضاً إضافة ملفات أناشيد تملكها أو مسموح لك باستخدامها.</div></div>
   <label style={{display:"block",marginTop:11,padding:14,borderRadius:18,background:C.lapis,color:"white",textAlign:"center",fontSize:12.5,fontWeight:700,cursor:"pointer",boxShadow:"0 12px 28px rgba(23,59,87,.12)"}}>＋ أضف نشيداً من جهازك<input type="file" accept="audio/*" multiple hidden onChange={upload}/></label>
   {status&&<div style={{marginTop:10,padding:10,borderRadius:14,background:C.sun,fontSize:10.5,textAlign:"center"}}>{status}</div>}
   {current&&<div style={{marginTop:16,padding:18,borderRadius:26,background:C.lilac,boxShadow:"0 14px 32px rgba(38,52,59,.06)"}}><div style={{fontSize:10,opacity:.5}}>يُشغّل الآن</div><div style={{fontSize:13,fontWeight:750,overflow:"hidden",textOverflow:"ellipsis",whiteSpace:"nowrap",marginTop:2}}>{current.name}</div><audio src={current.url} controls autoPlay style={{width:"100%",marginTop:13}}/></div>}
   <div style={{marginTop:10,display:"grid",gap:9}}>{rows.map((x,i)=><div key={x.id} style={{display:"grid",gridTemplateColumns:"52px 1fr auto",gap:10,alignItems:"center",padding:11,borderRadius:20,background:tones[i%tones.length]}}><button onClick={()=>choose(x)} style={{width:48,height:48,border:0,borderRadius:17,background:"rgba(255,255,255,.72)",fontSize:20}}>▶</button><button onClick={()=>choose(x)} style={{border:0,background:"transparent",fontFamily:"inherit",textAlign:"right",color:"inherit",minWidth:0}}><b style={{fontSize:12.5,display:"block",overflow:"hidden",textOverflow:"ellipsis",whiteSpace:"nowrap"}}>{x.name}</b><small style={{opacity:.42}}>{Math.max(1,Math.round((x.size||0)/1024/1024*10)/10)} MB</small></button><button onClick={()=>remove(x.id)} style={{width:36,height:36,border:0,borderRadius:13,background:"rgba(255,255,255,.5)",color:"#A44D3C"}}>×</button></div>)}</div>
  </div>
 </div>
}
