const ITEMS=[
 {rx:/القرآن الكريم|Quran/i,svg:'<svg viewBox="0 0 24 24"><path class="lux-fill" d="M4.1 5.6c2.9-.8 5.4-.3 7.9 1.4v12c-2.5-1.4-5-1.8-7.9-1z"/><path class="lux-fill lux-alt" d="M19.9 5.6c-2.9-.8-5.4-.3-7.9 1.4v12c2.5-1.4 5-1.8 7.9-1z"/><path class="lux-gold" d="M12 7v12"/><path class="lux-line" d="m12 9.2 1 1.1-1 1.1-1-1.1z"/></svg>'},
 {rx:/^المعلم$|المعلّم|Teacher/i,svg:'<svg viewBox="0 0 24 24"><circle class="lux-fill" cx="12" cy="7.5" r="3"/><path class="lux-fill lux-alt" d="M6.2 19.3c.8-3.4 2.7-5.1 5.8-5.1s5 1.7 5.8 5.1z"/><path class="lux-line" d="M17.2 7.1 20 5.7v7.1l-2.8-1.4"/><path class="lux-gold" d="M8.5 19.3h7"/></svg>'},
 {rx:/^الأناشيد$|Nasheeds/i,svg:'<svg viewBox="0 0 24 24"><path class="lux-fill" d="M9.4 18.2V6.4l8.2-1.7v11.8"/><circle class="lux-fill lux-alt" cx="6.8" cy="18.1" r="2.4"/><circle class="lux-fill lux-alt" cx="15" cy="16.4" r="2.4"/><path class="lux-gold" d="M9.4 8.4l8.2-1.7"/></svg>'},
 {rx:/أناشيد الأطفال|Kids Nasheeds/i,svg:'<svg viewBox="0 0 24 24"><path class="lux-fill" d="M9.2 17.8V7.2l7.6-1.5v10.6"/><circle class="lux-fill lux-alt" cx="6.6" cy="17.8" r="2.3"/><circle class="lux-fill lux-alt" cx="14.3" cy="16.3" r="2.3"/><path class="lux-gold" d="M4.6 5.3 5.2 4l.6 1.3 1.3.6-1.3.6-.6 1.3-.6-1.3-1.3-.6z"/></svg>'}
];
function style(){if(document.getElementById('kids-shelf-luxury-icons'))return;const s=document.createElement('style');s.id='kids-shelf-luxury-icons';s.textContent=`.kids-shelf-lux-icon{display:grid!important;place-items:center!important;color:#9d9689!important;background:rgba(255,255,255,.34)!important}.kids-shelf-lux-icon svg{width:26px!important;height:26px!important;display:block!important}.kids-shelf-lux-icon .lux-fill{fill:currentColor;opacity:.13;stroke:currentColor;stroke-width:1.35;stroke-linecap:round;stroke-linejoin:round}.kids-shelf-lux-icon .lux-alt{opacity:.08}.kids-shelf-lux-icon .lux-line{fill:none;stroke:currentColor;stroke-width:1.35;stroke-linecap:round;stroke-linejoin:round}.kids-shelf-lux-icon .lux-gold{fill:#b59a62;stroke:#b59a62;stroke-width:1.1;stroke-linecap:round;stroke-linejoin:round}`;document.head.appendChild(s)}
function iconSlot(btn){const els=[...btn.children].filter(x=>x.tagName==='DIV'||x.tagName==='SPAN');return els.find(x=>{if(x.classList.contains('kids-shelf-lux-icon'))return true;const t=(x.textContent||'').trim();return x.querySelector('svg')||t.length<=3})||els[0]||null}
function apply(){style();document.querySelectorAll('button').forEach(btn=>{const text=(btn.textContent||'').replace(/\s+/g,' ').trim();const item=ITEMS.find(x=>x.rx.test(text));if(!item)return;const slot=iconSlot(btn);if(!slot)return;slot.innerHTML=item.svg;slot.classList.add('kids-shelf-lux-icon');slot.dataset.kidsShelfLux='1'})}
export function installKidsShelfLuxuryIcons(){apply();let q=false;const run=()=>{if(q)return;q=true;requestAnimationFrame(()=>{q=false;apply()})};new MutationObserver(run).observe(document.body,{childList:true,subtree:true});document.addEventListener('click',run,true);window.addEventListener('sakinah:feature',run);window.addEventListener('sakinah:global-root',run)}
