import React,{useEffect,useMemo,useRef,useState} from "react";

const C={bg:"#16232E",bg2:"#1B2A36",ivory:"#F6F3EC",text:"#F7F4EC",gold:"#C0A062",gold2:"#D9BC80",ink:"#16232E",muted:"rgba(247,244,236,.48)"};
const SURAH_AR=["الفاتحة","البقرة","آل عمران","النساء","المائدة","الأنعام","الأعراف","الأنفال","التوبة","يونس","هود","يوسف","الرعد","إبراهيم","الحجر","النحل","الإسراء","الكهف","مريم","طه","الأنبياء","الحج","المؤمنون","النور","الفرقان","الشعراء","النمل","القصص","العنكبوت","الروم","لقمان","السجدة","الأحزاب","سبأ","فاطر","يس","الصافات","ص","الزمر","غافر","فصلت","الشورى","الزخرف","الدخان","الجاثية","الأحقاف","محمد","الفتح","الحجرات","ق","الذاريات","الطور","النجم","القمر","الرحمن","الواقعة","الحديد","المجادلة","الحشر","الممتحنة","الصف","الجمعة","المنافقون","التغابن","الطلاق","التحريم","الملك","القلم","الحاقة","المعارج","نوح","الجن","المزمل","المدثر","القيامة","الإنسان","المرسلات","النبأ","النازعات","عبس","التكوير","الانفطار","المطففين","الانشقاق","البروج","الطارق","الأعلى","الغاشية","الفجر","البلد","الشمس","الليل","الضحى","الشرح","التين","العلق","القدر","البينة","الزلزلة","العاديات","القارعة","التكاثر","العصر","الهمزة","الفيل","قريش","الماعون","الكوثر","الكافرون","النصر","المسد","الإخلاص","الفلق","الناس"];
const HEIGHTS=[22,34,18,44,28,52,30,20,38,26,48,24,36,58,32,22,42,28,50,20,34,46,26,38,18,54,30,24,44,32,20,40,28,36,22,48,26,34,19,30];
const fmt=n=>!Number.isFinite(n)?"00:00":`${String(Math.floor(n/60)).padStart(2,"0")}:${String(Math.floor(n%60)).padStart(2,"0")}`;
const ar=n=>String(n).replace(/\d/g,d=>"٠١٢٣٤٥٦٧٨٩"[d]);
const safe=v=>String(v||"سورة").replace(/[\\/:*?"<>|]+/g,"-").trim();
const iconBtn={border:0,background:"transparent",color:"inherit",fontFamily:"inherit",cursor:"pointer",padding:0};
function TeacherIcon(){return <svg viewBox="0 0 32 32" width="28" height="28" aria-hidden="true"><circle cx="16" cy="9" r="5" fill="#D8D9D6"/><path d="M7 26c.7-6.4 4.1-9.4 9-9.4s8.3 3 9 9.4" fill="#F7F5EE"/><path d="M11 27h10" stroke="#B8944F" strokeWidth="1.8" strokeLinecap="round"/><path d="M24 8.5v8" stroke="#B8944F" strokeWidth="1.5" strokeLinecap="round"/></svg>}
function NasheedIcon(){return <svg viewBox="0 0 32 32" width="28" height="28" aria-hidden="true"><path d="M20 7v13.3a4.8 4.8 0 1 1-2-3.9V9.5l9-2v10.8a4.8 4.8 0 1 1-2-3.9V5.8z" fill="#B8944F"/></svg>}
function KidsIcon(){return <svg viewBox="0 0 32 32" width="28" height="28" aria-hidden="true"><path d="M18 8v12.2a4.4 4.4 0 1 1-2-3.7V9.8l8-1.8v9.7a4.4 4.4 0 1 1-2-3.7V6.2z" fill="#D9DAD7"/><path d="M7.2 8.2l.9 2.1 2.1.9-2.1.9-.9 2.1-.9-2.1-2.1-.9 2.1-.9z" fill="#B8944F"/></svg>}
function Shell({children}){return <div className="mm-quran-player" dir="rtl"><style>{`.mm-quran-player{position:absolute;inset:0;background:#0E1720;overflow:hidden;font-family:'Noto Kufi Arabic',Tahoma,sans-serif;color:${C.text}}.mm-quran-scroll{height:100%;overflow-y:auto;scrollbar-width:none;background:${C.bg};max-width:520px;margin:auto;box-shadow:0 40px 90px -40px rgba(0,0,0,.8)}.mm-quran-scroll::-webkit-scrollbar{display:none}.mm-tap{transition:transform .15s ease,opacity .2s ease}.mm-tap:active{transform:scale(.96)}.mm-wavebar{transition:background .12s linear}.mm-surah-card{transition:background .16s ease,border-color .16s ease}.mm-surah-card:active{transform:scale(.985)}@media(min-width:700px){.mm-quran-scroll{margin:18px auto;height:calc(100% - 36px);border-radius:34px;border:1px solid rgba(192,160,98,.14)}}`}</style><div className="mm-quran-scroll">{children}</div></div>}
export function LiveQuranAudio({lang="ar",go,initialSurah=1}){
 const audio=useRef(null); const [reciters,setReciters]=useState([]),[selected,setSelected]=useState(null),[moshaf,setMoshaf]=useState(null); const [surah,setSurah]=useState(Number(initialSurah)||1),[playing,setPlaying]=useState(false),[pos,setPos]=useState(0),[dur,setDur]=useState(0); const [speed,setSpeed]=useState(1),[repeat,setRepeat]=useState(false),[shuffle,setShuffle]=useState(false),[favorite,setFavorite]=useState(false),[downloading,setDownloading]=useState(false),[recOpen,setRecOpen]=useState(false),[loopSection,setLoopSection]=useState(true),[ayahs,setAyahs]=useState([]); const [loading,setLoading]=useState(true),[err,setErr]=useState("");
 useEffect(()=>{setLoading(true);fetch(`https://www.mp3quran.net/api/v3/reciters?language=${lang==="ar"?"ar":"eng"}`).then(r=>{if(!r.ok)throw new Error();return r.json()}).then(x=>{const rows=(x.reciters||[]).map(r=>({...r,moshaf:(r.moshaf||[]).filter(m=>Number(m.surah_total)===114)})).filter(r=>r.moshaf.length);setReciters(rows);setSelected(rows[0]||null);setMoshaf(rows[0]?.moshaf?.[0]||null);setLoading(false)}).catch(()=>{setErr("تعذر تحميل مكتبة القرّاء");setLoading(false)})},[lang]);
 useEffect(()=>{fetch(`https://api.alquran.cloud/v1/surah/${surah}/quran-uthmani`).then(r=>r.json()).then(j=>setAyahs(j?.data?.ayahs||[])).catch(()=>setAyahs([]))},[surah]);
 const src=moshaf?`${moshaf.server}${String(surah).padStart(3,"0")}.mp3`:""; useEffect(()=>{if(audio.current)audio.current.playbackRate=speed},[speed,src]); useEffect(()=>{try{const list=JSON.parse(localStorage.getItem("muslim-mirror-quran-favorites")||"[]");setFavorite(Array.isArray(list)&&list.some(x=>x.src===src))}catch{setFavorite(false)}},[src]);
 const pct=dur?Math.min(1,pos/dur):0,played=Math.round(pct*HEIGHTS.length),ayahIndex=ayahs.length?Math.min(ayahs.length-1,Math.floor(pct*ayahs.length)):0,currentAyah=ayahs[ayahIndex],remaining=Math.max(0,dur-pos);
 const toggle=()=>{if(!audio.current||!src)return;audio.current.paused?audio.current.play().catch(()=>{}):audio.current.pause()}; const changeSurah=n=>{let next=Math.min(114,Math.max(1,n));if(shuffle)next=1+Math.floor(Math.random()*114);audio.current?.pause();setSurah(next);setPos(0);setPlaying(false)}; const seek=e=>{if(!audio.current||!dur)return;const r=e.currentTarget.getBoundingClientRect(),p=Math.min(1,Math.max(0,(e.clientX-r.left)/r.width));audio.current.currentTime=p*dur;setPos(p*dur)};
 const toggleFavorite=()=>{if(!src)return;try{const key="muslim-mirror-quran-favorites",raw=JSON.parse(localStorage.getItem(key)||"[]"),list=Array.isArray(raw)?raw:[],i=list.findIndex(x=>x.src===src);if(i>=0)list.splice(i,1);else list.unshift({src,surah:SURAH_AR[surah-1],reciter:selected?.name||"",savedAt:Date.now()});localStorage.setItem(key,JSON.stringify(list));setFavorite(i<0)}catch{}};
 const download=async()=>{if(!src||downloading)return;setDownloading(true);const filename=`Muslim Mirror - سورة ${safe(SURAH_AR[surah-1])}${selected?.name?` - ${safe(selected.name)}`:""}.mp3`;try{const r=await fetch(src,{mode:"cors"});if(!r.ok)throw new Error();const blob=await r.blob(),url=URL.createObjectURL(blob),a=document.createElement("a");a.href=url;a.download=filename;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),30000)}catch{window.open(src,"_blank","noopener")}finally{setDownloading(false)}}; const chooseReciter=r=>{audio.current?.pause();setSelected(r);setMoshaf(r.moshaf[0]);setRecOpen(false);setPos(0);setPlaying(false)};
 const tabs=[["quran-teacher",<TeacherIcon/>,"المعلّم"],["adult-nasheeds",<NasheedIcon/>,"الأناشيد"],["kids-nasheeds",<KidsIcon/>,"أناشيد الأطفال"]];
 return <Shell><audio ref={audio} src={src} loop={repeat} preload="metadata" onPlay={()=>setPlaying(true)} onPause={()=>setPlaying(false)} onLoadedMetadata={e=>setDur(e.currentTarget.duration)} onTimeUpdate={e=>setPos(e.currentTarget.currentTime)} onEnded={()=>{setPlaying(false);if(!repeat)changeSurah(surah+1)}}/><div style={{minHeight:"100%",position:"relative",background:`radial-gradient(110% 55% at 50% -6%,rgba(192,160,98,.24),transparent 62%),${C.bg}`}}>
 <header style={{padding:"20px 24px 0",position:"relative",minHeight:32,display:"flex",alignItems:"center",justifyContent:"center"}}><button className="mm-tap" onClick={()=>go?.("quran-home")} style={{...iconBtn,position:"absolute",right:24,fontSize:20,color:"rgba(247,244,236,.7)"}}>→</button><div style={{textAlign:"center",fontFamily:"Amiri,serif",fontSize:22,whiteSpace:"nowrap"}}>مِرْآةُ الْمُسْلِمِ</div></header>
 <div style={{margin:"18px 24px 0",display:"grid",gridTemplateColumns:"repeat(3,minmax(0,1fr))",gap:10}}>{tabs.map(([id,ic,label])=><button key={id} className="mm-tap" onClick={()=>go?.(id)} style={{minWidth:0,minHeight:102,padding:"14px 4px 12px",borderRadius:20,border:"1px solid rgba(192,160,98,.42)",background:C.ivory,color:C.ink,fontFamily:"inherit",cursor:"pointer",display:"flex",flexDirection:"column",alignItems:"center",justifyContent:"center",gap:8,boxShadow:"0 10px 26px rgba(0,0,0,.08)"}}><span style={{height:30,display:"grid",placeItems:"center"}}>{ic}</span><span style={{fontSize:11,whiteSpace:"nowrap"}}>{label}</span></button>)}</div>
 <div style={{padding:"26px 34px 20px",textAlign:"center"}}><div style={{fontSize:12,color:C.muted,minHeight:20}}>{loading?"تحميل القرّاء…":err||`${selected?.name||""}${moshaf?.name?` · ${moshaf.name}`:""}`}</div><div style={{display:"grid",gridTemplateColumns:"30px 1fr 30px",alignItems:"center",marginTop:15}}><button className="mm-tap" onClick={toggleFavorite} style={{...iconBtn,fontSize:19,color:favorite?C.gold:"rgba(247,244,236,.62)"}}>{favorite?"♥":"♡"}</button><div style={{fontFamily:"monospace",fontSize:10,letterSpacing:".20em",color:"rgba(247,244,236,.32)",direction:"ltr"}}>SURAH {String(surah).padStart(3,"0")}</div><button className="mm-tap" onClick={download} style={{...iconBtn,fontSize:20,color:downloading?C.gold:"rgba(247,244,236,.62)"}}>⤓</button></div></div>
 <section style={{margin:"0 24px",padding:"18px 18px 19px",borderRadius:20,background:"rgba(247,244,236,.055)",border:"1px solid rgba(247,244,236,.08)"}}><div style={{display:"grid",gridTemplateColumns:"1fr auto 1fr",alignItems:"center"}}><span style={{fontSize:10.5,color:"rgba(247,244,236,.42)"}}>متابعة الآية</span><span style={{fontFamily:"Amiri,serif",fontSize:20,padding:"0 8px"}}>سورة {SURAH_AR[surah-1]}</span><span style={{fontFamily:"monospace",fontSize:9.5,letterSpacing:".15em",color:C.gold,direction:"ltr",textAlign:"left"}}>AYAH {currentAyah?.numberInSurah||"—"}</span></div><div style={{fontFamily:"'Amiri Quran','Amiri',serif",fontSize:25,lineHeight:2.05,marginTop:12,textAlign:"center",minHeight:90,display:"grid",placeItems:"center"}}>{currentAyah?.text||"يتم تحميل نص الآية…"}</div></section>
 <div style={{padding:"22px 30px 0"}}><div onClick={seek} style={{display:"flex",alignItems:"flex-end",gap:2,height:56,cursor:"pointer"}}>{HEIGHTS.map((h,i)=><span className="mm-wavebar" key={i} style={{flex:1,height:h,borderRadius:2,background:i<played?C.gold:"rgba(247,244,236,.18)"}}/>)}</div><div style={{display:"flex",justifyContent:"space-between",marginTop:10,fontFamily:"monospace",fontSize:11,color:"rgba(247,244,236,.5)",direction:"ltr"}}><span>{fmt(pos)}</span><span>-{fmt(remaining)}</span></div></div>
 <div style={{padding:"14px 32px 0",display:"flex",alignItems:"center",justifyContent:"space-between"}}><button className="mm-tap" onClick={()=>setRepeat(v=>!v)} style={{...iconBtn,fontSize:20,color:repeat?C.gold:"rgba(247,244,236,.45)"}}>↻</button><button className="mm-tap" onClick={()=>changeSurah(surah-1)} style={{...iconBtn,fontSize:23,color:"rgba(247,244,236,.88)",direction:"ltr"}}>▶❙</button><button className="mm-tap" onClick={toggle} style={{width:70,height:70,borderRadius:"50%",border:0,background:C.gold,color:C.ink,fontSize:23,cursor:"pointer",boxShadow:"0 14px 32px -12px rgba(192,160,98,.9)"}}>{playing?"❚❚":"▶"}</button><button className="mm-tap" onClick={()=>changeSurah(surah+1)} style={{...iconBtn,fontSize:23,color:"rgba(247,244,236,.88)",direction:"ltr"}}>❙◀</button><button className="mm-tap" onClick={()=>setShuffle(v=>!v)} style={{...iconBtn,fontSize:20,color:shuffle?C.gold:"rgba(247,244,236,.45)"}}>⇄</button></div>
 <section style={{margin:"18px 24px 0",padding:"16px 18px",borderRadius:18,background:"rgba(192,160,98,.11)",border:"1px solid rgba(192,160,98,.18)"}}><div style={{display:"flex",justifyContent:"space-between",alignItems:"center"}}><div><div style={{fontSize:12}}>تكرار المقطع</div><div style={{fontSize:10,color:C.muted,marginTop:4}}>للحفظ والمراجعة</div></div><button onClick={()=>setLoopSection(v=>!v)} style={{width:43,height:24,borderRadius:20,border:0,padding:3,background:loopSection?C.gold:"rgba(247,244,236,.14)",cursor:"pointer"}}><span style={{display:"block",width:18,height:18,borderRadius:"50%",background:C.ivory,transform:`translateX(${loopSection?-17:0}px)`,transition:"transform .18s"}}/></button></div><div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:9,marginTop:14}}><button style={{padding:"10px",borderRadius:12,border:"1px solid rgba(247,244,236,.08)",background:"rgba(247,244,236,.04)",color:C.text,fontFamily:"inherit",fontSize:10}}>بداية · {fmt(Math.max(0,pos-12))}</button><button style={{padding:"10px",borderRadius:12,border:"1px solid rgba(247,244,236,.08)",background:"rgba(247,244,236,.04)",color:C.text,fontFamily:"inherit",fontSize:10}}>نهاية · {fmt(Math.min(dur||pos+12,pos+12))}</button></div></section>
 <div style={{padding:"18px 24px 0",display:"flex",justifyContent:"space-between",alignItems:"center"}}><span style={{fontSize:11,color:C.muted}}>سرعة التشغيل</span><div style={{display:"flex",gap:7}}>{[.75,1,1.25,1.5].map(x=><button key={x} onClick={()=>setSpeed(x)} style={{minWidth:46,padding:"8px 7px",borderRadius:12,border:`1px solid ${speed===x?C.gold:"rgba(247,244,236,.08)"}`,background:speed===x?C.gold:"rgba(247,244,236,.035)",color:speed===x?C.ink:C.text,fontFamily:"inherit",fontSize:10}}>{x}×</button>)}</div></div>
 <section style={{marginTop:24,padding:"20px 24px",borderTop:"1px solid rgba(247,244,236,.07)"}}><div style={{display:"flex",justifyContent:"space-between",alignItems:"center"}}><div><div style={{fontSize:11,color:C.muted}}>القارئ</div><div style={{fontFamily:"Amiri,serif",fontSize:23,marginTop:5}}>{selected?.name||"—"}</div></div><button onClick={()=>setRecOpen(v=>!v)} style={{padding:"10px 13px",borderRadius:12,border:"1px solid rgba(192,160,98,.26)",background:"transparent",color:C.gold,fontFamily:"inherit",fontSize:10}}>تغيير القارئ</button></div>{recOpen&&<div style={{marginTop:13,maxHeight:230,overflowY:"auto",borderTop:"1px solid rgba(247,244,236,.06)"}}>{reciters.map(r=><button key={r.id} onClick={()=>chooseReciter(r)} style={{width:"100%",padding:"13px 2px",border:0,borderBottom:"1px solid rgba(247,244,236,.055)",background:"transparent",color:C.text,textAlign:"right",fontFamily:"inherit"}}>{r.name}</button>)}</div>}</section>
 <section style={{padding:"8px 24px 120px"}}><div style={{display:"flex",justifyContent:"space-between",alignItems:"end",marginBottom:13}}><div><div style={{fontSize:11,color:C.muted}}>السور</div><div style={{fontFamily:"Amiri,serif",fontSize:24,marginTop:3}}>القرآن الكريم</div></div><span style={{fontSize:10,color:C.gold}}>١١٤ سورة</span></div><div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:9}}>{SURAH_AR.map((name,i)=>{const active=i+1===surah;return <button className="mm-surah-card" key={name} onClick={()=>changeSurah(i+1)} style={{minHeight:72,padding:"11px 12px",borderRadius:15,border:`1px solid ${active?"rgba(192,160,98,.6)":"rgba(247,244,236,.07)"}`,background:active?"rgba(192,160,98,.12)":"rgba(247,244,236,.025)",color:C.text,fontFamily:"inherit",textAlign:"right",display:"grid",gridTemplateColumns:"1fr 30px",alignItems:"center",gap:8}}><span><b style={{display:"block",fontFamily:"Amiri,serif",fontSize:18,fontWeight:400}}>سورة {name}</b><small style={{display:"block",fontSize:9,color:C.muted,marginTop:4}}>اضغط للاستماع</small></span><span style={{width:28,height:28,borderRadius:"50%",border:"1px solid rgba(192,160,98,.25)",display:"grid",placeItems:"center",fontSize:9,color:C.gold}}>{ar(i+1)}</span></button>})}</div></section>
 </div></Shell>;
}
