import React,{useEffect,useMemo,useState} from "react";

const C={ivory:"#F6F3EC",ink:"#10100F",lapis:"#173B57",gold:"#B59A62",red:"#9C4A3B"};
const btn={border:"1px solid rgba(16,16,15,.09)",borderRadius:14,padding:11,background:"transparent",fontFamily:"inherit",color:"inherit"};
const RX=/ذكر|دعاء|أذكار|أدعية|استعاذ|رقية|نوم|صباح|مساء|استغفار|تسبيح|تحميد|تكبير|تهليل|صلاة على النبي/;
function Shell({go,title="أذكار السنة الموثقة",sub="أذكار وأدعية من أحاديث HadeethEnc الموثقة",children}){return <div style={{position:"absolute",inset:0,background:C.ivory,color:C.ink,display:"flex",flexDirection:"column"}} dir="rtl"><div style={{padding:"22px 22px 0"}}><button onClick={()=>go?.(null)} style={{...btn,border:0,padding:0}}>رجوع ←</button></div><div style={{flex:1,overflowY:"auto",padding:"15px 22px 130px"}}><div style={{fontFamily:"Fraunces,serif",fontSize:29}}>{title}</div><div style={{fontSize:11.5,opacity:.48,lineHeight:1.7,marginTop:7}}>{sub}</div>{children}<div style={{fontSize:9.5,opacity:.42,lineHeight:1.7,marginTop:22}}>المصدر: HadeethEnc.com. لا يعرض سكينة نصاً منسوباً للسنة دون مصدر حي.</div></div></div>}
export function LiveSunnahAdhkar({go}){
 const [cats,setCats]=useState([]),[cat,setCat]=useState(null),[rows,setRows]=useState([]),[detail,setDetail]=useState(null),[q,setQ]=useState(""),[busy,setBusy]=useState(true),[err,setErr]=useState("");
 useEffect(()=>{fetch("https://hadeethenc.com/api/v1/categories/roots/?language=ar").then(r=>{if(!r.ok)throw new Error();return r.json()}).then(x=>{const all=Array.isArray(x)?x:[];const filtered=all.filter(c=>RX.test(c.title||""));setCats(filtered.length?filtered:all);setBusy(false)}).catch(()=>{setErr("تعذر الاتصال بمصدر الأذكار حالياً");setBusy(false)})},[]);
 const openCat=c=>{setCat(c);setRows([]);setDetail(null);setErr("");setBusy(true);fetch(`https://hadeethenc.com/api/v1/hadeeths/list/?language=ar&category_id=${encodeURIComponent(c.id)}&page=1&per_page=100`).then(r=>{if(!r.ok)throw new Error();return r.json()}).then(x=>{setRows(Array.isArray(x.data)?x.data:[]);setBusy(false)}).catch(()=>{setErr("تعذر تحميل أحاديث هذا الباب");setBusy(false)})};
 const openHadith=h=>{setDetail(null);setErr("");setBusy(true);fetch(`https://hadeethenc.com/api/v1/hadeeths/one/?language=ar&id=${encodeURIComponent(h.id)}`).then(r=>{if(!r.ok)throw new Error();return r.json()}).then(x=>{setDetail(x||null);setBusy(false)}).catch(()=>{setErr("تعذر تحميل النص");setBusy(false)})};
 const shown=useMemo(()=>rows.filter(x=>(x.title||"").includes(q)),[rows,q]);
 if(detail)return <Shell go={()=>setDetail(null)} title={detail.title||"ذكر من السنة"} sub={detail.attribution||"حديث موثق"}><article style={{marginTop:18,padding:18,borderRadius:22,background:"rgba(255,255,255,.5)",border:"1px solid rgba(16,16,15,.07)"}}><div style={{fontFamily:"serif",fontSize:20,lineHeight:2}}>{detail.hadeeth||detail.hadith||detail.text||""}</div>{detail.explanation&&<><div style={{fontSize:12,fontWeight:700,marginTop:22}}>الشرح</div><div style={{fontSize:12,lineHeight:1.9,marginTop:8}}>{detail.explanation}</div></>}{Array.isArray(detail.hints)&&detail.hints.length>0&&<><div style={{fontSize:12,fontWeight:700,marginTop:22}}>الفوائد</div>{detail.hints.map((x,i)=><div key={i} style={{padding:"8px 0",borderTop:"1px solid rgba(16,16,15,.06)",fontSize:11.5,lineHeight:1.8}}>• {x}</div>)}</>}{detail.reference&&<div style={{marginTop:18,padding:12,borderRadius:14,background:"rgba(181,154,98,.10)",fontSize:10.5,lineHeight:1.7}}>{detail.reference}</div>}</article></Shell>;
 if(cat)return <Shell go={()=>{setCat(null);setRows([]);setQ("")}} title={cat.title||"باب الأذكار"} sub="اختر نصاً لعرض الحديث والشرح والمصدر"><input value={q} onChange={e=>setQ(e.target.value)} placeholder="ابحث في هذا الباب…" style={{...btn,width:"100%",boxSizing:"border-box",marginTop:16}}/>{busy&&<div style={{marginTop:20,opacity:.5}}>تحميل…</div>}{err&&<div style={{marginTop:16,color:C.red}}>{err}</div>}<div style={{marginTop:10}}>{shown.map(h=><button key={h.id} onClick={()=>openHadith(h)} style={{width:"100%",padding:"13px 2px",border:0,borderTop:"1px solid rgba(16,16,15,.07)",background:"transparent",fontFamily:"inherit",textAlign:"right",color:"inherit"}}><b style={{fontSize:12.5,lineHeight:1.7}}>{h.title}</b><small style={{display:"block",opacity:.4,marginTop:4}}>رقم {h.id}</small></button>)}</div></Shell>;
 return <Shell go={go}>{busy&&<div style={{marginTop:22,opacity:.5}}>تحميل أبواب الأذكار…</div>}{err&&<div style={{marginTop:18,color:C.red}}>{err}</div>}<div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:9,marginTop:18}}>{cats.map((c,i)=><button key={c.id} onClick={()=>openCat(c)} style={{...btn,minHeight:108,textAlign:"right",background:i===0?"linear-gradient(145deg,#173B57,#0C293E)":"rgba(255,255,255,.48)",color:i===0?"white":C.ink}}><div style={{fontSize:21,color:i===0?"#E7D29B":C.gold}}>✦</div><div style={{fontSize:12.5,fontWeight:700,lineHeight:1.6,marginTop:12}}>{c.title}</div></button>)}</div></Shell>;
}
