import React,{useEffect,useMemo,useRef,useState} from "react";

const C={ivory:"#F6F3EC",ink:"#10100F",lapis:"#173B57",gold:"#B59A62"};
const nd=(s,lang)=>lang==="ar"?String(s).replace(/[0-9]/g,d=>"٠١٢٣٤٥٦٧٨٩"[d]):String(s);
const fmt=n=>!Number.isFinite(n)?"0:00":`${Math.floor(n/60)}:${String(Math.floor(n%60)).padStart(2,"0")}`;
const SURAH_AR=["الفاتحة","البقرة","آل عمران","النساء","المائدة","الأنعام","الأعراف","الأنفال","التوبة","يونس","هود","يوسف","الرعد","إبراهيم","الحجر","النحل","الإسراء","الكهف","مريم","طه","الأنبياء","الحج","المؤمنون","النور","الفرقان","الشعراء","النمل","القصص","العنكبوت","الروم","لقمان","السجدة","الأحزاب","سبأ","فاطر","يس","الصافات","ص","الزمر","غافر","فصلت","الشورى","الزخرف","الدخان","الجاثية","الأحقاف","محمد","الفتح","الحجرات","ق","الذاريات","الطور","النجم","القمر","الرحمن","الواقعة","الحديد","المجادلة","الحشر","الممتحنة","الصف","الجمعة","المنافقون","التغابن","الطلاق","التحريم","الملك","القلم","الحاقة","المعارج","نوح","الجن","المزمل","المدثر","القيامة","الإنسان","المرسلات","النبأ","النازعات","عبس","التكوير","الانفطار","المطففين","الانشقاق","البروج","الطارق","الأعلى","الغاشية","الفجر","البلد","الشمس","الليل","الضحى","الشرح","التين","العلق","القدر","البينة","الزلزلة","العاديات","القارعة","التكاثر","العصر","الهمزة","الفيل","قريش","الماعون","الكوثر","الكافرون","النصر","المسد","الإخلاص","الفلق","الناس"];
function Shell({lang,go,children}){return <div style={{position:"absolute",inset:0,background:C.ivory,color:C.ink,display:"flex",flexDirection:"column"}}><style>{`.sakinah-audio-page{scrollbar-width:none;-ms-overflow-style:none}.sakinah-audio-page::-webkit-scrollbar{display:none;width:0;height:0}`}</style><div className="sakinah-audio-page" style={{flex:1,overflowY:"auto",padding:"22px 22px 130px"}}>{children}</div></div>}
export function LiveQuranAudio({lang,go,initialSurah=1}){
 const [reciters,setReciters]=useState([]),[selected,setSelected]=useState(null),[moshaf,setMoshaf]=useState(null),[surah,setSurah]=useState(Number(initialSurah)||1),[q,setQ]=useState(""),[loading,setLoading]=useState(true),[err,setErr]=useState(""),[playing,setPlaying]=useState(false),[pos,setPos]=useState(0),[dur,setDur]=useState(0),[speed,setSpeed]=useState(1),[repeat,setRepeat]=useState(false),[view,setView]=useState("player");
 const audio=useRef(null);
 useEffect(()=>{setLoading(true);fetch(`https://www.mp3quran.net/api/v3/reciters?language=${lang==="ar"?"ar":"eng"}`).then(r=>{if(!r.ok)throw new Error();return r.json()}).then(x=>{const rows=(x.reciters||[]).map(r=>({...r,moshaf:(r.moshaf||[]).filter(m=>Number(m.surah_total)===114)})).filter(r=>r.moshaf.length);setReciters(rows);setSelected(rows[0]||null);setMoshaf(rows[0]?.moshaf?.[0]||null);setLoading(false)}).catch(()=>{setErr(lang==="ar"?"تعذر تحميل مكتبة القرّاء":"Could not load reciter library");setLoading(false)})},[lang]);
 const src=moshaf?`${moshaf.server}${String(surah).padStart(3,"0")}.mp3`:"";
 useEffect(()=>{if(audio.current)audio.current.playbackRate=speed},[speed,src]);
 const filtered=useMemo(()=>reciters.filter(r=>(r.name||"").toLowerCase().includes(q.toLowerCase())),[reciters,q]);
 const openReciter=r=>{setSelected(r);setMoshaf(r.moshaf[0]);setPlaying(false);setPos(0);setView("surahs");requestAnimationFrame(()=>window.scrollTo(0,0))};
 const pickSurah=n=>{setSurah(n);setPlaying(false);setPos(0);setView("player");requestAnimationFrame(()=>window.scrollTo(0,0))};
 const toggle=()=>{if(!audio.current||!src)return;if(playing){audio.current.pause();setPlaying(false)}else{audio.current.play().then(()=>setPlaying(true)).catch(()=>{})}};
 if(view==="surahs")return <Shell lang={lang} go={go}><button onClick={()=>setView("player")} style={{border:0,background:"transparent",fontFamily:"inherit",cursor:"pointer",fontSize:14,textAlign:"right",padding:0}}>← رجوع</button><div style={{marginTop:18,fontFamily:"Fraunces,serif",fontSize:31}}>{selected?.name}</div><div style={{fontSize:12,opacity:.48,marginTop:6}}>{moshaf?.name||""}</div><div style={{fontSize:13,marginTop:22,marginBottom:8}}>اختر السورة</div><div>{SURAH_AR.map((name,i)=><button key={i+1} onClick={()=>pickSurah(i+1)} style={{width:"100%",display:"grid",gridTemplateColumns:"42px 1fr auto",alignItems:"center",gap:12,padding:"15px 2px",border:0,borderTop:"1px solid rgba(16,16,15,.07)",background:"transparent",fontFamily:"inherit",color:"inherit",textAlign:"right",cursor:"pointer"}}><span style={{width:34,height:34,borderRadius:"50%",display:"grid",placeItems:"center",border:"1px solid rgba(181,154,98,.28)",fontSize:11,color:C.gold}}>{nd(i+1,lang)}</span><b style={{fontSize:19,fontWeight:500}}>سورة {name}</b><span style={{opacity:.3,fontSize:18}}>←</span></button>)}</div></Shell>;
 return <Shell lang={lang} go={go}><audio ref={audio} src={src} loop={repeat} preload="metadata" onLoadedMetadata={e=>setDur(e.currentTarget.duration)} onTimeUpdate={e=>setPos(e.currentTarget.currentTime)} onEnded={()=>{setPlaying(false);if(!repeat&&surah<114)setSurah(v=>v+1)}}/>
  <button onClick={()=>go("quran-home")} style={{border:0,background:"transparent",fontFamily:"inherit",cursor:"pointer",color:"inherit",padding:0}}>← القرآن</button>
  <div style={{fontFamily:"Fraunces,serif",fontSize:29,marginTop:18}}>استمع للقرآن</div><div style={{fontSize:11.5,opacity:.48,marginTop:7}}>ختمات كاملة وروايات متعددة · مصدر حي</div>
  <div style={{marginTop:17,borderRadius:28,padding:19,background:"linear-gradient(145deg,#17232a,#0b1318)",color:"white",boxShadow:"0 20px 50px rgba(0,0,0,.18)"}}><div style={{aspectRatio:"1.45",borderRadius:22,display:"grid",placeItems:"center",background:"radial-gradient(circle at 35% 30%,rgba(181,154,98,.34),rgba(255,255,255,.035) 60%)",border:"1px solid rgba(255,255,255,.08)"}}><div style={{textAlign:"center"}}><div style={{fontFamily:"serif",fontSize:43}}>ٱلْقُرْآن</div><div style={{fontSize:9,opacity:.45,letterSpacing:".16em",marginTop:9}}>SAKINAH · AUDIO</div></div></div><div style={{textAlign:"center",marginTop:15}}><button onClick={()=>selected&&setView("surahs")} style={{border:0,background:"transparent",color:"white",fontFamily:"inherit",fontSize:21,cursor:"pointer"}}>{selected?.name||"اختر قارئاً"}</button><div style={{fontSize:10,opacity:.48,marginTop:5}}>{moshaf?.name||""} · سورة {SURAH_AR[surah-1]||nd(surah,lang)}</div></div><input type="range" min="0" max={dur||1} value={Math.min(pos,dur||1)} onChange={e=>{const v=Number(e.target.value);if(audio.current)audio.current.currentTime=v;setPos(v)}} style={{width:"100%",marginTop:17,accentColor:"#d5bd83"}}/><div style={{display:"flex",justifyContent:"space-between",fontSize:9,opacity:.45}}><span>{fmt(pos)}</span><span>{fmt(dur)}</span></div><div style={{display:"grid",gridTemplateColumns:"1fr 44px 62px 44px 1fr",gap:7,alignItems:"center",marginTop:12}}><button onClick={()=>setRepeat(v=>!v)} style={{border:0,background:"transparent",color:repeat?"#d5bd83":"white",opacity:repeat?1:.5,fontSize:19}}>↻</button><button onClick={()=>setSurah(v=>Math.max(1,v-1))} style={{height:44,border:0,borderRadius:"50%",background:"rgba(255,255,255,.08)",color:"white",fontSize:20}}>‹</button><button onClick={toggle} style={{height:62,border:0,borderRadius:"50%",background:C.ivory,fontSize:20}}>{playing?"Ⅱ":"▶"}</button><button onClick={()=>setSurah(v=>Math.min(114,v+1))} style={{height:44,border:0,borderRadius:"50%",background:"rgba(255,255,255,.08)",color:"white",fontSize:20}}>›</button><div/></div><div style={{display:"flex",gap:6,justifyContent:"center",marginTop:13}}>{[.75,1,1.25,1.5].map(x=><button key={x} onClick={()=>setSpeed(x)} style={{border:"1px solid rgba(255,255,255,.11)",borderRadius:13,padding:"5px 7px",background:speed===x?"rgba(213,189,131,.18)":"transparent",color:"white",fontSize:9}}>{x}×</button>)}</div></div>
  <input value={q} onChange={e=>setQ(e.target.value)} placeholder="ابحث باسم القارئ…" style={{marginTop:13,width:"100%",boxSizing:"border-box",padding:12,borderRadius:13,border:"1px solid rgba(16,16,15,.09)",background:"transparent",fontFamily:"inherit"}}/><div style={{fontSize:10,opacity:.45,marginTop:9}}>{loading?"تحميل القرّاء…":err||`${nd(filtered.length,lang)} قارئ بختمة كاملة متاح الآن`}</div>
  <div style={{marginTop:8}}>{filtered.map(r=><button key={r.id} onClick={()=>openReciter(r)} style={{width:"100%",border:0,borderTop:"1px solid rgba(16,16,15,.07)",background:selected?.id===r.id?"rgba(181,154,98,.08)":"transparent",padding:"15px 2px",fontFamily:"inherit",textAlign:"right",color:"inherit",cursor:"pointer"}}><b style={{fontSize:22.5,lineHeight:1.35}}>{r.name}</b><small style={{display:"block",opacity:.42,marginTop:6,fontSize:12}}>{r.moshaf.map(m=>m.name).join(" · ")}</small></button>)}</div>
 </Shell>
}
