import React,{useEffect,useMemo,useRef,useState} from "react";

const C={ivory:"#F6F3EC",paper:"#FCFAF5",ink:"#10100F",lapis:"#173B57",gold:"#B59A62",soft:"#9D9689"};
const nd=(s,lang)=>lang==="ar"?String(s).replace(/[0-9]/g,d=>"٠١٢٣٤٥٦٧٨٩"[d]):String(s);
const fmt=n=>!Number.isFinite(n)?"0:00":`${Math.floor(n/60)}:${String(Math.floor(n%60)).padStart(2,"0")}`;
const SURAH_AR=["الفاتحة","البقرة","آل عمران","النساء","المائدة","الأنعام","الأعراف","الأنفال","التوبة","يونس","هود","يوسف","الرعد","إبراهيم","الحجر","النحل","الإسراء","الكهف","مريم","طه","الأنبياء","الحج","المؤمنون","النور","الفرقان","الشعراء","النمل","القصص","العنكبوت","الروم","لقمان","السجدة","الأحزاب","سبأ","فاطر","يس","الصافات","ص","الزمر","غافر","فصلت","الشورى","الزخرف","الدخان","الجاثية","الأحقاف","محمد","الفتح","الحجرات","ق","الذاريات","الطور","النجم","القمر","الرحمن","الواقعة","الحديد","المجادلة","الحشر","الممتحنة","الصف","الجمعة","المنافقون","التغابن","الطلاق","التحريم","الملك","القلم","الحاقة","المعارج","نوح","الجن","المزمل","المدثر","القيامة","الإنسان","المرسلات","النبأ","النازعات","عبس","التكوير","الانفطار","المطففين","الانشقاق","البروج","الطارق","الأعلى","الغاشية","الفجر","البلد","الشمس","الليل","الضحى","الشرح","التين","العلق","القدر","البينة","الزلزلة","العاديات","القارعة","التكاثر","العصر","الهمزة","الفيل","قريش","الماعون","الكوثر","الكافرون","النصر","المسد","الإخلاص","الفلق","الناس"];
const softBtn={border:"1px solid rgba(16,16,15,.08)",background:"rgba(255,255,255,.58)",color:C.ink,fontFamily:"inherit"};

function Shell({children}){return <div style={{position:"absolute",inset:0,background:C.ivory,color:C.ink,overflow:"hidden"}}><style>{`.mm-audio{height:100%;overflow-y:auto;overflow-x:hidden;padding:18px 16px 132px;box-sizing:border-box;scrollbar-width:none}.mm-audio::-webkit-scrollbar{display:none}.mm-audio button{cursor:pointer}.mm-player{max-width:700px;margin:0 auto}.mm-press{transition:transform .15s ease,background .15s ease}.mm-press:active{transform:scale(.95)}.mm-playlist-row{transition:background .15s ease}.mm-playlist-row:active{background:rgba(181,154,98,.08)!important}@media(max-width:430px){.mm-audio{padding:16px 12px 126px}.mm-disc{width:248px!important;height:248px!important}.mm-disc svg{width:248px!important;height:248px!important}.mm-disc-core{inset:25px!important}.mm-title{font-size:27px!important}.mm-sub{font-size:11px!important}.mm-tool-label{font-size:9px!important}}`}</style><div className="mm-audio">{children}</div></div>}
function Icon({type,size=20}){const p={width:size,height:size,viewBox:"0 0 24 24",fill:"none",stroke:"currentColor",strokeWidth:1.55,strokeLinecap:"round",strokeLinejoin:"round"};if(type==="list")return <svg {...p}><path d="M6 7h12M6 12h12M6 17h12"/></svg>;if(type==="heart")return <svg {...p}><path d="M12 19s-7-4.3-7-9.1A3.9 3.9 0 0 1 12 7.5a3.9 3.9 0 0 1 7 2.4C19 14.7 12 19 12 19Z"/></svg>;if(type==="repeat")return <svg {...p}><path d="M7 7h9l-2-2M17 17H8l2 2M18 7a5 5 0 0 1 1 3M6 17a5 5 0 0 1-1-3"/></svg>;if(type==="timer")return <svg {...p}><circle cx="12" cy="13" r="7"/><path d="M9 3h6M12 6v2M12 13l3-2"/></svg>;if(type==="download")return <svg {...p}><path d="M12 4v11m-4-4 4 4 4-4M5 19h14"/></svg>;if(type==="search")return <svg {...p}><circle cx="10.5" cy="10.5" r="5.5"/><path d="m15 15 4 4"/></svg>;return <svg {...p}><circle cx="12" cy="12" r="8"/></svg>}
function safeName(v){return String(v||"سورة").replace(/[\\/:*?"<>|]+/g,"-").trim()||"سورة"}
function Top({title,onBack,caption}){return <div style={{display:"grid",gridTemplateColumns:"auto 1fr auto",alignItems:"center",gap:10}}><button onClick={onBack} style={{...softBtn,width:40,height:40,borderRadius:14}}>←</button><div style={{textAlign:"center"}}><div style={{fontSize:15,fontWeight:650}}>{title}</div>{caption&&<div style={{fontSize:9.5,opacity:.42,marginTop:2}}>{caption}</div>}</div><div style={{width:40}}/></div>}

export function LiveQuranAudio({lang="ar",go,initialSurah=1}){
 const [reciters,setReciters]=useState([]),[selected,setSelected]=useState(null),[moshaf,setMoshaf]=useState(null),[surah,setSurah]=useState(()=>Number(localStorage.getItem("muslim-mirror-last-surah"))||Number(initialSurah)||1),[q,setQ]=useState(""),[loading,setLoading]=useState(true),[err,setErr]=useState(""),[playing,setPlaying]=useState(false),[pos,setPos]=useState(0),[dur,setDur]=useState(0),[speed,setSpeed]=useState(1),[repeat,setRepeat]=useState(false),[view,setView]=useState("player"),[favorite,setFavorite]=useState(false),[downloading,setDownloading]=useState(false),[sleep,setSleep]=useState(0);
 const audio=useRef(null),autoPlayNext=useRef(false),sleepTimer=useRef(null);
 useEffect(()=>{setLoading(true);fetch(`https://www.mp3quran.net/api/v3/reciters?language=${lang==="ar"?"ar":"eng"}`).then(r=>{if(!r.ok)throw new Error();return r.json()}).then(x=>{const rows=(x.reciters||[]).map(r=>({...r,moshaf:(r.moshaf||[]).filter(m=>Number(m.surah_total)===114)})).filter(r=>r.moshaf.length);let saved=null;try{saved=JSON.parse(localStorage.getItem("muslim-mirror-last-reciter")||"null")}catch{}const first=rows.find(r=>r.id===saved?.id)||rows[0]||null;setReciters(rows);setSelected(first);setMoshaf(first?.moshaf?.find(m=>m.id===saved?.moshafId)||first?.moshaf?.[0]||null);setLoading(false)}).catch(()=>{setErr("تعذر تحميل مكتبة القرّاء");setLoading(false)})},[lang]);
 const src=moshaf?`${moshaf.server}${String(surah).padStart(3,"0")}.mp3`:"";
 useEffect(()=>{try{localStorage.setItem("muslim-mirror-last-surah",String(surah));if(selected&&moshaf)localStorage.setItem("muslim-mirror-last-reciter",JSON.stringify({id:selected.id,moshafId:moshaf.id}))}catch{}},[surah,selected,moshaf]);
 useEffect(()=>{if(audio.current)audio.current.playbackRate=speed},[speed,src]);
 useEffect(()=>{try{const list=JSON.parse(localStorage.getItem("muslim-mirror-quran-favorites")||"[]");setFavorite(Array.isArray(list)&&list.some(x=>x.src===src))}catch{setFavorite(false)}},[src]);
 useEffect(()=>{if(view!=="player"||!autoPlayNext.current||!audio.current||!src)return;autoPlayNext.current=false;requestAnimationFrame(()=>audio.current?.play().catch(()=>{}))},[view,src]);
 useEffect(()=>()=>{if(sleepTimer.current)clearTimeout(sleepTimer.current)},[]);
 const filtered=useMemo(()=>reciters.filter(r=>(r.name||"").toLowerCase().includes(q.toLowerCase())),[reciters,q]);
 const openReciter=r=>{audio.current?.pause();setSelected(r);setMoshaf(r.moshaf[0]);setPlaying(false);setPos(0);setView("surahs")};
 const pickSurah=n=>{autoPlayNext.current=true;setSurah(n);setPlaying(false);setPos(0);setView("player")};
 const changeSurah=n=>{const next=Math.min(114,Math.max(1,n));audio.current?.pause();if(audio.current)audio.current.currentTime=0;setSurah(next);setPlaying(false);setPos(0)};
 const seekBy=seconds=>{if(!audio.current)return;const next=Math.max(0,Math.min(dur||Infinity,audio.current.currentTime+seconds));audio.current.currentTime=next;setPos(next)};
 const toggle=()=>{if(!audio.current||!src)return;audio.current.paused?audio.current.play().catch(()=>{}):audio.current.pause()};
 const toggleFavorite=()=>{if(!src)return;try{const key="muslim-mirror-quran-favorites",raw=JSON.parse(localStorage.getItem(key)||"[]"),list=Array.isArray(raw)?raw:[],i=list.findIndex(x=>x.src===src);if(i>=0)list.splice(i,1);else list.unshift({src,surah:SURAH_AR[surah-1],reciter:selected?.name||"",savedAt:Date.now()});localStorage.setItem(key,JSON.stringify(list));setFavorite(i<0)}catch{}};
 const setSleepTimer=min=>{if(sleepTimer.current)clearTimeout(sleepTimer.current);setSleep(min);if(min>0)sleepTimer.current=setTimeout(()=>{audio.current?.pause();setSleep(0)},min*60*1000)};
 const download=async()=>{if(!src||downloading)return;setDownloading(true);const filename=`Muslim Mirror - سورة ${safeName(SURAH_AR[surah-1])}${selected?.name?` - ${safeName(selected.name)}`:""}.mp3`;try{const r=await fetch(src,{mode:"cors"});if(!r.ok)throw new Error();const blob=await r.blob(),url=URL.createObjectURL(blob),a=document.createElement("a");a.href=url;a.download=filename;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),30000)}catch{window.open(src,"_blank","noopener")}finally{setDownloading(false)}};
 const pct=dur?Math.max(0,Math.min(1,pos/dur)):0,circ=2*Math.PI*111;

 if(view==="surahs")return <Shell><div className="mm-player" dir="rtl"><Top title="قائمة السور" caption={selected?.name||""} onBack={()=>setView("player")}/><div style={{display:"flex",justifyContent:"space-between",alignItems:"center",marginTop:22,padding:"0 4px"}}><div><div style={{fontSize:22,fontWeight:650}}>١١٤ سورة</div><div style={{fontSize:10.5,opacity:.42,marginTop:3}}>{moshaf?.name||""}</div></div><button onClick={()=>setView("reciters")} style={{...softBtn,borderRadius:999,padding:"9px 13px",fontSize:11}}>تغيير القارئ</button></div><div style={{marginTop:14,borderTop:"1px solid rgba(16,16,15,.07)"}}>{SURAH_AR.map((name,i)=>{const active=surah===i+1;return <button className="mm-playlist-row" key={i} onClick={()=>pickSurah(i+1)} style={{width:"100%",display:"grid",gridTemplateColumns:"42px 1fr auto",gap:12,alignItems:"center",padding:"13px 4px",border:0,borderBottom:"1px solid rgba(16,16,15,.06)",background:active?"rgba(181,154,98,.07)":"transparent",fontFamily:"inherit",textAlign:"right",color:C.ink}}><span style={{width:34,height:34,borderRadius:12,display:"grid",placeItems:"center",background:active?C.lapis:"rgba(255,255,255,.55)",color:active?"white":C.gold,border:"1px solid rgba(16,16,15,.06)",fontSize:10}}>{nd(i+1,lang)}</span><span><b style={{fontSize:16.5,fontWeight:600}}>سورة {name}</b>{active&&<small style={{display:"block",fontSize:9.5,color:C.gold,marginTop:3}}>قيد التشغيل</small>}</span><span style={{opacity:.25}}>←</span></button>})}</div></div></Shell>;

 if(view==="reciters")return <Shell><div className="mm-player" dir="rtl"><Top title="القرّاء" caption="اختر القارئ ثم السورة" onBack={()=>setView("player")}/><div style={{position:"relative",marginTop:20}}><span style={{position:"absolute",right:13,top:12,color:C.soft}}><Icon type="search" size={18}/></span><input autoFocus value={q} onChange={e=>setQ(e.target.value)} placeholder="ابحث باسم القارئ…" style={{width:"100%",boxSizing:"border-box",padding:"12px 42px 12px 13px",borderRadius:17,border:"1px solid rgba(16,16,15,.08)",background:C.paper,fontFamily:"inherit",outline:"none"}}/></div><div style={{fontSize:10,opacity:.42,margin:"9px 3px 4px"}}>{loading?"تحميل القرّاء…":err||`${nd(filtered.length,lang)} قارئ متاح`}</div><div style={{borderTop:"1px solid rgba(16,16,15,.07)"}}>{filtered.map(r=>{const active=selected?.id===r.id;return <button className="mm-playlist-row" key={r.id} onClick={()=>openReciter(r)} style={{width:"100%",display:"grid",gridTemplateColumns:"44px 1fr auto",gap:12,alignItems:"center",border:0,borderBottom:"1px solid rgba(16,16,15,.06)",background:active?"rgba(181,154,98,.07)":"transparent",padding:"13px 3px",fontFamily:"inherit",textAlign:"right",color:C.ink}}><span style={{width:36,height:36,borderRadius:"50%",display:"grid",placeItems:"center",background:active?C.lapis:"rgba(255,255,255,.58)",color:active?"white":C.gold,fontSize:13}}>{(r.name||"ق").trim().charAt(0)}</span><span><b style={{fontSize:16.5,fontWeight:600}}>{r.name}</b><small style={{display:"block",fontSize:9.5,opacity:.42,marginTop:3}}>{r.moshaf.map(m=>m.name).join(" · ")}</small></span><span style={{opacity:.25}}>←</span></button>})}</div></div></Shell>;

 return <Shell><div className="mm-player" dir="rtl"><audio ref={audio} src={src} loop={repeat} preload="metadata" onPlay={()=>setPlaying(true)} onPause={()=>setPlaying(false)} onLoadedMetadata={e=>setDur(e.currentTarget.duration)} onTimeUpdate={e=>setPos(e.currentTarget.currentTime)} onEnded={()=>setPlaying(false)}/><Top title="استمع للقرآن" caption="MUSLIM MIRROR · AUDIO" onBack={()=>go?.("quran-home")}/>
 <div style={{textAlign:"center",marginTop:18}}><div className="mm-title" style={{fontSize:30,fontWeight:650}}>سورة {SURAH_AR[surah-1]}</div><button onClick={()=>setView("reciters")} style={{border:0,background:"transparent",fontFamily:"inherit",color:C.lapis,fontSize:13.5,marginTop:5}}>{selected?.name||"اختر قارئاً"}</button><div className="mm-sub" style={{fontSize:10.5,opacity:.42,marginTop:2}}>{moshaf?.name||""}</div></div>
 <div className="mm-disc" style={{width:286,height:286,position:"relative",margin:"22px auto 10px",display:"grid",placeItems:"center"}}>
  <svg width="286" height="286" viewBox="0 0 286 286" style={{position:"absolute",inset:0,transform:"rotate(-90deg)"}}><circle cx="143" cy="143" r="111" fill="none" stroke="rgba(16,16,15,.075)" strokeWidth="2"/><circle cx="143" cy="143" r="111" fill="none" stroke={C.gold} strokeWidth="3" strokeLinecap="round" strokeDasharray={circ} strokeDashoffset={circ*(1-pct)} style={{transition:"stroke-dashoffset .25s linear"}}/></svg>
  <div className="mm-disc-core" style={{position:"absolute",inset:29,borderRadius:"50%",background:"radial-gradient(circle at 34% 28%,#31536c 0%,#173B57 46%,#102B40 100%)",boxShadow:"0 24px 50px rgba(23,59,87,.22),inset 0 0 0 1px rgba(255,255,255,.08)",display:"grid",placeItems:"center",overflow:"hidden"}}><div style={{position:"absolute",inset:"12%",borderRadius:"50%",border:"1px solid rgba(255,255,255,.08)"}}/><div style={{position:"absolute",inset:"26%",borderRadius:"50%",border:"1px solid rgba(181,154,98,.18)"}}/><div style={{position:"relative",textAlign:"center",color:"white"}}><div style={{fontFamily:"'Amiri Quran','Noto Naskh Arabic',serif",fontSize:28,lineHeight:1.2}}>القرآن الكريم</div><div style={{width:26,height:1,background:C.gold,margin:"10px auto"}}/><div style={{fontSize:15}}>سورة {SURAH_AR[surah-1]}</div><div style={{fontSize:9,opacity:.58,marginTop:5}}>{nd(surah,lang)} / ١١٤</div></div></div>
 </div>
 <div style={{display:"flex",justifyContent:"space-between",fontSize:10,opacity:.42,direction:"ltr",maxWidth:286,margin:"0 auto"}}><span>{fmt(pos)}</span><span>{fmt(dur)}</span></div>
 <input aria-label="موضع التشغيل" type="range" min="0" max={dur||1} value={Math.min(pos,dur||1)} onChange={e=>{const v=Number(e.target.value);if(audio.current)audio.current.currentTime=v;setPos(v)}} style={{width:"100%",maxWidth:330,display:"block",margin:"8px auto 0",accentColor:C.gold}}/>
 <div style={{display:"grid",gridTemplateColumns:"52px 62px 76px 62px 52px",justifyContent:"center",alignItems:"center",gap:7,marginTop:18,direction:"ltr"}}><button className="mm-press" onClick={()=>seekBy(-15)} style={{...softBtn,width:42,height:42,borderRadius:"50%",fontSize:10}}>↶15</button><button className="mm-press" onClick={()=>changeSurah(surah-1)} style={{...softBtn,width:52,height:52,borderRadius:"50%",fontSize:24}}>‹</button><button className="mm-press" onClick={toggle} style={{width:72,height:72,borderRadius:"50%",border:0,background:C.lapis,color:"white",fontSize:24,boxShadow:"0 13px 30px rgba(23,59,87,.24)"}}>{playing?"Ⅱ":"▶"}</button><button className="mm-press" onClick={()=>changeSurah(surah+1)} style={{...softBtn,width:52,height:52,borderRadius:"50%",fontSize:24}}>›</button><button className="mm-press" onClick={()=>seekBy(15)} style={{...softBtn,width:42,height:42,borderRadius:"50%",fontSize:10}}>15↷</button></div>
 <button onClick={()=>setView("surahs")} style={{...softBtn,borderRadius:999,padding:"9px 15px",display:"flex",alignItems:"center",gap:7,margin:"16px auto 0",fontSize:11}}><Icon type="list" size={17}/> قائمة السور</button>
 <div style={{display:"grid",gridTemplateColumns:"repeat(4,1fr)",gap:8,marginTop:17}}><button className="mm-press" onClick={toggleFavorite} style={{...softBtn,borderRadius:17,minHeight:58,display:"grid",placeItems:"center",gap:4,color:favorite?C.gold:C.ink,background:favorite?"rgba(181,154,98,.10)":"rgba(255,255,255,.58)"}}><Icon type="heart"/><span className="mm-tool-label" style={{fontSize:9.5}}>{favorite?"مفضلة":"المفضلة"}</span></button><button className="mm-press" onClick={download} disabled={downloading} style={{...softBtn,borderRadius:17,minHeight:58,display:"grid",placeItems:"center",gap:4,color:C.lapis,opacity:downloading?.5:1}}><Icon type="download"/><span className="mm-tool-label" style={{fontSize:9.5}}>{downloading?"حفظ…":"حفظ"}</span></button><button className="mm-press" onClick={()=>setRepeat(v=>!v)} style={{...softBtn,borderRadius:17,minHeight:58,display:"grid",placeItems:"center",gap:4,color:repeat?C.gold:C.ink,background:repeat?"rgba(181,154,98,.10)":"rgba(255,255,255,.58)"}}><Icon type="repeat"/><span className="mm-tool-label" style={{fontSize:9.5}}>تكرار</span></button><button className="mm-press" onClick={()=>setSleepTimer(sleep===0?15:sleep===15?30:sleep===30?60:0)} style={{...softBtn,borderRadius:17,minHeight:58,display:"grid",placeItems:"center",gap:4,color:sleep?C.gold:C.ink}}><Icon type="timer"/><span className="mm-tool-label" style={{fontSize:9.5}}>{sleep?`${sleep} د`:"المؤقت"}</span></button></div>
 <div style={{display:"flex",alignItems:"center",justifyContent:"space-between",gap:10,marginTop:10,padding:"9px 11px",border:"1px solid rgba(16,16,15,.07)",borderRadius:17,background:"rgba(255,255,255,.42)"}}><span style={{fontSize:10.5,opacity:.48}}>السرعة</span><div style={{display:"flex",gap:4,direction:"ltr"}}>{[.75,1,1.25,1.5].map(x=><button key={x} onClick={()=>setSpeed(x)} style={{border:0,borderRadius:999,padding:"6px 8px",fontFamily:"inherit",fontSize:9.5,background:speed===x?C.lapis:"transparent",color:speed===x?"white":C.ink}}>{x}×</button>)}</div></div>
 </div></Shell>
}
