import React,{useEffect,useMemo,useState}from"react";
const C={ivory:"#F6F3EC",ink:"#10100F",lapis:"#173B57",gold:"#B59A62"};
const nd=(s,l)=>l==="ar"?String(s).replace(/[0-9]/g,d=>"٠١٢٣٤٥٦٧٨٩"[d]):String(s);
function Shell({lang,go,children}){return <div style={{position:"absolute",inset:0,background:C.ivory,color:C.ink,display:"flex",flexDirection:"column"}}><div style={{padding:"22px 22px 0"}}><button onClick={()=>go("quran-home")} style={{border:0,background:"transparent",fontFamily:"inherit",cursor:"pointer",color:"inherit"}}>{lang==="ar"?"← القرآن":"← Quran"}</button></div><div style={{flex:1,overflowY:"auto",padding:"15px 22px 130px"}}>{children}</div></div>}
export function LiveTafsirCenter({lang,go}){
 const [editions,setEditions]=useState([]),[selected,setSelected]=useState(""),[surah,setSurah]=useState(1),[ayah,setAyah]=useState(1),[data,setData]=useState(null),[loading,setLoading]=useState(true),[err,setErr]=useState(""),[compare,setCompare]=useState(false),[second,setSecond]=useState("");
 useEffect(()=>{fetch("https://api.alquran.cloud/v1/edition/type/tafsir").then(r=>{if(!r.ok)throw new Error();return r.json()}).then(x=>{const a=(x.data||[]).filter(e=>e.format==="text");setEditions(a);setSelected(a[0]?.identifier||"");setSecond(a[1]?.identifier||"");setLoading(false)}).catch(()=>{setErr(lang==="ar"?"تعذر تحميل قائمة التفاسير":"Could not load tafsir editions");setLoading(false)})},[lang]);
 useEffect(()=>{if(!selected)return;setLoading(true);setErr("");const ids=compare&&second&&second!==selected?`${selected},${second}`:selected;fetch(`https://api.alquran.cloud/v1/ayah/${surah}:${ayah}/editions/quran-uthmani,${ids}`).then(r=>{if(!r.ok)throw new Error();return r.json()}).then(x=>{setData(x.data||[]);setLoading(false)}).catch(()=>{setErr(lang==="ar"?"تعذر تحميل التفسير لهذه الآية":"Could not load tafsir for this ayah");setLoading(false)})},[selected,second,surah,ayah,compare,lang]);
 const tafsirs=useMemo(()=>data?data.filter(x=>x.edition?.type==="tafsir"):[],[data]);const quran=useMemo(()=>data?.find(x=>x.edition?.identifier==="quran-uthmani"),[data]);
 return <Shell lang={lang} go={go}><div style={{fontFamily:"Fraunces,serif",fontSize:29}}>{lang==="ar"?"التفسير":"Tafsir"}</div><div style={{fontSize:11.5,opacity:.48,marginTop:7,lineHeight:1.7}}>{lang==="ar"?"التفاسير المتاحة تُقرأ مباشرة من مزود القرآن، بدون أسماء ثابتة أو نصوص مصطنعة.":"Available tafsirs are loaded directly from the Quran provider—no hard-coded or invented text."}</div>
 <div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:8,marginTop:15}}><label style={{fontSize:10.5,opacity:.65}}>{lang==="ar"?"السورة":"Surah"}<input type="number" min="1" max="114" value={surah} onChange={e=>{setSurah(Math.max(1,Math.min(114,Number(e.target.value)||1)));setAyah(1)}} style={{display:"block",width:"100%",boxSizing:"border-box",marginTop:5,padding:10,borderRadius:12,border:"1px solid rgba(16,16,15,.09)",background:"transparent"}}/></label><label style={{fontSize:10.5,opacity:.65}}>{lang==="ar"?"الآية":"Ayah"}<input type="number" min="1" value={ayah} onChange={e=>setAyah(Math.max(1,Number(e.target.value)||1))} style={{display:"block",width:"100%",boxSizing:"border-box",marginTop:5,padding:10,borderRadius:12,border:"1px solid rgba(16,16,15,.09)",background:"transparent"}}/></label></div>
 <select value={selected} onChange={e=>setSelected(e.target.value)} style={{width:"100%",marginTop:10,padding:11,borderRadius:13,border:"1px solid rgba(16,16,15,.09)",background:"transparent",fontFamily:"inherit"}}>{editions.map(e=><option key={e.identifier} value={e.identifier}>{e.englishName||e.name||e.identifier} · {e.language}</option>)}</select>
 <label style={{display:"flex",justifyContent:"space-between",alignItems:"center",marginTop:12,fontSize:11.5}}><span>{lang==="ar"?"مقارنة تفسيرين":"Compare two tafsirs"}</span><input type="checkbox" checked={compare} onChange={e=>setCompare(e.target.checked)}/></label>{compare&&<select value={second} onChange={e=>setSecond(e.target.value)} style={{width:"100%",marginTop:8,padding:11,borderRadius:13,border:"1px solid rgba(16,16,15,.09)",background:"transparent",fontFamily:"inherit"}}>{editions.map(e=><option key={e.identifier} value={e.identifier}>{e.englishName||e.name||e.identifier} · {e.language}</option>)}</select>}
 {loading&&<div style={{marginTop:25,opacity:.5}}>{lang==="ar"?"تحميل التفسير…":"Loading tafsir…"}</div>}{err&&<div style={{marginTop:20,color:"#8b3c31",lineHeight:1.7}}>{err}</div>}
 {quran&&<div style={{marginTop:18,padding:18,borderRadius:18,background:"rgba(181,154,98,.09)",border:"1px solid rgba(181,154,98,.15)"}}><div style={{fontSize:9.5,opacity:.42}}>{lang==="ar"?`سورة ${nd(surah,lang)} · آية ${nd(ayah,lang)}`:`Surah ${surah} · Ayah ${ayah}`}</div><div style={{fontFamily:"'Noto Naskh Arabic','Amiri',serif",fontSize:27,lineHeight:2.05,direction:"rtl",textAlign:"right",marginTop:10}}>{quran.text}</div></div>}
 <div style={{marginTop:10}}>{tafsirs.map((t,i)=><div key={t.edition?.identifier||i} style={{padding:"17px 0",borderTop:"1px solid rgba(16,16,15,.07)"}}><div style={{fontSize:11,fontWeight:700}}>{t.edition?.englishName||t.edition?.name||t.edition?.identifier}</div><div style={{fontSize:12.5,lineHeight:1.9,marginTop:9,whiteSpace:"pre-wrap"}}>{t.text}</div></div>)}</div>
 <div style={{marginTop:14,fontSize:9.8,opacity:.42,lineHeight:1.7}}>{lang==="ar"?`المصدر الحي يعرض حالياً ${nd(editions.length,lang)} إصدار تفسير متاح عبر المزود.`:`The live provider currently exposes ${editions.length} tafsir editions.`}</div></Shell>}

export function HadithNineBooksGate({lang,go}){const books=["صحيح البخاري","صحيح مسلم","سنن أبي داود","جامع الترمذي","سنن النسائي","سنن ابن ماجه","موطأ مالك","مسند أحمد","سنن الدارمي"];return <Shell lang={lang} go={go}><div style={{fontFamily:"Fraunces,serif",fontSize:29}}>{lang==="ar"?"جامع الكتب التسعة":"Nine Books Collection"}</div><div style={{fontSize:11.5,opacity:.5,marginTop:8,lineHeight:1.75}}>{lang==="ar"?"الواجهة جاهزة، لكن النصوص لا تُملأ من مصدر مجهول. الربط النهائي يحتاج corpus موثوق بترقيم وإسناد ونسخة واضحة.":"The interface is ready, but hadith text is never filled from an unknown source. Final wiring requires a trusted corpus with numbering, isnad and edition provenance."}</div><div style={{marginTop:16}}>{books.map((b,i)=><div key={b} style={{display:"grid",gridTemplateColumns:"34px 1fr auto",gap:10,alignItems:"center",padding:"13px 0",borderTop:"1px solid rgba(16,16,15,.07)"}}><div style={{width:30,height:30,borderRadius:"50%",border:"1px solid rgba(16,16,15,.11)",display:"grid",placeItems:"center",fontSize:9}}>{nd(i+1,lang)}</div><b style={{fontSize:12.5}}>{b}</b><span style={{fontSize:9.5,opacity:.35}}>{lang==="ar"?"بانتظار المصدر":"Source pending"}</span></div>)}</div></Shell>}
