import React,{useEffect,useMemo,useState} from "react";

const C={ivory:"#F6F3EC",ink:"#10100F",lapis:"#173B57",gold:"#B59A62",red:"#9C4A3B",soft:"#EEE7D8",green:"#416F5A"};
const btn={border:"1px solid rgba(16,16,15,.08)",borderRadius:15,padding:11,background:"rgba(255,255,255,.48)",fontFamily:"inherit",color:"inherit"};
const RX=/ذكر|دعاء|أذكار|أدعية|استعاذ|رقية|نوم|صباح|مساء|استغفار|تسبيح|تحميد|تكبير|تهليل|صلاة على النبي/;
const ar=n=>String(n).replace(/[0-9]/g,d=>"٠١٢٣٤٥٦٧٨٩"[d]);
function Shell({go,title="أذكار السنة الموثقة",sub="أذكار وأدعية من أحاديث HadeethEnc الموثقة",children}){return <div style={{position:"absolute",inset:0,background:C.ivory,color:C.ink,display:"flex",flexDirection:"column"}} dir="rtl"><div style={{flex:1,overflowY:"auto",padding:"30px 18px calc(330px + env(safe-area-inset-bottom,0px))",scrollPaddingBottom:"calc(330px + env(safe-area-inset-bottom,0px))"}}><main style={{maxWidth:680,margin:"0 auto"}}><header style={{textAlign:"center"}}><div style={{fontSize:9.5,color:C.gold,letterSpacing:1.25}}>SUNNAH · SAKINAH</div><h1 style={{fontSize:29,margin:"6px 0 6px"}}>{title}</h1><p style={{fontSize:10.5,opacity:.47,lineHeight:1.8,margin:0}}>{sub}</p><div style={{width:92,height:1,background:"linear-gradient(90deg,transparent,#B59A62,transparent)",margin:"15px auto 0"}}/></header>{children}<section style={{marginTop:18,padding:12,borderRadius:16,background:"rgba(181,154,98,.08)",fontSize:9.5,opacity:.58,lineHeight:1.8}}>المصدر: HadeethEnc.com. لا يعرض سكينة نصاً منسوباً للسنة دون مصدر حي موثوق.</section><div aria-hidden="true" style={{height:70}}/></main></div></div>}
export function LiveSunnahAdhkar({go}){
 const [cats,setCats]=useState([]),[cat,setCat]=useState(null),[rows,setRows]=useState([]),[detail,setDetail]=useState(null),[q,setQ]=useState(""),[busy,setBusy]=useState(true),[err,setErr]=useState("");
 useEffect(()=>{fetch("https://hadeethenc.com/api/v1/categories/roots/?language=ar").then(r=>{if(!r.ok)throw new Error();return r.json()}).then(x=>{const all=Array.isArray(x)?x:[];const filtered=all.filter(c=>RX.test(c.title||""));setCats(filtered.length?filtered:all);setBusy(false)}).catch(()=>{setErr("تعذر الاتصال بمصدر الأذكار حالياً");setBusy(false)})},[]);
 const openCat=c=>{setCat(c);setRows([]);setDetail(null);setErr("");setBusy(true);fetch(`https://hadeethenc.com/api/v1/hadeeths/list/?language=ar&category_id=${encodeURIComponent(c.id)}&page=1&per_page=100`).then(r=>{if(!r.ok)throw new Error();return r.json()}).then(x=>{setRows(Array.isArray(x.data)?x.data:[]);setBusy(false)}).catch(()=>{setErr("تعذر تحميل أحاديث هذا الباب");setBusy(false)})};
 const openHadith=h=>{setDetail(null);setErr("");setBusy(true);fetch(`https://hadeethenc.com/api/v1/hadeeths/one/?language=ar&id=${encodeURIComponent(h.id)}`).then(r=>{if(!r.ok)throw new Error();return r.json()}).then(x=>{setDetail(x||null);setBusy(false)}).catch(()=>{setErr("تعذر تحميل النص");setBusy(false)})};
 const shown=useMemo(()=>rows.filter(x=>(x.title||"").includes(q)),[rows,q]);
 if(detail)return <Shell go={()=>setDetail(null)} title={detail.title||"ذكر من السنة"} sub={detail.attribution||"حديث موثق من المصدر"}><button onClick={()=>setDetail(null)} style={{...btn,marginTop:16,padding:"8px 11px",fontSize:10}}>عودة إلى الباب</button><article style={{marginTop:12,padding:"18px 16px",borderRadius:22,background:"rgba(255,255,255,.55)",border:"1px solid rgba(16,16,15,.065)"}}><div style={{fontFamily:"'Noto Naskh Arabic','Amiri',serif",fontSize:21,lineHeight:2.05,textAlign:"right"}}>{detail.hadeeth||detail.hadith||detail.text||""}</div>{detail.explanation&&<><div style={{fontSize:11,color:C.gold,fontWeight:700,marginTop:20}}>الشرح</div><div style={{fontSize:11.5,lineHeight:1.95,marginTop:7,opacity:.76}}>{detail.explanation}</div></>}{Array.isArray(detail.hints)&&detail.hints.length>0&&<><div style={{fontSize:11,color:C.gold,fontWeight:700,marginTop:20}}>الفوائد</div>{detail.hints.map((x,i)=><div key={i} style={{padding:"9px 0",borderTop:"1px solid rgba(16,16,15,.055)",fontSize:11,lineHeight:1.85}}>• {x}</div>)}</>}{detail.reference&&<div style={{marginTop:16,padding:11,borderRadius:14,background:"rgba(181,154,98,.10)",fontSize:10,lineHeight:1.8}}>{detail.reference}</div>}</article></Shell>;
 if(cat)return <Shell go={()=>{setCat(null);setRows([]);setQ("")}} title={cat.title||"باب الأذكار"} sub="اختر حديثاً لعرض النص والشرح والمصدر"><button onClick={()=>{setCat(null);setRows([]);setQ("")}} style={{...btn,marginTop:16,padding:"8px 11px",fontSize:10}}>كل الأبواب</button><div style={{display:"grid",gridTemplateColumns:"1fr auto",gap:8,alignItems:"center",marginTop:10}}><input value={q} onChange={e=>setQ(e.target.value)} placeholder="ابحث في هذا الباب…" style={{...btn,width:"100%",boxSizing:"border-box",background:"rgba(255,255,255,.56)"}}/><span style={{fontSize:9.5,opacity:.42}}>{ar(shown.length)} حديث</span></div>{busy&&<div style={{marginTop:18,opacity:.5,fontSize:10}}>تحميل…</div>}{err&&<div style={{marginTop:14,color:C.red,fontSize:10.5}}>{err}</div>}<div style={{marginTop:12}}>{shown.map((h,i)=><button key={h.id} onClick={()=>openHadith(h)} style={{width:"100%",padding:"12px 13px",marginTop:8,border:"1px solid rgba(16,16,15,.06)",borderRadius:17,background:"rgba(255,255,255,.45)",fontFamily:"inherit",textAlign:"right",color:"inherit",display:"grid",gridTemplateColumns:"34px 1fr auto",gap:9,alignItems:"center"}}><span style={{width:31,height:31,borderRadius:11,display:"grid",placeItems:"center",background:"rgba(181,154,98,.13)",color:C.gold,fontSize:9.5}}>{ar(i+1)}</span><span><b style={{fontSize:12,lineHeight:1.65}}>{h.title}</b><small style={{display:"block",opacity:.4,marginTop:3}}>حديث رقم {ar(h.id)}</small></span><span style={{opacity:.3,fontSize:16}}>‹</span></button>)}</div></Shell>;
 return <Shell go={go}>{busy&&<div style={{marginTop:20,opacity:.5,textAlign:"center",fontSize:10}}>تحميل أبواب الأذكار…</div>}{err&&<div style={{marginTop:16,color:C.red,textAlign:"center",fontSize:10.5}}>{err}</div>}{!busy&&!err&&<><section style={{display:"grid",gridTemplateColumns:"repeat(3,1fr)",gap:1,marginTop:18,border:"1px solid rgba(16,16,15,.055)",borderRadius:18,overflow:"hidden",background:"rgba(16,16,15,.04)"}}>{[[cats.length,"أبواب"],["حي","المصدر"],["100","حد العرض"]].map(([n,l])=><div key={l} style={{padding:"10px 5px",background:"rgba(255,255,255,.62)",textAlign:"center"}}><b style={{fontSize:15,color:C.lapis}}>{typeof n==="number"?ar(n):n}</b><small style={{display:"block",fontSize:8.5,opacity:.42,marginTop:2}}>{l}</small></div>)}</section><div style={{display:"flex",justifyContent:"space-between",alignItems:"end",marginTop:18,marginBottom:7}}><div><div style={{fontSize:9.5,color:C.gold}}>المكتبة</div><h2 style={{fontSize:19,margin:"2px 0"}}>اختر الباب</h2></div><span style={{fontSize:9,opacity:.4}}>مرتب من المصدر</span></div><div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:8}}>{cats.map((c,i)=><button key={c.id} onClick={()=>openCat(c)} style={{...btn,minHeight:88,textAlign:"right",padding:"13px",background:i===0?"linear-gradient(145deg,#173B57,#0C293E)":"rgba(255,255,255,.50)",color:i===0?"white":C.ink,display:"flex",flexDirection:"column",justifyContent:"space-between"}}><div style={{display:"flex",justifyContent:"space-between",alignItems:"center"}}><span style={{fontSize:17,color:i===0?"#E7D29B":C.gold}}>✦</span><span style={{fontSize:9,opacity:.42}}>باب</span></div><div style={{fontSize:11.5,fontWeight:700,lineHeight:1.55,marginTop:12}}>{c.title}</div></button>)}</div></>}</Shell>;
}