import React,{useEffect,useMemo,useState} from "react";
import NineBooksCenter from "./NineBooksCenter.jsx";

const C={ivory:"#F6F3EC",ink:"#10100F",lapis:"#173B57",gold:"#B59A62",red:"#9C4A3B"};
const btn={border:"1px solid rgba(16,16,15,.09)",borderRadius:14,padding:11,background:"transparent",fontFamily:"inherit",color:"inherit"};
function Shell({go,children,title="الأحاديث النبوية",sub="موسوعة أحاديث صحيحة ومشروحة من HadeethEnc"}){return <div style={{position:"absolute",inset:0,background:C.ivory,color:C.ink,display:"flex",flexDirection:"column"}} dir="rtl"><div style={{padding:"22px 22px 0"}}><button onClick={()=>go?.(null)} style={{...btn,border:0,padding:0}}>رجوع ←</button></div><div style={{flex:1,overflowY:"auto",padding:"15px 22px 130px"}}><div style={{fontFamily:"Fraunces,serif",fontSize:29}}>{title}</div><div style={{fontSize:11.5,opacity:.48,lineHeight:1.7,marginTop:7}}>{sub}</div>{children}<div style={{fontSize:9.5,opacity:.42,lineHeight:1.7,marginTop:22}}>المصدر: HadeethEnc.com — موسوعة الأحاديث النبوية المترجمة. يعرض سكينة المحتوى كما يرد من المصدر دون تعديل.</div></div></div>}

export function LiveHadithHub({go}){
 const [cats,setCats]=useState([]),[cat,setCat]=useState(null),[rows,setRows]=useState([]),[detail,setDetail]=useState(null),[q,setQ]=useState(""),[loading,setLoading]=useState(true),[err,setErr]=useState(""),[nineBooks,setNineBooks]=useState(false);
 useEffect(()=>{setLoading(true);fetch("https://hadeethenc.com/api/v1/categories/roots/?language=ar").then(r=>{if(!r.ok)throw new Error();return r.json()}).then(x=>{setCats(Array.isArray(x)?x:[]);setLoading(false)}).catch(()=>{setErr("تعذر الاتصال بمصدر الأحاديث حالياً");setLoading(false)})},[]);
 const openCat=c=>{setCat(c);setRows([]);setDetail(null);setErr("");setLoading(true);fetch(`https://hadeethenc.com/api/v1/hadeeths/list/?language=ar&category_id=${encodeURIComponent(c.id)}&page=1&per_page=50`).then(r=>{if(!r.ok)throw new Error();return r.json()}).then(x=>{setRows(Array.isArray(x.data)?x.data:[]);setLoading(false)}).catch(()=>{setErr("تعذر تحميل أحاديث هذا الباب");setLoading(false)})};
 const openHadith=h=>{setDetail(null);setErr("");setLoading(true);fetch(`https://hadeethenc.com/api/v1/hadeeths/one/?language=ar&id=${encodeURIComponent(h.id)}`).then(r=>{if(!r.ok)throw new Error();return r.json()}).then(x=>{setDetail(x||null);setLoading(false)}).catch(()=>{setErr("تعذر تحميل نص الحديث");setLoading(false)})};
 const shown=useMemo(()=>rows.filter(x=>(x.title||"").includes(q)),[rows,q]);
 if(nineBooks)return <div style={{position:"absolute",inset:0,zIndex:42000,background:C.ivory}} dir="rtl"><NineBooksCenter/><button onClick={()=>setNineBooks(false)} aria-label="الرجوع إلى صفحة الحديث" style={{position:"fixed",top:66,right:14,zIndex:42050,border:"1px solid rgba(16,16,15,.08)",borderRadius:999,padding:"8px 12px",background:"rgba(246,243,236,.94)",backdropFilter:"blur(14px)",fontFamily:"inherit",fontSize:11,color:C.ink,boxShadow:"0 5px 18px rgba(16,16,15,.06)"}}>رجوع إلى الحديث ←</button></div>;
 if(detail)return <Shell go={()=>setDetail(null)} title={detail.title||"الحديث"} sub={detail.attribution||"حديث موثق من HadeethEnc"}><article style={{marginTop:18,padding:18,borderRadius:22,background:"rgba(255,255,255,.48)",border:"1px solid rgba(16,16,15,.07)"}}><div style={{fontFamily:"serif",fontSize:20,lineHeight:2}}>{detail.hadeeth||detail.hadith||detail.text||""}</div>{detail.explanation&&<><div style={{fontSize:12,fontWeight:700,marginTop:22}}>الشرح</div><div style={{fontSize:12,lineHeight:1.9,marginTop:8}}>{detail.explanation}</div></>}{Array.isArray(detail.hints)&&detail.hints.length>0&&<><div style={{fontSize:12,fontWeight:700,marginTop:22}}>الفوائد</div><div style={{marginTop:8}}>{detail.hints.map((x,i)=><div key={i} style={{padding:"8px 0",borderTop:"1px solid rgba(16,16,15,.06)",fontSize:11.5,lineHeight:1.8}}>• {x}</div>)}</div></>}{detail.reference&&<div style={{marginTop:18,padding:12,borderRadius:14,background:"rgba(181,154,98,.10)",fontSize:10.5,lineHeight:1.7}}>{detail.reference}</div>}</article></Shell>;
 if(cat)return <Shell go={()=>{setCat(null);setRows([]);setQ("")}} title={cat.title||"باب الحديث"} sub="اختر حديثاً لعرض النص والشرح والفوائد"><input value={q} onChange={e=>setQ(e.target.value)} placeholder="ابحث في أحاديث هذا الباب…" style={{...btn,width:"100%",boxSizing:"border-box",marginTop:16}}/>{loading&&<div style={{marginTop:22,opacity:.5}}>تحميل…</div>}{err&&<div style={{marginTop:18,color:C.red}}>{err}</div>}<div style={{marginTop:10}}>{shown.map(h=><button key={h.id} onClick={()=>openHadith(h)} style={{width:"100%",padding:"13px 2px",border:0,borderTop:"1px solid rgba(16,16,15,.07)",background:"transparent",fontFamily:"inherit",textAlign:"right",color:"inherit"}}><b style={{fontSize:12.5,lineHeight:1.7}}>{h.title}</b><small style={{display:"block",opacity:.4,marginTop:4}}>رقم {h.id}</small></button>)}</div></Shell>;
 return <Shell go={go}><button onClick={()=>setNineBooks(true)} style={{width:"100%",minHeight:156,marginTop:20,padding:"20px 18px",border:0,borderRadius:26,background:"linear-gradient(145deg,#173B57,#0C293E)",color:"white",fontFamily:"inherit",textAlign:"right",boxShadow:"0 18px 42px rgba(23,59,87,.14)",display:"grid",gridTemplateColumns:"1fr auto",gap:14,alignItems:"center"}}><span><span style={{display:"block",fontSize:10,color:"#E7D29B",letterSpacing:.5}}>مكتبة الحديث</span><b style={{display:"block",fontSize:24,marginTop:7,lineHeight:1.35}}>الكتب التسعة</b><small style={{display:"block",fontSize:11,opacity:.68,lineHeight:1.8,marginTop:7}}>صحيح البخاري، صحيح مسلم، السنن والمسانيد مرتبة في مكتبة واحدة</small><span style={{display:"inline-block",marginTop:15,fontSize:10.5,color:"#E7D29B"}}>افتح المكتبة ←</span></span><span aria-hidden="true" style={{width:64,height:76,borderRadius:20,display:"grid",placeItems:"center",background:"rgba(255,255,255,.09)",color:"#E7D29B",fontSize:34}}>▤</span></button>{loading&&<div style={{marginTop:22,opacity:.5}}>تحميل أبواب الحديث…</div>}{err&&<div style={{marginTop:18,color:C.red}}>{err}</div>}<div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:9,marginTop:18}}>{cats.map((c,i)=><button key={c.id} onClick={()=>openCat(c)} style={{...btn,minHeight:112,textAlign:"right",background:i===0?"linear-gradient(145deg,#173B57,#0C293E)":"rgba(255,255,255,.48)",color:i===0?"white":C.ink}}><div style={{fontSize:22,color:i===0?"#E7D29B":C.gold}}>▤</div><div style={{fontSize:12.5,fontWeight:700,lineHeight:1.6,marginTop:12}}>{c.title}</div></button>)}</div></Shell>;
}
