import React,{useEffect,useMemo,useState} from "react";
const C={ivory:"#F6F3EC",ink:"#10100F",lapis:"#173B57",gold:"#B59A62",red:"#A44D3C"};
const btn={border:"1px solid rgba(16,16,15,.09)",borderRadius:14,padding:11,background:"transparent",fontFamily:"inherit",color:"inherit"};
export function LiveTafsir({lang="ar",go}){
 const [ref,setRef]=useState("1:1"),[editions,setEditions]=useState([]),[edition,setEdition]=useState(""),[ayah,setAyah]=useState(null),[tafsir,setTafsir]=useState(null),[busy,setBusy]=useState(false),[err,setErr]=useState("");
 useEffect(()=>{fetch("https://api.alquran.cloud/v1/edition/type/tafsir").then(r=>{if(!r.ok)throw new Error();return r.json()}).then(j=>{const rows=Array.isArray(j?.data)?j.data:[];setEditions(rows);const ar=rows.find(x=>x.language==="ar")||rows[0];setEdition(ar?.identifier||"")}).catch(()=>setErr(lang==="ar"?"تعذر تحميل قائمة التفاسير":"Could not load tafsir editions"))},[lang]);
 const selected=useMemo(()=>editions.find(x=>x.identifier===edition),[editions,edition]);
 const load=async()=>{if(!edition||!/^(?:[1-9]|[1-9][0-9]|1[01][0-4]):[1-9][0-9]{0,2}$/.test(ref.trim())){setErr(lang==="ar"?"أدخل مرجعاً مثل 2:255 واختر تفسيراً":"Enter a reference such as 2:255 and choose a tafsir");return}setBusy(true);setErr("");try{const [a,t]=await Promise.all([fetch(`https://api.alquran.cloud/v1/ayah/${encodeURIComponent(ref.trim())}/quran-uthmani`),fetch(`https://api.alquran.cloud/v1/ayah/${encodeURIComponent(ref.trim())}/${encodeURIComponent(edition)}`)]);if(!a.ok||!t.ok)throw new Error();const [aj,tj]=await Promise.all([a.json(),t.json()]);setAyah(aj?.data||null);setTafsir(tj?.data||null)}catch{setErr(lang==="ar"?"تعذر تحميل الآية أو التفسير الآن":"Could not load the ayah or tafsir right now")}finally{setBusy(false)}};
 return <div style={{position:"absolute",inset:0,background:C.ivory,color:C.ink,display:"flex",flexDirection:"column"}} dir={lang==="ar"?"rtl":"ltr"}>
  <div style={{padding:"22px 22px 0"}}><button onClick={()=>go?.("trusted-daily")} style={{...btn,border:0,padding:0}}>{lang==="ar"?"← المحتوى الموثق":"← Sourced content"}</button></div>
  <div style={{flex:1,overflowY:"auto",padding:"15px 22px 130px"}}>
   <div style={{fontFamily:"Fraunces,serif",fontSize:29}}>{lang==="ar"?"التفسير":"Tafsir"}</div>
   <div style={{fontSize:11.5,opacity:.48,lineHeight:1.75,marginTop:7}}>{lang==="ar"?"اختر تفسيراً متاحاً من مصدر القرآن، ثم افتح أي آية بمرجع السورة والآية.":"Choose an available tafsir edition from the Quran source, then open any ayah by surah:ayah reference."}</div>
   <div style={{display:"grid",gridTemplateColumns:"110px 1fr auto",gap:8,marginTop:16}}><input value={ref} onChange={e=>setRef(e.target.value)} onKeyDown={e=>e.key==="Enter"&&load()} placeholder="2:255" style={{...btn,minWidth:0}}/><select value={edition} onChange={e=>setEdition(e.target.value)} style={{...btn,minWidth:0}}><option value="">{lang==="ar"?"اختر تفسيراً":"Choose tafsir"}</option>{editions.map(x=><option key={x.identifier} value={x.identifier}>{x.name||x.englishName||x.identifier} · {x.language}</option>)}</select><button onClick={load} disabled={busy||!edition} style={{...btn,background:C.lapis,color:"white",border:0}}>{busy?"…":(lang==="ar"?"فتح":"Open")}</button></div>
   {err&&<div style={{marginTop:10,fontSize:10.5,color:C.red}}>{err}</div>}
   {ayah&&<div style={{marginTop:18,padding:18,borderRadius:20,background:"rgba(181,154,98,.09)",border:"1px solid rgba(181,154,98,.16)"}}><div style={{fontSize:10,opacity:.45}}>{ayah.surah?.name} · {lang==="ar"?"آية":"Ayah"} {ayah.numberInSurah}</div><div dir="rtl" style={{fontFamily:"'Amiri Quran','Noto Naskh Arabic',serif",fontSize:24,lineHeight:2.05,textAlign:"right",marginTop:9}}>{ayah.text}</div></div>}
   {tafsir&&<div style={{marginTop:12,padding:18,borderRadius:20,border:"1px solid rgba(16,16,15,.08)",background:"rgba(255,255,255,.48)"}}><div style={{fontSize:10,opacity:.45}}>{selected?.name||selected?.englishName||edition}</div><div style={{fontSize:14,lineHeight:2,whiteSpace:"pre-wrap",marginTop:9}}>{tafsir.text}</div><div style={{fontSize:9.5,opacity:.4,marginTop:12}}>Al Quran Cloud · {edition} · {ref}</div></div>}
  </div>
 </div>
}
