import React,{useMemo,useState} from "react";

const C={bg:'#F7F3EA',paper:'#FDFBF7',navy:'#102D43',gold:'#C0A062',gold2:'#B08D4F',muted:'#8E96A0',soft:'#A9B0B8',text:'#102D43'};
const NAMES=[
 {num:'٠١',ar:'الرَّحْمٰن',latin:'AR-RAHMAAN',meaning:'واسع الرحمة',theme:'الرحمة',proof:'الرَّحْمٰنُ عَلَّمَ الْقُرْآنَ',ref:'الرحمن · ١',full:'ذو الرحمة الواسعة التي شملت الخلق كلّهم في الدنيا.'},
 {num:'٠٢',ar:'الرَّحِيم',latin:'AR-RAHEEM',meaning:'رحيم بالمؤمنين',theme:'الرحمة',proof:'وَكَانَ بِالْمُؤْمِنِينَ رَحِيمًا',ref:'الأحزاب · ٤٣',full:'رحمة خاصّة موصولة بالمؤمنين في الدنيا والآخرة.'},
 {num:'٠٣',ar:'المَلِك',latin:'AL-MALIK',meaning:'المالك المتصرّف',theme:'العزّة',proof:'فَتَعَالَى اللَّهُ الْمَلِكُ الْحَقُّ',ref:'المؤمنون · ١١٦',full:'المالك لكل شيء، المتصرّف في الملك بلا منازع.'},
 {num:'٠٤',ar:'القُدُّوس',latin:'AL-QUDDUS',meaning:'المنزَّه عن النقص',theme:'العزّة',proof:'المَلِكِ القُدُّوسِ العَزِيزِ الحَكِيمِ',ref:'الجمعة · ١',full:'الطاهر المنزَّه عن كل عيب ونقص.'},
 {num:'٠٥',ar:'السَّلَام',latin:'AS-SALAAM',meaning:'السالم من كل عيب',theme:'الرحمة',proof:'السَّلَامُ المُؤْمِنُ المُهَيْمِنُ',ref:'الحشر · ٢٣',full:'السالم من كل نقص، ومنه السلامة لخلقه.'},
 {num:'٠٦',ar:'المُؤْمِن',latin:'AL-MU’MIN',meaning:'مانح الأمان',theme:'الرحمة',proof:'المُؤْمِنُ المُهَيْمِنُ العَزِيزُ',ref:'الحشر · ٢٣',full:'الذي يؤمِّن خلقه ويصدّق رسله بالبراهين.'},
 {num:'٠٧',ar:'المُهَيْمِن',latin:'AL-MUHAYMIN',meaning:'الرقيب الحفيظ',theme:'العلم',proof:'العَزِيزُ الجَبَّارُ المُتَكَبِّرُ',ref:'الحشر · ٢٣',full:'المطّلع على خلقه، الحافظ لهم، الشهيد عليهم.'},
 {num:'٠٨',ar:'العَزِيز',latin:'AL-AZEEZ',meaning:'الغالب القوي',theme:'العزّة',proof:'وَهُوَ العَزِيزُ الحَكِيمُ',ref:'الحشر · ٢٤',full:'الغالب الذي لا يُمتنع عليه شيء، ولا يُغلب.'},
 {num:'٢١',ar:'الخَبِير',latin:'AL-KHABEER',meaning:'العالم بالدقائق',theme:'العلم',proof:'وَهُوَ اللَّطِيفُ الخَبِيرُ',ref:'الأنعام · ١٠٣',full:'المطّلع على بواطن الأمور ودقائقها.'},
 {num:'٢٢',ar:'الحَلِيم',latin:'AL-HALEEM',meaning:'لا يعاجل بالعقوبة',theme:'الرحمة',proof:'وَاللَّهُ غَفُورٌ حَلِيمٌ',ref:'البقرة · ٢٢٥',full:'الذي لا يستفزّه غضب ولا يعاجل بالعقوبة.'},
 {num:'٢٣',ar:'العَظِيم',latin:'AL-AZEEM',meaning:'ذو العظمة',theme:'العزّة',proof:'وَهُوَ العَلِيُّ العَظِيمُ',ref:'البقرة · ٢٥٥',full:'الذي لا شيء أعظم منه ذاتاً وصفاتٍ وأفعالاً.'},
 {num:'٢٤',ar:'الغَفُور',latin:'AL-GHAFOOR',meaning:'كثير المغفرة',theme:'الرحمة',proof:'إِنَّ اللَّهَ غَفُورٌ رَحِيمٌ',ref:'البقرة · ١٧٣',full:'الذي يغفر الذنوب مهما كثرت لمن تاب.'}
];
const CHIPS=['الكل','الرحمة','العزّة','العلم'];
const arNum=n=>String(n).replace(/\d/g,d=>'٠١٢٣٤٥٦٧٨٩'[d]);

export default function NamesOfAllahPremium({go}){
 const[chip,setChip]=useState('الكل'),[query,setQuery]=useState(''),[selected,setSelected]=useState(null),[saved,setSaved]=useState(()=>new Set());
 const shown=useMemo(()=>NAMES.filter(n=>(chip==='الكل'||n.theme===chip)&&(!query||`${n.ar} ${n.meaning} ${n.latin}`.toLowerCase().includes(query.trim().toLowerCase()))),[chip,query]);
 const today=NAMES[0];
 const toggleSaved=n=>setSaved(s=>{const x=new Set(s);x.has(n.num)?x.delete(n.num):x.add(n.num);return x});
 return <div className="names-premium" dir="rtl">
  <style>{`
   .names-premium{position:fixed;inset:0;z-index:2147483550;background:#E6E0D4;color:${C.text};font-family:'Noto Kufi Arabic','Cairo',sans-serif;overflow:auto;scrollbar-width:none}.names-premium::-webkit-scrollbar{display:none}.names-premium *{box-sizing:border-box}
   .np-shell{width:min(100%,430px);min-height:100%;margin:auto;background:${C.bg};padding-bottom:96px}.np-top{position:sticky;top:0;z-index:20;background:rgba(247,243,234,.94);backdrop-filter:blur(10px);border-bottom:1px solid rgba(16,45,67,.07);padding:15px 20px;display:grid;grid-template-columns:40px 1fr 40px;align-items:center}.np-iconbtn{border:0;background:transparent;color:${C.gold2};font-size:18px;cursor:pointer}.np-headtitle{text-align:center;font-size:13px;font-weight:600}.np-intro{text-align:center;padding:22px 20px 0}.np-kicker{font-family:'IBM Plex Mono',monospace;font-size:9px;letter-spacing:.3em;color:${C.gold2};direction:ltr}.np-title{font-family:'Amiri',serif;font-size:30px;margin-top:7px}.np-sub{font-size:11px;color:${C.muted};margin-top:7px}
   .np-today{margin:18px 20px 0;padding:20px;border-radius:24px;background:${C.navy};color:${C.bg};position:relative;overflow:hidden}.np-today:before{content:'';position:absolute;inset:0;background:radial-gradient(85% 80% at 85% -14%,rgba(192,160,98,.30),transparent 62%);pointer-events:none}.np-today>*{position:relative}.np-todayhead{display:flex;align-items:center;justify-content:space-between;font-size:11px}.np-name{font-family:'Amiri',serif;font-size:44px;line-height:1.25;text-align:center;margin-top:14px}.np-latin{text-align:center;font-family:'IBM Plex Mono',monospace;font-size:10px;letter-spacing:.22em;color:rgba(247,243,234,.45);margin-top:6px;direction:ltr}.np-desc{text-align:center;font-size:12px;color:rgba(247,243,234,.7);margin-top:12px;line-height:1.9}.np-actions{display:flex;gap:9px;margin-top:18px}.np-primary{flex:1;border:0;border-radius:999px;padding:11px;background:${C.gold};color:${C.navy};font-size:13px;font-weight:600}.np-round{width:46px;border-radius:999px;border:1px solid rgba(247,243,234,.18);background:transparent;color:${C.gold};font-size:15px}
   .np-search{margin:18px 20px 0;display:flex;align-items:center;gap:9px;background:${C.paper};border:1px solid rgba(16,45,67,.09);border-radius:16px;padding:11px 14px}.np-search input{flex:1;border:0;outline:0;background:transparent;font-family:inherit;font-size:13px;color:${C.text}}.np-search span{color:${C.soft}}
   .np-chips{margin:14px 20px 0;display:grid;grid-template-columns:repeat(4,1fr);gap:7px}.np-chip{padding:8px 0;border-radius:999px;font-size:11px;cursor:pointer}.np-list{margin:20px 20px 0}.np-listhead{display:flex;justify-content:space-between;align-items:baseline;margin-bottom:11px}.np-grid{display:grid;grid-template-columns:1fr 1fr;gap:9px}.np-card{padding:14px 14px 15px;border-radius:18px;background:${C.paper};border:1px solid rgba(16,45,67,.07);cursor:pointer}.np-cardtop{display:flex;justify-content:space-between;align-items:center}.np-tag,.np-num{font-family:'IBM Plex Mono',monospace;font-size:9px}.np-tag{color:${C.gold2}}.np-num{color:#C3C9CF}.np-cardname{font-family:'Amiri',serif;font-size:27px;text-align:center;margin-top:8px;line-height:1.3}.np-meaning{font-size:11px;color:#6F7A85;text-align:center;margin-top:8px}.np-more{text-align:center;padding:24px 20px 28px}.np-more span{display:inline-flex;padding:11px 22px;border-radius:999px;background:rgba(192,160,98,.14);color:#8E6F38;font-size:12px;font-weight:600}
   .np-overlay{position:fixed;inset:0;z-index:30;background:rgba(16,45,67,.45);display:flex;align-items:flex-end;justify-content:center}.np-sheet{width:min(100%,430px);background:${C.bg};border-radius:30px 30px 0 0;padding:22px 22px 28px;box-shadow:0 -20px 50px -20px rgba(16,45,67,.6)}.np-sheetbar{display:flex;justify-content:space-between;align-items:center}.np-sheetname{font-family:'Amiri',serif;font-size:40px;text-align:center;margin-top:12px}.np-box{margin-top:10px;padding:16px 18px;border-radius:18px;background:${C.paper};border:1px solid rgba(16,45,67,.07)}.np-proof{font-family:'Amiri',serif;font-size:19px;line-height:2;text-align:center;margin-top:8px}
  `}</style>
  <div className="np-shell">
   <header className="np-top"><button className="np-iconbtn" onClick={()=>go?.('home')} aria-label="رجوع">→</button><div className="np-headtitle">أسماء الله الحسنى</div><button className="np-iconbtn" onClick={()=>document.querySelector('.np-search input')?.focus()} aria-label="بحث">⌕</button></header>
   <div className="np-intro"><div className="np-kicker">99 NAMES</div><div className="np-title">أسماء الله الحسنى</div><div className="np-sub">الاسم · المعنى · الشرح والدليل</div></div>
   <section className="np-today"><div className="np-todayhead"><span style={{color:'rgba(247,243,234,.5)'}}>اسم اليوم</span><span style={{fontFamily:'IBM Plex Mono',color:C.gold}}>٠١ / ٩٩</span></div><div className="np-name">{today.ar}</div><div className="np-latin">{today.latin}</div><div className="np-desc">ذو الرحمة الواسعة التي شملت الخلق كلّهم.</div><div className="np-actions"><button className="np-primary" onClick={()=>setSelected(today)}>اقرأ الشرح</button><button className="np-round" onClick={()=>toggleSaved(today)}>{saved.has(today.num)?'✓':'↗'}</button></div></section>
   <label className="np-search"><span>⌕</span><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="ابحث باسم أو معنى…"/></label>
   <div className="np-chips">{CHIPS.map(c=><button key={c} className="np-chip" onClick={()=>setChip(c)} style={{background:chip===c?C.navy:'transparent',color:chip===c?C.bg:'#5B6672',border:`1px solid ${chip===c?C.navy:'rgba(16,45,67,.14)'}`}}>{c}</button>)}</div>
   <section className="np-list"><div className="np-listhead"><strong style={{fontSize:13}}>{chip==='الكل'?'الأسماء':`أسماء ${chip}`}</strong><span style={{fontSize:11,color:C.soft}}>{arNum(shown.length)} من ٩٩</span></div><div className="np-grid">{shown.map(n=><button key={n.num} className="np-card" onClick={()=>setSelected(n)}><div className="np-cardtop"><span className="np-tag">{n.theme}</span><span className="np-num">{n.num}</span></div><div className="np-cardname">{n.ar}</div><div className="np-meaning">{n.meaning}</div></button>)}</div></section>
   <div className="np-more"><span>عرض الأسماء الـ٩٩</span></div>
  </div>
  {selected&&<div className="np-overlay" onClick={()=>setSelected(null)}><div className="np-sheet" onClick={e=>e.stopPropagation()}><div className="np-sheetbar"><button className="np-iconbtn" onClick={()=>setSelected(null)}>✕</button><span style={{fontFamily:'IBM Plex Mono',fontSize:10,color:C.gold2}}>{selected.num} / ٩٩</span></div><div className="np-sheetname">{selected.ar}</div><div className="np-latin" style={{color:C.soft}}>{selected.latin}</div><div className="np-box"><div style={{fontSize:11,color:C.gold2}}>المعنى</div><div style={{fontSize:13,lineHeight:1.9,marginTop:7}}>{selected.full}</div></div><div className="np-box"><div style={{fontSize:11,color:C.gold2}}>من الدليل</div><div className="np-proof">{selected.proof}</div><div style={{fontSize:10,color:C.soft,textAlign:'center',marginTop:8}}>{selected.ref}</div></div><div className="np-actions"><button className="np-primary" style={{background:C.navy,color:C.bg}} onClick={()=>toggleSaved(selected)}>{saved.has(selected.num)?'محفوظ':'أضف إلى المحفوظات'}</button><button className="np-round" style={{borderColor:'rgba(16,45,67,.14)',color:C.gold2}}>↗</button></div></div></div>}
 </div>;
}
