import React,{useEffect,useMemo,useState} from "react";

const C={ivory:"#F6F3EC",ink:"#10100F",lapis:"#173B57",gold:"#B59A62",green:"#4F915C"};
const btn={border:"1px solid rgba(16,16,15,.08)",borderRadius:16,padding:12,background:"rgba(255,255,255,.56)",fontFamily:"inherit",color:"inherit"};
const profile=()=>{try{return localStorage.getItem("sakinah-active-profile")||"me"}catch{return "me"}};
const key=n=>`sakinah-native-${profile()}-${n}`;
const read=(n,d)=>{try{const x=localStorage.getItem(key(n));return x==null?d:JSON.parse(x)}catch{return d}};
const native=()=>typeof window!=="undefined"&&window.SakinahNative?window.SakinahNative:null;
const write=(n,v)=>{try{localStorage.setItem(key(n),JSON.stringify(v))}catch{}}
function Shell({lang,go,titleAr,titleEn,children}){return <div style={{position:"fixed",inset:0,zIndex:50000,background:C.ivory,color:C.ink,overflowY:"auto",padding:"25px 22px 130px"}} dir={lang==="ar"?"rtl":"ltr"}><button onClick={go} style={{...btn,border:0,padding:0,background:"transparent"}}>{lang==="ar"?"رجوع ←":"← Back"}</button><div style={{fontFamily:"Fraunces,serif",fontSize:31,marginTop:16}}>{lang==="ar"?titleAr:titleEn}</div>{children}</div>}
async function coords(){return new Promise((ok,fail)=>navigator.geolocation?navigator.geolocation.getCurrentPosition(p=>ok(p.coords),fail,{enableHighAccuracy:true,timeout:10000}):fail())}
async function todayTimes(){const c=await coords();const r=await fetch(`https://api.aladhan.com/v1/timings?latitude=${c.latitude}&longitude=${c.longitude}&method=4`);const j=await r.json();return j?.data}
const PR=["Fajr","Dhuhr","Asr","Maghrib","Isha"];
function cleanTime(v=""){return v.split(" ")[0]}
function epochToday(v){const [h,m]=cleanTime(v).split(":").map(Number);const d=new Date();d.setHours(h||0,m||0,0,0);return d.getTime()}
function nextPrayer(timings){if(!timings)return null;const now=Date.now();for(const p of PR){const at=epochToday(timings[p]);if(at>now)return [p,cleanTime(timings[p]),at]}const d=new Date();d.setDate(d.getDate()+1);const [h,m]=cleanTime(timings.Fajr).split(":").map(Number);d.setHours(h||0,m||0,0,0);return ["Fajr",cleanTime(timings.Fajr),d.getTime()]}
function syncNative(cfg,data){const bridge={schema:2,updatedAt:new Date().toISOString(),profile:profile(),notifications:cfg,timings:data?.timings||null,calendar:data?.date||null};write("native-bridge",bridge);const n=native();if(!n)return;try{n.saveBridgeState(JSON.stringify(bridge))}catch{}
 if(data?.timings){for(const p of PR){try{if(cfg[p])n.schedulePrayer(p,epochToday(data.timings[p]),`حان وقت صلاة ${p}`);else n.cancelPrayer(p)}catch{}}
 const nxt=nextPrayer(data.timings);if(nxt){try{localStorage.setItem("sakinah-widget-next-prayer",nxt[0]);localStorage.setItem("sakinah-widget-next-time",nxt[1]);n.saveBridgeState(JSON.stringify({...bridge,nextPrayer:nxt[0],nextPrayerTime:nxt[1]}));n.refreshWidget()}catch{}}
 }
}

export function NativeDailyCenter({lang,go}){
 const [cfg,setCfg]=useState(()=>read("adhan",{Fajr:true,Dhuhr:true,Asr:true,Maghrib:true,Isha:true,friday:true,ramadan:true,adhkar:true,voice:"default"}));
 const [times,setTimes]=useState(null),[msg,setMsg]=useState("");
 useEffect(()=>{todayTimes().then(x=>{setTimes(x);syncNative(cfg,x)}).catch(()=>{})},[]);
 const set=(k,v)=>{const n={...cfg,[k]:v};setCfg(n);write("adhan",n);syncNative(n,times)};
 const permission=async()=>{if(native()){setMsg(lang==="ar"?"إذن Android الأصلي يدار من النظام وتم تجهيز الجدولة.":"Android native permission is managed by the system and scheduling is ready.");return}if(!("Notification" in window)){setMsg(lang==="ar"?"المتصفح لا يدعم الإشعارات":"Notifications unsupported");return}const p=await Notification.requestPermission();setMsg(p==="granted"?(lang==="ar"?"تم تفعيل إذن الإشعارات":"Notifications enabled"):(lang==="ar"?"لم يتم منح الإذن":"Permission not granted"))};
 const test=()=>{if(native()){const at=Date.now()+8000;try{native().schedulePrayer("test",at,lang==="ar"?"اختبار تنبيه سكينة":"Sakinah notification test");setMsg(lang==="ar"?"تم جدولة اختبار Android بعد 8 ثوانٍ":"Android test scheduled in 8 seconds")}catch{};return}if(Notification?.permission==="granted")new Notification(lang==="ar"?"سكينة":"Sakinah",{body:lang==="ar"?"هذا اختبار لتنبيه الصلاة والذكر.":"Prayer and adhkar notification test."})};
 const day=times?.date?.hijri; const isRamadan=day?.month?.number===9; const isFriday=new Date().getDay()===5;
 return <Shell lang={lang} go={go} titleAr="المؤذن والتنبيهات" titleEn="Adhan & Notifications"><div style={{fontSize:11.5,opacity:.5,lineHeight:1.8,marginTop:7}}>{native()?(lang==="ar"?"متصل الآن بـ Android Native: AlarmManager والإشعارات والـWidget يستلمون إعدادات سكينة مباشرة.":"Connected to Android Native: alarms, notifications and widget consume Sakinah settings directly."):(lang==="ar"?"نسخة الويب تستخدم إشعارات المتصفح، وتبقى نفس الإعدادات جاهزة للـAndroid Native.":"Web uses browser notifications while the same settings stay ready for Android Native.")}</div>
 <div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:8,marginTop:18}}><button onClick={permission} style={{...btn,background:C.lapis,color:"white",border:0}}>{lang==="ar"?"تفعيل الإشعارات":"Enable notifications"}</button><button onClick={test} style={btn}>{lang==="ar"?"اختبار تنبيه":"Test alert"}</button></div>{msg&&<div style={{fontSize:10.5,marginTop:8,opacity:.6}}>{msg}</div>}
 <div style={{marginTop:18,borderRadius:22,overflow:"hidden",border:"1px solid rgba(16,16,15,.07)",background:"rgba(255,255,255,.45)"}}>{PR.map(p=><label key={p} style={{display:"flex",alignItems:"center",justifyContent:"space-between",gap:12,padding:"14px 15px",borderBottom:"1px solid rgba(16,16,15,.06)"}}><div><b style={{fontSize:12.5}}>{p}</b><small style={{display:"block",opacity:.42,marginTop:3}}>{times?.timings?.[p]||"--:--"}</small></div><input type="checkbox" checked={!!cfg[p]} onChange={e=>set(p,e.target.checked)}/></label>)}</div>
 <div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:8,marginTop:12}}><label style={btn}><span>{lang==="ar"?"تنبيه الجمعة":"Friday mode"}</span><input style={{float:"inline-end"}} type="checkbox" checked={!!cfg.friday} onChange={e=>set("friday",e.target.checked)}/></label><label style={btn}><span>{lang==="ar"?"تنبيهات رمضان":"Ramadan mode"}</span><input style={{float:"inline-end"}} type="checkbox" checked={!!cfg.ramadan} onChange={e=>set("ramadan",e.target.checked)}/></label></div>
 {(isFriday||isRamadan)&&<div style={{marginTop:12,padding:15,borderRadius:18,background:"rgba(181,154,98,.10)",fontSize:11.5,lineHeight:1.8}}>{isFriday&&(lang==="ar"?"اليوم جمعة: سورة الكهف، الصلاة على النبي ﷺ، التبكير والدعاء.":"Friday: Al-Kahf, salawat, early preparation and dua.")}{isFriday&&isRamadan&&<br/>}{isRamadan&&(lang==="ar"?"رمضان: السحور، الإمساك، الإفطار، الورد والقيام.":"Ramadan: suhoor, imsak, iftar, wird and qiyam.")}</div>}
 </Shell>}

export function WidgetLockPreview({lang,go}){const [data,setData]=useState(null);useEffect(()=>{todayTimes().then(x=>{setData(x);const n=nextPrayer(x?.timings);if(native()&&n){try{native().saveBridgeState(JSON.stringify({schema:2,nextPrayer:n[0],nextPrayerTime:n[1]}));native().refreshWidget()}catch{}}}).catch(()=>{})},[]);const next=useMemo(()=>nextPrayer(data?.timings),[data]);return <Shell lang={lang} go={go} titleAr="Widget وشاشة القفل" titleEn="Widget & Lock Screen"><div style={{marginTop:20,padding:20,borderRadius:28,background:"linear-gradient(145deg,#173B57,#0C293E)",color:"white",boxShadow:"0 18px 38px rgba(23,59,87,.22)"}}><div style={{fontSize:10,opacity:.6}}>{lang==="ar"?"الصلاة القادمة":"NEXT PRAYER"}</div><div style={{fontFamily:"Fraunces,serif",fontSize:30,marginTop:8}}>{next?.[0]||"—"}</div><div style={{fontSize:42,color:"#E7D29B",marginTop:8}}>{next?.[1]||"--:--"}</div><div style={{marginTop:18,paddingTop:14,borderTop:"1px solid rgba(255,255,255,.14)",fontSize:11,opacity:.75}}>{lang==="ar"?"آية اليوم · ذكر سريع · المسبحة":"Ayah of the day · Quick dhikr · Tasbih"}</div></div><div style={{marginTop:14,fontSize:11.5,opacity:.5,lineHeight:1.8}}>{native()?(lang==="ar"?"Android Widget متصل بهذه البيانات، ويدعم home_screen وkeyguard عندما يسمح الجهاز بذلك.":"Android Widget is connected to this data and supports home_screen and keyguard where the device allows it."):(lang==="ar"?"هذه معاينة الويب لنفس بيانات الـWidget.":"This is the web preview of the same widget data.")}</div></Shell>}
