import React,{useEffect,useMemo,useRef,useState} from "react";

const C={ivory:"#F6F3EC",ink:"#10100F",lapis:"#173B57",gold:"#B59A62"};
const btn={border:"1px solid rgba(16,16,15,.08)",borderRadius:18,padding:12,background:"rgba(255,255,255,.62)",fontFamily:"inherit",color:"inherit"};
const profile=()=>{try{return localStorage.getItem("sakinah-active-profile")||"me"}catch{return"me"}};
const key=n=>`sakinah-native-${profile()}-${n}`;
const read=(n,d)=>{try{const x=localStorage.getItem(key(n));return x==null?d:JSON.parse(x)}catch{return d}};
const write=(n,v)=>{try{localStorage.setItem(key(n),JSON.stringify(v))}catch{}};
const native=()=>typeof window!=="undefined"&&window.SakinahNative?window.SakinahNative:null;
const PR=["Fajr","Dhuhr","Asr","Maghrib","Isha"];
const PR_AR={Fajr:"الفجر",Dhuhr:"الظهر",Asr:"العصر",Maghrib:"المغرب",Isha:"العشاء"};
const MUEZZINS=[
 {id:"default",ar:"تنبيه فقط",en:"Alert only",asset:null},
 {id:"wadie-al-yamani",ar:"وديع اليمني",en:"Wadie Al-Yamani",asset:"/audio/adhan/وديع اليمني.ogg"},
 {id:"ahmed-al-nafis",ar:"أحمد النفيس",en:"Ahmed Al-Nafis",asset:"/audio/adhan/احمد النفيس.ogg"},
 {id:"mishary-alafasy",ar:"مشاري العفاسي",en:"Mishary Alafasy",asset:"/audio/adhan/مشاري العفاسي .ogg"},
 {id:"ahmed-galal-yahia",ar:"أحمد جلال يحيى",en:"Ahmed Galal Yahia",asset:"/audio/adhan/احمد يحيى.ogg"}
];
const voiceById=id=>MUEZZINS.find(x=>x.id===id)||MUEZZINS[0];
function Shell({lang,go,titleAr,titleEn,children}){return <div style={{position:"fixed",inset:0,zIndex:50000,background:"linear-gradient(180deg,#FAF7F0,#F3EFE6)",color:C.ink,overflowY:"auto"}} dir={lang==="ar"?"rtl":"ltr"}><div style={{maxWidth:720,margin:"0 auto",padding:"max(76px,calc(env(safe-area-inset-top) + 48px)) 18px 130px",boxSizing:"border-box"}}><button onClick={go} style={{...btn,padding:"8px 12px",borderRadius:999}}>{lang==="ar"?"→ رجوع":"← Back"}</button><div style={{textAlign:"center",marginTop:12}}><div style={{fontSize:10,color:C.gold,letterSpacing:.8}}>SAKINAH</div><div style={{fontSize:30,lineHeight:1.5,fontWeight:700,marginTop:2}}>{lang==="ar"?titleAr:titleEn}</div></div>{children}</div></div>}
async function coords(){return new Promise((ok,fail)=>navigator.geolocation?navigator.geolocation.getCurrentPosition(p=>ok(p.coords),fail,{enableHighAccuracy:true,timeout:10000}):fail())}
async function todayTimes(){const c=await coords();const r=await fetch(`https://api.aladhan.com/v1/timings?latitude=${c.latitude}&longitude=${c.longitude}&method=4`);const j=await r.json();return j?.data}
function cleanTime(v=""){return v.split(" ")[0]}
function epochToday(v){const [h,m]=cleanTime(v).split(":").map(Number);const d=new Date();d.setHours(h||0,m||0,0,0);return d.getTime()}
function epochNext(v){let at=epochToday(v);if(at<=Date.now()){const d=new Date(at);d.setDate(d.getDate()+1);at=d.getTime()}return at}
function nextPrayer(timings){if(!timings)return null;const now=Date.now();for(const p of PR){const at=epochToday(timings[p]);if(at>now)return[p,cleanTime(timings[p]),at]}const d=new Date();d.setDate(d.getDate()+1);const [h,m]=cleanTime(timings.Fajr).split(":").map(Number);d.setHours(h||0,m||0,0,0);return["Fajr",cleanTime(timings.Fajr),d.getTime()]}
function syncNative(cfg,data){const voices=Object.fromEntries(PR.map(p=>{const id=(cfg.voices||{})[p]||cfg.voice||"default";const v=voiceById(id);return[p,{id,asset:v.asset}]}));const bridge={schema:4,updatedAt:new Date().toISOString(),profile:profile(),notifications:cfg,voiceAssets:voices,timings:data?.timings||null,calendar:data?.date||null};write("native-bridge",bridge);const n=native();if(!n)return;try{n.saveBridgeState(JSON.stringify(bridge))}catch{}if(data?.timings){for(const p of PR){try{if(cfg[p])n.schedulePrayer(p,epochNext(data.timings[p]),`حان وقت صلاة ${PR_AR[p]}`);else n.cancelPrayer(p)}catch{}}const nxt=nextPrayer(data.timings);if(nxt){try{localStorage.setItem("sakinah-widget-next-prayer",nxt[0]);localStorage.setItem("sakinah-widget-next-time",nxt[1]);n.saveBridgeState(JSON.stringify({...bridge,nextPrayer:nxt[0],nextPrayerTime:nxt[1]}));n.refreshWidget()}catch{}}}}
function Switch({on,onChange}){return <button type="button" onClick={()=>onChange(!on)} style={{width:46,height:27,padding:3,border:0,borderRadius:999,background:on?C.lapis:"rgba(16,16,15,.12)",display:"flex",alignItems:"center",justifyContent:on?"flex-end":"flex-start"}}><span style={{width:21,height:21,borderRadius:"50%",background:"white",boxShadow:"0 2px 7px rgba(0,0,0,.12)"}}/></button>}
function VoiceCapsule({lang,value,onChange,onPreview,playing}){const [open,setOpen]=useState(false);const current=voiceById(value);return <div style={{position:"relative"}}><div style={{display:"grid",gridTemplateColumns:current.asset?"1fr 46px":"1fr",gap:7}}><button type="button" onClick={()=>setOpen(v=>!v)} style={{minHeight:52,border:"1px solid rgba(16,16,15,.07)",borderRadius:999,background:"rgba(255,255,255,.72)",padding:"8px 14px",display:"flex",alignItems:"center",justifyContent:"space-between",gap:10,fontFamily:"inherit",color:C.ink}}><span style={{display:"flex",alignItems:"center",gap:10,minWidth:0}}><span style={{width:36,height:36,borderRadius:"50%",display:"grid",placeItems:"center",background:"rgba(181,154,98,.14)",color:C.gold,fontSize:17}}>◉</span><span style={{textAlign:lang==="ar"?"right":"left"}}><small style={{display:"block",fontSize:9.5,opacity:.45}}>{lang==="ar"?"المؤذن":"Muezzin"}</small><b style={{fontSize:12.5}}>{lang==="ar"?current.ar:current.en}</b></span></span><span style={{opacity:.45}}>{open?"⌃":"⌄"}</span></button>{current.asset&&<button type="button" onClick={()=>onPreview(current)} style={{width:46,height:46,alignSelf:"center",border:0,borderRadius:"50%",background:playing?C.gold:C.lapis,color:"white",fontSize:14}}>{playing?"■":"▶"}</button>}</div>{open&&<div style={{position:"absolute",top:"calc(100% + 7px)",left:0,right:0,zIndex:30,padding:7,borderRadius:22,background:"#FFFCF7",boxShadow:"0 18px 48px rgba(16,16,15,.14)",border:"1px solid rgba(16,16,15,.07)"}}>{MUEZZINS.map(x=><button key={x.id} type="button" onClick={()=>{onChange(x.id);setOpen(false)}} style={{width:"100%",border:0,borderRadius:15,padding:"11px 12px",background:value===x.id?"rgba(181,154,98,.13)":"transparent",fontFamily:"inherit",color:C.ink,textAlign:lang==="ar"?"right":"left",display:"flex",justifyContent:"space-between"}}><span>{lang==="ar"?x.ar:x.en}</span><span>{x.asset?"♪":""}{value===x.id?" ✓":""}</span></button>)}</div>}</div>}

export function NativeDailyCenter({lang,go}){
 const [cfg,setCfg]=useState(()=>read("adhan",{Fajr:true,Dhuhr:true,Asr:true,Maghrib:true,Isha:true,friday:true,ramadan:true,voice:"default",voices:{}}));
 const [times,setTimes]=useState(null),[msg,setMsg]=useState(""),[playing,setPlaying]=useState("");
 const audioRef=useRef(null);
 useEffect(()=>{todayTimes().then(x=>{setTimes(x);syncNative(cfg,x)}).catch(()=>{});return()=>{try{audioRef.current?.pause()}catch{}}},[]);
 const set=(k,v)=>{const n={...cfg,[k]:v};setCfg(n);write("adhan",n);syncNative(n,times)};
 const setVoice=(p,v)=>{const n={...cfg,voices:{...(cfg.voices||{}),[p]:v}};setCfg(n);write("adhan",n);syncNative(n,times)};
 const setAllVoice=v=>{const n={...cfg,voice:v,voices:Object.fromEntries(PR.map(p=>[p,v]))};setCfg(n);write("adhan",n);syncNative(n,times)};
 const preview=v=>{try{if(audioRef.current){audioRef.current.pause();audioRef.current.currentTime=0}if(playing===v.id){setPlaying("");return}if(!v.asset)return;const a=new Audio(v.asset);audioRef.current=a;a.onended=()=>setPlaying("");a.onerror=()=>{setPlaying("");setMsg(lang==="ar"?"تعذر تشغيل ملف الأذان":"Could not play adhan file")};a.play().then(()=>setPlaying(v.id)).catch(()=>setMsg(lang==="ar"?"اضغط مرة أخرى للسماح بتشغيل الصوت":"Tap again to allow audio playback"))}catch{}};
 const permission=async()=>{if(native()){setMsg(lang==="ar"?"تم تجهيز جدولة Android الأصلية.":"Android native scheduling is ready.");return}if(!("Notification" in window)){setMsg(lang==="ar"?"المتصفح لا يدعم الإشعارات":"Notifications unsupported");return}const p=await Notification.requestPermission();setMsg(p==="granted"?(lang==="ar"?"تم تفعيل الإشعارات":"Notifications enabled"):(lang==="ar"?"لم يتم منح الإذن":"Permission not granted"))};
 const test=()=>{const v=voiceById(cfg.voice||"default");if(v.asset){preview(v);setMsg(lang==="ar"?`تشغيل معاينة: ${v.ar}`:`Preview: ${v.en}`);return}if(Notification?.permission==="granted")new Notification(lang==="ar"?"سكينة":"Sakinah",{body:lang==="ar"?"اختبار تنبيه الصلاة":"Prayer alert test"});else setMsg(lang==="ar"?"اختر مؤذناً بصوت فعلي أو فعّل الإشعارات":"Choose a muezzin with audio or enable notifications")};
 const day=times?.date?.hijri,isRamadan=day?.month?.number===9,isFriday=new Date().getDay()===5;
 return <Shell lang={lang} go={go} titleAr="المؤذن والتنبيهات" titleEn="Adhan & Notifications"><div style={{fontSize:11.5,opacity:.5,lineHeight:1.8,margin:"6px auto 0",textAlign:"center",maxWidth:560}}>{lang==="ar"?"اختر المؤذن واستمع للصوت مباشرة قبل اعتماده لكل صلاة.":"Choose a muezzin and preview the real audio before assigning it."}</div><div style={{display:"grid",gridTemplateColumns:"1.2fr .8fr",gap:9,marginTop:18}}><button onClick={permission} style={{...btn,background:C.lapis,color:"white",border:0,minHeight:54,fontWeight:700}}>{lang==="ar"?"تفعيل الإشعارات":"Enable notifications"}</button><button onClick={test} style={{...btn,minHeight:54}}>{lang==="ar"?"▶ اختبار صوت المؤذن":"▶ Test muezzin"}</button></div>{msg&&<div style={{fontSize:10.5,marginTop:9,padding:"10px 12px",borderRadius:14,background:"rgba(181,154,98,.10)"}}>{msg}</div>}<section style={{marginTop:18,padding:15,borderRadius:26,background:"rgba(255,255,255,.55)",border:"1px solid rgba(16,16,15,.055)"}}><div style={{fontSize:13,fontWeight:800,marginBottom:10}}>{lang==="ar"?"المؤذن الافتراضي":"Default muezzin"}</div><VoiceCapsule lang={lang} value={cfg.voice||"default"} onChange={setAllVoice} onPreview={preview} playing={playing===(cfg.voice||"default")}/></section><div style={{marginTop:14,display:"grid",gap:9}}>{PR.map(p=>{const selected=(cfg.voices||{})[p]||cfg.voice||"default";return <div key={p} style={{padding:14,borderRadius:24,background:"rgba(255,255,255,.72)",border:"1px solid rgba(16,16,15,.055)"}}><div style={{display:"flex",alignItems:"center",justifyContent:"space-between",gap:12}}><div><div style={{fontSize:14,fontWeight:800}}>{lang==="ar"?PR_AR[p]:p}</div><div style={{fontSize:11,opacity:.42,marginTop:3}}>{times?.timings?.[p]||"--:--"}</div></div><Switch on={!!cfg[p]} onChange={v=>set(p,v)}/></div><div style={{marginTop:11}}><VoiceCapsule lang={lang} value={selected} onChange={v=>setVoice(p,v)} onPreview={preview} playing={playing===selected}/></div></div>})}</div><div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:9,marginTop:12}}><div style={{...btn,display:"flex",alignItems:"center",justifyContent:"space-between"}}><span>{lang==="ar"?"تنبيه الجمعة":"Friday mode"}</span><Switch on={!!cfg.friday} onChange={v=>set("friday",v)}/></div><div style={{...btn,display:"flex",alignItems:"center",justifyContent:"space-between"}}><span>{lang==="ar"?"تنبيهات رمضان":"Ramadan mode"}</span><Switch on={!!cfg.ramadan} onChange={v=>set("ramadan",v)}/></div></div>{(isFriday||isRamadan)&&<div style={{marginTop:12,padding:15,borderRadius:18,background:"rgba(181,154,98,.10)",fontSize:11.5,lineHeight:1.8}}>{isFriday&&(lang==="ar"?"اليوم جمعة: سورة الكهف، الصلاة على النبي ﷺ، التبكير والدعاء.":"Friday: Al-Kahf, salawat, early preparation and dua.")}{isFriday&&isRamadan&&<br/>}{isRamadan&&(lang==="ar"?"رمضان: السحور، الإمساك، الإفطار، الورد والقيام.":"Ramadan: suhoor, imsak, iftar, wird and qiyam.")}</div>}</Shell>;
}

export function WidgetLockPreview({lang,go}){const [data,setData]=useState(null);useEffect(()=>{todayTimes().then(setData).catch(()=>{})},[]);const next=useMemo(()=>nextPrayer(data?.timings),[data]);return <Shell lang={lang} go={go} titleAr="Widget وشاشة القفل" titleEn="Widget & Lock Screen"><div style={{marginTop:20,padding:20,borderRadius:28,background:"linear-gradient(145deg,#173B57,#0C293E)",color:"white"}}><div style={{fontSize:10,opacity:.6}}>{lang==="ar"?"الصلاة القادمة":"NEXT PRAYER"}</div><div style={{fontSize:30,marginTop:8}}>{lang==="ar"?(PR_AR[next?.[0]]||"—"):(next?.[0]||"—")}</div><div style={{fontSize:42,color:"#E7D29B",marginTop:8}}>{next?.[1]||"--:--"}</div></div></Shell>}
