import React,{useEffect,useMemo,useRef,useState} from "react";

const C={ivory:"#F6F3EC",ink:"#10100F",lapis:"#173B57",gold:"#B59A62",green:"#416F5A",soft:"#EEE7D8",red:"#A44D3C"};
const ar=n=>String(n).replace(/[0-9]/g,d=>"٠١٢٣٤٥٦٧٨٩"[d]);
const rad=x=>x*Math.PI/180;
function haversine(a,b,c,d){const R=6371,dp=rad(c-a),dl=rad(d-b),x=Math.sin(dp/2)**2+Math.cos(rad(a))*Math.cos(rad(c))*Math.sin(dl/2)**2;return 2*R*Math.asin(Math.sqrt(x))}
function distText(km){return km<1?`${ar(Math.round(km*1000))} م`:`${ar(km.toFixed(2))} كم`}
function accuracyLabel(m){if(m==null)return "—";if(m<=10)return "ممتازة";if(m<=25)return "جيدة جداً";if(m<=50)return "جيدة";return "ضعيفة"}

export default function NearbyMosquesPro(){
 const[loc,setLoc]=useState(null),[accuracy,setAccuracy]=useState(null),[bestAccuracy,setBestAccuracy]=useState(null),[rows,setRows]=useState([]),[busy,setBusy]=useState(false),[gpsOn,setGpsOn]=useState(false),[status,setStatus]=useState("جاري تشغيل GPS عالي الدقة…"),[lastSearch,setLastSearch]=useState(null);
 const watchRef=useRef(null),searchTimer=useRef(null),lastSearchLoc=useRef(null);
 const sorted=useMemo(()=>loc?rows.map(x=>({...x,dist:haversine(loc.lat,loc.lon,x.lat,x.lon)})).sort((a,b)=>a.dist-b.dist):rows,[rows,loc]);
 const searchMosques=async(position=loc,force=false)=>{if(!position||busy)return;const prev=lastSearchLoc.current;if(!force&&prev&&haversine(prev.lat,prev.lon,position.lat,position.lon)<0.15)return;setBusy(true);setStatus("جاري تحديث المساجد القريبة…");try{const q=`[out:json][timeout:25];(nwr(around:7000,${position.lat},${position.lon})[amenity=place_of_worship][religion=muslim];nwr(around:7000,${position.lat},${position.lon})[building=mosque];);out center tags;`;const r=await fetch("https://overpass-api.de/api/interpreter",{method:"POST",headers:{"Content-Type":"application/x-www-form-urlencoded;charset=UTF-8"},body:`data=${encodeURIComponent(q)}`});if(!r.ok)throw new Error("search");const j=await r.json();const map=new Map();for(const x of j.elements||[]){const a=x.lat??x.center?.lat,b=x.lon??x.center?.lon;if(a==null||b==null)continue;const key=`${a.toFixed(5)}:${b.toFixed(5)}`;if(map.has(key))continue;map.set(key,{id:x.id,name:x.tags?.["name:ar"]||x.tags?.name||x.tags?.["name:en"]||"مسجد",lat:a,lon:b,dist:haversine(position.lat,position.lon,a,b),street:x.tags?.["addr:street"]||"",city:x.tags?.["addr:city"]||""});}const data=[...map.values()].sort((a,b)=>a.dist-b.dist).slice(0,30);setRows(data);lastSearchLoc.current=position;setLastSearch(new Date());setStatus(data.length?`تم العثور على ${ar(data.length)} مسجد ضمن ٧ كم`:`لم تظهر مساجد ضمن ٧ كم من موقعك الحالي.`)}catch{setStatus("تعذر تحديث بيانات المساجد الآن. تأكد من الإنترنت ثم حاول مرة أخرى.")}finally{setBusy(false)}};
 const stopGps=()=>{if(watchRef.current!=null&&navigator.geolocation){navigator.geolocation.clearWatch(watchRef.current);watchRef.current=null}setGpsOn(false)};
 const startGps=()=>{if(!navigator.geolocation){setStatus("خدمة الموقع غير متاحة على هذا الجهاز.");return}stopGps();setStatus("جاري الحصول على موقع دقيق…");watchRef.current=navigator.geolocation.watchPosition(p=>{const next={lat:p.coords.latitude,lon:p.coords.longitude};const acc=Number(p.coords.accuracy)||null;setLoc(next);setAccuracy(acc);setBestAccuracy(v=>v==null?acc:acc==null?v:Math.min(v,acc));setGpsOn(true);setStatus(acc!=null&&acc>50?`GPS يعمل، لكن الدقة الحالية ${ar(Math.round(acc))} م. انتظر قليلاً أو اقترب من نافذة/مكان مفتوح.`:`GPS عالي الدقة يعمل الآن · دقة ${acc?ar(Math.round(acc)):"—"} م`);clearTimeout(searchTimer.current);searchTimer.current=setTimeout(()=>searchMosques(next,false),600)},e=>{setGpsOn(false);if(e.code===1)setStatus("لم يتم منح إذن الموقع. فعّل الموقع الدقيق للتطبيق من إعدادات النظام.");else if(e.code===2)setStatus("تعذر الحصول على إشارة GPS حالياً. حاول في مكان مفتوح.");else setStatus("انتهت مهلة تحديد الموقع. أعد تشغيل GPS.")},{enableHighAccuracy:true,timeout:20000,maximumAge:0})};
 useEffect(()=>{startGps();return()=>{stopGps();clearTimeout(searchTimer.current)}},[]);
 const refresh=()=>{startGps();if(loc)searchMosques(loc,true)};
 return <div dir="rtl" style={{position:"absolute",inset:0,overflowY:"auto",background:C.ivory,color:C.ink,scrollPaddingBottom:"calc(380px + env(safe-area-inset-bottom,0px))"}}><main style={{maxWidth:680,margin:"0 auto",paddingTop:30,paddingLeft:18,paddingRight:18,paddingBottom:"calc(380px + env(safe-area-inset-bottom,0px))",boxSizing:"border-box"}}>
  <header style={{textAlign:"center"}}><div style={{fontSize:9.5,color:C.gold,letterSpacing:1.3}}>MOSQUES · SAKINAH</div><h1 style={{fontSize:29,margin:"5px 0 6px"}}>أقرب مسجد</h1><p style={{fontSize:10.5,opacity:.47,lineHeight:1.8,margin:0}}>بحث حي بالـGPS عالي الدقة وترتيب المساجد تلقائياً حسب موقعك الحالي</p></header>
  <section style={{marginTop:18,padding:15,borderRadius:22,background:"linear-gradient(145deg,#173B57,#234F6B)",color:"white",boxShadow:"0 14px 34px rgba(23,59,87,.14)"}}><div style={{display:"flex",justifyContent:"space-between",alignItems:"center",gap:10}}><div><div style={{fontSize:9,opacity:.6}}>حالة الموقع</div><b style={{display:"block",fontSize:13,marginTop:4}}>{gpsOn?"GPS مباشر ومفعّل":"بانتظار GPS"}</b></div><span style={{display:"flex",alignItems:"center",gap:6,fontSize:9.5,opacity:.75}}><i style={{width:8,height:8,borderRadius:"50%",background:gpsOn?"#8FD2A6":"#E4B18D"}}/>{gpsOn?"LIVE":"OFF"}</span></div><div style={{display:"grid",gridTemplateColumns:"repeat(3,1fr)",gap:7,marginTop:13}}>{[[accuracy?`${ar(Math.round(accuracy))} م`:"—","الدقة الحالية"],[bestAccuracy?`${ar(Math.round(bestAccuracy))} م`:"—","أفضل دقة"],[loc?`${ar(sorted.length)}`:"—","المساجد"]].map(([v,l])=><div key={l} style={{padding:"10px 5px",borderRadius:14,background:"rgba(255,255,255,.075)",textAlign:"center"}}><b style={{fontSize:15,color:"#E8D497"}}>{v}</b><small style={{display:"block",fontSize:8,opacity:.55,marginTop:2}}>{l}</small></div>)}</div>{loc&&<div style={{fontSize:8.5,opacity:.52,textAlign:"center",marginTop:9}}>{ar(loc.lat.toFixed(6))} ، {ar(loc.lon.toFixed(6))} · دقة {accuracyLabel(accuracy)}</div>}</section>
  <button onClick={refresh} disabled={busy} style={{width:"100%",marginTop:12,border:0,borderRadius:17,padding:13,background:C.lapis,color:"white",fontFamily:"inherit",fontWeight:700}}>{busy?"جاري التحديث…":"تحديث GPS والبحث"}</button>
  {status&&<div style={{marginTop:9,padding:"10px 12px",borderRadius:14,background:"rgba(16,16,15,.035)",fontSize:9.5,lineHeight:1.7,opacity:.62}}>{status}</div>}
  <section style={{marginTop:18}}><div style={{display:"flex",justifyContent:"space-between",alignItems:"end",marginBottom:7}}><div><div style={{fontSize:9.5,color:C.gold}}>الأقرب إليك</div><h2 style={{fontSize:20,margin:"2px 0"}}>المساجد القريبة</h2></div><span style={{fontSize:8.5,opacity:.38}}>{lastSearch?`آخر تحديث ${lastSearch.toLocaleTimeString("ar-IQ",{hour:"2-digit",minute:"2-digit"})}`:""}</span></div>{sorted.map((x,i)=><article key={`${x.id}-${x.lat}-${x.lon}`} style={{display:"grid",gridTemplateColumns:"42px 1fr auto",gap:10,alignItems:"center",padding:"12px 0",borderTop:"1px solid rgba(16,16,15,.065)"}}><div style={{width:38,height:38,borderRadius:14,display:"grid",placeItems:"center",background:i===0?"rgba(65,111,90,.12)":"rgba(181,154,98,.10)",color:i===0?C.green:C.gold,fontSize:10,fontWeight:800}}>{ar(i+1)}</div><div><b style={{fontSize:12.5}}>{x.name}</b><div style={{display:"flex",gap:7,alignItems:"center",fontSize:9.3,opacity:.45,marginTop:4}}><span>{distText(x.dist)}</span>{(x.street||x.city)&&<><span>·</span><span>{[x.street,x.city].filter(Boolean).join("، ")}</span></>}</div></div><a href={`https://www.google.com/maps/dir/?api=1&destination=${x.lat},${x.lon}`} target="_blank" rel="noreferrer" style={{textDecoration:"none",border:"1px solid rgba(16,16,15,.08)",borderRadius:13,padding:"8px 10px",fontSize:9.5,color:C.ink,background:"rgba(255,255,255,.5)"}}>الاتجاه</a></article>)}{!busy&&sorted.length===0&&<div style={{padding:"28px 12px",textAlign:"center",fontSize:10.5,opacity:.45}}>فعّل GPS وانتظر تحديد موقعك لعرض المساجد القريبة.</div>}</section>
  <section style={{marginTop:14,padding:12,borderRadius:16,background:"rgba(181,154,98,.08)",fontSize:9,lineHeight:1.8,opacity:.6}}>لأفضل دقة GPS فعّل «الموقع الدقيق» للتطبيق، واستخدمه في مكان مفتوح أو قرب نافذة. تتحدث المسافات تلقائياً كلما تحسن موقعك أو تحركت.</section>
  <div aria-hidden="true" style={{height:110}}/>
 </main></div>;
}
