import React,{useEffect,useMemo,useState} from "react";

const C={ivory:"#F6F3EC",ink:"#10100F",lapis:"#173B57",gold:"#B59A62",green:"#416F5A",red:"#9C4A3B",soft:"#EEE7D8"};
const MANIFEST="/data/hadiths/manifest.json";
const ar=n=>String(n??"").replace(/[0-9]/g,d=>"٠١٢٣٤٥٦٧٨٩"[d]);
const textOf=h=>{const v=h?.arabic;return typeof v==="string"?v:String(v?.text??v?.body??v?.hadith??v?.contents??"").trim()};
const chapterName=c=>String(c?.arabic?.title??c?.arabic?.name??c?.arabic??"").trim();
async function loadGzipJson(url){
 const r=await fetch(url,{cache:"force-cache"});
 if(!r.ok)throw new Error("missing");
 const buf=await r.arrayBuffer();
 const bytes=new Uint8Array(buf);
 const isGzip=bytes.length>2&&bytes[0]===0x1f&&bytes[1]===0x8b;
 if(!isGzip)return JSON.parse(new TextDecoder("utf-8").decode(bytes));
 if(typeof DecompressionStream!=="function")throw new Error("gzip-unsupported");
 const ds=new DecompressionStream("gzip");
 return new Response(new Blob([buf]).stream().pipeThrough(ds)).json();
}

export default function NineBooksCenter(){
 const[manifest,setManifest]=useState(null),[bookMeta,setBookMeta]=useState(null),[bookData,setBookData]=useState(null),[chapter,setChapter]=useState(null),[detail,setDetail]=useState(null),[q,setQ]=useState(""),[busy,setBusy]=useState(true),[err,setErr]=useState("");
 const[saved,setSaved]=useState(()=>{try{return JSON.parse(localStorage.getItem("sakinah-nine-books-saved"))||{}}catch{return{}}});
 const[lastBook,setLastBook]=useState(()=>{try{return localStorage.getItem("sakinah-nine-last-book")||""}catch{return""}});
 useEffect(()=>{let alive=true;setBusy(true);fetch(MANIFEST,{cache:"no-cache"}).then(r=>{if(!r.ok)throw new Error();return r.json()}).then(j=>alive&&setManifest(j)).catch(()=>alive&&setErr("بيانات الكتب التسعة المحلية غير مثبتة بعد.")).finally(()=>alive&&setBusy(false));return()=>{alive=false}},[]);
 const books=manifest?.books||[];
 const visibleBooks=useMemo(()=>books.filter(b=>`${b.titleAr} ${b.titleEn} ${b.authorAr}`.toLowerCase().includes(q.trim().toLowerCase())),[books,q]);
 const chapters=bookData?.chapters||[],hadiths=bookData?.hadiths||[];
 const rows=useMemo(()=>chapter?hadiths.filter(h=>String(h.chapterId)===String(chapter.id)):hadiths,[hadiths,chapter]);
 const shownHadiths=useMemo(()=>{const s=q.trim();return s?rows.filter(h=>`${h.idInBook??h.id??""} ${textOf(h)}`.includes(s)):rows},[rows,q]);
 const chapterCounts=useMemo(()=>{const m=new Map();hadiths.forEach(h=>{const k=String(h.chapterId);m.set(k,(m.get(k)||0)+1)});return m},[hadiths]);
 const openBook=async b=>{setBookMeta(b);setBookData(null);setChapter(null);setDetail(null);setQ("");setErr("");setBusy(true);try{localStorage.setItem("sakinah-nine-last-book",b.id);setLastBook(b.id)}catch{}try{setBookData(await loadGzipJson(b.file))}catch(e){setErr(e?.message==="gzip-unsupported"?"هذا المتصفح لا يدعم فك ضغط بيانات الكتب المحلية.":"تعذر فتح بيانات هذا الكتاب المحلية.")}finally{setBusy(false)}};
 const saveKey=detail&&`${bookMeta?.id}:${detail.idInBook??detail.id}`;
 const toggleSave=()=>{if(!saveKey)return;const n={...saved,[saveKey]:!saved[saveKey]};setSaved(n);try{localStorage.setItem("sakinah-nine-books-saved",JSON.stringify(n))}catch{}};
 const share=async()=>{if(!detail)return;const no=detail.idInBook??detail.id??"",text=`${bookMeta?.titleAr||"حديث"}\nحديث رقم ${no}\n\n${textOf(detail)}`;try{if(navigator.share)await navigator.share({title:bookMeta?.titleAr||"حديث",text});else await navigator.clipboard.writeText(text)}catch{}};
 const last=books.find(b=>b.id===lastBook);
 if(detail){const no=detail.idInBook??detail.id;return <Shell><Top title={bookMeta.titleAr} sub={`حديث رقم ${ar(no)}`} back={()=>setDetail(null)}/><article style={reader}><div className="nine-books-hadith-text" style={readerText}>{textOf(detail)||"النص غير متاح."}</div></article><div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:8,marginTop:10}}><button onClick={toggleSave} style={{...action,color:saved[saveKey]?C.green:C.ink}}>{saved[saveKey]?"محفوظ ✓":"حفظ"}</button><button onClick={share} style={action}>مشاركة</button></div><section style={source}>مصدر محلي · {bookMeta.titleAr} · الحديث {ar(no)}</section></Shell>}
 if(bookData){if(chapter)return <Shell><Top title={chapterName(chapter)||bookMeta.titleAr} sub={`${ar(shownHadiths.length)} حديث`} back={()=>{setChapter(null);setQ("")}}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="ابحث برقم الحديث أو داخل النص…" style={input}/><div style={{marginTop:10}}>{shownHadiths.map((h,i)=>{const no=h.idInBook??h.id??i+1;return <button key={`${no}-${i}`} onClick={()=>setDetail(h)} style={hadithRow}><span style={numberBox}>{ar(no)}</span><span style={{minWidth:0}}><b style={{fontSize:11.8}}>حديث رقم {ar(no)}</b><small style={preview}>{textOf(h)}</small></span><span style={{opacity:.25,fontSize:18}}>‹</span></button>})}</div></Shell>;
 return <Shell><Top title={bookMeta.titleAr} sub={`${ar(bookMeta.count)} حديث · ${ar(bookMeta.chapters)} باب`} back={()=>{setBookMeta(null);setBookData(null);setQ("")}}/><div style={{fontSize:10.5,opacity:.46,lineHeight:1.8,marginTop:-5}}>{bookMeta.authorAr}</div><div style={sectionHead}><b>الأبواب</b><span>{ar(chapters.length)} باب</span></div><div style={{display:"grid",gap:8}}>{chapters.map((c,i)=>{const count=chapterCounts.get(String(c.id))||0;return <button key={`${c.id}-${i}`} onClick={()=>setChapter(c)} style={bookRow}><span style={{width:42,height:42,borderRadius:13,background:"rgba(181,154,98,.12)",color:C.gold,display:"grid",placeItems:"center",fontSize:16}}>{ar(i+1)}</span><span style={{minWidth:0}}><b style={{display:"block",fontSize:13,lineHeight:1.55}}>{chapterName(c)||`الباب ${ar(i+1)}`}</b><small style={{display:"block",fontSize:9,opacity:.42,marginTop:4}}>{ar(count)} حديث</small></span><span style={{marginInlineStart:"auto",opacity:.25,fontSize:18}}>‹</span></button>})}</div></Shell>}
 return <Shell><header style={{textAlign:"center",paddingTop:2}}><div style={{fontSize:9.5,color:C.gold,letterSpacing:1.2}}>HADITH · Muslim Mirror</div><h1 style={{fontSize:30,margin:"6px 0 5px"}}>الكتب التسعة</h1><p style={{fontSize:10.5,opacity:.46,lineHeight:1.8,margin:0}}>مكتبة حديث محلية تعمل بدون إنترنت بعد تثبيت حزمة البيانات</p></header><div style={{position:"relative",marginTop:18}}><input value={q} onChange={e=>setQ(e.target.value)} placeholder="ابحث عن كتاب…" style={{...input,paddingRight:42}}/><span style={{position:"absolute",right:15,top:"50%",transform:"translateY(-50%)",opacity:.35}}>⌕</span></div>{last&&!q&&<button onClick={()=>openBook(last)} style={continueCard}><span style={{fontSize:22,color:C.gold}}>▤</span><span><small style={{display:"block",fontSize:9,opacity:.5}}>متابعة القراءة</small><b style={{display:"block",fontSize:13,marginTop:3}}>{last.titleAr}</b></span><span style={{marginInlineStart:"auto",opacity:.35}}>‹</span></button>}{busy&&<Loading text="تحميل المكتبة المحلية…"/>}{err&&<Notice>{err}</Notice>}<div style={sectionHead}><b>جميع الكتب</b><span>{ar(visibleBooks.length)} كتب</span></div><div style={{display:"grid",gap:8}}>{visibleBooks.map((b,i)=><button key={b.id} onClick={()=>openBook(b)} style={bookRow}><span style={{width:42,height:52,borderRadius:13,background:i<2?C.lapis:"rgba(181,154,98,.12)",color:i<2?"#E7D29B":C.gold,display:"grid",placeItems:"center",fontSize:20}}>▤</span><span style={{minWidth:0}}><b style={{display:"block",fontSize:13}}>{b.titleAr}</b><small style={{display:"block",fontSize:9,opacity:.42,marginTop:4}}>{b.authorAr}</small></span><span style={{marginInlineStart:"auto",textAlign:"left"}}><small style={{display:"block",fontSize:8.5,opacity:.4}}>{ar(b.count)} حديث</small><span style={{display:"block",opacity:.25,fontSize:18,marginTop:3}}>‹</span></span></button>)}</div>{!busy&&!err&&visibleBooks.length===0&&<div style={{padding:28,textAlign:"center",fontSize:10.5,opacity:.45}}>لا يوجد كتاب مطابق للبحث.</div>}</Shell>}
function Top({title,sub,back}){return <><button onClick={back} style={{...action,width:"auto",padding:"8px 11px"}}>رجوع</button><header style={{textAlign:"center",margin:"15px 0 14px"}}><div style={{fontSize:9.5,color:C.gold}}>مكتبة الحديث</div><h1 style={{fontSize:28,margin:"4px 0"}}>{title}</h1><div style={{fontSize:9.5,opacity:.42}}>{sub}</div></header></>}
function Shell({children}){return <div dir="rtl" style={{position:"absolute",inset:0,width:"100%",maxWidth:"100vw",overflowY:"auto",overflowX:"hidden",background:C.ivory,color:C.ink,boxSizing:"border-box"}}><main style={{width:"100%",maxWidth:660,minWidth:0,margin:"0 auto",boxSizing:"border-box",overflowX:"hidden",padding:"30px 18px calc(150px + env(safe-area-inset-bottom,0px))"}}>{children}</main></div>}
function Loading({text}){return <div style={{padding:22,textAlign:"center",fontSize:10,opacity:.45}}>{text}</div>}
function Notice({children}){return <div style={{marginTop:10,padding:11,borderRadius:14,background:"rgba(156,74,59,.07)",color:C.red,fontSize:10}}>{children}</div>}
const input={width:"100%",maxWidth:"100%",boxSizing:"border-box",padding:"13px 14px",borderRadius:17,border:"1px solid rgba(16,16,15,.08)",background:"rgba(255,255,255,.64)",fontFamily:"inherit",outline:"none",color:C.ink};
const action={border:"1px solid rgba(16,16,15,.08)",borderRadius:14,padding:"10px 11px",background:"rgba(255,255,255,.58)",fontFamily:"inherit",color:C.ink,fontSize:10};
const reader={width:"100%",maxWidth:"100%",boxSizing:"border-box",padding:"20px 17px",borderRadius:24,background:"#FFFDF8",border:"1px solid rgba(16,16,15,.065)",boxShadow:"0 10px 30px rgba(16,16,15,.035)"};
const readerText={fontFamily:"'Noto Naskh Arabic','Amiri',serif",fontSize:"clamp(21px,5vw,29px)",lineHeight:2.15,direction:"rtl",textAlign:"justify",textAlignLast:"right",textJustify:"auto",letterSpacing:"normal",wordSpacing:"normal",fontKerning:"normal",fontFeatureSettings:'"liga" 1, "calt" 1',whiteSpace:"normal",width:"100%",maxWidth:"100%",overflowWrap:"break-word"};
const source={marginTop:14,padding:12,borderRadius:16,background:"rgba(181,154,98,.08)",fontSize:9.5,lineHeight:1.8,opacity:.65};
const sectionHead={display:"flex",justifyContent:"space-between",alignItems:"center",margin:"20px 2px 9px",fontSize:12};
const continueCard={width:"100%",maxWidth:"100%",boxSizing:"border-box",marginTop:12,padding:"12px 14px",border:"1px solid rgba(181,154,98,.18)",borderRadius:18,background:"rgba(181,154,98,.08)",fontFamily:"inherit",color:C.ink,display:"flex",gap:11,alignItems:"center",textAlign:"right"};
const bookRow={width:"100%",maxWidth:"100%",boxSizing:"border-box",padding:"10px 11px",border:"1px solid rgba(16,16,15,.055)",borderRadius:18,background:"rgba(255,255,255,.5)",fontFamily:"inherit",color:C.ink,display:"flex",alignItems:"center",gap:11,textAlign:"right"};
const numberBox={width:34,height:34,borderRadius:11,display:"grid",placeItems:"center",background:"rgba(181,154,98,.12)",color:C.gold,fontSize:9};
const preview={display:"-webkit-box",WebkitLineClamp:2,WebkitBoxOrient:"vertical",overflow:"hidden",fontFamily:"'Noto Naskh Arabic','Amiri',serif",fontSize:12,lineHeight:1.7,opacity:.55,marginTop:3};
const hadithRow={width:"100%",maxWidth:"100%",boxSizing:"border-box",padding:"11px 3px",border:0,borderTop:"1px solid rgba(16,16,15,.06)",background:"transparent",fontFamily:"inherit",color:C.ink,display:"grid",gridTemplateColumns:"38px minmax(0,1fr) auto",gap:9,alignItems:"center",textAlign:"right"};
