import React,{useEffect,useMemo,useState} from "react";

const C={ivory:"#F6F3EC",ink:"#10100F",lapis:"#173B57",gold:"#B59A62",green:"#416F5A",red:"#9C4A3B",soft:"#EEE7D8"};
const API="https://api.hadith.gading.dev";
const BOOKS=[
 {id:"bukhari",ar:"صحيح البخاري",en:"Sahih al-Bukhari",short:"البخاري"},
 {id:"muslim",ar:"صحيح مسلم",en:"Sahih Muslim",short:"مسلم"},
 {id:"abudawud",ar:"سنن أبي داود",en:"Sunan Abi Dawud",short:"أبو داود"},
 {id:"tirmidzi",ar:"جامع الترمذي",en:"Jami at-Tirmidhi",short:"الترمذي"},
 {id:"nasai",ar:"سنن النسائي",en:"Sunan an-Nasa'i",short:"النسائي"},
 {id:"ibnu-majah",ar:"سنن ابن ماجه",en:"Sunan Ibn Majah",short:"ابن ماجه"},
 {id:"malik",ar:"موطأ الإمام مالك",en:"Muwatta Malik",short:"مالك"},
 {id:"ahmad",ar:"مسند الإمام أحمد",en:"Musnad Ahmad",short:"أحمد"},
 {id:"darimi",ar:"سنن الدارمي",en:"Sunan ad-Darimi",short:"الدارمي"}
];
const ar=n=>String(n).replace(/[0-9]/g,d=>"٠١٢٣٤٥٦٧٨٩"[d]);
const clean=x=>String(x??"").replace(/<[^>]+>/g,"").trim();

export default function NineBooksCenter(){
 const[books,setBooks]=useState(BOOKS),[book,setBook]=useState(null),[rows,setRows]=useState([]),[detail,setDetail]=useState(null),[q,setQ]=useState(""),[from,setFrom]=useState(1),[busy,setBusy]=useState(true),[err,setErr]=useState("");
 const[saved,setSaved]=useState(()=>{try{return JSON.parse(localStorage.getItem("sakinah-nine-books-saved"))||{}}catch{return{}}});
 useEffect(()=>{let alive=true;fetch(`${API}/books`).then(r=>{if(!r.ok)throw new Error();return r.json()}).then(j=>{const list=j?.data||j?.books||[];if(!alive||!Array.isArray(list))return;setBooks(BOOKS.map(b=>{const m=list.find(x=>String(x.id||x.name||"").toLowerCase()===b.id||String(x.name||"").toLowerCase().includes(b.id.replace("ibnu-","ibnu ")));return {...b,total:m?.available??m?.total??m?.count??null}}))}).catch(()=>{}).finally(()=>alive&&setBusy(false));return()=>{alive=false}},[]);
 const loadBook=async(b,start=1)=>{setBook(b);setDetail(null);setRows([]);setErr("");setBusy(true);setFrom(start);const end=start+39;try{const r=await fetch(`${API}/books/${b.id}?range=${start}-${end}`);if(!r.ok)throw new Error();const j=await r.json();const data=j?.data?.hadiths||j?.data?.items||j?.data||j?.hadiths||[];setRows(Array.isArray(data)?data:[])}catch{setErr("تعذر تحميل أحاديث هذا الكتاب الآن.")}finally{setBusy(false)}};
 const openHadith=async(row)=>{const no=row.number??row.no??row.id;setBusy(true);setErr("");try{const r=await fetch(`${API}/books/${book.id}/${no}`);if(!r.ok)throw new Error();const j=await r.json();setDetail(j?.data?.contents||j?.data||j)}catch{setDetail(row);setErr("تم عرض النص المحمّل من القائمة، وتعذر تحميل تفاصيل إضافية.")}finally{setBusy(false)}};
 const filtered=useMemo(()=>rows.filter(x=>{const t=`${x.number||""} ${x.arab||x.arabic||x.text||""} ${x.id||""}`;return !q.trim()||t.includes(q.trim())}),[rows,q]);
 const saveKey=detail&&`${book?.id}:${detail.number??detail.no??detail.id}`;
 const toggleSave=()=>{if(!saveKey)return;const n={...saved,[saveKey]:!saved[saveKey]};setSaved(n);try{localStorage.setItem("sakinah-nine-books-saved",JSON.stringify(n))}catch{}};
 const share=async()=>{if(!detail)return;const text=`${book?.ar}\nحديث رقم ${detail.number??detail.no??detail.id??""}\n\n${clean(detail.arab||detail.arabic||detail.text||detail.contents||"")}`;try{if(navigator.share)await navigator.share({title:book?.ar||"حديث",text});else await navigator.clipboard.writeText(text)}catch{}};
 if(detail){const n=detail.number??detail.no??detail.id;return <Shell><div style={{display:"flex",justifyContent:"space-between",alignItems:"center",gap:8}}><button onClick={()=>setDetail(null)} style={ghost}>عودة إلى {book.ar}</button><div style={{display:"flex",gap:7}}><button onClick={toggleSave} style={{...ghost,color:saved[saveKey]?C.green:C.ink}}>{saved[saveKey]?"محفوظ ✓":"حفظ"}</button><button onClick={share} style={ghost}>مشاركة</button></div></div><header style={{textAlign:"center",margin:"18px 0 12px"}}><div style={{fontSize:9.5,color:C.gold}}>الكتب التسعة</div><h1 style={{fontSize:27,margin:"4px 0"}}>{book.ar}</h1><div style={{fontSize:10,opacity:.42}}>حديث رقم {ar(n??"—")}</div></header><article style={{padding:"20px 17px",borderRadius:24,background:"#FFFDF8",border:"1px solid rgba(16,16,15,.065)",boxShadow:"0 10px 30px rgba(16,16,15,.035)"}}><div style={{fontFamily:"'Noto Naskh Arabic','Amiri',serif",fontSize:"clamp(21px,5vw,29px)",lineHeight:2.15,textAlign:"right",whiteSpace:"pre-wrap"}}>{clean(detail.arab||detail.arabic||detail.text||detail.contents||"")||"النص غير متاح في الاستجابة الحالية."}</div></article>{(detail.id||detail.number||detail.no)&&<section style={{marginTop:10,padding:12,borderRadius:16,background:"rgba(181,154,98,.08)",fontSize:9.5,lineHeight:1.8}}>المصدر الحي: {book.en} · الرقم {n}. لا يضيف سكينة نصاً من عنده.</section>}{err&&<div style={{marginTop:10,fontSize:10,color:C.red}}>{err}</div>}</Shell>}
 if(book)return <Shell><div style={{display:"flex",justifyContent:"space-between",alignItems:"center",gap:8}}><button onClick={()=>{setBook(null);setRows([]);setQ("")}} style={ghost}>كل الكتب</button><span style={{fontSize:9.5,opacity:.42}}>{book.total?`${ar(book.total)} حديث`:"مصدر حي"}</span></div><header style={{textAlign:"center",margin:"18px 0 14px"}}><div style={{fontSize:9.5,color:C.gold}}>الكتب التسعة</div><h1 style={{fontSize:28,margin:"4px 0"}}>{book.ar}</h1><div style={{fontSize:10,opacity:.42}}>{book.en}</div></header><input value={q} onChange={e=>setQ(e.target.value)} placeholder="ابحث برقم الحديث أو داخل النص المحمّل…" style={input}/>{busy&&<div style={{padding:22,textAlign:"center",fontSize:10,opacity:.45}}>تحميل الأحاديث…</div>}{err&&<div style={{marginTop:12,color:C.red,fontSize:10}}>{err}</div>}<div style={{marginTop:10}}>{filtered.map((h,i)=>{const no=h.number??h.no??h.id??from+i;return <button key={`${no}-${i}`} onClick={()=>openHadith(h)} style={hadithRow}><span style={{width:34,height:34,borderRadius:11,display:"grid",placeItems:"center",background:"rgba(181,154,98,.12)",color:C.gold,fontSize:9}}>{ar(no)}</span><span style={{minWidth:0}}><b style={{fontSize:11.5}}>حديث رقم {ar(no)}</b><small style={{display:"-webkit-box",WebkitLineClamp:2,WebkitBoxOrient:"vertical",overflow:"hidden",fontFamily:"'Noto Naskh Arabic','Amiri',serif",fontSize:12,lineHeight:1.7,opacity:.55,marginTop:3}}>{clean(h.arab||h.arabic||h.text||"")}</small></span><span style={{opacity:.3}}>‹</span></button>})}</div><div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:8,marginTop:14}}><button disabled={from<=1||busy} onClick={()=>loadBook(book,Math.max(1,from-40))} style={{...ghost,opacity:from<=1?.35:1}}>السابق</button><button disabled={busy} onClick={()=>loadBook(book,from+40)} style={ghost}>التالي</button></div></Shell>;
 return <Shell><header style={{textAlign:"center"}}><div style={{fontSize:9.5,color:C.gold,letterSpacing:1.2}}>HADITH · SAKINAH</div><h1 style={{fontSize:30,margin:"6px 0 6px"}}>الكتب التسعة</h1><p style={{fontSize:10.5,opacity:.47,lineHeight:1.8,margin:0}}>مكتبة حديث حية: افتح الكتاب ثم اقرأ النص العربي وابحث واحفظ وشارك</p></header><section style={{display:"grid",gridTemplateColumns:"repeat(3,1fr)",gap:1,marginTop:18,border:"1px solid rgba(16,16,15,.055)",borderRadius:18,overflow:"hidden",background:"rgba(16,16,15,.04)"}}>{[[9,"كتب"],[Object.values(saved).filter(Boolean).length,"محفوظ"],[busy?"…":"حي","المصدر"]].map(([n,l])=><div key={l} style={{padding:"11px 5px",background:"rgba(255,255,255,.65)",textAlign:"center"}}><b style={{fontSize:17,color:C.lapis}}>{typeof n==="number"?ar(n):n}</b><small style={{display:"block",fontSize:8.5,opacity:.42,marginTop:2}}>{l}</small></div>)}</section><div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:9,marginTop:18}}>{books.map((b,i)=><button key={b.id} onClick={()=>loadBook(b,1)} style={{minHeight:112,padding:"14px 13px",borderRadius:20,border:"1px solid rgba(16,16,15,.065)",background:i===0?"linear-gradient(145deg,#173B57,#0E2F47)":"rgba(255,255,255,.52)",color:i===0?"white":C.ink,fontFamily:"inherit",textAlign:"right",display:"flex",flexDirection:"column",justifyContent:"space-between"}}><div style={{display:"flex",justifyContent:"space-between",alignItems:"center"}}><span style={{fontSize:18,color:i===0?"#E7D29B":C.gold}}>▤</span><span style={{fontSize:9,opacity:.45}}>{ar(i+1)}</span></div><div><b style={{display:"block",fontSize:13,lineHeight:1.55}}>{b.ar}</b><small style={{display:"block",fontSize:9,opacity:.45,marginTop:4,direction:"ltr",textAlign:"right"}}>{b.en}</small>{b.total&&<small style={{display:"block",fontSize:8.5,opacity:.4,marginTop:4}}>{ar(b.total)} حديث</small>}</div></button>)}</div><section style={{marginTop:16,padding:13,borderRadius:17,background:"rgba(181,154,98,.08)",fontSize:9.5,lineHeight:1.8,opacity:.65}}>النصوص تُحمّل من مصدر خارجي حي يدعم الكتب التسعة. إذا انقطع المصدر، لا يعرض التطبيق نصاً مخمّناً أو مصنوعاً محلياً.</section></Shell>;
}

function Shell({children}){return <div dir="rtl" style={{position:"absolute",inset:0,overflowY:"auto",background:C.ivory,color:C.ink}}><main style={{maxWidth:720,margin:"0 auto",padding:"30px 18px calc(360px + env(safe-area-inset-bottom,0px))"}}>{children}<div aria-hidden="true" style={{height:80}}/></main></div>}
const ghost={border:"1px solid rgba(16,16,15,.08)",borderRadius:14,padding:"9px 11px",background:"rgba(255,255,255,.52)",fontFamily:"inherit",color:C.ink,fontSize:10};
const input={width:"100%",boxSizing:"border-box",padding:"12px 13px",borderRadius:16,border:"1px solid rgba(16,16,15,.08)",background:"rgba(255,255,255,.55)",fontFamily:"inherit",outline:"none"};
const hadithRow={width:"100%",display:"grid",gridTemplateColumns:"42px 1fr auto",gap:9,alignItems:"center",padding:"11px 12px",marginTop:8,border:"1px solid rgba(16,16,15,.06)",borderRadius:17,background:"rgba(255,255,255,.46)",fontFamily:"inherit",color:C.ink,textAlign:"right"};
