import React,{useEffect,useMemo,useState} from "react";

const C={ivory:"#F6F3EC",paper:"#FDFBF7",ink:"#102D43",lapis:"#102D43",gold:"#C0A062",muted:"#7C868F",green:"#416F5A",red:"#9C4A3B"};
const MANIFEST="/data/hadiths/manifest.json";
const ar=n=>String(n??"").replace(/[0-9]/g,d=>"٠١٢٣٤٥٦٧٨٩"[d]);
const textOf=h=>{const v=h?.arabic;return typeof v==="string"?v:String(v?.text??v?.body??v?.hadith??v?.contents??"").trim()};
const chapterName=c=>String(c?.arabic?.title??c?.arabic?.name??c?.arabic??"").trim();
async function loadGzipJson(url){
 const r=await fetch(url,{cache:"force-cache"});
 if(!r.ok)throw new Error("missing");
 const buf=await r.arrayBuffer();
 const bytes=new Uint8Array(buf);
 const isGzip=bytes.length>2&&bytes[0]===0x1f&&bytes[1]===0x8b;
 if(!isGzip)return JSON.parse(new TextDecoder("utf-8").decode(bytes));
 if(typeof DecompressionStream!=="function")throw new Error("gzip-unsupported");
 const ds=new DecompressionStream("gzip");
 return new Response(new Blob([buf]).stream().pipeThrough(ds)).json();
}
function BookGlyph({dark=false}){return <span style={{width:44,height:44,borderRadius:14,background:dark?"rgba(247,243,234,.09)":"rgba(192,160,98,.08)",border:`1px solid ${dark?"rgba(192,160,98,.35)":"rgba(16,45,67,.06)"}`,display:"grid",placeItems:"center",color:C.gold,flex:"none"}}><svg viewBox="0 0 24 24" width="22" height="22" fill="none" stroke="currentColor" strokeWidth="1.45" strokeLinecap="round" strokeLinejoin="round"><path d="M4.5 5.5c2.8-.8 5.3-.3 7.5 1.4v12c-2.3-1.3-4.8-1.7-7.5-1z"/><path d="M19.5 5.5c-2.8-.8-5.3-.3-7.5 1.4v12c2.3-1.3 4.8-1.7 7.5-1z"/><path d="M12 7v12"/></svg></span>}

export default function NineBooksCenter(){
 const[manifest,setManifest]=useState(null),[bookMeta,setBookMeta]=useState(null),[bookData,setBookData]=useState(null),[chapter,setChapter]=useState(null),[detail,setDetail]=useState(null),[q,setQ]=useState(""),[busy,setBusy]=useState(true),[err,setErr]=useState("");
 const[saved,setSaved]=useState(()=>{try{return JSON.parse(localStorage.getItem("sakinah-nine-books-saved"))||{}}catch{return{}}});
 const[lastBook,setLastBook]=useState(()=>{try{return localStorage.getItem("sakinah-nine-last-book")||""}catch{return""}});
 useEffect(()=>{let alive=true;setBusy(true);fetch(MANIFEST,{cache:"no-cache"}).then(r=>{if(!r.ok)throw new Error();return r.json()}).then(j=>alive&&setManifest(j)).catch(()=>alive&&setErr("بيانات الكتب التسعة المحلية غير مثبتة بعد.")).finally(()=>alive&&setBusy(false));return()=>{alive=false}},[]);
 const books=manifest?.books||[];
 const visibleBooks=useMemo(()=>books.filter(b=>`${b.titleAr} ${b.titleEn} ${b.authorAr}`.toLowerCase().includes(q.trim().toLowerCase())),[books,q]);
 const chapters=bookData?.chapters||[],hadiths=bookData?.hadiths||[];
 const rows=useMemo(()=>chapter?hadiths.filter(h=>String(h.chapterId)===String(chapter.id)):hadiths,[hadiths,chapter]);
 const shownHadiths=useMemo(()=>{const s=q.trim();return s?rows.filter(h=>`${h.idInBook??h.id??""} ${textOf(h)}`.includes(s)):rows},[rows,q]);
 const chapterCounts=useMemo(()=>{const m=new Map();hadiths.forEach(h=>{const k=String(h.chapterId);m.set(k,(m.get(k)||0)+1)});return m},[hadiths]);
 const openBook=async b=>{setBookMeta(b);setBookData(null);setChapter(null);setDetail(null);setQ("");setErr("");setBusy(true);try{localStorage.setItem("sakinah-nine-last-book",b.id);setLastBook(b.id)}catch{}try{setBookData(await loadGzipJson(b.file))}catch(e){setErr(e?.message==="gzip-unsupported"?"هذا المتصفح لا يدعم فك ضغط بيانات الكتب المحلية.":"تعذر فتح بيانات هذا الكتاب المحلية.")}finally{setBusy(false)}};
 const saveKey=detail&&`${bookMeta?.id}:${detail.idInBook??detail.id}`;
 const toggleSave=()=>{if(!saveKey)return;const n={...saved,[saveKey]:!saved[saveKey]};setSaved(n);try{localStorage.setItem("sakinah-nine-books-saved",JSON.stringify(n))}catch{}};
 const share=async()=>{if(!detail)return;const no=detail.idInBook??detail.id??"",text=`${bookMeta?.titleAr||"حديث"}\nحديث رقم ${no}\n\n${textOf(detail)}`;try{if(navigator.share)await navigator.share({title:bookMeta?.titleAr||"حديث",text});else await navigator.clipboard.writeText(text)}catch{}};
 const last=books.find(b=>b.id===lastBook)||books[0];
 if(detail){const no=detail.idInBook??detail.id;return <Shell><Top title={bookMeta.titleAr} sub={`حديث رقم ${ar(no)}`} back={()=>setDetail(null)}/><article style={reader}><div className="nine-books-hadith-text" style={readerText}>{textOf(detail)||"النص غير متاح."}</div></article><div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:8,marginTop:10}}><button onClick={toggleSave} style={{...action,color:saved[saveKey]?C.green:C.ink}}>{saved[saveKey]?"محفوظ ✓":"حفظ"}</button><button onClick={share} style={action}>مشاركة</button></div></Shell>}
 if(bookData){if(chapter)return <Shell><Top title={chapterName(chapter)||bookMeta.titleAr} sub={`${ar(shownHadiths.length)} حديث`} back={()=>{setChapter(null);setQ("")}}/><Search value={q} onChange={setQ} placeholder="ابحث برقم الحديث أو داخل النص…"/><div style={{marginTop:14}}>{shownHadiths.map((h,i)=>{const no=h.idInBook??h.id??i+1;return <button key={`${no}-${i}`} onClick={()=>setDetail(h)} style={hadithRow}><span style={numberBox}>{ar(no)}</span><span style={{minWidth:0}}><b style={{fontSize:12.5,fontWeight:600}}>حديث رقم {ar(no)}</b><small style={preview}>{textOf(h)}</small></span><span style={{opacity:.24,fontSize:19}}>‹</span></button>})}</div></Shell>;
 return <Shell><Top title={bookMeta.titleAr} sub={`${bookMeta.authorAr} · ${ar(bookMeta.count)} حديث`} back={()=>{setBookMeta(null);setBookData(null);setQ("")}}/><div style={{display:"flex",justifyContent:"space-between",alignItems:"center",margin:"22px 2px 7px",fontSize:11}}><span style={{color:C.muted}}>{ar(chapters.length)} باب</span><b style={{fontWeight:600}}>الأبواب</b></div><div>{chapters.map((c,i)=>{const count=chapterCounts.get(String(c.id))||0;return <button key={`${c.id}-${i}`} onClick={()=>setChapter(c)} style={listRow}><span style={{width:30,color:C.gold,fontSize:11,textAlign:"center"}}>{ar(i+1)}</span><span style={{flex:1,minWidth:0}}><b style={{display:"block",fontFamily:"Amiri,serif",fontSize:16,fontWeight:400}}>{chapterName(c)||`الباب ${ar(i+1)}`}</b><small style={{display:"block",fontSize:9.5,color:C.muted,marginTop:3}}>{ar(count)} حديث</small></span><span style={{opacity:.22,fontSize:18}}>‹</span></button>})}</div></Shell>}
 return <Shell><header style={{textAlign:"center",paddingTop:6}}><div style={{fontFamily:"'IBM Plex Mono',monospace",fontSize:9,letterSpacing:".3em",color:C.gold,direction:"ltr"}}>HADITH LIBRARY</div><h1 style={{fontFamily:"Amiri,serif",fontWeight:400,fontSize:31,margin:"8px 0 4px"}}>الكتب التسعة</h1><p style={{fontSize:12,color:C.muted,lineHeight:1.8,margin:0}}>مكتبة محليّة تعمل بدون إنترنت · {ar(books.reduce((n,b)=>n+(Number(b.count)||0),0)||40000)} حديث</p></header><Search value={q} onChange={setQ} placeholder="ابحث عن كتاب أو باب أو راوٍ…"/>{last&&!q&&<button onClick={()=>openBook(last)} style={continueCard}><div style={{position:"absolute",inset:0,background:"radial-gradient(80% 70% at 90% -20%,rgba(192,160,98,.28),transparent 60%)",pointerEvents:"none"}}/><BookGlyph dark/><span style={{position:"relative",flex:1,minWidth:0,textAlign:"right"}}><small style={{display:"block",fontSize:10,color:"rgba(247,243,234,.5)"}}>متابعة القراءة</small><b style={{display:"block",fontFamily:"Amiri,serif",fontSize:21,fontWeight:400,marginTop:2}}>{last.titleAr}</b><span style={{display:"block",height:3,background:"rgba(247,243,234,.16)",borderRadius:3,marginTop:9,overflow:"hidden"}}><i style={{display:"block",width:"38%",height:"100%",background:C.gold,borderRadius:3}}/></span></span><span style={{position:"relative",fontSize:18,color:"rgba(247,243,234,.36)"}}>‹</span></button>}{busy&&<Loading text="تحميل المكتبة المحلية…"/>}{err&&<Notice>{err}</Notice>}<div style={{display:"flex",justifyContent:"space-between",alignItems:"center",margin:"24px 2px 5px",fontSize:11}}><span style={{color:C.muted}}>{ar(visibleBooks.length)} كتب</span><b style={{fontWeight:600}}>جميع الكتب</b></div><div>{visibleBooks.map((b,i)=><button key={b.id} onClick={()=>openBook(b)} style={listRow}><span style={{width:26,color:C.gold,fontFamily:"monospace",fontSize:10,textAlign:"center"}}>{ar(i+1)}</span><BookGlyph/><span style={{flex:1,minWidth:0,textAlign:"right"}}><b style={{display:"block",fontFamily:"Amiri,serif",fontSize:18,fontWeight:400}}>{b.titleAr}</b><small style={{display:"block",fontSize:9.5,color:C.muted,marginTop:3,whiteSpace:"nowrap",overflow:"hidden",textOverflow:"ellipsis"}}>{b.authorAr}</small></span><span style={{textAlign:"left",flex:"none"}}><small style={{display:"block",fontSize:9,color:C.muted}}>{ar(b.count)} حديث</small><span style={{display:"block",opacity:.22,fontSize:17,marginTop:4}}>‹</span></span></button>)}</div>{!busy&&!err&&visibleBooks.length===0&&<div style={{padding:28,textAlign:"center",fontSize:10.5,color:C.muted}}>لا يوجد كتاب مطابق للبحث.</div>}</Shell>}
function Search({value,onChange,placeholder}){return <div style={{marginTop:20,display:"flex",alignItems:"center",gap:10,background:C.paper,border:"1px solid rgba(16,45,67,.09)",borderRadius:16,padding:"12px 15px"}}><svg viewBox="0 0 24 24" width="17" height="17" fill="none" stroke="#A9B0B8" strokeWidth="1.6"><circle cx="11" cy="11" r="6.5"/><path d="m16 16 4 4"/></svg><input value={value} onChange={e=>onChange(e.target.value)} placeholder={placeholder} style={{flex:1,minWidth:0,border:0,outline:0,background:"transparent",fontFamily:"inherit",fontSize:13,color:C.ink,textAlign:"right"}}/></div>}
function Top({title,sub,back}){return <><div style={{height:44,display:"grid",gridTemplateColumns:"36px 1fr 36px",alignItems:"center",borderBottom:"1px solid rgba(16,45,67,.07)",margin:"-8px 0 0"}}><button onClick={back} style={{border:0,background:"transparent",fontSize:18,color:C.gold,cursor:"pointer"}}>→</button><b style={{textAlign:"center",fontFamily:"Amiri,serif",fontWeight:400,fontSize:18}}>{title}</b><span/></div><div style={{textAlign:"center",fontSize:10.5,color:C.muted,marginTop:10,lineHeight:1.7}}>{sub}</div></>}
function Shell({children}){return <div dir="rtl" style={{position:"absolute",inset:0,width:"100%",maxWidth:"100vw",overflowY:"auto",overflowX:"hidden",background:C.ivory,color:C.ink,boxSizing:"border-box"}}><main style={{width:"100%",maxWidth:660,minWidth:0,margin:"0 auto",boxSizing:"border-box",overflowX:"hidden",padding:"18px 20px calc(145px + env(safe-area-inset-bottom,0px))"}}>{children}</main></div>}
function Loading({text}){return <div style={{padding:22,textAlign:"center",fontSize:10,color:C.muted}}>{text}</div>}
function Notice({children}){return <div style={{marginTop:10,padding:11,borderRadius:14,background:"rgba(156,74,59,.07)",color:C.red,fontSize:10}}>{children}</div>}
const action={border:"1px solid rgba(16,45,67,.08)",borderRadius:14,padding:"10px 11px",background:C.paper,fontFamily:"inherit",color:C.ink,fontSize:10};
const reader={width:"100%",maxWidth:"100%",boxSizing:"border-box",padding:"20px 17px",borderRadius:22,background:C.paper,border:"1px solid rgba(16,45,67,.07)",marginTop:18};
const readerText={fontFamily:"'Noto Naskh Arabic','Amiri',serif",fontSize:"clamp(21px,5vw,29px)",lineHeight:2.15,direction:"rtl",textAlign:"justify",textAlignLast:"right",width:"100%",overflowWrap:"break-word"};
const continueCard={width:"100%",maxWidth:"100%",boxSizing:"border-box",marginTop:12,padding:"16px 18px",border:0,borderRadius:20,background:C.lapis,color:"#F7F3EA",fontFamily:"inherit",display:"flex",alignItems:"center",gap:14,textAlign:"right",position:"relative",overflow:"hidden",cursor:"pointer"};
const listRow={width:"100%",maxWidth:"100%",boxSizing:"border-box",padding:"13px 2px",border:0,borderTop:"1px solid rgba(16,45,67,.07)",background:"transparent",fontFamily:"inherit",color:C.ink,display:"flex",alignItems:"center",gap:11,textAlign:"right",cursor:"pointer"};
const numberBox={width:34,height:34,borderRadius:11,display:"grid",placeItems:"center",background:"rgba(192,160,98,.10)",color:C.gold,fontSize:9};
const preview={display:"-webkit-box",WebkitLineClamp:2,WebkitBoxOrient:"vertical",overflow:"hidden",fontFamily:"'Noto Naskh Arabic','Amiri',serif",fontSize:12,lineHeight:1.7,color:C.muted,marginTop:3};
const hadithRow={width:"100%",maxWidth:"100%",boxSizing:"border-box",padding:"11px 3px",border:0,borderTop:"1px solid rgba(16,45,67,.07)",background:"transparent",fontFamily:"inherit",color:C.ink,display:"grid",gridTemplateColumns:"38px minmax(0,1fr) auto",gap:9,alignItems:"center",textAlign:"right"};
