import React,{useMemo,useState} from "react";

const C={ivory:"#F6F3EC",ink:"#10100F",lapis:"#173B57",gold:"#B59A62"};
const PREFIXES=["sakinah-","sk-"];
function Shell({lang,go,children}){return <div style={{position:"absolute",inset:0,background:C.ivory,color:C.ink,display:"flex",flexDirection:"column"}}><div style={{padding:"22px 22px 0"}}><button onClick={()=>go("me")} style={{border:0,background:"transparent",fontFamily:"inherit",cursor:"pointer",color:"inherit"}}>{lang==="ar"?"← حسابي":"← Me"}</button></div><div style={{flex:1,overflowY:"auto",padding:"15px 22px 130px"}}>{children}</div></div>}
function collect(){const data={version:1,createdAt:new Date().toISOString(),local:{}};for(let i=0;i<localStorage.length;i++){const k=localStorage.key(i);if(PREFIXES.some(p=>k?.startsWith(p)))data.local[k]=localStorage.getItem(k)}return data}
export function OfflineBackupCenter({lang,go}){
 const [status,setStatus]=useState("");const [cacheInfo,setCacheInfo]=useState([]);const keys=useMemo(()=>{try{return Object.keys(collect().local)}catch{return[]}},[status]);
 const exportData=()=>{try{const blob=new Blob([JSON.stringify(collect(),null,2)],{type:"application/json"});const u=URL.createObjectURL(blob);const a=document.createElement("a");a.href=u;a.download=`sakinah-backup-${new Date().toISOString().slice(0,10)}.json`;a.click();URL.revokeObjectURL(u);setStatus(lang==="ar"?"تم إنشاء النسخة الاحتياطية":"Backup created")}catch{setStatus(lang==="ar"?"تعذر إنشاء النسخة":"Could not create backup")}};
 const importData=f=>{if(!f)return;const r=new FileReader();r.onload=()=>{try{const x=JSON.parse(String(r.result||""));if(x?.version!==1||!x.local||typeof x.local!=="object")throw new Error();Object.entries(x.local).forEach(([k,v])=>{if(PREFIXES.some(p=>k.startsWith(p))&&typeof v==="string")localStorage.setItem(k,v)});setStatus(lang==="ar"?"تمت الاستعادة بنجاح · أعد فتح التطبيق":"Restore complete · reopen the app")}catch{setStatus(lang==="ar"?"ملف النسخة غير صالح":"Invalid backup file")}};r.readAsText(f)};
 const inspectCaches=async()=>{if(!('caches'in window)){setStatus(lang==="ar"?"التخزين دون إنترنت غير مدعوم":"Offline cache unavailable");return}const names=await caches.keys();const rows=[];for(const n of names){const c=await caches.open(n);const req=await c.keys();rows.push([n,req.length])}setCacheInfo(rows);setStatus(lang==="ar"?"تم تحديث حالة التخزين":"Offline status refreshed")};
 const clearCaches=async()=>{if(!('caches'in window))return;for(const n of await caches.keys())await caches.delete(n);setCacheInfo([]);setStatus(lang==="ar"?"تم مسح المحتوى المحفوظ دون إنترنت":"Offline cache cleared")};
 return <Shell lang={lang} go={go}><div style={{fontFamily:"Fraunces,serif",fontSize:29}}>{lang==="ar"?"النسخ والـ Offline":"Backup & Offline"}</div><div style={{fontSize:11.5,opacity:.48,lineHeight:1.7,marginTop:7}}>{lang==="ar"?"نسخة خاصة من بياناتك على جهازك، ومراقبة المحتوى المخزن للاستخدام دون إنترنت.":"Private device backup plus visibility into content cached for offline use."}</div>
 <div style={{marginTop:18,display:"grid",gridTemplateColumns:"1fr 1fr",gap:9}}><button onClick={exportData} style={{padding:14,border:0,borderRadius:16,background:C.lapis,color:"white",fontFamily:"inherit",fontWeight:600}}>{lang==="ar"?"تصدير نسخة":"Export backup"}</button><label style={{padding:14,borderRadius:16,border:"1px solid rgba(16,16,15,.10)",textAlign:"center",fontSize:12,fontWeight:600,cursor:"pointer"}}>{lang==="ar"?"استيراد نسخة":"Import backup"}<input type="file" accept="application/json" hidden onChange={e=>importData(e.target.files?.[0])}/></label></div>
 <div style={{marginTop:18,padding:15,borderRadius:18,border:"1px solid rgba(16,16,15,.08)",background:"rgba(255,255,255,.42)"}}><div style={{fontSize:12.5,fontWeight:650}}>{lang==="ar"?"بيانات محلية مشمولة":"Local data included"}</div><div style={{fontSize:10.5,opacity:.48,marginTop:7,lineHeight:1.7}}>{lang==="ar"?`${keys.length} مفاتيح محلية: البروفايلات، الملاحظات، الحسابات، التقدم، المفضلة وإعدادات سكينة عند وجودها.`:`${keys.length} local keys: profiles, notes, ledger, progress, favorites and Sakinah preferences when present.`}</div></div>
 <div style={{marginTop:18,display:"flex",gap:8}}><button onClick={inspectCaches} style={{flex:1,padding:11,borderRadius:14,border:"1px solid rgba(16,16,15,.09)",background:"transparent",fontFamily:"inherit"}}>{lang==="ar"?"فحص Offline":"Inspect offline"}</button><button onClick={clearCaches} style={{flex:1,padding:11,borderRadius:14,border:"1px solid rgba(16,16,15,.09)",background:"transparent",fontFamily:"inherit"}}>{lang==="ar"?"مسح Offline":"Clear offline"}</button></div>
 {cacheInfo.map(([n,c])=><div key={n} style={{display:"flex",justifyContent:"space-between",padding:"10px 2px",borderBottom:"1px solid rgba(16,16,15,.06)",fontSize:10.5}}><span>{n}</span><b>{c}</b></div>)}
 {status&&<div style={{marginTop:14,fontSize:10.5,color:C.gold}}>{status}</div>}
 <div style={{marginTop:18,fontSize:9.8,opacity:.4,lineHeight:1.7}}>{lang==="ar"?"هذه النسخة لا تُرفع إلى خادم. المزامنة السحابية تُفعل لاحقاً بحساب المستخدم وتشفير مناسب.":"This backup stays on the device. Cloud sync will be added later with user accounts and appropriate encryption."}</div></Shell>
}
