const ID='sakinah-page-title-morph';
const STYLE_ID='sakinah-page-title-morph-style';
const TITLE_CLASS='sakinah-centered-page-title';
let current=null,scroller=null,ghost=null,start=null,raf=0;
const clamp=v=>Math.max(0,Math.min(1,v));
const ease=t=>1-Math.pow(1-clamp(t),3);
function ensureStyle(){if(document.getElementById(STYLE_ID))return;const s=document.createElement('style');s.id=STYLE_ID;s.textContent=`.${TITLE_CLASS}{transform:none!important;translate:none!important;position:static!important;inset:auto!important}.sakinah-title-motion-active{opacity:0!important}#${ID}{position:fixed!important;z-index:2147483640!important;pointer-events:none!important;white-space:nowrap!important;margin:0!important;padding:0!important;background:transparent!important;color:#10100F!important;line-height:1.2!important;transform-origin:top left!important;will-change:left,top,transform,opacity!important;text-align:right!important;direction:rtl!important}`;document.head.appendChild(s)}
function visible(el){if(!el||!el.isConnected)return false;const c=getComputedStyle(el);return c.display!=='none'&&c.visibility!=='hidden'&&el.getClientRects().length>0}
function canScroll(el){if(!el||el===document.body||el===document.documentElement)return false;const c=getComputedStyle(el);return /(auto|scroll|overlay)/.test(c.overflowY)&&el.scrollHeight>el.clientHeight+4}
function findScroller(el){let p=el?.parentElement;while(p){if(canScroll(p))return p;p=p.parentElement}return document.scrollingElement||document.documentElement}
function topOf(s){if(!s||s===document.scrollingElement||s===document.documentElement||s===document.body)return window.scrollY||document.documentElement.scrollTop||0;return s.scrollTop||0}
function pick(){const a=[...document.querySelectorAll(`.${TITLE_CLASS}`)].filter(visible).filter(e=>!e.closest('#sakinah-back-bar'));if(!a.length)return null;return a.reduce((b,e)=>{const r=e.getBoundingClientRect(),br=b?.getBoundingClientRect();if(!b)return e;const score=Math.abs(r.top-118)+(r.width<50?1000:0),bs=Math.abs(br.top-118)+(br.width<50?1000:0);return score<bs?e:b},null)}
function makeGhost(){if(ghost?.isConnected)return ghost;ghost=document.getElementById(ID)||document.createElement('div');ghost.id=ID;ghost.setAttribute('aria-hidden','true');if(!ghost.isConnected)document.body.appendChild(ghost);return ghost}
function reset(){if(current?.isConnected){current.classList.remove('sakinah-title-motion-active')}current=null;scroller=null;start=null;if(ghost){ghost.style.opacity='0';ghost.textContent=''}}
function bind(){const t=pick();if(!t){reset();return false}if(t===current&&start)return true;if(current?.isConnected)current.classList.remove('sakinah-title-motion-active');current=t;scroller=findScroller(t);const r=t.getBoundingClientRect();const cs=getComputedStyle(t);start={left:r.left,top:r.top,width:r.width,height:r.height,scroll:topOf(scroller),fontSize:parseFloat(cs.fontSize)||30,fontFamily:cs.fontFamily,fontWeight:cs.fontWeight,color:cs.color};const g=makeGhost();g.textContent=(t.textContent||'').trim();g.style.fontFamily=start.fontFamily;g.style.fontWeight=start.fontWeight;g.style.fontSize=`${start.fontSize}px`;g.style.color=start.color;return true}
function render(){raf=0;if(!bind())return;const y=Math.max(0,topOf(scroller)-start.scroll);const p=ease(y/120);if(p<=0.015){current.classList.remove('sakinah-title-motion-active');ghost.style.opacity='0';return}current.classList.add('sakinah-title-motion-active');const targetTop=72;const targetRight=22;const targetScale=.70;const targetLeft=window.innerWidth-targetRight-(start.width*targetScale);const left=start.left+(targetLeft-start.left)*p;const top=start.top+(targetTop-start.top)*p;const scale=1+(targetScale-1)*p;ghost.style.left=`${left}px`;ghost.style.top=`${top}px`;ghost.style.transform=`scale(${scale})`;ghost.style.opacity='1'}
function schedule(){if(raf)return;raf=requestAnimationFrame(render)}
export function installPageTitleMorph(){ensureStyle();setTimeout(schedule,0);document.addEventListener('scroll',schedule,true);window.addEventListener('resize',()=>{start=null;schedule()},{passive:true});new MutationObserver(()=>{if(!current?.isConnected){start=null;schedule()}}).observe(document.body,{childList:true,subtree:true});['sakinah:feature','sakinah:native','sakinah:devotion','sakinah:global-root','popstate'].forEach(n=>window.addEventListener(n,()=>{reset();setTimeout(schedule,40)}));}
