import React,{useMemo,useState} from "react";

const C={ivory:"#F6F3EC",ink:"#10100F",lapis:"#173B57",gold:"#B59A62",green:"#416F5A",red:"#A44D3C"};
const btn={border:"1px solid rgba(16,16,15,.08)",borderRadius:16,padding:11,background:"rgba(255,255,255,.58)",fontFamily:"inherit",color:"inherit"};
const profile=()=>{try{return localStorage.getItem("sakinah-active-profile")||"me"}catch{return"me"}};
const read=(k,d)=>{try{const x=localStorage.getItem(k);return x==null?d:JSON.parse(x)}catch{return d}};
const write=(k,v)=>{try{localStorage.setItem(k,JSON.stringify(v))}catch{}};
const key=n=>`muslim-mirror-${n}-${profile()}`;
const PR=[["Fajr","الفجر"],["Dhuhr","الظهر"],["Asr","العصر"],["Maghrib","المغرب"],["Isha","العشاء"]];
const dayKey=(d=new Date())=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`;
function Shell({go,title,sub,children}){return <div dir="rtl" style={{position:"fixed",inset:0,zIndex:60000,background:C.ivory,color:C.ink,overflowY:"auto"}}><main style={{maxWidth:720,margin:"0 auto",padding:"max(72px,calc(env(safe-area-inset-top) + 46px)) 18px 140px"}}><button onClick={()=>go("my-day")} style={{...btn,borderRadius:999,padding:"8px 12px"}}>→ رجوع</button><header style={{textAlign:"center",marginTop:14}}><div style={{fontSize:10,color:C.gold,letterSpacing:.8}}>MUSLIM MIRROR</div><h1 style={{fontSize:29,margin:"4px 0"}}>{title}</h1><p style={{fontSize:10.5,opacity:.48,lineHeight:1.8,margin:0}}>{sub}</p></header>{children}</main></div>}
function Toggle({on,onChange}){return <button onClick={()=>onChange(!on)} style={{width:46,height:27,padding:3,border:0,borderRadius:999,background:on?C.lapis:"rgba(16,16,15,.12)",display:"flex",justifyContent:on?"flex-end":"flex-start"}}><span style={{width:21,height:21,borderRadius:"50%",background:"white"}}/></button>}

export function PrayerJournal({go}){
 const [log,setLog]=useState(()=>read(key("prayer-log"),{}));
 const today=dayKey(),todayLog=log[today]||{};
 const mark=(p,state)=>{const next={...log,[today]:{...todayLog,[p]:state}};setLog(next);write(key("prayer-log"),next)};
 const stats=useMemo(()=>{let on=0,late=0,missed=0,total=0;for(let i=0;i<7;i++){const d=new Date();d.setDate(d.getDate()-i);const x=log[dayKey(d)]||{};for(const [p] of PR){if(!x[p])continue;total++;if(x[p]==="on")on++;else if(x[p]==="late")late++;else if(x[p]==="missed")missed++;}}return{on,late,missed,total}},[log]);
 return <Shell go={go} title="سجل الصلاة" sub="متابعة شخصية بسيطة ومحلية على جهازك للأسبوع الأخير"><section style={{marginTop:18,display:"grid",gridTemplateColumns:"repeat(3,1fr)",gap:8}}><div style={{...btn,textAlign:"center"}}><small style={{opacity:.45}}>في وقتها</small><b style={{display:"block",fontSize:22,color:C.green,marginTop:4}}>{stats.on}</b></div><div style={{...btn,textAlign:"center"}}><small style={{opacity:.45}}>متأخرة</small><b style={{display:"block",fontSize:22,color:C.gold,marginTop:4}}>{stats.late}</b></div><div style={{...btn,textAlign:"center"}}><small style={{opacity:.45}}>فاتتني</small><b style={{display:"block",fontSize:22,color:C.red,marginTop:4}}>{stats.missed}</b></div></section><section style={{marginTop:14,display:"grid",gap:9}}>{PR.map(([p,ar])=><div key={p} style={{padding:14,borderRadius:22,background:"rgba(255,255,255,.62)",border:"1px solid rgba(16,16,15,.055)"}}><div style={{display:"flex",justifyContent:"space-between",alignItems:"center"}}><b>{ar}</b><span style={{fontSize:10,opacity:.4}}>{today}</span></div><div style={{display:"grid",gridTemplateColumns:"repeat(3,1fr)",gap:7,marginTop:10}}>{[["on","في وقتها",C.green],["late","متأخرة",C.gold],["missed","فاتتني",C.red]].map(([id,label,color])=><button key={id} onClick={()=>mark(p,id)} style={{...btn,padding:"9px 6px",background:todayLog[p]===id?`${color}18`:"rgba(255,255,255,.4)",borderColor:todayLog[p]===id?`${color}55`:"rgba(16,16,15,.07)"}}>{todayLog[p]===id?"✓ ":""}{label}</button>)}</div></div>)}</section><div style={{marginTop:13,padding:12,borderRadius:16,background:"rgba(23,59,87,.06)",fontSize:10.5,lineHeight:1.8}}>السجل محفوظ محلياً لكل بروفايل، والغرض منه المتابعة الذاتية فقط وليس إصدار حكم أو تقييم ديني.</div></Shell>
}

export function TravelModeCenter({go}){
 const storage="sakinah-native-"+profile()+"-adhan";
 const [cfg,setCfg]=useState(()=>read(storage,{travelMode:true,travelThresholdKm:20,prePrayer:true,prePrayerMinutes:10}));
 const save=n=>{setCfg(n);write(storage,n)};
 return <Shell go={go} title="السفر والتنبيهات الذكية" sub="تحديث المواقيت تلقائياً عند الانتقال وتنبيه اختياري قبل الصلاة"><section style={{marginTop:18,padding:15,borderRadius:24,background:"rgba(255,255,255,.62)",border:"1px solid rgba(16,16,15,.055)"}}><div style={{display:"flex",justifyContent:"space-between",alignItems:"center",gap:12}}><div><b>وضع السفر</b><div style={{fontSize:10,opacity:.45,marginTop:3}}>إعادة جلب المواقيت والقبلة عند تغيّر موقعك</div></div><Toggle on={cfg.travelMode!==false} onChange={v=>save({...cfg,travelMode:v})}/></div><label style={{display:"block",marginTop:14,fontSize:10.5}}>المسافة التي تعتبر انتقالاً مهماً · {Number(cfg.travelThresholdKm||20)} كم<input type="range" min="5" max="100" step="5" value={Number(cfg.travelThresholdKm||20)} onChange={e=>save({...cfg,travelThresholdKm:Number(e.target.value)})} style={{width:"100%",marginTop:8}}/></label></section><section style={{marginTop:12,padding:15,borderRadius:24,background:"rgba(255,255,255,.62)",border:"1px solid rgba(16,16,15,.055)"}}><div style={{display:"flex",justifyContent:"space-between",alignItems:"center",gap:12}}><div><b>تنبيه قبل الصلاة</b><div style={{fontSize:10,opacity:.45,marginTop:3}}>إشعار هادئ قبل موعد الصلاة بدون تشغيل الأذان</div></div><Toggle on={cfg.prePrayer!==false} onChange={v=>save({...cfg,prePrayer:v})}/></div><div style={{display:"grid",gridTemplateColumns:"repeat(4,1fr)",gap:7,marginTop:12}}>{[5,10,15,30].map(m=><button key={m} onClick={()=>save({...cfg,prePrayerMinutes:m})} style={{...btn,padding:"10px 5px",background:Number(cfg.prePrayerMinutes||10)===m?"rgba(23,59,87,.12)":"rgba(255,255,255,.4)"}}>{m} د</button>)}</div></section><button onClick={()=>go("alerts")} style={{...btn,width:"100%",marginTop:12,background:C.lapis,color:"white",border:0}}>فتح إعدادات المؤذن وتطبيق التغييرات</button></Shell>
}
