import React,{useEffect,useMemo,useState} from "react";

const C={ivory:"#F6F3EC",ink:"#10100F",lapis:"#173B57",gold:"#B59A62",green:"#416F5A",soft:"#EEE7D8",red:"#A44D3C"};
const rad=x=>x*Math.PI/180,deg=x=>x*180/Math.PI;
const KAABA={lat:21.4225,lon:39.8262};
function bearing(lat,lon){const p=rad(lat),l=rad(lon),kLat=rad(KAABA.lat),d=rad(KAABA.lon)-l;return (deg(Math.atan2(Math.sin(d),Math.cos(p)*Math.tan(kLat)-Math.sin(p)*Math.cos(d)))+360)%360}
function distance(lat,lon){const R=6371,dp=rad(KAABA.lat-lat),dl=rad(KAABA.lon-lon),a=Math.sin(dp/2)**2+Math.cos(rad(lat))*Math.cos(rad(KAABA.lat))*Math.sin(dl/2)**2;return 2*R*Math.asin(Math.sqrt(a))}
const ar=n=>String(n).replace(/[0-9]/g,d=>"٠١٢٣٤٥٦٧٨٩"[d]);
const dirName=d=>{const names=["شمال","شمال شرقي","شرق","جنوب شرقي","جنوب","جنوب غربي","غرب","شمال غربي"];return names[Math.round(((d%360)+360)%360/45)%8]};
export default function QiblaPro(){
 const[loc,setLoc]=useState(null),[heading,setHeading]=useState(null),[accuracy,setAccuracy]=useState(null),[status,setStatus]=useState("جاري تحديد موقعك…"),[sensorOn,setSensorOn]=useState(false);
 const qibla=useMemo(()=>loc?bearing(loc.lat,loc.lon):null,[loc]);
 const dist=useMemo(()=>loc?distance(loc.lat,loc.lon):null,[loc]);
 const relative=qibla==null?qibla:heading==null?qibla:(qibla-heading+360)%360;
 const aligned=relative!=null&&heading!=null&&(relative<4||relative>356);
 const requestLocation=()=>{setStatus("جاري تحديد موقعك…");if(!navigator.geolocation){setStatus("هذا الجهاز لا يوفر خدمة الموقع.");return}navigator.geolocation.getCurrentPosition(p=>{setLoc({lat:p.coords.latitude,lon:p.coords.longitude});setAccuracy(p.coords.accuracy||null);setStatus("")},()=>setStatus("تعذر تحديد الموقع. فعّل GPS واسمح للتطبيق باستخدام الموقع."),{enableHighAccuracy:true,timeout:15000,maximumAge:20000})};
 const enableCompass=async()=>{try{if(typeof DeviceOrientationEvent!=="undefined"&&typeof DeviceOrientationEvent.requestPermission==="function"){const ok=await DeviceOrientationEvent.requestPermission();if(ok!=="granted"){setStatus("لم يتم منح إذن مستشعر الاتجاه.");return}}const on=e=>{let h=null;if(typeof e.webkitCompassHeading==="number")h=e.webkitCompassHeading;else if(typeof e.alpha==="number")h=(360-e.alpha)%360;if(h!=null){setHeading(h);setSensorOn(true)}};window.addEventListener("deviceorientationabsolute",on,true);window.addEventListener("deviceorientation",on,true);setStatus("حرّك الهاتف بشكل رقم 8 إذا احتاجت البوصلة إلى معايرة.")}catch{setStatus("مستشعر الاتجاه غير متاح على هذا الجهاز.")}};
 useEffect(()=>{requestLocation()},[]);
 const ticks=Array.from({length:36},(_,i)=>i*10);
 return <div dir="rtl" style={{position:"absolute",inset:0,overflowY:"auto",background:C.ivory,color:C.ink}}><main style={{maxWidth:680,margin:"0 auto",padding:"30px 18px calc(300px + env(safe-area-inset-bottom,0px))"}}>
  <header style={{textAlign:"center"}}><div style={{fontSize:9.5,color:C.gold,letterSpacing:1.4}}>QIBLA · SAKINAH</div><h1 style={{fontSize:29,margin:"5px 0 5px"}}>اتجاه القبلة</h1><p style={{fontSize:10.5,opacity:.47,lineHeight:1.8,margin:0}}>اتجاه مباشر نحو الكعبة من موقعك مع دعم بوصلة الجهاز عند توفرها</p></header>
  <section style={{marginTop:20,borderRadius:30,padding:"20px 16px 18px",background:"linear-gradient(155deg,#102E44,#1D4C69)",color:"white",boxShadow:"0 18px 48px rgba(23,59,87,.18)"}}>
   <div style={{display:"flex",justifyContent:"space-between",alignItems:"center",fontSize:9.5,opacity:.68}}><span>{sensorOn?"البوصلة مباشرة":"اتجاه محسوب"}</span><span style={{display:"flex",gap:5,alignItems:"center"}}><i style={{width:7,height:7,borderRadius:"50%",background:loc?"#8AC8A0":"#E3B48E"}}/>{loc?"الموقع جاهز":"بانتظار الموقع"}</span></div>
   <div style={{display:"grid",placeItems:"center",padding:"18px 0 8px"}}><div style={{width:"min(74vw,320px)",height:"min(74vw,320px)",maxWidth:320,maxHeight:320,minWidth:260,minHeight:260,borderRadius:"50%",position:"relative",background:"radial-gradient(circle at 50% 48%,rgba(255,255,255,.11),rgba(255,255,255,.02) 62%,rgba(0,0,0,.08))",border:"1px solid rgba(255,255,255,.14)",boxShadow:"inset 0 0 0 12px rgba(255,255,255,.018),0 20px 45px rgba(0,0,0,.14)"}}>
    {ticks.map(v=><i key={v} style={{position:"absolute",left:"50%",top:"50%",width:v%90===0?2:1,height:v%90===0?13:8,background:v%90===0?"rgba(255,255,255,.75)":"rgba(255,255,255,.28)",transformOrigin:"50% 142px",transform:`translate(-50%,-142px) rotate(${v}deg)`}}/>)}
    <span style={{position:"absolute",top:18,left:"50%",transform:"translateX(-50%)",fontSize:11,opacity:.7}}>N</span><span style={{position:"absolute",bottom:18,left:"50%",transform:"translateX(-50%)",fontSize:10,opacity:.45}}>S</span><span style={{position:"absolute",left:19,top:"50%",transform:"translateY(-50%)",fontSize:10,opacity:.45}}>W</span><span style={{position:"absolute",right:19,top:"50%",transform:"translateY(-50%)",fontSize:10,opacity:.45}}>E</span>
    <div style={{position:"absolute",left:"50%",top:"50%",width:8,height:116,borderRadius:8,background:`linear-gradient(${aligned?"#E8D497":C.gold},rgba(255,255,255,.20))`,transformOrigin:"50% 100%",transform:`translate(-50%,-100%) rotate(${relative||0}deg)`,transition:"transform .22s ease"}}><span style={{position:"absolute",top:-17,left:"50%",transform:"translateX(-50%)",fontSize:20}}>◆</span></div>
    <div style={{position:"absolute",left:"50%",top:"50%",transform:"translate(-50%,-50%)",width:92,height:92,borderRadius:"50%",display:"grid",placeItems:"center",textAlign:"center",background:"rgba(10,31,46,.86)",border:`1px solid ${aligned?"rgba(232,212,151,.8)":"rgba(255,255,255,.16)"}`,boxShadow:"0 8px 24px rgba(0,0,0,.18)"}}><div><div style={{fontSize:8.5,opacity:.55}}>الكعبة</div><div style={{fontSize:22,fontWeight:700,color:"#E8D497",marginTop:2}}>{qibla==null?"—":`${ar(qibla.toFixed(0))}°`}</div></div></div>
   </div></div>
   <div style={{textAlign:"center",marginTop:4}}><b style={{fontSize:15}}>{aligned?"أنت باتجاه القبلة ✓":qibla==null?"نحدد موقعك الآن…":heading==null?`اتجاه القبلة ${dirName(qibla)}`:"دوّر الهاتف حتى يصبح المؤشر للأعلى"}</b><div style={{fontSize:9.5,opacity:.55,marginTop:4}}>{heading!=null?`اتجاه الجهاز ${ar(heading.toFixed(0))}° · القبلة ${ar(qibla?.toFixed(0))}°`:"يمكنك استخدام الدرجة الظاهرة حتى بدون مستشعر بوصلة"}</div></div>
  </section>
  <section style={{display:"grid",gridTemplateColumns:"repeat(3,1fr)",gap:8,marginTop:12}}><div style={{padding:"12px 7px",borderRadius:17,background:"rgba(255,255,255,.5)",border:"1px solid rgba(16,16,15,.06)",textAlign:"center"}}><small style={{fontSize:8.5,opacity:.42}}>اتجاه القبلة</small><b style={{display:"block",fontSize:18,color:C.lapis,marginTop:4}}>{qibla==null?"—":`${ar(qibla.toFixed(1))}°`}</b></div><div style={{padding:"12px 7px",borderRadius:17,background:"rgba(255,255,255,.5)",border:"1px solid rgba(16,16,15,.06)",textAlign:"center"}}><small style={{fontSize:8.5,opacity:.42}}>المسافة إلى الكعبة</small><b style={{display:"block",fontSize:17,color:C.lapis,marginTop:4}}>{dist==null?"—":`${ar(Math.round(dist).toLocaleString("en"))} كم`}</b></div><div style={{padding:"12px 7px",borderRadius:17,background:"rgba(255,255,255,.5)",border:"1px solid rgba(16,16,15,.06)",textAlign:"center"}}><small style={{fontSize:8.5,opacity:.42}}>دقة الموقع</small><b style={{display:"block",fontSize:17,color:C.lapis,marginTop:4}}>{accuracy?`${ar(Math.round(accuracy))} م`:"—"}</b></div></section>
  <section style={{marginTop:13,padding:14,borderRadius:20,background:"rgba(181,154,98,.08)",border:"1px solid rgba(181,154,98,.10)"}}><div style={{display:"flex",justifyContent:"space-between",gap:12}}><div><b style={{fontSize:11.5}}>موقعك الحالي</b><div style={{fontSize:9.5,opacity:.45,marginTop:4}}>{loc?`${ar(loc.lat.toFixed(4))} ، ${ar(loc.lon.toFixed(4))}`:"لم يتم تحديد الموقع بعد"}</div></div><span style={{fontSize:18,color:C.gold}}>⌖</span></div></section>
  <div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:8,marginTop:12}}><button onClick={enableCompass} style={{border:0,borderRadius:16,padding:12,background:C.lapis,color:"white",fontFamily:"inherit",fontWeight:650}}>{sensorOn?"البوصلة مفعّلة":"تشغيل البوصلة"}</button><button onClick={requestLocation} style={{border:"1px solid rgba(16,16,15,.08)",borderRadius:16,padding:12,background:"rgba(255,255,255,.52)",fontFamily:"inherit",color:C.ink}}>تحديث الموقع</button></div>
  {status&&<div style={{marginTop:10,padding:"10px 12px",borderRadius:14,background:"rgba(16,16,15,.035)",fontSize:9.5,lineHeight:1.7,opacity:.58}}>{status}</div>}
  <section style={{marginTop:14,fontSize:9,opacity:.42,lineHeight:1.75,textAlign:"center"}}>لأفضل دقة: أبعد الهاتف عن المعادن والمغناطيس، وحرّكه على شكل رقم 8 عند الحاجة للمعايرة. اتجاه القبلة الجغرافي يبقى محسوباً من موقعك حتى إذا لم يتوفر مستشعر البوصلة.</section>
 </main></div>;
}
