import React,{useEffect,useMemo,useRef,useState} from "react";

const C={ivory:"#F6F3EC",ink:"#10100F",lapis:"#173B57",gold:"#B59A62",green:"#416F5A",soft:"#EEE7D8",red:"#A44D3C"};
const rad=x=>x*Math.PI/180,deg=x=>x*180/Math.PI;
const KAABA={lat:21.4225,lon:39.8262};
function bearing(lat,lon){const p=rad(lat),l=rad(lon),kLat=rad(KAABA.lat),d=rad(KAABA.lon)-l;return (deg(Math.atan2(Math.sin(d),Math.cos(p)*Math.tan(kLat)-Math.sin(p)*Math.cos(d)))+360)%360}
function distance(lat,lon){const R=6371,dp=rad(KAABA.lat-lat),dl=rad(KAABA.lon-lon),a=Math.sin(dp/2)**2+Math.cos(rad(lat))*Math.cos(rad(KAABA.lat))*Math.sin(dl/2)**2;return 2*R*Math.asin(Math.sqrt(a))}
const ar=n=>String(n).replace(/[0-9]/g,d=>"٠١٢٣٤٥٦٧٨٩"[d]);
const dirName=d=>{const names=["شمال","شمال شرقي","شرق","جنوب شرقي","جنوب","جنوب غربي","غرب","شمال غربي"];return names[Math.round(((d%360)+360)%360/45)%8]};
function smoothAngle(prev,next,f=.24){if(prev==null)return next;let delta=((next-prev+540)%360)-180;return (prev+delta*f+360)%360}
const native=()=>typeof window!=="undefined"&&window.SakinahNative?window.SakinahNative:null;

export default function QiblaPro(){
 const[loc,setLoc]=useState(null),[heading,setHeading]=useState(null),[accuracy,setAccuracy]=useState(null),[status,setStatus]=useState("جاري تشغيل الموقع عالي الدقة…"),[sensorOn,setSensorOn]=useState(false),[gpsLive,setGpsLive]=useState(false),[bestAccuracy,setBestAccuracy]=useState(null),[lastFix,setLastFix]=useState(null),[declination,setDeclination]=useState(0),[headingMode,setHeadingMode]=useState("—");
 const watchRef=useRef(null),headingRef=useRef(null),orientationHandlerRef=useRef(null),absoluteHandlerRef=useRef(null),locRef=useRef(null),declinationRef=useRef(0);
 const qibla=useMemo(()=>loc?bearing(loc.lat,loc.lon):null,[loc]);
 const dist=useMemo(()=>loc?distance(loc.lat,loc.lon):null,[loc]);
 const relative=qibla==null?qibla:heading==null?qibla:(qibla-heading+360)%360;
 const aligned=relative!=null&&heading!=null&&(relative<3||relative>357);

 const updateDeclination=(lat,lon)=>{const n=native();let d=0;try{if(n?.magneticDeclination)d=Number(n.magneticDeclination(lat,lon,0,Date.now()))||0}catch{}declinationRef.current=d;setDeclination(d)};
 const applyPosition=p=>{const a=Number.isFinite(p.coords.accuracy)?p.coords.accuracy:null;const next={lat:p.coords.latitude,lon:p.coords.longitude};locRef.current=next;setLoc(next);updateDeclination(next.lat,next.lon);setAccuracy(a);setBestAccuracy(v=>a==null?v:(v==null?a:Math.min(v,a)));setLastFix(Date.now());setGpsLive(true);setStatus(a!=null&&a>50?`تم تحديد الموقع، ننتظر دقة أفضل… الدقة الحالية ${Math.round(a)} م`:"الموقع عالي الدقة يعمل مباشرة.")};
 const locationError=e=>{setGpsLive(false);const msg=e?.code===1?"إذن الموقع مرفوض. اسمح للموقع الدقيق من إعدادات التطبيق.":e?.code===2?"إشارة GPS غير متاحة حالياً. انتقل لمكان مفتوح وحاول مجدداً.":"انتهت مهلة GPS. أعد المحاولة في مكان مفتوح.";setStatus(msg)};
 const stopLocationWatch=()=>{if(watchRef.current!=null&&navigator.geolocation){navigator.geolocation.clearWatch(watchRef.current);watchRef.current=null}setGpsLive(false)};
 const startLocationWatch=()=>{if(!navigator.geolocation){setStatus("هذا الجهاز لا يوفر خدمة الموقع.");return}stopLocationWatch();setStatus("جاري التقاط GPS عالي الدقة…");navigator.geolocation.getCurrentPosition(applyPosition,locationError,{enableHighAccuracy:true,timeout:18000,maximumAge:0});watchRef.current=navigator.geolocation.watchPosition(applyPosition,locationError,{enableHighAccuracy:true,timeout:20000,maximumAge:0})};

 const applyHeading=h=>{if(!Number.isFinite(h))return;const next=smoothAngle(headingRef.current,(h+360)%360,.22);headingRef.current=next;setHeading(next);setSensorOn(true)};
 const readOrientation=e=>{let h=null,mode="";if(typeof e.webkitCompassHeading==="number"&&Number.isFinite(e.webkitCompassHeading)){h=e.webkitCompassHeading;mode="True North"}else if(e.absolute===true&&typeof e.alpha==="number"){const magnetic=(360-e.alpha)%360;h=(magnetic+declinationRef.current+360)%360;mode=native()?.magneticDeclination?"True North مصحح":"Absolute"}else if(typeof e.alpha==="number"&&native()?.magneticDeclination&&locRef.current){const magnetic=(360-e.alpha)%360;h=(magnetic+declinationRef.current+360)%360;mode="True North مصحح"}if(h!=null){setHeadingMode(mode);applyHeading(h)}};
 const stopCompass=()=>{if(absoluteHandlerRef.current)window.removeEventListener("deviceorientationabsolute",absoluteHandlerRef.current,true);if(orientationHandlerRef.current)window.removeEventListener("deviceorientation",orientationHandlerRef.current,true);absoluteHandlerRef.current=null;orientationHandlerRef.current=null;setSensorOn(false)};
 const enableCompass=async()=>{try{if(typeof DeviceOrientationEvent==="undefined"){setStatus("هذا الجهاز لا يوفّر مستشعر اتجاه متوافقاً.");return}if(typeof DeviceOrientationEvent.requestPermission==="function"){const ok=await DeviceOrientationEvent.requestPermission();if(ok!=="granted"){setStatus("لم يتم منح إذن البوصلة. فعّله من إعدادات النظام.");return}}stopCompass();headingRef.current=null;absoluteHandlerRef.current=readOrientation;orientationHandlerRef.current=readOrientation;window.addEventListener("deviceorientationabsolute",absoluteHandlerRef.current,true);window.addEventListener("deviceorientation",orientationHandlerRef.current,true);setStatus("البوصلة تعمل مع تصحيح الشمال الحقيقي. حرّك الهاتف بشكل رقم 8 لمعايرة أدق.");setTimeout(()=>{if(headingRef.current==null)setStatus("لم تصل قراءة موثوقة من حساس الاتجاه. تأكد أن الهاتف يحتوي بوصلة وأن إذن الحركة مفعّل.")},3000)}catch{setStatus("تعذر تشغيل مستشعر البوصلة على هذا الجهاز.")}};
 const recalibrate=()=>{headingRef.current=null;setHeading(null);setStatus("أعد المعايرة: حرّك الهاتف ببطء على شكل رقم 8 ثم اجعله أفقياً.");if(!sensorOn)enableCompass()};

 useEffect(()=>{startLocationWatch();return()=>{stopLocationWatch();stopCompass()}},[]);
 const ticks=Array.from({length:36},(_,i)=>i*10);
 const quality=accuracy==null?"—":accuracy<=10?"ممتازة":accuracy<=25?"جيدة جداً":accuracy<=50?"جيدة":"تحتاج تحسين";
 return <div dir="rtl" style={{position:"absolute",inset:0,overflowY:"auto",background:C.ivory,color:C.ink,scrollPaddingBottom:"calc(390px + env(safe-area-inset-bottom,0px))"}}><main style={{maxWidth:680,margin:"0 auto",paddingTop:30,paddingLeft:18,paddingRight:18,paddingBottom:"calc(390px + env(safe-area-inset-bottom,0px))",boxSizing:"border-box"}}>
  <header style={{textAlign:"center"}}><div style={{fontSize:9.5,color:C.gold,letterSpacing:1.4}}>QIBLA · MUSLIM MIRROR</div><h1 style={{fontSize:29,margin:"5px 0 5px"}}>اتجاه القبلة</h1><p style={{fontSize:10.5,opacity:.47,lineHeight:1.8,margin:0}}>GPS عالي الدقة وبوصلة مصححة إلى الشمال الحقيقي لتثبيت اتجاه الكعبة</p></header>
  <section style={{marginTop:20,borderRadius:30,padding:"20px 16px 18px",background:"linear-gradient(155deg,#102E44,#1D4C69)",color:"white",boxShadow:"0 18px 48px rgba(23,59,87,.18)"}}>
   <div style={{display:"flex",justifyContent:"space-between",alignItems:"center",fontSize:9.5,opacity:.72}}><span>{sensorOn?`● ${headingMode}`:"○ البوصلة غير مفعّلة"}</span><span>{gpsLive?"● GPS مباشر":"○ GPS متوقف"}</span></div>
   <div style={{display:"grid",placeItems:"center",padding:"18px 0 8px"}}><div style={{width:"min(74vw,320px)",height:"min(74vw,320px)",maxWidth:320,maxHeight:320,minWidth:260,minHeight:260,borderRadius:"50%",position:"relative",background:"radial-gradient(circle at 50% 48%,rgba(255,255,255,.11),rgba(255,255,255,.02) 62%,rgba(0,0,0,.08))",border:"1px solid rgba(255,255,255,.14)",boxShadow:"inset 0 0 0 12px rgba(255,255,255,.018),0 20px 45px rgba(0,0,0,.14)"}}>
    {ticks.map(v=><i key={v} style={{position:"absolute",left:"50%",top:"50%",width:v%90===0?2:1,height:v%90===0?13:8,background:v%90===0?"rgba(255,255,255,.75)":"rgba(255,255,255,.28)",transformOrigin:"50% 142px",transform:`translate(-50%,-142px) rotate(${v}deg)`}}/>)}
    <span style={{position:"absolute",top:18,left:"50%",transform:"translateX(-50%)",fontSize:11,opacity:.7}}>N</span><span style={{position:"absolute",bottom:18,left:"50%",transform:"translateX(-50%)",fontSize:10,opacity:.45}}>S</span><span style={{position:"absolute",left:19,top:"50%",transform:"translateY(-50%)",fontSize:10,opacity:.45}}>W</span><span style={{position:"absolute",right:19,top:"50%",transform:"translateY(-50%)",fontSize:10,opacity:.45}}>E</span>
    <div style={{position:"absolute",left:"50%",top:"50%",width:8,height:116,borderRadius:8,background:`linear-gradient(${aligned?"#E8D497":C.gold},rgba(255,255,255,.20))`,transformOrigin:"50% 100%",transform:`translate(-50%,-100%) rotate(${relative||0}deg)`,transition:"transform .18s linear"}}><span style={{position:"absolute",top:-17,left:"50%",transform:"translateX(-50%)",fontSize:20}}>◆</span></div>
    <div style={{position:"absolute",left:"50%",top:"50%",transform:"translate(-50%,-50%)",width:92,height:92,borderRadius:"50%",display:"grid",placeItems:"center",textAlign:"center",background:"rgba(10,31,46,.86)",border:`1px solid ${aligned?"rgba(232,212,151,.8)":"rgba(255,255,255,.16)"}`,boxShadow:"0 8px 24px rgba(0,0,0,.18)"}}><div><div style={{fontSize:8.5,opacity:.55}}>الكعبة</div><div style={{fontSize:22,fontWeight:700,color:"#E8D497",marginTop:2}}>{qibla==null?"—":`${ar(qibla.toFixed(0))}°`}</div></div></div>
   </div></div>
   <div style={{textAlign:"center",marginTop:4}}><b style={{fontSize:15}}>{aligned?"أنت باتجاه القبلة ✓":qibla==null?"نحدد موقعك الآن…":heading==null?`اتجاه القبلة ${dirName(qibla)}`:"دوّر الهاتف حتى يصبح المؤشر للأعلى"}</b><div style={{fontSize:9.5,opacity:.58,marginTop:4}}>{heading!=null?`اتجاه الجهاز ${ar(heading.toFixed(0))}° · القبلة ${ar(qibla?.toFixed(0))}° · الانحراف ${ar(declination.toFixed(1))}°`:"شغّل البوصلة للحصول على توجيه مباشر أثناء دوران الهاتف"}</div></div>
  </section>
  <section style={{display:"grid",gridTemplateColumns:"repeat(3,1fr)",gap:8,marginTop:12}}><div style={{padding:"12px 7px",borderRadius:17,background:"rgba(255,255,255,.5)",border:"1px solid rgba(16,16,15,.06)",textAlign:"center"}}><small style={{fontSize:8.5,opacity:.42}}>اتجاه القبلة</small><b style={{display:"block",fontSize:18,color:C.lapis,marginTop:4}}>{qibla==null?"—":`${ar(qibla.toFixed(1))}°`}</b></div><div style={{padding:"12px 7px",borderRadius:17,background:"rgba(255,255,255,.5)",border:"1px solid rgba(16,16,15,.06)",textAlign:"center"}}><small style={{fontSize:8.5,opacity:.42}}>المسافة إلى الكعبة</small><b style={{display:"block",fontSize:17,color:C.lapis,marginTop:4}}>{dist==null?"—":`${ar(Math.round(dist).toLocaleString("en"))} كم`}</b></div><div style={{padding:"12px 7px",borderRadius:17,background:"rgba(255,255,255,.5)",border:"1px solid rgba(16,16,15,.06)",textAlign:"center"}}><small style={{fontSize:8.5,opacity:.42}}>دقة GPS</small><b style={{display:"block",fontSize:17,color:accuracy!=null&&accuracy<=25?C.green:C.lapis,marginTop:4}}>{accuracy?`${ar(Math.round(accuracy))} م`:"—"}</b><small style={{display:"block",fontSize:8,opacity:.38,marginTop:2}}>{quality}</small></div></section>
  <section style={{marginTop:13,padding:14,borderRadius:20,background:"rgba(181,154,98,.08)",border:"1px solid rgba(181,154,98,.10)"}}><div style={{display:"flex",justifyContent:"space-between",gap:12}}><div><b style={{fontSize:11.5}}>الموقع المباشر</b><div style={{fontSize:9.5,opacity:.48,marginTop:4}}>{loc?`${ar(loc.lat.toFixed(6))} ، ${ar(loc.lon.toFixed(6))}`:"لم يتم تحديد الموقع بعد"}</div><div style={{fontSize:8.5,opacity:.35,marginTop:4}}>{bestAccuracy!=null?`أفضل دقة في هذه الجلسة: ${ar(Math.round(bestAccuracy))} م`:"بانتظار قراءة GPS"}{lastFix?` · تحديث ${ar(Math.max(0,Math.round((Date.now()-lastFix)/1000)))} ث`:""}</div></div><span style={{fontSize:18,color:C.gold}}>⌖</span></div></section>
  <div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:8,marginTop:12}}><button onClick={enableCompass} style={{border:0,borderRadius:16,padding:12,background:C.lapis,color:"white",fontFamily:"inherit",fontWeight:650}}>{sensorOn?"إعادة تشغيل البوصلة":"تشغيل البوصلة"}</button><button onClick={startLocationWatch} style={{border:"1px solid rgba(16,16,15,.08)",borderRadius:16,padding:12,background:"rgba(255,255,255,.52)",fontFamily:"inherit",color:C.ink}}>{gpsLive?"تحديث GPS بدقة عالية":"تشغيل GPS الدقيق"}</button></div>
  <button onClick={recalibrate} style={{width:"100%",marginTop:8,border:"1px solid rgba(181,154,98,.18)",borderRadius:15,padding:10,background:"rgba(181,154,98,.08)",fontFamily:"inherit",color:C.ink}}>معايرة البوصلة من جديد</button>
  {status&&<div style={{marginTop:10,padding:"10px 12px",borderRadius:14,background:"rgba(16,16,15,.035)",fontSize:9.5,lineHeight:1.7,opacity:.62}}>{status}</div>}
  <section style={{marginTop:14,fontSize:9,opacity:.42,lineHeight:1.75,textAlign:"center"}}>لأفضل نتيجة: فعّل «الموقع الدقيق»، حرّك الهاتف بشكل رقم 8 للمعايرة، وأبعده عن المعادن والمغناطيس. على Android يتم تصحيح الانحراف المغناطيسي نحو الشمال الحقيقي حسب موقعك الحالي.</section>
  <div aria-hidden="true" style={{height:100,flex:"0 0 100px"}}/>
 </main></div>;
}
