import React,{useMemo,useState} from "react";

const C={ivory:"#F6F3EC",ink:"#10100F",lapis:"#173B57",gold:"#B59A62",green:"#4F915C",red:"#A44D3C"};
const btn={border:"1px solid rgba(16,16,15,.09)",borderRadius:14,padding:11,background:"transparent",fontFamily:"inherit",color:"inherit"};
const profile=()=>{try{return localStorage.getItem("sakinah-active-profile")||"me"}catch{return "me"}};
function norm(s=""){return s.normalize("NFKD").replace(/[\u064B-\u065F\u0670\u06D6-\u06ED]/g,"").replace(/[إأآٱ]/g,"ا").replace(/ى/g,"ي").replace(/ؤ/g,"و").replace(/ئ/g,"ي").replace(/ـ/g,"").replace(/\s+/g," ").trim().toLowerCase()}
function Shell({lang,go,titleAr,titleEn,subAr,subEn,children,back="islamic-search"}){return <div style={{position:"absolute",inset:0,background:C.ivory,color:C.ink,display:"flex",flexDirection:"column"}}><div style={{padding:"22px 22px 0"}}><button onClick={()=>go(back)} style={{...btn,border:0,padding:0}}>{lang==="ar"?"← رجوع":"← Back"}</button></div><div style={{flex:1,overflowY:"auto",padding:"15px 22px 130px"}}><div style={{fontFamily:"Fraunces,serif",fontSize:29}}>{lang==="ar"?titleAr:titleEn}</div><div style={{fontSize:11.5,opacity:.5,lineHeight:1.75,marginTop:7}}>{lang==="ar"?subAr:subEn}</div>{children}</div></div>}
async function qSearch(q){const r=await fetch(`https://api.alquran.cloud/v1/search/${encodeURIComponent(q)}/all/quran-uthmani`);if(!r.ok)throw new Error("search");const j=await r.json();const x=j?.data?.matches||j?.data||[];return Array.isArray(x)?x:[]}
async function ayah(ref){const r=await fetch(`https://api.alquran.cloud/v1/ayah/${encodeURIComponent(ref)}/quran-uthmani`);if(!r.ok)throw new Error("ayah");const j=await r.json();return j?.data}
function Results({lang,rows}){return <div style={{marginTop:14}}>{rows.slice(0,100).map((x,i)=><div key={`${x.number||i}-${x.numberInSurah||i}`} style={{padding:"13px 0",borderTop:"1px solid rgba(16,16,15,.07)"}}><div style={{fontSize:10,opacity:.45}}>{x.surah?.name||x.surah?.englishName} · {lang==="ar"?"آية":"Ayah"} {x.numberInSurah}</div><div dir="rtl" style={{fontSize:20,lineHeight:2,fontFamily:"'Amiri Quran','Noto Naskh Arabic',serif",marginTop:6}}>{x.text}</div></div>)}</div>}

const TOPICS=[
 ["الرحمة","Mercy"],["الصبر","Patience"],["التوبة","Repentance"],["الدعاء","Dua"],["الوالدين","Parents"],["الأسرة","Family"],["المال","Wealth"],["العدل","Justice"],["العلم","Knowledge"],["الجنة","Paradise"],["النار","Hellfire"],["القيامة","Resurrection"],["الأنبياء","Prophets"],["الصلاة","Prayer"],["الصيام","Fasting"],["الزكاة","Zakat"]
];
export function QuranTopicExplorer({lang,go}){const [topic,setTopic]=useState("الرحمة"),[rows,setRows]=useState([]),[busy,setBusy]=useState(false),[err,setErr]=useState("");const run=async(q=topic)=>{setBusy(true);setErr("");try{setRows(await qSearch(q))}catch{setErr(lang==="ar"?"تعذر التحليل الآن":"Analysis unavailable") }finally{setBusy(false)}};return <Shell lang={lang} go={go} titleAr="موضوعات القرآن" titleEn="Quran Topics" subAr="استكشف الآيات المرتبطة بموضوع واحد من النص القرآني الحي" subEn="Explore live Quran verses around a selected topic"><div style={{marginTop:16,display:"grid",gridTemplateColumns:"repeat(2,1fr)",gap:7}}>{TOPICS.map(([ar,en])=><button key={ar} onClick={()=>{setTopic(ar);run(ar)}} style={{...btn,background:topic===ar?"rgba(181,154,98,.12)":"transparent",textAlign:lang==="ar"?"right":"left"}}>{lang==="ar"?ar:en}</button>)}</div><div style={{marginTop:12,display:"grid",gridTemplateColumns:"1fr auto",gap:8}}><input value={topic} onChange={e=>setTopic(e.target.value)} placeholder={lang==="ar"?"موضوع مخصص…":"Custom topic…"} style={{...btn,width:"100%",boxSizing:"border-box"}}/><button onClick={()=>run()} style={{...btn,background:C.lapis,color:"white",border:0}}>{busy?"…":(lang==="ar"?"استكشف":"Explore")}</button></div>{err&&<div style={{marginTop:10,color:C.red,fontSize:10.5}}>{err}</div>}<Results lang={lang} rows={rows}/></Shell>}

export function QuranWordCompare({lang,go}){const [a,setA]=useState("الدنيا"),[b,setB]=useState("الآخرة"),[ra,setRa]=useState([]),[rb,setRb]=useState([]),[busy,setBusy]=useState(false);const run=async()=>{setBusy(true);try{const [x,y]=await Promise.all([qSearch(a),qSearch(b)]);setRa(x);setRb(y)}finally{setBusy(false)}};const summary=(q,r)=>({q,count:r.length,surahs:new Set(r.map(x=>x.surah?.number)).size,top:Object.entries(r.reduce((m,x)=>{const k=x.surah?.name||x.surah?.englishName||"?";m[k]=(m[k]||0)+1;return m},{})).sort((x,y)=>y[1]-x[1]).slice(0,5)});const A=summary(a,ra),B=summary(b,rb);return <Shell lang={lang} go={go} titleAr="مقارنة الكلمات" titleEn="Word Comparison" subAr="قارن كلمتين أو اسمين: عدد النتائج، السور والتوزيع" subEn="Compare two words or names by occurrences, surahs and distribution"><div style={{marginTop:16,display:"grid",gridTemplateColumns:"1fr 1fr",gap:8}}><input value={a} onChange={e=>setA(e.target.value)} style={{...btn,minWidth:0}}/><input value={b} onChange={e=>setB(e.target.value)} style={{...btn,minWidth:0}}/></div><button onClick={run} style={{...btn,width:"100%",marginTop:8,background:C.lapis,color:"white",border:0}}>{busy?"…":(lang==="ar"?"قارن الآن":"Compare now")}</button><div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:9,marginTop:14}}>{[A,B].map(x=><div key={x.q} style={{padding:15,borderRadius:18,background:"rgba(181,154,98,.09)",border:"1px solid rgba(181,154,98,.14)"}}><div style={{fontSize:16,fontWeight:700}}>{x.q}</div><div style={{fontSize:24,fontFamily:"Fraunces,serif",marginTop:8}}>{x.count}</div><div style={{fontSize:9.5,opacity:.45}}>{lang==="ar"?`نتيجة في ${x.surahs} سورة`:`matches in ${x.surahs} surahs`}</div><div style={{marginTop:9,fontSize:10.5,lineHeight:1.8}}>{x.top.map(([s,n])=><div key={s}>{s} · {n}</div>)}</div></div>)}</div></Shell>}

const ENTITIES={
 prophets:["آدم","نوح","إبراهيم","إسماعيل","إسحاق","يعقوب","يوسف","موسى","هارون","داود","سليمان","أيوب","يونس","زكريا","يحيى","عيسى","محمد"],
 peoples:["عاد","ثمود","مدين","بني إسرائيل","قوم لوط","أصحاب الكهف","أصحاب الفيل"],
 places:["مكة","بكة","المدينة","مصر","سيناء","طور","بابل"],
 angels:["جبريل","ميكال","هاروت","ماروت"]
};
export function QuranEntityMap({lang,go}){const [kind,setKind]=useState("prophets"),[name,setName]=useState("موسى"),[rows,setRows]=useState([]),[busy,setBusy]=useState(false);const run=async(n=name)=>{setBusy(true);try{setRows(await qSearch(n))}finally{setBusy(false)}};const labels={prophets:["الأنبياء","Prophets"],peoples:["الأقوام","Peoples"],places:["الأماكن","Places"],angels:["الملائكة","Angels"]};return <Shell lang={lang} go={go} titleAr="خريطة الأسماء في القرآن" titleEn="Quran Name Map" subAr="أسماء الأنبياء والأقوام والأماكن والملائكة مع مواضع ذكرها" subEn="Prophets, peoples, places and angels with their Quran mentions"><div style={{marginTop:16,display:"grid",gridTemplateColumns:"repeat(4,1fr)",gap:6}}>{Object.keys(ENTITIES).map(k=><button key={k} onClick={()=>setKind(k)} style={{...btn,padding:9,fontSize:10,background:kind===k?"rgba(181,154,98,.12)":"transparent"}}>{lang==="ar"?labels[k][0]:labels[k][1]}</button>)}</div><div style={{marginTop:10,display:"flex",gap:7,flexWrap:"wrap"}}>{ENTITIES[kind].map(n=><button key={n} onClick={()=>{setName(n);run(n)}} style={{...btn,padding:"8px 10px",background:name===n?"rgba(23,59,87,.08)":"transparent"}}>{n}</button>)}</div>{busy&&<div style={{marginTop:12,fontSize:11,opacity:.45}}>{lang==="ar"?"جاري البحث…":"Searching…"}</div>}<Results lang={lang} rows={rows}/></Shell>}

function roughStem(w){let x=norm(w).replace(/^(وال|فال|بال|كال|لل|ال)/,"").replace(/^(و|ف|ب|ك|ل)/,"").replace(/(كما|هما|كم|كن|نا|ها|هم|هن|ه|ي|ك)$/," ").trim();x=x.replace(/(ات|ون|ين|ان|ة|ه|ي)$/g,"");return x.length>=3?x:norm(w)}
export function QuranRootExplorer({lang,go}){const [q,setQ]=useState("رحمة"),[rows,setRows]=useState([]),[busy,setBusy]=useState(false),[stem,setStem]=useState("");const run=async()=>{const s=roughStem(q);setStem(s);setBusy(true);try{const variants=[q,s,`${s}ة`].filter((x,i,a)=>x&&a.indexOf(x)===i);const blocks=await Promise.all(variants.map(v=>qSearch(v).catch(()=>[])));const map=new Map();blocks.flat().forEach(x=>map.set(`${x.surah?.number}:${x.numberInSurah}`,x));setRows([...map.values()])}finally{setBusy(false)}};return <Shell lang={lang} go={go} titleAr="استكشاف الجذر" titleEn="Root Explorer" subAr="بحث تقريبي يجمع تصريفات قريبة؛ ليس محللاً صرفياً أكاديمياً" subEn="Approximate stemming that groups nearby forms; not an academic morphology engine"><div style={{marginTop:16,display:"grid",gridTemplateColumns:"1fr auto",gap:8}}><input value={q} onChange={e=>setQ(e.target.value)} onKeyDown={e=>e.key==="Enter"&&run()} style={{...btn,minWidth:0}}/><button onClick={run} style={{...btn,background:C.lapis,color:"white",border:0}}>{busy?"…":(lang==="ar"?"حلّل":"Explore")}</button></div>{stem&&<div style={{marginTop:10,fontSize:10.5,opacity:.5}}>{lang==="ar"?"الجذر/الساق التقريبي":"Approximate stem"}: <b>{stem}</b> · {rows.length} {lang==="ar"?"موضع":"matches"}</div>}<Results lang={lang} rows={rows}/></Shell>}

export function TadabburAyah({lang,go}){const [ref,setRef]=useState("2:286"),[data,setData]=useState(null),[topic,setTopic]=useState(""),[related,setRelated]=useState([]),[note,setNote]=useState(""),[busy,setBusy]=useState(false),[saved,setSaved]=useState(false);const load=async()=>{setBusy(true);setSaved(false);try{const x=await ayah(ref);setData(x);const seed=(topic||x?.text||"").split(/\s+/).filter(Boolean).slice(0,2).join(" ");setRelated(seed?await qSearch(seed).catch(()=>[]):[]);const k=`sakinah-tadabbur-${profile()}-${ref.replace(":","-")}`;try{setNote(localStorage.getItem(k)||"")}catch{}}finally{setBusy(false)}};const save=()=>{try{localStorage.setItem(`sakinah-tadabbur-${profile()}-${ref.replace(":","-")}`,note);setSaved(true)}catch{}};return <Shell lang={lang} go={go} titleAr="تدبّر الآية" titleEn="Ayah Reflection" subAr="آية موثقة، روابط نصية مشابهة، ومساحة تأمل خاصة بك" subEn="A sourced ayah, related textual matches and your private reflection"><div style={{marginTop:16,display:"grid",gridTemplateColumns:"110px 1fr auto",gap:7}}><input value={ref} onChange={e=>setRef(e.target.value)} placeholder="2:286" style={{...btn,minWidth:0}}/><input value={topic} onChange={e=>setTopic(e.target.value)} placeholder={lang==="ar"?"موضوع اختياري":"Optional topic"} style={{...btn,minWidth:0}}/><button onClick={load} style={{...btn,background:C.lapis,color:"white",border:0}}>{busy?"…":(lang==="ar"?"فتح":"Open")}</button></div>{data&&<><div style={{marginTop:16,padding:18,borderRadius:20,background:"rgba(181,154,98,.09)",border:"1px solid rgba(181,154,98,.15)"}}><div style={{fontSize:10,opacity:.45}}>{data.surah?.name} · {lang==="ar"?"آية":"Ayah"} {data.numberInSurah}</div><div dir="rtl" style={{fontSize:24,lineHeight:2.1,fontFamily:"'Amiri Quran','Noto Naskh Arabic',serif",marginTop:8}}>{data.text}</div></div><textarea value={note} onChange={e=>setNote(e.target.value)} placeholder={lang==="ar"?"ما العبرة التي خرجت بها؟ ماذا غيّرت فيك الآية؟":"What lesson did you take from this ayah?"} style={{...btn,width:"100%",boxSizing:"border-box",minHeight:140,marginTop:12,lineHeight:1.8,resize:"vertical"}}/><button onClick={save} style={{...btn,width:"100%",marginTop:8,background:saved?C.green:C.lapis,color:"white",border:0}}>{saved?(lang==="ar"?"تم الحفظ ✓":"Saved ✓"):(lang==="ar"?"حفظ التدبّر":"Save reflection")}</button><div style={{marginTop:18,fontSize:12,fontWeight:700}}>{lang==="ar"?"مواضع نصية مرتبطة":"Related textual matches"}</div><Results lang={lang} rows={related.filter(x=>`${x.surah?.number}:${x.numberInSurah}`!==ref).slice(0,12)}/></>}</Shell>}

export function QuranIntelligenceHub({lang,go}){const cards=[["quran-topics","موضوعات القرآن","Quran Topics","الرحمة، الصبر، الأسرة، المال، الجنة وغيرها"],["quran-compare","مقارنة الكلمات","Word Comparison","قارن اسمين أو كلمتين وتوزعهما"],["quran-entities","خريطة الأسماء","Name Map","الأنبياء والأقوام والأماكن والملائكة"],["quran-roots","استكشاف الجذور","Root Explorer","تجميع تقريبي للتصريفات القريبة"],["tadabbur-ayah","تدبّر الآية","Ayah Reflection","الآية والمواضع المرتبطة وتأملك الخاص"],["quran-analytics","الإحصاءات الدقيقة","Quran Analytics","عدد الحروف والكلمات ومرات الذكر"]];return <Shell lang={lang} go={go} titleAr="ذكاء القرآن" titleEn="Quran Intelligence" subAr="أدوات تحليل وتدبّر فوق النص القرآني الحي، بدون حذف البحث الأصلي" subEn="Analysis and reflection tools layered on the live Quran text"><div style={{marginTop:17,display:"grid",gridTemplateColumns:"1fr 1fr",gap:9}}>{cards.map(([id,ar,en,sub])=><button key={id} onClick={()=>go(id)} style={{...btn,minHeight:115,textAlign:lang==="ar"?"right":"left",background:"rgba(255,255,255,.46)"}}><div style={{fontSize:19,color:C.gold}}>◌</div><div style={{fontSize:12.5,fontWeight:700,marginTop:8}}>{lang==="ar"?ar:en}</div><div style={{fontSize:9.5,opacity:.45,lineHeight:1.55,marginTop:5}}>{sub}</div></button>)}</div></Shell>}
