import React,{useEffect,useMemo,useState} from "react";

const C={ivory:"#F6F3EC",ink:"#10100F",lapis:"#173B57",gold:"#B59A62"};
const PR=["Fajr","Dhuhr","Asr","Maghrib","Isha"];
const AR={Fajr:"الفجر",Dhuhr:"الظهر",Asr:"العصر",Maghrib:"المغرب",Isha:"العشاء",Sunrise:"الشروق"};
const clean=v=>(v||"").split(" ")[0];
const east=s=>String(s).replace(/[0-9]/g,d=>"٠١٢٣٤٥٦٧٨٩"[d]);
function hm(v){const [h,m]=clean(v).split(":").map(Number);return (h||0)+(m||0)/60}
function epoch(v,dayOffset=0){const [h,m]=clean(v).split(":").map(Number);const d=new Date();d.setDate(d.getDate()+dayOffset);d.setHours(h||0,m||0,0,0);return d.getTime()}
function nextPrayer(t){if(!t)return null;const now=Date.now();for(const p of PR){const at=epoch(t[p]);if(at>now)return {id:p,time:clean(t[p]),at}}return {id:"Fajr",time:clean(t.Fajr),at:epoch(t.Fajr,1)}}
function leftParts(ms){const total=Math.max(0,Math.floor(ms/60000));return {h:Math.floor(total/60),m:total%60}}
function stageFor(t,now){if(!t)return {dark:false,from:"#F6F3EC",via:"#F3ECDD",to:"#E9D8B9"};const x=now.getHours()+now.getMinutes()/60;const fajr=hm(t.Fajr),sun=hm(t.Sunrise),dhuhr=hm(t.Dhuhr),asr=hm(t.Asr),mag=hm(t.Maghrib),isha=hm(t.Isha);if(x<fajr||x>=isha+.5)return {dark:true,from:"#100C15",via:"#141A2A",to:"#0B0910"};if(x<sun)return {dark:true,from:"#0B0C10",via:"#16283A",to:"#33566E"};if(x<dhuhr)return {dark:false,from:"#F1E6C9",via:"#F5EFDF",to:"#F6F3EC"};if(x<asr)return {dark:false,from:"#FAF8F2",via:"#F4F0E4",to:"#EEE6D1"};if(x<mag)return {dark:false,from:"#F5EEE0",via:"#EDDCC0",to:"#DFC4A1"};return {dark:true,from:"#D9A776",via:"#6B4438",to:"#1C0F12"}}
function DayArc({timings,now,dark}){if(!timings)return <div style={{height:72}}/>;const times=[timings.Fajr,timings.Sunrise,timings.Dhuhr,timings.Asr,timings.Maghrib,timings.Isha].map(hm);const nowH=now.getHours()+now.getMinutes()/60;const start=times[0],end=times[5];const pct=Math.max(0,Math.min(1,(nowH-start)/(end-start||1)));const x=18+pct*264;const y=63-Math.sin(pct*Math.PI)*44;return <div style={{height:78,position:"relative"}}><svg viewBox="0 0 300 78" width="100%" height="78" aria-hidden="true"><path d="M18 63 Q150 -20 282 63" fill="none" stroke={dark?"rgba(246,243,236,.20)":"rgba(16,16,15,.16)"} strokeWidth="1.2"/><path d="M18 63 Q150 -20 282 63" fill="none" stroke={C.gold} strokeWidth="1.8" strokeDasharray="430" strokeDashoffset={430*(1-pct)} strokeLinecap="round"/><circle cx={x} cy={y} r="5" fill={C.gold}/>{times.map((_,i)=>{const p=i/(times.length-1),px=18+p*264,py=63-Math.sin(p*Math.PI)*44;return <circle key={i} cx={px} cy={py} r="2.2" fill={dark?"rgba(246,243,236,.62)":"rgba(16,16,15,.48)"}/>})}</svg></div>}
function emit(id){window.dispatchEvent(new CustomEvent("sakinah:feature",{detail:id}))}
export default function SakinahLiveHome(){
 const [data,setData]=useState(null),[status,setStatus]=useState(""),[tick,setTick]=useState(Date.now());
 const load=()=>{setStatus("جاري تحديد الموقع…");if(!navigator.geolocation){setStatus("الموقع غير مدعوم على هذا الجهاز");return}navigator.geolocation.getCurrentPosition(async p=>{try{const {latitude,longitude}=p.coords;const r=await fetch(`https://api.aladhan.com/v1/timings?latitude=${latitude}&longitude=${longitude}&method=4`);if(!r.ok)throw new Error();const j=await r.json();setData(j?.data||null);setStatus("")}catch{setStatus("تعذر تحميل مواقيت الصلاة الآن")}},()=>setStatus("فعّل الموقع واسمح لسكينة بالوصول إليه"),{enableHighAccuracy:true,timeout:12000})};
 useEffect(()=>{load();const id=setInterval(()=>setTick(Date.now()),30000);return()=>clearInterval(id)},[]);
 const next=useMemo(()=>nextPrayer(data?.timings),[data,tick]);
 const now=new Date(tick),stage=stageFor(data?.timings,now),fg=stage.dark?C.ivory:C.ink;
 const rem=next?leftParts(next.at-tick):{h:0,m:0};
 const date=new Intl.DateTimeFormat("ar-IQ",{weekday:"long",day:"numeric",month:"long"}).format(now);
 const hijri=data?.date?.hijri?.date?`${data.date.hijri.day} ${data.date.hijri.month?.ar||""} ${data.date.hijri.year}`:"";
 return <div style={{minHeight:"100vh",background:C.ivory,color:C.ink,paddingBottom:118}} dir="rtl">
  <section style={{minHeight:430,padding:"26px 24px 24px",background:`linear-gradient(180deg,${stage.from} 0%,${stage.via} 55%,${stage.to} 100%)`,color:fg,transition:"background .5s ease,color .5s ease",display:"flex",flexDirection:"column"}}>
   <header style={{display:"flex",alignItems:"center",justifyContent:"space-between",gap:12}}><div><div style={{fontSize:10,letterSpacing:1.2,opacity:.42}}>SAKINAH</div><div style={{fontFamily:"Fraunces,serif",fontSize:31,marginTop:4}}>سكينة</div><div style={{fontSize:10.5,opacity:.48,marginTop:4}}>{date}{hijri?` · ${hijri}`:""}</div></div><button onClick={load} style={{width:43,height:43,borderRadius:15,border:`1px solid ${stage.dark?"rgba(246,243,236,.16)":"rgba(16,16,15,.08)"}`,background:stage.dark?"rgba(255,255,255,.06)":"rgba(255,255,255,.35)",color:fg,fontSize:18}}>↻</button></header>
   <div style={{marginTop:"auto",paddingTop:34}}>
    <div style={{fontSize:12,letterSpacing:".16em",fontWeight:600,opacity:.55}}>{next?AR[next.id]:"الصلاة القادمة"}</div>
    <div style={{fontSize:60,lineHeight:1,margin:"8px 0 5px",fontWeight:600,fontFamily:"'IBM Plex Sans Arabic','Cairo',sans-serif",letterSpacing:"-.03em"}}>{next?east(next.time):"--:--"}</div>
    <div style={{fontSize:13,opacity:.58,fontWeight:500}}>{next?`متبقي ${east(rem.h)} ساعة و ${east(rem.m)} دقيقة`:"بانتظار مواقيت موقعك"}</div>
    {status&&<div style={{marginTop:9,fontSize:10.5,opacity:.62}}>{status}</div>}
   </div>
   <div style={{marginTop:24}}><DayArc timings={data?.timings} now={now} dark={stage.dark}/></div>
  </section>
  <div style={{padding:"0 20px"}}>
   <div style={{display:"grid",gridTemplateColumns:"repeat(5,1fr)",gap:5,marginTop:18,paddingBottom:15,borderBottom:"1px solid rgba(16,16,15,.08)"}}>{PR.map(p=><div key={p} style={{textAlign:"center"}}><div style={{fontSize:8.5,opacity:.42}}>{AR[p]}</div><div style={{fontSize:12.5,marginTop:5,color:next?.id===p?C.gold:C.ink,fontWeight:next?.id===p?700:500}}>{east(clean(data?.timings?.[p])||"--:--")}</div></div>)}</div>
   <div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:10,marginTop:13}}><button onClick={()=>emit("qibla")} style={{minHeight:94,border:0,borderRadius:22,padding:16,background:"rgba(255,255,255,.57)",boxShadow:"0 12px 28px rgba(16,16,15,.05)",textAlign:"right",fontFamily:"inherit",color:C.ink}}><div style={{fontSize:23,color:C.gold}}>⌖</div><div style={{fontSize:13,fontWeight:700,marginTop:12}}>اتجاه القبلة</div><div style={{fontSize:9.5,opacity:.42,marginTop:4}}>GPS + البوصلة</div></button><button onClick={()=>emit("alerts")} style={{minHeight:94,border:0,borderRadius:22,padding:16,background:"rgba(255,255,255,.57)",boxShadow:"0 12px 28px rgba(16,16,15,.05)",textAlign:"right",fontFamily:"inherit",color:C.ink}}><div style={{fontSize:23,color:C.gold}}>◔</div><div style={{fontSize:13,fontWeight:700,marginTop:12}}>المؤذن</div><div style={{fontSize:9.5,opacity:.42,marginTop:4}}>تنبيهات وأصوات الصلاة</div></button></div>
   <section style={{marginTop:25}}><div style={{display:"flex",justifyContent:"space-between",alignItems:"center"}}><div><div style={{fontSize:10,opacity:.42}}>القرآن الكريم</div><div style={{fontFamily:"Fraunces,serif",fontSize:25,marginTop:3}}>اقرأ · استمع · تدبّر</div></div><button onClick={()=>emit("quran-intelligence")} style={{border:0,background:"transparent",fontFamily:"inherit",fontSize:11,color:C.lapis}}>فتح القرآن ←</button></div><div style={{display:"grid",gridTemplateColumns:"1.15fr .85fr",gap:10,marginTop:13}}><button onClick={()=>emit("quran-player")} style={{minHeight:145,border:0,borderRadius:25,padding:18,background:"linear-gradient(145deg,#181E22,#0D1418)",color:"white",textAlign:"right",fontFamily:"inherit"}}><div style={{fontSize:25,color:"#E7D29B"}}>♪</div><div style={{fontSize:16,fontWeight:700,marginTop:37}}>مشغل القرآن</div><div style={{fontSize:9.5,opacity:.5,marginTop:5}}>قرّاء · سور · تكرار · سرعة</div></button><button onClick={()=>emit("tafsir-library")} style={{minHeight:145,border:"1px solid rgba(16,16,15,.07)",borderRadius:25,padding:18,background:"rgba(255,255,255,.5)",textAlign:"right",fontFamily:"inherit",color:C.ink}}><div style={{fontSize:25,color:C.gold}}>▥</div><div style={{fontSize:14,fontWeight:700,marginTop:37}}>التفسير</div><div style={{fontSize:9.5,opacity:.45,marginTop:5}}>مصادر حية موثقة</div></button></div></section>
   <section style={{marginTop:25}}><div style={{fontSize:10,opacity:.42}}>اختصارات</div><div style={{display:"grid",gridTemplateColumns:"repeat(3,1fr)",gap:8,marginTop:10}}>{[["nine-books","▤","الأحاديث"],["smart-quranic-adhkar","◎","الأذكار"],["daily-tools","☼","أدوات يومي"],["mosques","⌂","المساجد"],["tasbeeh","◉","المسبحة"],["profiles","♙","البروفايلات"]].map(([id,icon,label])=><button key={id} onClick={()=>emit(id)} style={{minHeight:84,border:"1px solid rgba(16,16,15,.07)",borderRadius:19,background:"rgba(255,255,255,.44)",fontFamily:"inherit",color:C.ink}}><div style={{fontSize:20,color:C.gold}}>{icon}</div><div style={{fontSize:10.5,fontWeight:650,marginTop:8}}>{label}</div></button>)}</div></section>
  </div>
 </div>
}
