import React,{useEffect,useState} from "react";
import SakinahSevenDock from "./SakinahSevenDock.jsx";
import {TrustedDailyHub} from "./trustedDaily.jsx";
import QuranicDuasCenter from "./QuranicDuasCenter.jsx";
import SmartAdhkarCenter from "./SmartAdhkarCenter.jsx";
import SeerahStoriesCenter from "./SeerahStoriesCenter.jsx";
import {KidsWorldHub,KidsQuizLive} from "./kidsWorld.jsx";
import KidsQuranStories from "./KidsQuranStories.jsx";
import QuranTeacherLive from "./QuranTeacherLive.jsx";
import {KidsNasheedsLive} from "./kidsNasheeds.jsx";
import {OfflineBackupCenter} from "./offlineBackup.jsx";
import {DailyReflection} from "./dailyReflection.jsx";
import NamesOfAllahPremium from "./NamesOfAllahPremium.jsx";
import NineBooksCenter from "./NineBooksCenter.jsx";
import {LiveTafsir} from "./liveTafsir.jsx";
import {LiveSunnahAdhkar} from "./liveSunnahAdhkar.jsx";
import {LiveWorshipTimes} from "./liveWorshipTimes.jsx";
import {DailyToolsHub,FastingCenter,RamadanCenter,SmartKhatmah,MemorizationCenter,JumuahCenter,ParentalControls,PrivacyLock} from "./dailySuite.jsx";
import IslamicCalendarCenter from "./IslamicCalendarCenter.jsx";
import PremiumCardMaker from "./PremiumCardMaker.jsx";
import {SmartMyDay} from "./smartMyDay.jsx";
import PrayerJournal from "./PrayerJournal.jsx";
import {UniversalIslamicSearch,SavedLibrary} from "./searchLibrary.jsx";
import {SmartQuranAnalytics} from "./quranAnalytics.jsx";
import {QuranIntelligenceHub,QuranTopicExplorer,QuranWordCompare,QuranEntityMap,QuranRootExplorer,TadabburAyah} from "./quranInsights.jsx";
import {LiveQuranAudio} from "./liveAudio.jsx";
import QuranToolsPremium from "./QuranToolsPremium.jsx";
import QuranCenter from "./QuranCenter.jsx";
import {NotesNotebook,AccountsNotebook} from "./personalNotebooks.jsx";
import {ZakatCenter} from "./worshipUtilities.jsx";
import QiblaPro from "./QiblaPro.jsx";
import NearbyMosquesPro from "./NearbyMosquesPro.jsx";
import ManasikGuide from "./ManasikGuide.jsx";
import {UnifiedProfiles} from "./devotionSuite.jsx";
import PrayerLearningCenter from "./PrayerLearningCenter.jsx";
import ModernTasbeeh from "./ModernTasbeeh.jsx";
import {NativeDailyCenter} from "./nativeDaily.jsx";
import WidgetCenter from "./WidgetCenter.jsx";
import {AdhanAudioSettings} from "./adhanAudioSettings.jsx";

const CLOSE_ROUTES=new Set([null,"","app","home","discover","profile","me","profiles-center"]);
const ALLOWED=new Set(["daily-tools","daily-reflection","trusted-daily","quranic-duas","smart-quranic-adhkar","sourced-seerah","kids-world","kids-home","kids-quran-live","kids-quiz-live","kids-nasheeds","kids-sourced-stories","offline-backup","islamic-calendar","fasting-center","ramadan-center","smart-khatmah","memorization-center","names-live","hisn-center","jumuah-center","worship-times","parental-controls","privacy-lock","card-maker","islamic-search","saved-library","quran-analytics","quran-intelligence","quran-topics","quran-compare","quran-entities","quran-roots","tadabbur-ayah","my-day","prayer-journal","quran-player","quran-mushaf","quran-audio","quran-teacher","nine-books","tafsir-library","notes","accounts","profiles","qibla","mosques","zakat","manasik","tasbeeh","guide","alerts","adhan-audio","widget"]);
export default function SakinahAllFeaturesLayer({children}){
 const [feature,setFeature]=useState(null),lang="ar";
 const open=to=>{if(CLOSE_ROUTES.has(to)){setFeature(null);return}if(to==="quran-home")to="quran-player";if(to==="quran-search")to="islamic-search";if(to==="live-names")to="names-live";if(to==="dua-library")to="quranic-duas";if(to==="travel-mode")to="alerts";setFeature(ALLOWED.has(to)?to:null)};
 useEffect(()=>{const h=e=>open(e.detail||null);window.addEventListener("sakinah:feature",h);return()=>window.removeEventListener("sakinah:feature",h)},[]);
 useEffect(()=>{const h=()=>setFeature(null);window.addEventListener("sakinah-profile-change",h);window.addEventListener("sakinah:global-root",h);return()=>{window.removeEventListener("sakinah-profile-change",h);window.removeEventListener("sakinah:global-root",h)}},[]);
 const close=()=>setFeature(null),go=open;
 const screens={"daily-tools":<DailyToolsHub lang={lang} go={go}/>,"daily-reflection":<DailyReflection lang={lang} go={go}/>,"trusted-daily":<TrustedDailyHub lang={lang} go={go}/>,"quranic-duas":<QuranicDuasCenter/>,"smart-quranic-adhkar":<SmartAdhkarCenter/>,"sourced-seerah":<SeerahStoriesCenter/>,"kids-sourced-stories":<KidsQuranStories go={go}/>,"kids-world":<KidsWorldHub lang={lang} go={go}/>,"kids-home":<KidsWorldHub lang={lang} go={go}/>,"kids-quran-live":<QuranTeacherLive go={go} back="kids-home"/>,"quran-teacher":<QuranTeacherLive go={go} learningOnly back="quran-player"/>,"kids-quiz-live":<KidsQuizLive lang={lang} go={go}/>,"kids-nasheeds":<KidsNasheedsLive lang={lang} go={go}/>,"offline-backup":<OfflineBackupCenter lang={lang} go={go}/>,"islamic-calendar":<IslamicCalendarCenter/>,"fasting-center":<FastingCenter lang={lang} go={go}/>,"ramadan-center":<RamadanCenter lang={lang} go={go}/>,"smart-khatmah":<SmartKhatmah lang={lang} go={go}/>,"memorization-center":<MemorizationCenter lang={lang} go={go}/>,"names-live":<NamesOfAllahPremium go={go}/>,"hisn-center":<LiveSunnahAdhkar go={go}/>,"jumuah-center":<JumuahCenter lang={lang} go={go}/>,"worship-times":<LiveWorshipTimes go={go}/>,"parental-controls":<ParentalControls lang={lang} go={go}/>,"privacy-lock":<PrivacyLock lang={lang} go={go}/>,"card-maker":<PremiumCardMaker lang={lang} go={go}/>,"islamic-search":<UniversalIslamicSearch lang={lang} go={go}/>,"saved-library":<SavedLibrary lang={lang} go={go}/>,"quran-analytics":<SmartQuranAnalytics lang={lang} go={go}/>,"quran-intelligence":<QuranIntelligenceHub lang={lang} go={go}/>,"quran-topics":<QuranTopicExplorer lang={lang} go={go}/>,"quran-compare":<QuranWordCompare lang={lang} go={go}/>,"quran-entities":<QuranEntityMap lang={lang} go={go}/>,"quran-roots":<QuranRootExplorer lang={lang} go={go}/>,"tadabbur-ayah":<TadabburAyah lang={lang} go={go}/>,"my-day":<SmartMyDay lang={lang} go={go}/>,"prayer-journal":<PrayerJournal go={go}/>,"quran-player":<QuranToolsPremium go={go}/>,"quran-mushaf":<QuranCenter/>,"quran-audio":<LiveQuranAudio lang={lang} go={go}/>,"nine-books":<NineBooksCenter/>,"tafsir-library":<LiveTafsir lang={lang} go={go}/>,"notes":<NotesNotebook lang={lang} go={close}/>,"accounts":<AccountsNotebook lang={lang} go={close}/>,"profiles":<UnifiedProfiles lang={lang} go={close}/>,"qibla":<QiblaPro/>,"mosques":<NearbyMosquesPro/>,"zakat":<ZakatCenter lang={lang} go={close}/>,"manasik":<ManasikGuide/>,"tasbeeh":<ModernTasbeeh lang={lang} go={close}/>,"guide":<PrayerLearningCenter/>,"alerts":<NativeDailyCenter lang={lang} go={close}/>,"adhan-audio":<AdhanAudioSettings lang={lang} go={close}/>,"widget":<WidgetCenter lang={lang}/>};
 if(!feature)return children||<SakinahSevenDock/>;
 return <div className="global-feature-shell" data-feature={feature} style={{minHeight:"100vh",position:"relative"}} dir="rtl">{screens[feature]||null}</div>;
}
