import React,{useEffect,useMemo,useState} from "react";

const C={ivory:"#F6F3EC",ink:"#10100F",lapis:"#173B57",gold:"#B59A62"};
const PR=["Fajr","Dhuhr","Asr","Maghrib","Isha"];
const AR={Fajr:"الفجر",Dhuhr:"الظهر",Asr:"العصر",Maghrib:"المغرب",Isha:"العشاء"};
const clean=v=>(v||"").split(" ")[0];
function epoch(v,dayOffset=0){const [h,m]=clean(v).split(":").map(Number);const d=new Date();d.setDate(d.getDate()+dayOffset);d.setHours(h||0,m||0,0,0);return d.getTime()}
function nextPrayer(t){if(!t)return null;const now=Date.now();for(const p of PR){const at=epoch(t[p]);if(at>now)return {id:p,time:clean(t[p]),at}}return {id:"Fajr",time:clean(t.Fajr),at:epoch(t.Fajr,1)}}
function left(ms){if(ms<=0)return "00:00";const m=Math.floor(ms/60000),h=Math.floor(m/60),mm=m%60;return `${String(h).padStart(2,"0")}:${String(mm).padStart(2,"0")}`}
function emit(id){window.dispatchEvent(new CustomEvent("sakinah:feature",{detail:id}))}
export default function SakinahLiveHome(){
 const [data,setData]=useState(null),[status,setStatus]=useState(""),[tick,setTick]=useState(Date.now());
 const load=()=>{setStatus("جاري تحديد الموقع…");if(!navigator.geolocation){setStatus("الموقع غير مدعوم على هذا الجهاز");return}navigator.geolocation.getCurrentPosition(async p=>{try{const {latitude,longitude}=p.coords;const r=await fetch(`https://api.aladhan.com/v1/timings?latitude=${latitude}&longitude=${longitude}&method=4`);if(!r.ok)throw new Error();const j=await r.json();setData(j?.data||null);setStatus("")}catch{setStatus("تعذر تحميل مواقيت الصلاة الآن")}},()=>setStatus("فعّل الموقع واسمح لسكينة بالوصول إليه"),{enableHighAccuracy:true,timeout:12000})};
 useEffect(()=>{load();const id=setInterval(()=>setTick(Date.now()),30000);return()=>clearInterval(id)},[]);
 const next=useMemo(()=>nextPrayer(data?.timings),[data,tick]);
 const date=new Intl.DateTimeFormat("ar-IQ",{weekday:"long",day:"numeric",month:"long"}).format(new Date());
 const hijri=data?.date?.hijri?.date?`${data.date.hijri.day} ${data.date.hijri.month?.ar||""} ${data.date.hijri.year}`:"";
 return <div style={{minHeight:"100vh",background:C.ivory,color:C.ink,padding:"26px 20px 118px"}} dir="rtl">
  <header style={{display:"flex",alignItems:"center",justifyContent:"space-between",gap:12}}><div><div style={{fontSize:10,letterSpacing:1.2,opacity:.42}}>SAKINAH</div><div style={{fontFamily:"Fraunces,serif",fontSize:31,marginTop:4}}>سكينة</div><div style={{fontSize:10.5,opacity:.48,marginTop:4}}>{date}{hijri?` · ${hijri}`:""}</div></div><button onClick={load} style={{width:43,height:43,borderRadius:15,border:"1px solid rgba(16,16,15,.08)",background:"rgba(255,255,255,.5)",fontSize:18}}>↻</button></header>
  <section style={{marginTop:23,padding:21,borderRadius:30,background:"linear-gradient(145deg,#173B57,#0B283B)",color:"white",boxShadow:"0 22px 55px rgba(23,59,87,.20)"}}><div style={{fontSize:10,opacity:.58}}>الصلاة القادمة</div><div style={{display:"flex",alignItems:"end",justifyContent:"space-between",gap:14,marginTop:10}}><div><div style={{fontFamily:"Fraunces,serif",fontSize:36}}>{next?AR[next.id]:"—"}</div><div style={{fontSize:11,opacity:.55,marginTop:5}}>{next?`بعد ${left(next.at-tick)}`:"بانتظار مواقيت موقعك"}</div></div><div style={{fontSize:42,color:"#E7D29B",fontWeight:600}}>{next?.time||"--:--"}</div></div>{status&&<div style={{marginTop:13,fontSize:10.5,opacity:.65}}>{status}</div>}<div style={{display:"grid",gridTemplateColumns:"repeat(5,1fr)",gap:5,marginTop:20,paddingTop:16,borderTop:"1px solid rgba(255,255,255,.12)"}}>{PR.map(p=><div key={p} style={{textAlign:"center"}}><div style={{fontSize:8.5,opacity:.5}}>{AR[p]}</div><div style={{fontSize:12.5,marginTop:5,color:next?.id===p?"#E7D29B":"white",fontWeight:next?.id===p?700:500}}>{clean(data?.timings?.[p])||"--:--"}</div></div>)}</div></section>
  <div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:10,marginTop:13}}><button onClick={()=>emit("qibla")} style={{minHeight:94,border:0,borderRadius:22,padding:16,background:"rgba(255,255,255,.57)",boxShadow:"0 12px 28px rgba(16,16,15,.05)",textAlign:"right",fontFamily:"inherit",color:C.ink}}><div style={{fontSize:23,color:C.gold}}>⌖</div><div style={{fontSize:13,fontWeight:700,marginTop:12}}>اتجاه القبلة</div><div style={{fontSize:9.5,opacity:.42,marginTop:4}}>GPS + البوصلة</div></button><button onClick={()=>emit("alerts")} style={{minHeight:94,border:0,borderRadius:22,padding:16,background:"rgba(255,255,255,.57)",boxShadow:"0 12px 28px rgba(16,16,15,.05)",textAlign:"right",fontFamily:"inherit",color:C.ink}}><div style={{fontSize:23,color:C.gold}}>◔</div><div style={{fontSize:13,fontWeight:700,marginTop:12}}>المؤذن</div><div style={{fontSize:9.5,opacity:.42,marginTop:4}}>تنبيهات وأصوات الصلاة</div></button></div>
  <section style={{marginTop:25}}><div style={{display:"flex",justifyContent:"space-between",alignItems:"center"}}><div><div style={{fontSize:10,opacity:.42}}>القرآن الكريم</div><div style={{fontFamily:"Fraunces,serif",fontSize:25,marginTop:3}}>اقرأ · استمع · تدبّر</div></div><button onClick={()=>emit("quran-intelligence")} style={{border:0,background:"transparent",fontFamily:"inherit",fontSize:11,color:C.lapis}}>فتح القرآن ←</button></div><div style={{display:"grid",gridTemplateColumns:"1.15fr .85fr",gap:10,marginTop:13}}><button onClick={()=>emit("quran-player")} style={{minHeight:145,border:0,borderRadius:25,padding:18,background:"linear-gradient(145deg,#181E22,#0D1418)",color:"white",textAlign:"right",fontFamily:"inherit"}}><div style={{fontSize:25,color:"#E7D29B"}}>♪</div><div style={{fontSize:16,fontWeight:700,marginTop:37}}>مشغل القرآن</div><div style={{fontSize:9.5,opacity:.5,marginTop:5}}>قرّاء · سور · تكرار · سرعة</div></button><button onClick={()=>emit("tafsir-library")} style={{minHeight:145,border:"1px solid rgba(16,16,15,.07)",borderRadius:25,padding:18,background:"rgba(255,255,255,.5)",textAlign:"right",fontFamily:"inherit",color:C.ink}}><div style={{fontSize:25,color:C.gold}}>▥</div><div style={{fontSize:14,fontWeight:700,marginTop:37}}>التفسير</div><div style={{fontSize:9.5,opacity:.45,marginTop:5}}>مصادر حية موثقة</div></button></div></section>
  <section style={{marginTop:25}}><div style={{fontSize:10,opacity:.42}}>اختصارات</div><div style={{display:"grid",gridTemplateColumns:"repeat(3,1fr)",gap:8,marginTop:10}}>{[["nine-books","▤","الأحاديث"],["smart-quranic-adhkar","◎","الأذكار"],["daily-tools","☼","أدوات يومي"],["mosques","⌂","المساجد"],["tasbeeh","◉","المسبحة"],["profiles","♙","البروفايلات"]].map(([id,icon,label])=><button key={id} onClick={()=>emit(id)} style={{minHeight:84,border:"1px solid rgba(16,16,15,.07)",borderRadius:19,background:"rgba(255,255,255,.44)",fontFamily:"inherit",color:C.ink}}><div style={{fontSize:20,color:C.gold}}>{icon}</div><div style={{fontSize:10.5,fontWeight:650,marginTop:8}}>{label}</div></button>)}</div></section>
 </div>
}
