import React,{useEffect,useMemo,useState} from "react";

const C={ivory:"#F6F3EC",ink:"#10100F",lapis:"#173B57",gold:"#B59A62"};
const profile=()=>{try{return localStorage.getItem("sakinah-active-profile")||"me"}catch{return "me"}};
const libKey=()=>`sakinah-library-${profile()}`;
const readLib=()=>{try{return JSON.parse(localStorage.getItem(libKey())||"[]")}catch{return []}};
const saveLib=x=>{try{localStorage.setItem(libKey(),JSON.stringify(x))}catch{}};
const btn={border:"1px solid rgba(16,16,15,.09)",borderRadius:14,padding:11,background:"transparent",fontFamily:"inherit",color:"inherit"};
function Shell({lang,go,titleAr,titleEn,subAr,subEn,children}){return <div style={{position:"absolute",inset:0,background:C.ivory,color:C.ink,display:"flex",flexDirection:"column"}}><div style={{padding:"22px 22px 0"}}><button onClick={()=>go("app")} style={{...btn,border:0,padding:0}}>{lang==="ar"?"← سكينة":"← Sakinah"}</button></div><div style={{flex:1,overflowY:"auto",padding:"15px 22px 130px"}}><div style={{fontFamily:"Fraunces,serif",fontSize:29}}>{lang==="ar"?titleAr:titleEn}</div><div style={{fontSize:11.5,opacity:.48,lineHeight:1.7,marginTop:7}}>{lang==="ar"?subAr:subEn}</div>{children}</div></div>}
function normalizeSearch(data){const rows=data?.data?.matches||data?.data||[];return Array.isArray(rows)?rows:[]}
export function UniversalIslamicSearch({lang,go}){
 const [q,setQ]=useState(""),[busy,setBusy]=useState(false),[rows,setRows]=useState([]),[error,setError]=useState("");
 const [library,setLibrary]=useState(readLib);
 const search=async()=>{const text=q.trim();if(!text)return;setBusy(true);setError("");try{const r=await fetch(`https://api.alquran.cloud/v1/search/${encodeURIComponent(text)}/all/quran-uthmani`);if(!r.ok)throw new Error();const j=await r.json();setRows(normalizeSearch(j).slice(0,80))}catch{setError(lang==="ar"?"تعذر البحث الآن. تحقق من الاتصال وحاول مجدداً.":"Search is unavailable right now. Check your connection and retry.")}finally{setBusy(false)}};
 const add=item=>{const key=item.number??item.numberInSurah??`${item.surah?.number||0}:${item.numberInSurah||0}:${item.text}`;if(library.some(x=>x.key===String(key)))return;const x=[{key:String(key),type:"quran",text:item.text||"",surah:item.surah?.name||"",surahEn:item.surah?.englishName||"",ayah:item.numberInSurah||"",savedAt:new Date().toISOString()},...library];setLibrary(x);saveLib(x)};
 const shortcuts=[["tafsir-library","التفسير الحي","Live Tafsir"],["nine-books","الأحاديث الموثقة","Verified Hadith"],["quran-intelligence","ذكاء القرآن","Quran Intelligence"],["quran-analytics","إحصاءات القرآن الذكية","Smart Quran Analytics"],["quranic-duas","الأدعية القرآنية","Quranic Duas"],["smart-quranic-adhkar","الأذكار الذكية","Smart Adhkar"],["sourced-seerah","السيرة وقصص الأنبياء","Seerah & Prophets"],["hisn-center","أذكار السنة الموثقة","Sourced Sunnah Adhkar"]];
 return <Shell lang={lang} go={go} titleAr="البحث الإسلامي الشامل" titleEn="Universal Islamic Search" subAr="بحث حي في القرآن مع وصول مباشر للتفسير والأحاديث والأدعية والأذكار والسيرة" subEn="Live Quran search with direct access to tafsir, hadith, duas, adhkar and seerah"><div style={{marginTop:18,display:"grid",gridTemplateColumns:"1fr auto",gap:8}}><input value={q} onChange={e=>setQ(e.target.value)} onKeyDown={e=>e.key==="Enter"&&search()} placeholder={lang==="ar"?"ابحث بكلمة أو عبارة قرآنية…":"Search a Quran word or phrase…"} style={{...btn,width:"100%",boxSizing:"border-box",background:"rgba(255,255,255,.5)"}}/><button onClick={search} disabled={busy} style={{...btn,background:C.lapis,color:"white",border:0,minWidth:82}}>{busy?(lang==="ar"?"بحث…":"Searching…"):(lang==="ar"?"بحث":"Search")}</button></div>{error&&<div style={{marginTop:12,fontSize:10.5,color:"#A44D3C"}}>{error}</div>}<div style={{marginTop:13,display:"grid",gridTemplateColumns:"1fr 1fr",gap:8}}>{shortcuts.map(([id,ar,en])=><button key={id} onClick={()=>go(id)} style={{...btn,textAlign:lang==="ar"?"right":"left",fontSize:11.5,background:"rgba(181,154,98,.07)"}}>{lang==="ar"?ar:en}</button>)}</div><div style={{marginTop:18}}>{rows.map((x,i)=><div key={`${x.number||i}-${x.numberInSurah||i}`} style={{padding:"14px 0",borderTop:"1px solid rgba(16,16,15,.07)"}}><div style={{display:"flex",justifyContent:"space-between",gap:10,alignItems:"start"}}><div style={{flex:1}}><div style={{fontSize:10,opacity:.45}}>{x.surah?.name||x.surah?.englishName} · {lang==="ar"?"آية":"Ayah"} {x.numberInSurah}</div><div dir="rtl" style={{fontSize:21,lineHeight:2.05,marginTop:7,fontFamily:"'Amiri Quran','Noto Naskh Arabic',serif"}}>{x.text}</div></div><button onClick={()=>add(x)} title={lang==="ar"?"حفظ":"Save"} style={{...btn,padding:"7px 9px",color:C.gold}}>♡</button></div></div>)}</div></Shell>}

export function SavedLibrary({lang,go}){
 const [rows,setRows]=useState(readLib),[q,setQ]=useState("");
 useEffect(()=>setRows(readLib()),[]);
 const shown=useMemo(()=>rows.filter(x=>(`${x.text} ${x.surah} ${x.surahEn}`).toLowerCase().includes(q.toLowerCase())),[rows,q]);
 const remove=k=>{const x=rows.filter(r=>r.key!==k);setRows(x);saveLib(x)};
 return <Shell lang={lang} go={go} titleAr="مكتبتي المحفوظة" titleEn="Saved Library" subAr="محفوظات مستقلة لكل بروفايل داخل سكينة" subEn="A separate saved library for each Sakinah profile"><input value={q} onChange={e=>setQ(e.target.value)} placeholder={lang==="ar"?"ابحث داخل محفوظاتك…":"Search your saved items…"} style={{...btn,marginTop:18,width:"100%",boxSizing:"border-box",background:"rgba(255,255,255,.45)"}}/><div style={{marginTop:12}}>{shown.length===0?<div style={{padding:"36px 8px",textAlign:"center",fontSize:11,opacity:.42}}>{lang==="ar"?"لا توجد عناصر محفوظة بعد":"Nothing saved yet"}</div>:shown.map(x=><div key={x.key} style={{padding:"14px 0",borderTop:"1px solid rgba(16,16,15,.07)"}}><div style={{display:"flex",justifyContent:"space-between",gap:12}}><div style={{flex:1}}><div style={{fontSize:10,opacity:.45}}>{x.surah||x.surahEn} {x.ayah?`· ${lang==="ar"?"آية":"Ayah"} ${x.ayah}`:""}</div><div dir="rtl" style={{fontSize:20,lineHeight:1.95,marginTop:6,fontFamily:"'Amiri Quran','Noto Naskh Arabic',serif"}}>{x.text}</div></div><button onClick={()=>remove(x.key)} style={{...btn,padding:"7px 9px",opacity:.55}}>×</button></div></div>)}</div><button onClick={()=>go("islamic-search")} style={{...btn,width:"100%",marginTop:15,background:C.lapis,color:"white",border:0}}>{lang==="ar"?"فتح البحث الإسلامي":"Open Islamic Search"}</button></Shell>}
