import React,{useEffect,useMemo,useState} from "react";

const C={ivory:"#F6F3EC",ink:"#10100F",lapis:"#173B57",gold:"#B59A62",green:"#4F915C"};
const profile=()=>{try{return localStorage.getItem("sakinah-active-profile")||"me"}catch{return"me"}};
const read=(k,d)=>{try{const v=localStorage.getItem(k);return v==null?d:JSON.parse(v)}catch{return d}};
const write=(k,v)=>{try{localStorage.setItem(k,JSON.stringify(v))}catch{}};
const key=n=>`sakinah-${n}-${profile()}`;
const btn={border:"1px solid rgba(16,16,15,.09)",borderRadius:14,padding:11,background:"transparent",fontFamily:"inherit",color:"inherit"};
const PRAYERS=[["Fajr","الفجر"],["Dhuhr","الظهر"],["Asr","العصر"],["Maghrib","المغرب"],["Isha","العشاء"]];
function toMin(x){if(!x)return null;const m=String(x).match(/(\d{1,2}):(\d{2})/);return m?Number(m[1])*60+Number(m[2]):null}
function nextPrayer(t){if(!t)return null;const now=new Date(),mins=now.getHours()*60+now.getMinutes();for(const[en,ar]of PRAYERS){const m=toMin(t[en]);if(m!=null&&m>=mins)return{en,ar,time:t[en],mins:m-mins}}return{en:"Fajr",ar:"الفجر",time:t.Fajr,mins:(24*60-mins)+(toMin(t.Fajr)||0)}}
function hijriParts(){try{const f=new Intl.DateTimeFormat("en-u-ca-islamic",{day:"numeric",month:"numeric",year:"numeric"});return Object.fromEntries(f.formatToParts(new Date()).filter(x=>["day","month","year"].includes(x.type)).map(x=>[x.type,Number(x.value)]))}catch{return{}}}
function Progress({value}){return <div style={{height:8,borderRadius:8,background:"rgba(16,16,15,.07)",overflow:"hidden"}}><div style={{height:"100%",width:`${Math.max(0,Math.min(100,value))}%`,background:C.gold}}/></div>}
function Card({item,go}){return <button onClick={()=>go(item.id)} style={{...btn,minHeight:82,padding:"13px 12px",textAlign:"right",display:"flex",gap:11,alignItems:"center",width:"100%"}}><span style={{width:36,height:36,borderRadius:12,border:"1px solid rgba(16,16,15,.08)",display:"grid",placeItems:"center",fontSize:16,flex:"0 0 auto"}}>{item.icon}</span><span><b style={{display:"block",fontSize:12.5}}>{item.ar}</b><small style={{display:"block",fontSize:9.5,opacity:.42,marginTop:3}}>{item.sub}</small></span></button>}
export function SmartMyDay({go}){
 const [timings,setTimings]=useState(()=>{try{return JSON.parse(localStorage.getItem("sakinah-prayer-times")||"null")}catch{return null}}),[locState,setLocState]=useState("idle");
 const dayKey=new Date().toISOString().slice(0,10),doneKey=key(`myday-${dayKey}`),[done,setDone]=useState(()=>read(doneKey,{}));
 const hijri=useMemo(hijriParts,[]),isFriday=new Date().getDay()===5,isRamadan=hijri.month===9,isWhite=[13,14,15].includes(hijri.day);
 const khatmahPage=read(key("khatmah-page"),1),khatmahDays=read(key("khatmah-days"),30),portion=Math.max(1,Math.ceil((604-khatmahPage+1)/Math.max(1,khatmahDays)));
 useEffect(()=>{if(!navigator.geolocation)return;setLocState("loading");navigator.geolocation.getCurrentPosition(async p=>{try{const r=await fetch(`https://api.aladhan.com/v1/timings?latitude=${p.coords.latitude}&longitude=${p.coords.longitude}&method=4`);if(!r.ok)throw 0;const x=await r.json(),t=x.data?.timings||null;setTimings(t);if(t)localStorage.setItem("sakinah-prayer-times",JSON.stringify(t));setLocState("ok")}catch{setLocState("offline")}},()=>setLocState("denied"),{enableHighAccuracy:false,timeout:10000,maximumAge:600000})},[]);
 const next=nextPrayer(timings),hour=new Date().getHours(),dhikr=hour<12?"أذكار الصباح":hour>=17?"أذكار المساء":"ذكر مناسب الآن";
 const items=[...(isFriday?[{id:"jumuah-center",ar:"برنامج الجمعة اليوم",icon:"⌁"}]:[]),...(isRamadan?[{id:"ramadan-center",ar:"برنامج رمضان اليوم",icon:"☾"}]:[]),...(isWhite?[{id:"fasting-center",ar:"اليوم من الأيام البيض",icon:"☽"}]:[]),{id:"daily-reflection",ar:"تأمّل اليوم",icon:"◌"},{id:"smart-khatmah",ar:`ورد القرآن · ${portion} صفحة`,icon:"◈"},{id:"smart-quranic-adhkar",ar:dhikr,icon:"✦"},{id:"worship-times",ar:"أوقات العبادة",icon:"◷"}];
 const mark=id=>{const x={...done,[id]:!done[id]};setDone(x);write(doneKey,x)},complete=items.filter(x=>done[x.id]).length;
 const date=new Date().toLocaleDateString("ar-IQ",{weekday:"long",day:"numeric",month:"long",year:"numeric"});
 const services=[{id:"prayer-journal",ar:"سجل الصلاة",sub:"متابعة أسبوعية للصلاة",icon:"✓"},{id:"travel-mode",ar:"السفر والتنبيهات",sub:"تحديث الموقع وتنبيه قبل الصلاة",icon:"⌖"},{id:"alerts",ar:"المؤذن والتنبيهات",sub:"الأذان والجدولة والفحص",icon:"◷"},{id:"qibla",ar:"القبلة",sub:"اتجاه الكعبة بالشمال الحقيقي",icon:"◆"},{id:"mosques",ar:"أقرب مسجد",sub:"المساجد القريبة منك",icon:"⌂"},{id:"hisn-center",ar:"حصن المسلم",sub:"أذكار اليوم والليلة",icon:"◇"}];
 return <div dir="rtl" style={{position:"absolute",inset:0,background:C.ivory,color:C.ink,overflowY:"auto"}}><main style={{maxWidth:720,margin:"0 auto",padding:"70px 22px 135px"}}><div style={{textAlign:"center"}}><div style={{fontSize:10,color:C.gold,letterSpacing:.8}}>MUSLIM MIRROR</div><h1 style={{fontSize:30,margin:"4px 0"}}>يومي الإسلامي</h1><div style={{fontSize:11.5,opacity:.48}}>{date}</div></div>
 <section style={{marginTop:18,borderRadius:26,padding:19,background:"linear-gradient(135deg,rgba(181,154,98,.18),rgba(255,255,255,.58))",border:"1px solid rgba(181,154,98,.14)"}}><div style={{display:"flex",justifyContent:"space-between",gap:14}}><div><small style={{opacity:.45}}>الصلاة القادمة</small><div style={{fontSize:26,marginTop:5}}>{next?next.ar:"تحديد الموقع…"}</div>{next&&<div style={{fontSize:11,opacity:.55,marginTop:4}}>{next.time} · {next.mins} دقيقة</div>}</div><button onClick={()=>go("alerts")} style={{...btn,padding:"8px 10px",fontSize:10}}>التنبيهات</button></div><div style={{fontSize:9.5,opacity:.38,marginTop:10}}>{locState==="offline"?"يتم استخدام آخر مواقيت محفوظة":locState==="denied"?"إذن الموقع غير مفعّل":"GPS"}</div></section>
 <div style={{marginTop:12,display:"grid",gridTemplateColumns:"repeat(3,1fr)",gap:8}}><div style={{...btn}}><small style={{opacity:.42}}>ورد اليوم</small><b style={{display:"block",fontSize:18,marginTop:5}}>{portion}</b></div><div style={{...btn}}><small style={{opacity:.42}}>إنجاز اليوم</small><b style={{display:"block",fontSize:18,marginTop:5}}>{complete}/{items.length}</b></div><button onClick={()=>go("prayer-journal")} style={{...btn,textAlign:"right"}}><small style={{opacity:.42}}>سجل الصلاة</small><b style={{display:"block",fontSize:14,marginTop:6}}>افتح السجل ›</b></button></div>
 <div style={{marginTop:16}}><Progress value={items.length?complete/items.length*100:0}/></div><div style={{marginTop:10}}>{items.map(item=><div key={item.id} style={{display:"grid",gridTemplateColumns:"42px 1fr auto",gap:10,alignItems:"center",padding:"12px 0",borderTop:"1px solid rgba(16,16,15,.07)"}}><button onClick={()=>mark(item.id)} style={{width:36,height:36,borderRadius:13,border:"1px solid rgba(16,16,15,.08)",background:done[item.id]?"rgba(79,145,92,.14)":"transparent",fontFamily:"inherit"}}>{done[item.id]?"✓":item.icon}</button><button onClick={()=>go(item.id)} style={{border:0,background:"transparent",fontFamily:"inherit",textAlign:"right",color:"inherit",fontSize:13,fontWeight:650}}>{item.ar}</button><span style={{opacity:.28}}>›</span></div>)}</div>
 <h2 style={{fontSize:16,margin:"22px 0 10px"}}>أدوات يومية ذكية</h2><div style={{display:"grid",gridTemplateColumns:"repeat(2,minmax(0,1fr))",gap:8}}>{services.map(x=><Card key={x.id} item={x} go={go}/>)}</div><button onClick={()=>go("daily-tools")} style={{...btn,width:"100%",marginTop:10}}>كل الأدوات اليومية ›</button></main></div>
}
