import React,{useEffect,useMemo,useState} from "react";

const C={ivory:"#F6F3EC",ink:"#10100F",lapis:"#173B57",gold:"#B59A62",green:"#4F915C"};
const profile=()=>{try{return localStorage.getItem("sakinah-active-profile")||"me"}catch{return"me"}};
const read=(k,d)=>{try{const v=localStorage.getItem(k);return v==null?d:JSON.parse(v)}catch{return d}};
const write=(k,v)=>{try{localStorage.setItem(k,JSON.stringify(v))}catch{}};
const key=n=>`sakinah-${n}-${profile()}`;
const btn={border:"1px solid rgba(16,16,15,.09)",borderRadius:14,padding:11,background:"transparent",fontFamily:"inherit",color:"inherit"};
const PRAYERS=[["Fajr","الفجر"],["Dhuhr","الظهر"],["Asr","العصر"],["Maghrib","المغرب"],["Isha","العشاء"]];
function toMin(x){if(!x)return null;const m=String(x).match(/(\d{1,2}):(\d{2})/);return m?Number(m[1])*60+Number(m[2]):null}
function nextPrayer(t){if(!t)return null;const now=new Date(),mins=now.getHours()*60+now.getMinutes();for(const[en,ar]of PRAYERS){const m=toMin(t[en]);if(m!=null&&m>=mins)return{en,ar,time:t[en],mins:m-mins}}return{en:"Fajr",ar:"الفجر",time:t.Fajr,mins:(24*60-mins)+(toMin(t.Fajr)||0)}}
function hijriParts(){try{const f=new Intl.DateTimeFormat("en-u-ca-islamic",{day:"numeric",month:"numeric",year:"numeric"});return Object.fromEntries(f.formatToParts(new Date()).filter(x=>["day","month","year"].includes(x.type)).map(x=>[x.type,Number(x.value)]))}catch{return{}}}
function Progress({value}){return <div style={{height:8,borderRadius:8,background:"rgba(16,16,15,.07)",overflow:"hidden"}}><div style={{height:"100%",width:`${Math.max(0,Math.min(100,value))}%`,background:C.gold}}/></div>}

function Icon({kind,done=false}){
 const common={width:23,height:23,viewBox:"0 0 24 24",fill:"none",stroke:done?C.green:"#9A8B6A",strokeWidth:1.45,strokeLinecap:"round",strokeLinejoin:"round"};
 if(done)return <svg {...common}><path d="m6.8 12.3 3.1 3.1 7.3-7.6"/></svg>;
 if(kind==="friday")return <svg {...common}><path d="M5 6h14v13H5zM8 4v4M16 4v4M5 9.5h14M8 13h8M8 16h5"/><path stroke={C.gold} d="M16.5 15.5h1.8"/></svg>;
 if(kind==="reflection")return <svg {...common}><circle cx="12" cy="12" r="7.2"/><path d="M8.5 13c1.7-2.8 4.7-4 7.2-2.7M9.2 16c1.6.7 3.2.8 4.8.2"/><path stroke={C.gold} d="M12 3v2"/></svg>;
 if(kind==="quran")return <svg {...common}><path d="M4.5 5.6c2.8-.8 5.3-.3 7.5 1.4v12c-2.3-1.3-4.8-1.7-7.5-1zM19.5 5.6c-2.8-.8-5.3-.3-7.5 1.4v12c2.3-1.3 4.8-1.7 7.5-1z"/><path stroke={C.gold} d="M12 7v12"/></svg>;
 if(kind==="adhkar")return <svg {...common}><circle cx="12" cy="12" r="5"/><path d="M12 2.5V5M12 19v2.5M2.5 12H5M19 12h2.5M5.4 5.4 7 7M17 17l1.6 1.6M18.6 5.4 17 7M7 17l-1.6 1.6"/><path stroke={C.gold} d="M9.2 12.2h5.6"/></svg>;
 if(kind==="time")return <svg {...common}><circle cx="12" cy="12" r="7.8"/><path d="M12 7v5l3.4 2"/><path stroke={C.gold} d="M12 2.5V4"/></svg>;
 if(kind==="journal")return <svg {...common}><rect x="4.5" y="4" width="15" height="16" rx="3"/><path d="M8 9h8M8 13h5"/><path stroke={C.gold} d="m13.8 16 1.4 1.4 2.8-3.2"/></svg>;
 if(kind==="travel")return <svg {...common}><path d="M5 15.5 19 12 5 8.5l2.2 3.5zM7.2 12H14"/><circle stroke={C.gold} cx="17.5" cy="6" r="1.5"/></svg>;
 if(kind==="bell")return <svg {...common}><path d="M7 17h10l-1.4-2.1V10a3.6 3.6 0 0 0-7.2 0v4.9zM9.8 19c.6 1.1 1.3 1.5 2.2 1.5s1.6-.4 2.2-1.5"/><path stroke={C.gold} d="M12 4V2.5"/></svg>;
 if(kind==="qibla")return <svg {...common}><circle cx="12" cy="12" r="7.8"/><path d="m14.8 7.2-1.7 5.9-5.9 1.7 1.7-5.9z"/><circle fill={C.gold} stroke="none" cx="12" cy="12" r="1"/></svg>;
 if(kind==="mosque")return <svg {...common}><path d="M5 19v-8h14v8M7.5 11V8.8a4.5 4.5 0 0 1 9 0V11M10 19v-4h4v4"/><path stroke={C.gold} d="M12 3.5V2"/></svg>;
 if(kind==="hisn")return <svg {...common}><path d="M6 4.5h12v15H6zM9 8.5h6M9 12h6M9 15.5h4"/><path stroke={C.gold} d="M6 17.5h12"/></svg>;
 if(kind==="ramadan")return <svg {...common}><path d="M15.4 4a8.2 8.2 0 1 0 3.9 14.5A8.9 8.9 0 0 1 15.4 4z"/><path stroke={C.gold} d="m17.5 6.1.7 1.3 1.3.7-1.3.7-.7 1.3-.7-1.3-1.3-.7 1.3-.7z"/></svg>;
 if(kind==="fasting")return <svg {...common}><path d="M15.8 4.2a7.9 7.9 0 1 0 3.7 13.9 8.6 8.6 0 0 1-3.7-13.9z"/><path stroke={C.gold} d="m17.9 6.3.55 1.05 1.1.55-1.1.55-.55 1.05-.55-1.05-1.1-.55 1.1-.55z"/></svg>;
 return <svg {...common}><circle cx="12" cy="12" r="7.5"/></svg>;
}
function IconBox({kind,done=false}){return <span aria-hidden="true" style={{width:44,height:44,borderRadius:15,border:"1px solid rgba(16,16,15,.08)",display:"grid",placeItems:"center",background:done?"rgba(79,145,92,.09)":"rgba(255,255,255,.28)",flex:"0 0 auto"}}><Icon kind={kind} done={done}/></span>}
function Card({item,go}){return <button onClick={()=>go(item.id)} style={{...btn,minHeight:94,padding:"14px",textAlign:"right",display:"flex",gap:12,alignItems:"center",width:"100%",background:"rgba(255,255,255,.30)"}}><IconBox kind={item.kind}/><span style={{minWidth:0}}><b style={{display:"block",fontSize:12.5,fontWeight:600}}>{item.ar}</b><small style={{display:"block",fontSize:9.5,opacity:.42,marginTop:4,lineHeight:1.65}}>{item.sub}</small></span></button>}

export function SmartMyDay({go}){
 const [timings,setTimings]=useState(()=>{try{return JSON.parse(localStorage.getItem("sakinah-prayer-times")||"null")}catch{return null}}),[locState,setLocState]=useState("idle");
 const dayKey=new Date().toISOString().slice(0,10),doneKey=key(`myday-${dayKey}`),[done,setDone]=useState(()=>read(doneKey,{}));
 const hijri=useMemo(hijriParts,[]),isFriday=new Date().getDay()===5,isRamadan=hijri.month===9,isWhite=[13,14,15].includes(hijri.day);
 const khatmahPage=read(key("khatmah-page"),1),khatmahDays=read(key("khatmah-days"),30),portion=Math.max(1,Math.ceil((604-khatmahPage+1)/Math.max(1,khatmahDays)));
 useEffect(()=>{if(!navigator.geolocation)return;setLocState("loading");navigator.geolocation.getCurrentPosition(async p=>{try{const r=await fetch(`https://api.aladhan.com/v1/timings?latitude=${p.coords.latitude}&longitude=${p.coords.longitude}&method=4`);if(!r.ok)throw 0;const x=await r.json(),t=x.data?.timings||null;setTimings(t);if(t)localStorage.setItem("sakinah-prayer-times",JSON.stringify(t));setLocState("ok")}catch{setLocState("offline")}},()=>setLocState("denied"),{enableHighAccuracy:false,timeout:10000,maximumAge:600000})},[]);
 const next=nextPrayer(timings),hour=new Date().getHours(),dhikr=hour<12?"أذكار الصباح":hour>=17?"أذكار المساء":"ذكر مناسب الآن";
 const items=[...(isFriday?[{id:"jumuah-center",ar:"برنامج الجمعة اليوم",kind:"friday"}]:[]),...(isRamadan?[{id:"ramadan-center",ar:"برنامج رمضان اليوم",kind:"ramadan"}]:[]),...(isWhite?[{id:"fasting-center",ar:"اليوم من الأيام البيض",kind:"fasting"}]:[]),{id:"daily-reflection",ar:"تأمّل اليوم",kind:"reflection"},{id:"smart-khatmah",ar:`ورد القرآن · ${portion} صفحة`,kind:"quran"},{id:"smart-quranic-adhkar",ar:dhikr,kind:"adhkar"},{id:"worship-times",ar:"أوقات العبادة",kind:"time"}];
 const mark=id=>{const x={...done,[id]:!done[id]};setDone(x);write(doneKey,x)},complete=items.filter(x=>done[x.id]).length;
 const date=new Date().toLocaleDateString("ar-IQ",{weekday:"long",day:"numeric",month:"long",year:"numeric"});
 const services=[{id:"prayer-journal",ar:"سجل الصلاة",sub:"متابعة أسبوعية للصلاة",kind:"journal"},{id:"travel-mode",ar:"السفر والتنبيهات",sub:"تحديث الموقع وتنبيه قبل الصلاة",kind:"travel"},{id:"alerts",ar:"المؤذن والتنبيهات",sub:"الأذان والجدولة والفحص",kind:"bell"},{id:"qibla",ar:"القبلة",sub:"اتجاه الكعبة بالشمال الحقيقي",kind:"qibla"},{id:"mosques",ar:"أقرب مسجد",sub:"المساجد القريبة منك",kind:"mosque"},{id:"hisn-center",ar:"حصن المسلم",sub:"أذكار اليوم والليلة",kind:"hisn"}];
 return <div data-smart-my-day="true" dir="rtl" style={{position:"absolute",inset:0,background:C.ivory,color:C.ink,overflowY:"auto"}}><main style={{maxWidth:720,margin:"0 auto",padding:"70px 22px 135px"}}><div style={{textAlign:"center"}}><div style={{fontSize:10,color:C.gold,letterSpacing:.8}}>MUSLIM MIRROR</div><h1 style={{fontSize:30,margin:"4px 0"}}>يومي الإسلامي</h1><div style={{fontSize:11.5,opacity:.48}}>{date}</div></div>
 <section style={{marginTop:18,borderRadius:26,padding:19,background:"linear-gradient(135deg,rgba(181,154,98,.18),rgba(255,255,255,.58))",border:"1px solid rgba(181,154,98,.14)"}}><div style={{display:"flex",justifyContent:"space-between",gap:14}}><div><small style={{opacity:.45}}>الصلاة القادمة</small><div style={{fontSize:26,marginTop:5}}>{next?next.ar:"تحديد الموقع…"}</div>{next&&<div style={{fontSize:11,opacity:.55,marginTop:4}}>{next.time} · {next.mins} دقيقة</div>}</div><button onClick={()=>go("alerts")} style={{...btn,padding:"8px 10px",fontSize:10}}>التنبيهات</button></div><div style={{fontSize:9.5,opacity:.38,marginTop:10}}>{locState==="offline"?"يتم استخدام آخر مواقيت محفوظة":locState==="denied"?"إذن الموقع غير مفعّل":"GPS"}</div></section>
 <div style={{marginTop:12,display:"grid",gridTemplateColumns:"repeat(3,1fr)",gap:8}}><div style={{...btn}}><small style={{opacity:.42}}>ورد اليوم</small><b style={{display:"block",fontSize:18,marginTop:5}}>{portion}</b></div><div style={{...btn}}><small style={{opacity:.42}}>إنجاز اليوم</small><b style={{display:"block",fontSize:18,marginTop:5}}>{complete}/{items.length}</b></div><button onClick={()=>go("prayer-journal")} style={{...btn,textAlign:"right"}}><small style={{opacity:.42}}>سجل الصلاة</small><b style={{display:"block",fontSize:14,marginTop:6}}>افتح السجل ›</b></button></div>
 <div style={{marginTop:16}}><Progress value={items.length?complete/items.length*100:0}/></div><div style={{marginTop:10}}>{items.map(item=><div key={item.id} style={{display:"grid",gridTemplateColumns:"52px minmax(0,1fr) 18px",gap:10,alignItems:"center",padding:"10px 0",borderTop:"1px solid rgba(16,16,15,.07)"}}><button aria-label={`تحديد ${item.ar}`} onClick={()=>mark(item.id)} style={{width:44,height:44,padding:0,border:0,background:"transparent",fontFamily:"inherit",display:"grid",placeItems:"center"}}><IconBox kind={item.kind} done={!!done[item.id]}/></button><button onClick={()=>go(item.id)} style={{border:0,background:"transparent",fontFamily:"inherit",textAlign:"right",color:"inherit",fontSize:13,fontWeight:600,minWidth:0}}>{item.ar}</button><span aria-hidden="true" style={{opacity:.28,fontSize:16}}>‹</span></div>)}</div>
 <h2 style={{fontSize:16,margin:"22px 0 10px"}}>أدوات يومية ذكية</h2><div style={{display:"grid",gridTemplateColumns:"repeat(2,minmax(0,1fr))",gap:8}}>{services.map(x=><Card key={x.id} item={x} go={go}/>)}</div><button onClick={()=>go("daily-tools")} style={{...btn,width:"100%",marginTop:10}}>كل الأدوات اليومية ›</button></main></div>
}
