import React,{useMemo,useState} from "react";

const C={ivory:"#F6F3EC",ink:"#10100F",lapis:"#173B57",gold:"#B59A62",green:"#416F5A",soft:"#EEE7D8"};
const ar=n=>String(n).replace(/[0-9]/g,d=>"٠١٢٣٤٥٦٧٨٩"[d]);
const GROUPS={
 morning:{label:"الصباح",sub:"ورد صباحي يجمع آيات وأذكاراً ثابتة مع عدد التكرار.",items:[
  {title:"آية الكرسي",type:"قرآن",source:"البقرة ٢:٢٥٥",count:1,text:"اللَّهُ لَا إِلَٰهَ إِلَّا هُوَ الْحَيُّ الْقَيُّومُ ۚ لَا تَأْخُذُهُ سِنَةٌ وَلَا نَوْمٌ ۚ لَهُ مَا فِي السَّمَاوَاتِ وَمَا فِي الْأَرْضِ ۗ مَنْ ذَا الَّذِي يَشْفَعُ عِنْدَهُ إِلَّا بِإِذْنِهِ ۚ يَعْلَمُ مَا بَيْنَ أَيْدِيهِمْ وَمَا خَلْفَهُمْ ۖ وَلَا يُحِيطُونَ بِشَيْءٍ مِنْ عِلْمِهِ إِلَّا بِمَا شَاءَ ۚ وَسِعَ كُرْسِيُّهُ السَّمَاوَاتِ وَالْأَرْضَ ۖ وَلَا يَئُودُهُ حِفْظُهُمَا ۚ وَهُوَ الْعَلِيُّ الْعَظِيمُ"},
  {title:"سورة الإخلاص",type:"قرآن",source:"الإخلاص ١١٢",count:3,text:"قُلْ هُوَ اللَّهُ أَحَدٌ ۝ اللَّهُ الصَّمَدُ ۝ لَمْ يَلِدْ وَلَمْ يُولَدْ ۝ وَلَمْ يَكُنْ لَهُ كُفُوًا أَحَدٌ"},
  {title:"سورة الفلق",type:"قرآن",source:"الفلق ١١٣",count:3,text:"قُلْ أَعُوذُ بِرَبِّ الْفَلَقِ ۝ مِنْ شَرِّ مَا خَلَقَ ۝ وَمِنْ شَرِّ غَاسِقٍ إِذَا وَقَبَ ۝ وَمِنْ شَرِّ النَّفَّاثَاتِ فِي الْعُقَدِ ۝ وَمِنْ شَرِّ حَاسِدٍ إِذَا حَسَدَ"},
  {title:"سورة الناس",type:"قرآن",source:"الناس ١١٤",count:3,text:"قُلْ أَعُوذُ بِرَبِّ النَّاسِ ۝ مَلِكِ النَّاسِ ۝ إِلَٰهِ النَّاسِ ۝ مِنْ شَرِّ الْوَسْوَاسِ الْخَنَّاسِ ۝ الَّذِي يُوَسْوِسُ فِي صُدُورِ النَّاسِ ۝ مِنَ الْجِنَّةِ وَالنَّاسِ"},
  {title:"سيد الاستغفار",type:"سنة",source:"صحيح البخاري",count:1,text:"اللَّهُمَّ أَنْتَ رَبِّي لَا إِلَهَ إِلَّا أَنْتَ، خَلَقْتَنِي وَأَنَا عَبْدُكَ، وَأَنَا عَلَى عَهْدِكَ وَوَعْدِكَ مَا اسْتَطَعْتُ، أَعُوذُ بِكَ مِنْ شَرِّ مَا صَنَعْتُ، أَبُوءُ لَكَ بِنِعْمَتِكَ عَلَيَّ، وَأَبُوءُ لَكَ بِذَنْبِي، فَاغْفِرْ لِي، فَإِنَّهُ لَا يَغْفِرُ الذُّنُوبَ إِلَّا أَنْتَ"},
  {title:"رضيت بالله رباً",type:"سنة",source:"سنن أبي داود والترمذي",count:3,text:"رَضِيتُ بِاللَّهِ رَبًّا، وَبِالْإِسْلَامِ دِينًا، وَبِمُحَمَّدٍ ﷺ نَبِيًّا"},
  {title:"بسم الله الذي لا يضر",type:"سنة",source:"سنن أبي داود والترمذي",count:3,text:"بِسْمِ اللَّهِ الَّذِي لَا يَضُرُّ مَعَ اسْمِهِ شَيْءٌ فِي الْأَرْضِ وَلَا فِي السَّمَاءِ، وَهُوَ السَّمِيعُ الْعَلِيمُ"},
  {title:"التسبيح",type:"سنة",source:"صحيح مسلم",count:100,text:"سُبْحَانَ اللَّهِ وَبِحَمْدِهِ"}
 ]},
 evening:{label:"المساء",sub:"ورد المساء مع النص الكامل وعدد التكرار.",items:[
  {title:"آية الكرسي",type:"قرآن",source:"البقرة ٢:٢٥٥",count:1,text:"اللَّهُ لَا إِلَٰهَ إِلَّا هُوَ الْحَيُّ الْقَيُّومُ ۚ لَا تَأْخُذُهُ سِنَةٌ وَلَا نَوْمٌ ۚ لَهُ مَا فِي السَّمَاوَاتِ وَمَا فِي الْأَرْضِ ۗ مَنْ ذَا الَّذِي يَشْفَعُ عِنْدَهُ إِلَّا بِإِذْنِهِ ۚ يَعْلَمُ مَا بَيْنَ أَيْدِيهِمْ وَمَا خَلْفَهُمْ ۖ وَلَا يُحِيطُونَ بِشَيْءٍ مِنْ عِلْمِهِ إِلَّا بِمَا شَاءَ ۚ وَسِعَ كُرْسِيُّهُ السَّمَاوَاتِ وَالْأَرْضَ ۖ وَلَا يَئُودُهُ حِفْظُهُمَا ۚ وَهُوَ الْعَلِيُّ الْعَظِيمُ"},
  {title:"سورة الإخلاص",type:"قرآن",source:"الإخلاص ١١٢",count:3,text:"قُلْ هُوَ اللَّهُ أَحَدٌ ۝ اللَّهُ الصَّمَدُ ۝ لَمْ يَلِدْ وَلَمْ يُولَدْ ۝ وَلَمْ يَكُنْ لَهُ كُفُوًا أَحَدٌ"},
  {title:"سورة الفلق",type:"قرآن",source:"الفلق ١١٣",count:3,text:"قُلْ أَعُوذُ بِرَبِّ الْفَلَقِ ۝ مِنْ شَرِّ مَا خَلَقَ ۝ وَمِنْ شَرِّ غَاسِقٍ إِذَا وَقَبَ ۝ وَمِنْ شَرِّ النَّفَّاثَاتِ فِي الْعُقَدِ ۝ وَمِنْ شَرِّ حَاسِدٍ إِذَا حَسَدَ"},
  {title:"سورة الناس",type:"قرآن",source:"الناس ١١٤",count:3,text:"قُلْ أَعُوذُ بِرَبِّ النَّاسِ ۝ مَلِكِ النَّاسِ ۝ إِلَٰهِ النَّاسِ ۝ مِنْ شَرِّ الْوَسْوَاسِ الْخَنَّاسِ ۝ الَّذِي يُوَسْوِسُ فِي صُدُورِ النَّاسِ ۝ مِنَ الْجِنَّةِ وَالنَّاسِ"},
  {title:"سيد الاستغفار",type:"سنة",source:"صحيح البخاري",count:1,text:"اللَّهُمَّ أَنْتَ رَبِّي لَا إِلَهَ إِلَّا أَنْتَ، خَلَقْتَنِي وَأَنَا عَبْدُكَ، وَأَنَا عَلَى عَهْدِكَ وَوَعْدِكَ مَا اسْتَطَعْتُ، أَعُوذُ بِكَ مِنْ شَرِّ مَا صَنَعْتُ، أَبُوءُ لَكَ بِنِعْمَتِكَ عَلَيَّ، وَأَبُوءُ لَكَ بِذَنْبِي، فَاغْفِرْ لِي، فَإِنَّهُ لَا يَغْفِرُ الذُّنُوبَ إِلَّا أَنْتَ"},
  {title:"رضيت بالله رباً",type:"سنة",source:"سنن أبي داود والترمذي",count:3,text:"رَضِيتُ بِاللَّهِ رَبًّا، وَبِالْإِسْلَامِ دِينًا، وَبِمُحَمَّدٍ ﷺ نَبِيًّا"},
  {title:"بسم الله الذي لا يضر",type:"سنة",source:"سنن أبي داود والترمذي",count:3,text:"بِسْمِ اللَّهِ الَّذِي لَا يَضُرُّ مَعَ اسْمِهِ شَيْءٌ فِي الْأَرْضِ وَلَا فِي السَّمَاءِ، وَهُوَ السَّمِيعُ الْعَلِيمُ"}
 ]},
 distress:{label:"الكرب",sub:"أدعية وآيات للكرب؛ ما لم يثبت له عدد مخصوص يظهر كقراءة واحدة ويمكن تكراره بلا تقييد.",items:[
  {title:"دعاء يونس عليه السلام",type:"قرآن",source:"الأنبياء ٢١:٨٧",count:1,text:"لَا إِلَٰهَ إِلَّا أَنْتَ سُبْحَانَكَ إِنِّي كُنْتُ مِنَ الظَّالِمِينَ"},
  {title:"حسبنا الله",type:"قرآن",source:"آل عمران ٣:١٧٣",count:1,text:"حَسْبُنَا اللَّهُ وَنِعْمَ الْوَكِيلُ"},
  {title:"دعاء الكرب",type:"سنة",source:"صحيح البخاري ومسلم",count:1,text:"لَا إِلَهَ إِلَّا اللَّهُ الْعَظِيمُ الْحَلِيمُ، لَا إِلَهَ إِلَّا اللَّهُ رَبُّ الْعَرْشِ الْعَظِيمِ، لَا إِلَهَ إِلَّا اللَّهُ رَبُّ السَّمَاوَاتِ وَرَبُّ الْأَرْضِ وَرَبُّ الْعَرْشِ الْكَرِيمِ"}
 ]},
 gratitude:{label:"الشكر",sub:"آيات وأذكار للشكر، مع العدد حيث ثبت.",items:[
  {title:"دعاء الشكر",type:"قرآن",source:"النمل ٢٧:١٩",count:1,text:"رَبِّ أَوْزِعْنِي أَنْ أَشْكُرَ نِعْمَتَكَ الَّتِي أَنْعَمْتَ عَلَيَّ وَعَلَىٰ وَالِدَيَّ وَأَنْ أَعْمَلَ صَالِحًا تَرْضَاهُ وَأَدْخِلْنِي بِرَحْمَتِكَ فِي عِبَادِكَ الصَّالِحِينَ"},
  {title:"وعد الزيادة بالشكر",type:"قرآن",source:"إبراهيم ١٤:٧",count:1,text:"لَئِنْ شَكَرْتُمْ لَأَزِيدَنَّكُمْ"},
  {title:"الحمد لله",type:"ذكر",source:"ذكر مطلق",count:33,text:"الْحَمْدُ لِلَّهِ"}
 ]}
};
function suggested(){const h=new Date().getHours();return h<11?"morning":h>=17?"evening":"gratitude"}
function Card({item,id,done,setDone}){const value=done[id]||0,complete=value>=item.count;const tap=()=>setDone(v=>({...v,[id]:Math.min(item.count,(v[id]||0)+1)}));const reset=()=>setDone(v=>({...v,[id]:0}));return <article style={{marginTop:10,borderRadius:22,border:"1px solid rgba(16,16,15,.065)",background:"rgba(255,255,255,.52)",overflow:"hidden"}}><div style={{padding:"14px 15px 4px",display:"flex",justifyContent:"space-between",gap:10,alignItems:"start"}}><div><div style={{display:"flex",alignItems:"center",gap:7,flexWrap:"wrap"}}><b style={{fontSize:13.5}}>{item.title}</b><span style={{fontSize:8.5,padding:"4px 7px",borderRadius:9,background:item.type==="قرآن"?"rgba(65,111,90,.10)":"rgba(181,154,98,.11)",color:item.type==="قرآن"?C.green:C.gold}}>{item.type}</span></div><div style={{fontSize:9.5,opacity:.4,marginTop:4}}>{item.source}</div></div><div style={{minWidth:58,textAlign:"center",padding:"6px 8px",borderRadius:13,background:C.soft}}><b style={{fontSize:14,color:C.lapis}}>{ar(item.count)}</b><small style={{display:"block",fontSize:8,opacity:.5}}>مرات</small></div></div><div style={{padding:"12px 16px 14px",fontFamily:item.type==="قرآن"?"'Noto Naskh Arabic','Amiri',serif":"inherit",fontSize:item.type==="قرآن"?20:15,lineHeight:item.type==="قرآن"?2.05:2,textAlign:"right"}}>{item.text}</div><div style={{display:"grid",gridTemplateColumns:"1fr auto",gap:7,padding:"0 14px 14px"}}><button onClick={tap} disabled={complete} style={{border:0,borderRadius:14,padding:11,fontFamily:"inherit",fontWeight:700,background:complete?"rgba(65,111,90,.12)":C.lapis,color:complete?C.green:"white"}}>{complete?"اكتمل ✓":`قرأتها · ${ar(value)} / ${ar(item.count)}`}</button><button onClick={reset} aria-label="تصفير العداد" style={{width:42,border:"1px solid rgba(16,16,15,.08)",borderRadius:14,background:"transparent",fontFamily:"inherit",color:C.ink}}>↺</button></div></article>}
export default function SmartAdhkarCenter(){const[ctx,setCtx]=useState(suggested()),[done,setDone]=useState({});const group=GROUPS[ctx];const total=group.items.reduce((s,x)=>s+x.count,0),current=group.items.reduce((s,x,i)=>s+Math.min(done[`${ctx}-${i}`]||0,x.count),0),pct=Math.round(current/total*100);return <div dir="rtl" style={{position:"absolute",inset:0,overflowY:"auto",background:C.ivory,color:C.ink,padding:"28px 16px calc(220px + env(safe-area-inset-bottom,0px))",boxSizing:"border-box"}}><main style={{maxWidth:650,margin:"0 auto"}}><header style={{textAlign:"center"}}><h1 style={{fontSize:28,margin:"6px 0"}}>ذكر مناسب الآن</h1><p style={{fontSize:10.5,opacity:.47,lineHeight:1.8,margin:0}}>نص الذكر كاملاً، مصدره، وعدد مرات قراءته في مكان واحد واضح.</p></header><nav style={{display:"grid",gridTemplateColumns:"repeat(4,1fr)",gap:7,marginTop:18}}>{Object.entries(GROUPS).map(([id,g])=><button key={id} onClick={()=>setCtx(id)} style={{padding:"10px 4px",borderRadius:15,border:ctx===id?`1px solid ${C.gold}`:"1px solid rgba(16,16,15,.08)",background:ctx===id?"rgba(181,154,98,.10)":"rgba(255,255,255,.42)",fontFamily:"inherit",color:C.ink}}>{g.label}</button>)}</nav><section style={{marginTop:13,padding:15,borderRadius:20,background:"rgba(23,59,87,.055)"}}><div style={{display:"flex",justifyContent:"space-between",alignItems:"center",gap:10}}><div><b style={{fontSize:13}}>ورد {group.label}</b><div style={{fontSize:9.5,opacity:.46,marginTop:3}}>{group.sub}</div></div><b style={{fontSize:18,color:C.lapis}}>{ar(pct)}٪</b></div><div style={{height:7,borderRadius:10,background:"rgba(23,59,87,.08)",overflow:"hidden",marginTop:11}}><div style={{height:"100%",width:`${pct}%`,background:C.gold,transition:"width .2s ease"}}/></div><div style={{fontSize:9,opacity:.38,marginTop:6}}>التقدم: {ar(current)} من {ar(total)} قراءة</div></section><section style={{marginTop:12}}>{group.items.map((item,i)=><Card key={`${ctx}-${i}`} item={item} id={`${ctx}-${i}`} done={done} setDone={setDone}/>)}</section><div style={{marginTop:14,padding:12,borderRadius:16,background:"rgba(181,154,98,.08)",fontSize:9.5,lineHeight:1.8,opacity:.65}}>الأعداد المعروضة مخصصة لما ورد له عدد في هذا الدليل. الأدعية التي لا يُقصد تقييدها بعدد يمكن تكرارها بقدر الحاجة، لذلك لا يضيف التطبيق عدداً شرعياً من عنده.</div></main></div>}
