import React,{useEffect,useMemo,useState} from "react";

const C={ivory:"#F6F3EC",ink:"#10100F",lapis:"#173B57",gold:"#B59A62",green:"#4F915C",soft:"#9D9689"};
const profile=()=>{try{return localStorage.getItem("sakinah-active-profile")||"me"}catch{return"me"}};
const read=(k,d)=>{try{const v=localStorage.getItem(k);return v==null?d:JSON.parse(v)}catch{return d}};
const write=(k,v)=>{try{localStorage.setItem(k,JSON.stringify(v))}catch{}};
const key=n=>`sakinah-${n}-${profile()}`;
const btn={border:"1px solid rgba(16,16,15,.09)",borderRadius:14,padding:11,background:"transparent",fontFamily:"inherit",color:"inherit"};
const PRAYERS=[["Fajr","الفجر"],["Dhuhr","الظهر"],["Asr","العصر"],["Maghrib","المغرب"],["Isha","العشاء"]];
function toMin(x){if(!x)return null;const m=String(x).match(/(\d{1,2}):(\d{2})/);return m?Number(m[1])*60+Number(m[2]):null}
function nextPrayer(t){if(!t)return null;const now=new Date(),mins=now.getHours()*60+now.getMinutes();for(const[en,ar]of PRAYERS){const m=toMin(t[en]);if(m!=null&&m>=mins)return{en,ar,time:t[en],mins:m-mins}}return{en:"Fajr",ar:"الفجر",time:t.Fajr,mins:(24*60-mins)+(toMin(t.Fajr)||0)}}
function hijriParts(){try{const f=new Intl.DateTimeFormat("en-u-ca-islamic",{day:"numeric",month:"numeric",year:"numeric"});return Object.fromEntries(f.formatToParts(new Date()).filter(x=>["day","month","year"].includes(x.type)).map(x=>[x.type,Number(x.value)]))}catch{return{}}}
function Progress({value}){return <div style={{height:8,borderRadius:8,background:"rgba(16,16,15,.07)",overflow:"hidden"}}><div style={{height:"100%",width:`${Math.max(0,Math.min(100,value))}%`,background:C.gold}}/></div>}

function Icon({kind,done=false}){
 const base={width:27,height:27,viewBox:"0 0 24 24",fill:"none",stroke:done?C.green:C.soft,strokeWidth:1.45,strokeLinecap:"round",strokeLinejoin:"round",style:{display:"block",overflow:"visible"}};
 const fill={fill:done?C.green:C.soft,opacity:done?.18:.16,stroke:done?C.green:C.soft};
 const alt={fill:done?C.green:C.soft,opacity:done?.12:.10,stroke:done?C.green:C.soft};
 const gold={fill:C.gold,stroke:C.gold,strokeWidth:1.15};
 const cut={fill:"none",stroke:"rgba(246,243,236,.92)",strokeWidth:1.45};
 if(done)return <svg {...base}><circle cx="12" cy="12" r="8.2" style={fill}/><path d="m7.4 12.2 3 3 6.3-6.6"/><path d="M9 19h6" stroke={C.gold}/></svg>;
 if(kind==="friday")return <svg {...base}><path d="M5.2 6.4h13.6v12.2H5.2z" style={fill}/><path d="M8 4.4v3.4M16 4.4v3.4M5.2 9.6h13.6"/><path d="M8.4 13h7.2M8.4 16h4.6" style={cut}/><path d="M16.2 15.6h2" style={gold}/></svg>;
 if(kind==="reflection")return <svg {...base}><circle cx="12" cy="12" r="8.4" style={fill}/><path d="M8.2 13c1.7-2.8 4.6-4 7.5-2.8M9 16c1.7.8 3.4.8 5 .2" style={cut}/><path d="M12 3.2v2M18.2 6.1l-1.4 1.4" stroke={C.gold}/></svg>;
 if(kind==="quran")return <svg {...base}><path d="M3.9 5.8c3.1-.9 5.8-.3 8.1 1.5v11.9c-2.5-1.5-5.2-2-8.1-1.1z" style={fill}/><path d="M20.1 5.8c-3.1-.9-5.8-.3-8.1 1.5v11.9c2.5-1.5 5.2-2 8.1-1.1z" style={alt}/><path d="M12 7.3v11.9"/><path d="m12 9.3 1.05 1.15L12 11.6l-1.05-1.15z" style={gold}/></svg>;
 if(kind==="adhkar")return <svg {...base}><path d="M7 15.1a5 5 0 0 1 10 0z" style={fill}/><path d="M4 16.9h16M8 19.6h8"/><path d="M12 3.7v2.1M5.8 6.6l1.5 1.5M18.2 6.6l-1.5 1.5M3.8 11.1h2.1M18.1 11.1h2.1" stroke={C.gold}/></svg>;
 if(kind==="time")return <svg {...base}><circle cx="12" cy="12" r="8.4" style={fill}/><path d="M12 7.2v5l3.3 2" style={cut}/><circle cx="12" cy="12" r="1" style={gold}/></svg>;
 if(kind==="journal")return <svg {...base}><path d="M5.3 4.5h12.2a1.7 1.7 0 0 1 1.7 1.7v13.3H7.6a2.3 2.3 0 0 1-2.3-2.3z" style={fill}/><path d="M8.6 8.5h6.4M8.6 11.8h5M8.6 15.1h3.6" style={cut}/><path d="m14.5 15.2 1.1 1.1 2.2-2.5" stroke={C.gold}/></svg>;
 if(kind==="travel")return <svg {...base}><path d="M4.8 15.4 19.2 12 4.8 8.6 7 12z" style={fill}/><path d="M7 12h7.3" style={cut}/><circle cx="17.4" cy="6" r="1.45" style={gold}/></svg>;
 if(kind==="bell")return <svg {...base}><path d="M6.5 9.5a5.5 5.5 0 0 1 11 0v4.2l1.7 2.3H4.8l1.7-2.3z" style={fill}/><path d="M9.8 19a2.4 2.4 0 0 0 4.4 0" stroke={C.gold}/></svg>;
 if(kind==="qibla")return <svg {...base}><circle cx="12" cy="12" r="8.6" style={fill}/><path d="m14.9 9.1-1.6 4.2-4.2 1.6 1.6-4.2z" style={cut}/><circle cx="12" cy="12" r="1.05" style={gold}/></svg>;
 if(kind==="mosque")return <svg {...base}><path d="M5 20v-8.2h14V20" style={fill}/><path d="M7.4 11.8V8.7a4.6 4.6 0 0 1 9.2 0v3.1M9.5 20v-4.7h5V20"/><path d="M12 3.1V1.9M10.7 3.3h2.6" stroke={C.gold}/></svg>;
 if(kind==="hisn")return <svg {...base}><path d="M5.3 4.2h10.9a2.1 2.1 0 0 1 2.1 2.1v13.5H7.7a2.4 2.4 0 0 1-2.4-2.4z" style={fill}/><path d="M8.7 8h6.2M8.7 11.3h6.2M8.7 14.6h4.5" style={cut}/><path d="M5.3 17.2c.7-.5 1.6-.8 2.6-.8h10.4" stroke={C.gold}/></svg>;
 if(kind==="ramadan")return <svg {...base}><path d="M15.4 4a8.2 8.2 0 1 0 3.9 14.5A8.9 8.9 0 0 1 15.4 4z" style={fill}/><path d="m17.5 6.1.7 1.3 1.3.7-1.3.7-.7 1.3-.7-1.3-1.3-.7 1.3-.7z" style={gold}/></svg>;
 if(kind==="fasting")return <svg {...base}><path d="M15.8 4.2a7.9 7.9 0 1 0 3.7 13.9 8.6 8.6 0 0 1-3.7-13.9z" style={fill}/><path d="m17.9 6.3.55 1.05 1.1.55-1.1.55-.55 1.05-.55-1.05-1.1-.55 1.1-.55z" style={gold}/></svg>;
 return <svg {...base}><circle cx="12" cy="12" r="8.2" style={fill}/></svg>;
}
function IconBox({kind,done=false}){return <span aria-hidden="true" style={{width:46,height:46,borderRadius:16,border:"1px solid rgba(16,16,15,.055)",display:"grid",placeItems:"center",color:C.soft,background:done?"rgba(79,145,92,.08)":"rgba(255,255,255,.46)",boxShadow:"inset 0 0 0 1px rgba(255,255,255,.42)",flex:"0 0 auto"}}><Icon kind={kind} done={done}/></span>}
function Card({item,go}){return <button onClick={()=>go(item.id)} style={{...btn,minHeight:94,padding:"14px",textAlign:"right",display:"flex",gap:12,alignItems:"center",width:"100%",background:"rgba(255,255,255,.30)"}}><IconBox kind={item.kind}/><span style={{minWidth:0}}><b style={{display:"block",fontSize:12.5,fontWeight:600}}>{item.ar}</b><small style={{display:"block",fontSize:9.5,opacity:.42,marginTop:4,lineHeight:1.65}}>{item.sub}</small></span></button>}

export function SmartMyDay({go}){
 const [timings,setTimings]=useState(()=>{try{return JSON.parse(localStorage.getItem("sakinah-prayer-times")||"null")}catch{return null}}),[locState,setLocState]=useState("idle");
 const dayKey=new Date().toISOString().slice(0,10),doneKey=key(`myday-${dayKey}`),[done,setDone]=useState(()=>read(doneKey,{}));
 const hijri=useMemo(hijriParts,[]),isFriday=new Date().getDay()===5,isRamadan=hijri.month===9,isWhite=[13,14,15].includes(hijri.day);
 const khatmahPage=read(key("khatmah-page"),1),khatmahDays=read(key("khatmah-days"),30),portion=Math.max(1,Math.ceil((604-khatmahPage+1)/Math.max(1,khatmahDays)));
 useEffect(()=>{if(!navigator.geolocation)return;setLocState("loading");navigator.geolocation.getCurrentPosition(async p=>{try{const r=await fetch(`https://api.aladhan.com/v1/timings?latitude=${p.coords.latitude}&longitude=${p.coords.longitude}&method=4`);if(!r.ok)throw 0;const x=await r.json(),t=x.data?.timings||null;setTimings(t);if(t)localStorage.setItem("sakinah-prayer-times",JSON.stringify(t));setLocState("ok")}catch{setLocState("offline")}},()=>setLocState("denied"),{enableHighAccuracy:false,timeout:10000,maximumAge:600000})},[]);
 const next=nextPrayer(timings),hour=new Date().getHours(),dhikr=hour<12?"أذكار الصباح":hour>=17?"أذكار المساء":"ذكر مناسب الآن";
 const items=[...(isFriday?[{id:"jumuah-center",ar:"برنامج الجمعة اليوم",kind:"friday"}]:[]),...(isRamadan?[{id:"ramadan-center",ar:"برنامج رمضان اليوم",kind:"ramadan"}]:[]),...(isWhite?[{id:"fasting-center",ar:"اليوم من الأيام البيض",kind:"fasting"}]:[]),{id:"daily-reflection",ar:"تأمّل اليوم",kind:"reflection"},{id:"smart-khatmah",ar:`ورد القرآن · ${portion} صفحة`,kind:"quran"},{id:"smart-quranic-adhkar",ar:dhikr,kind:"adhkar"},{id:"worship-times",ar:"أوقات العبادة",kind:"time"}];
 const mark=id=>{const x={...done,[id]:!done[id]};setDone(x);write(doneKey,x)},complete=items.filter(x=>done[x.id]).length;
 const date=new Date().toLocaleDateString("ar-IQ",{weekday:"long",day:"numeric",month:"long",year:"numeric"});
 const services=[{id:"prayer-journal",ar:"سجل الصلاة",sub:"متابعة أسبوعية للصلاة",kind:"journal"},{id:"alerts",ar:"السفر والتنبيهات",sub:"تحديث الموقع وتنبيه قبل الصلاة",kind:"travel"},{id:"alerts",ar:"المؤذن والتنبيهات",sub:"الأذان والجدولة والفحص",kind:"bell"},{id:"qibla",ar:"القبلة",sub:"اتجاه الكعبة بالشمال الحقيقي",kind:"qibla"},{id:"mosques",ar:"أقرب مسجد",sub:"المساجد القريبة منك",kind:"mosque"},{id:"hisn-center",ar:"حصن المسلم",sub:"أذكار اليوم والليلة",kind:"hisn"}];
 return <div data-smart-my-day="true" dir="rtl" style={{position:"absolute",inset:0,background:C.ivory,color:C.ink,overflowY:"auto"}}><main style={{maxWidth:720,margin:"0 auto",padding:"70px 22px 135px"}}><div style={{textAlign:"center"}}><div style={{fontSize:10,color:C.gold,letterSpacing:.8}}>MUSLIM MIRROR</div><h1 style={{fontSize:30,margin:"4px 0"}}>يومي الإسلامي</h1><div style={{fontSize:11.5,opacity:.48}}>{date}</div></div>
 <section style={{marginTop:18,borderRadius:26,padding:19,background:"linear-gradient(135deg,rgba(181,154,98,.18),rgba(255,255,255,.58))",border:"1px solid rgba(181,154,98,.14)"}}><div style={{display:"flex",justifyContent:"space-between",alignItems:"center",gap:14,minWidth:0}}><div style={{minWidth:0,flex:"1 1 auto"}}><small style={{opacity:.45}}>الصلاة القادمة</small><div style={{fontSize:26,marginTop:5}}>{next?next.ar:"تحديد الموقع…"}</div>{next&&<div style={{fontSize:11,opacity:.55,marginTop:4}}>{next.time} · {next.mins} دقيقة</div>}</div><button onClick={()=>go("alerts")} style={{...btn,flex:"0 0 auto",minWidth:86,height:38,padding:"0 14px",borderRadius:999,display:"inline-flex",alignItems:"center",justifyContent:"center",whiteSpace:"nowrap",lineHeight:1,fontSize:10.5,background:"rgba(255,255,255,.38)"}}>التنبيهات</button></div><div style={{fontSize:9.5,opacity:.38,marginTop:10}}>{locState==="offline"?"يتم استخدام آخر مواقيت محفوظة":locState==="denied"?"إذن الموقع غير مفعّل":"GPS"}</div></section>
 <div style={{marginTop:12,display:"grid",gridTemplateColumns:"repeat(3,1fr)",gap:8}}><div style={{...btn}}><small style={{opacity:.42}}>ورد اليوم</small><b style={{display:"block",fontSize:18,marginTop:5}}>{portion}</b></div><div style={{...btn}}><small style={{opacity:.42}}>إنجاز اليوم</small><b style={{display:"block",fontSize:18,marginTop:5}}>{complete}/{items.length}</b></div><button onClick={()=>go("prayer-journal")} style={{...btn,textAlign:"right"}}><small style={{opacity:.42}}>سجل الصلاة</small><b style={{display:"block",fontSize:14,marginTop:6}}>افتح السجل ›</b></button></div>
 <div style={{marginTop:16}}><Progress value={items.length?complete/items.length*100:0}/></div><div style={{marginTop:10}}>{items.map(item=><div key={item.id} style={{display:"grid",gridTemplateColumns:"52px minmax(0,1fr) 18px",gap:10,alignItems:"center",padding:"10px 0",borderTop:"1px solid rgba(16,16,15,.07)"}}><button aria-label={`تحديد ${item.ar}`} onClick={()=>mark(item.id)} style={{width:46,height:46,padding:0,border:0,background:"transparent",fontFamily:"inherit",display:"grid",placeItems:"center"}}><IconBox kind={item.kind} done={!!done[item.id]}/></button><button onClick={()=>go(item.id)} style={{border:0,background:"transparent",fontFamily:"inherit",textAlign:"right",color:"inherit",fontSize:13,fontWeight:600,minWidth:0}}>{item.ar}</button><span aria-hidden="true" style={{opacity:.22,fontSize:16}}>‹</span></div>)}</div>
 <h2 style={{fontSize:16,margin:"22px 0 10px"}}>أدوات يومية ذكية</h2><div style={{display:"grid",gridTemplateColumns:"repeat(2,minmax(0,1fr))",gap:8}}>{services.map((x,i)=><Card key={`${x.id}-${i}`} item={x} go={go}/>)}</div><button onClick={()=>go("daily-tools")} style={{...btn,width:"100%",marginTop:10}}>كل الأدوات اليومية ›</button></main></div>
}
