import React,{useEffect,useMemo,useState} from "react";

const C={ivory:"#F6F3EC",ink:"#10100F",lapis:"#173B57",gold:"#B59A62",green:"#4F915C",red:"#A44D3C"};
const btn={border:"1px solid rgba(16,16,15,.09)",borderRadius:15,padding:11,background:"rgba(255,255,255,.52)",fontFamily:"inherit",color:"inherit"};
function Shell({lang,go,titleAr,titleEn,subAr,subEn,children}){return <div style={{position:"absolute",inset:0,background:C.ivory,color:C.ink,display:"flex",flexDirection:"column"}} dir={lang==="ar"?"rtl":"ltr"}><div style={{padding:"22px 22px 0"}}><button onClick={()=>go("discover")} style={{...btn,border:0,padding:0,background:"transparent"}}>{lang==="ar"?"رجوع ←":"← Back"}</button></div><div style={{flex:1,overflowY:"auto",padding:"14px 22px 130px"}}><div style={{fontFamily:"Fraunces,serif",fontSize:30}}>{lang==="ar"?titleAr:titleEn}</div><div style={{fontSize:11.5,opacity:.48,lineHeight:1.8,marginTop:7}}>{lang==="ar"?subAr:subEn}</div>{children}</div></div>}
const rad=x=>x*Math.PI/180,deg=x=>x*180/Math.PI;
function qiblaBearing(lat,lon){const kaabaLat=rad(21.4225),kaabaLon=rad(39.8262),p=rad(lat),l=rad(lon),d=kaabaLon-l;return (deg(Math.atan2(Math.sin(d),Math.cos(p)*Math.tan(kaabaLat)-Math.sin(p)*Math.cos(d)))+360)%360}
function haversine(a,b,c,d){const R=6371,dp=rad(c-a),dl=rad(d-b),x=Math.sin(dp/2)**2+Math.cos(rad(a))*Math.cos(rad(c))*Math.sin(dl/2)**2;return 2*R*Math.asin(Math.sqrt(x))}

export function QiblaCompass({lang,go}){
 const [loc,setLoc]=useState(null),[heading,setHeading]=useState(null),[status,setStatus]=useState("");
 const bearing=loc?qiblaBearing(loc.lat,loc.lon):null;
 const rotation=bearing==null?0:heading==null?bearing:(bearing-heading+360)%360;
 const requestLocation=()=>{setStatus(lang==="ar"?"جاري تحديد موقعك…":"Locating…");navigator.geolocation?.getCurrentPosition(p=>{setLoc({lat:p.coords.latitude,lon:p.coords.longitude});setStatus("")},()=>setStatus(lang==="ar"?"تعذر الوصول إلى الموقع. فعّل GPS واسمح للموقع.":"Location unavailable. Enable GPS and allow access."),{enableHighAccuracy:true,timeout:12000})};
 const enableCompass=async()=>{try{if(typeof DeviceOrientationEvent!=="undefined"&&typeof DeviceOrientationEvent.requestPermission==="function"){const ok=await DeviceOrientationEvent.requestPermission();if(ok!=="granted")return}const on=e=>{const h=typeof e.webkitCompassHeading==="number"?e.webkitCompassHeading:(typeof e.alpha==="number"?(360-e.alpha)%360:null);if(h!=null)setHeading(h)};window.addEventListener("deviceorientationabsolute",on,true);window.addEventListener("deviceorientation",on,true);setStatus(lang==="ar"?"تم تفعيل مستشعر الاتجاه.":"Compass enabled.")}catch{setStatus(lang==="ar"?"تعذر تشغيل مستشعر البوصلة على هذا الجهاز.":"Compass sensor is unavailable on this device.")}};
 useEffect(()=>{requestLocation()},[]);
 return <Shell lang={lang} go={go} titleAr="القبلة" titleEn="Qibla Compass" subAr="اتجاه القبلة بالحساب الجغرافي مع دعم مستشعر البوصلة عند توفره" subEn="Qibla bearing from your location with live compass support when available"><div style={{marginTop:22,display:"grid",placeItems:"center"}}><div style={{width:250,height:250,borderRadius:"50%",border:"1px solid rgba(23,59,87,.16)",background:"radial-gradient(circle,#fff 0,#F6F3EC 70%)",position:"relative",boxShadow:"0 18px 50px rgba(23,59,87,.08)"}}><div style={{position:"absolute",inset:18,borderRadius:"50%",border:"1px dashed rgba(181,154,98,.4)"}}/><div style={{position:"absolute",top:13,left:"50%",transform:"translateX(-50%)",fontSize:10,opacity:.45}}>N</div><div style={{position:"absolute",left:"50%",top:"50%",width:5,height:92,borderRadius:6,background:`linear-gradient(${C.gold},${C.lapis})`,transformOrigin:"50% 100%",transform:`translate(-50%,-100%) rotate(${rotation}deg)`,transition:"transform .25s ease"}}/><div style={{position:"absolute",left:"50%",top:"50%",width:18,height:18,borderRadius:"50%",background:C.lapis,transform:"translate(-50%,-50%)",border:"4px solid #fff"}}/></div></div><div style={{marginTop:18,display:"grid",gridTemplateColumns:"1fr 1fr",gap:9}}><div style={{...btn,textAlign:"center"}}><small style={{opacity:.45}}>{lang==="ar"?"اتجاه القبلة":"Qibla bearing"}</small><div style={{fontSize:24,fontWeight:700,marginTop:5}}>{bearing==null?"—":`${bearing.toFixed(1)}°`}</div></div><div style={{...btn,textAlign:"center"}}><small style={{opacity:.45}}>{lang==="ar"?"اتجاه الجهاز":"Device heading"}</small><div style={{fontSize:24,fontWeight:700,marginTop:5}}>{heading==null?"—":`${heading.toFixed(1)}°`}</div></div></div><div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:8,marginTop:10}}><button onClick={requestLocation} style={{...btn,background:C.lapis,color:"white",border:0}}>{lang==="ar"?"تحديث الموقع":"Refresh location"}</button><button onClick={enableCompass} style={btn}>{lang==="ar"?"تشغيل البوصلة":"Enable compass"}</button></div>{status&&<div style={{marginTop:10,fontSize:10.5,opacity:.55}}>{status}</div>}</Shell>}

export function NearbyMosques({lang,go}){
 const [rows,setRows]=useState([]),[busy,setBusy]=useState(false),[status,setStatus]=useState("");
 const load=()=>{setBusy(true);setStatus(lang==="ar"?"جاري البحث عن المساجد القريبة…":"Searching nearby mosques…");navigator.geolocation?.getCurrentPosition(async p=>{const lat=p.coords.latitude,lon=p.coords.longitude;try{const q=`[out:json][timeout:20];(nwr(around:5000,${lat},${lon})[amenity=place_of_worship][religion=muslim];nwr(around:5000,${lat},${lon})[building=mosque];);out center tags;`;const r=await fetch("https://overpass-api.de/api/interpreter",{method:"POST",headers:{"Content-Type":"application/x-www-form-urlencoded;charset=UTF-8"},body:`data=${encodeURIComponent(q)}`});if(!r.ok)throw new Error();const j=await r.json();const data=(j.elements||[]).map(x=>{const a=x.lat??x.center?.lat,b=x.lon??x.center?.lon;return {id:x.id,name:x.tags?.name||x.tags?.["name:ar"]||x.tags?.["name:en"]||(lang==="ar"?"مسجد":"Mosque"),lat:a,lon:b,dist:a!=null?haversine(lat,lon,a,b):999}}).filter(x=>x.lat!=null).sort((a,b)=>a.dist-b.dist).slice(0,20);setRows(data);setStatus(data.length?"":(lang==="ar"?"لم تظهر نتائج ضمن 5 كم.":"No results found within 5 km."))}catch{setStatus(lang==="ar"?"تعذر تحميل المساجد الآن. حاول لاحقاً.":"Could not load nearby mosques right now.")}finally{setBusy(false)}},()=>{setBusy(false);setStatus(lang==="ar"?"فعّل الموقع واسمح للتطبيق بالوصول إليه.":"Enable location and allow access.")},{enableHighAccuracy:true,timeout:12000})};
 useEffect(()=>{load()},[]);
 return <Shell lang={lang} go={go} titleAr="أقرب مسجد" titleEn="Nearby Mosques" subAr="بحث جغرافي عن المساجد القريبة وترتيبها حسب المسافة" subEn="Find nearby mosques and sort them by distance"><button onClick={load} disabled={busy} style={{...btn,width:"100%",marginTop:18,background:C.lapis,color:"white",border:0}}>{busy?(lang==="ar"?"بحث…":"Searching…"):(lang==="ar"?"تحديث البحث":"Refresh search")}</button>{status&&<div style={{marginTop:10,fontSize:10.5,opacity:.55}}>{status}</div>}<div style={{marginTop:14}}>{rows.map((x,i)=><div key={`${x.id}-${i}`} style={{padding:"14px 0",borderTop:"1px solid rgba(16,16,15,.07)",display:"grid",gridTemplateColumns:"1fr auto",gap:12,alignItems:"center"}}><div><div style={{fontSize:13,fontWeight:700}}>{x.name}</div><div style={{fontSize:10,opacity:.45,marginTop:4}}>{x.dist<1?`${Math.round(x.dist*1000)} m`:`${x.dist.toFixed(2)} km`}</div></div><a href={`https://www.google.com/maps/search/?api=1&query=${x.lat},${x.lon}`} target="_blank" rel="noreferrer" style={{...btn,textDecoration:"none",padding:"8px 10px",fontSize:10}}>{lang==="ar"?"الخريطة":"Map"}</a></div>)}</div></Shell>}

export function ZakatCenter({lang,go}){
 const [assets,setAssets]=useState({cash:"",gold:"",silver:"",trade:"",receivables:"",debts:"",nisab:""});const [fitr,setFitr]=useState({people:"1",perPerson:""});
 const num=k=>Number(assets[k])||0,total=num("cash")+num("gold")+num("silver")+num("trade")+num("receivables")-num("debts"),nisab=num("nisab"),due=nisab>0&&total>=nisab?total*.025:0,fitrDue=(Number(fitr.people)||0)*(Number(fitr.perPerson)||0);
 const fields=[["cash","النقد والحسابات","Cash & bank"],["gold","قيمة الذهب الزكوي","Zakatable gold value"],["silver","قيمة الفضة الزكوية","Zakatable silver value"],["trade","عروض التجارة","Trade inventory"],["receivables","ديون مرجوة السداد","Expected receivables"],["debts","التزامات حالّة تُخصم","Immediate liabilities"],["nisab","قيمة النصاب بعملتك","Nisab value in your currency"]];
 return <Shell lang={lang} go={go} titleAr="ميزان الزكاة" titleEn="Zakat Calculator" subAr="حساب مساعد للزكاة المالية وزكاة الفطر. أدخل قيمة النصاب ومقدار الفطرة المعتمدين محلياً بعملتك." subEn="A helper for wealth zakat and Zakat al-Fitr. Enter the locally applicable nisab and per-person fitr amount in your currency."><div style={{marginTop:18,display:"grid",gap:8}}>{fields.map(([k,ar,en])=><label key={k} style={{display:"grid",gridTemplateColumns:"1fr 120px",gap:8,alignItems:"center",fontSize:11.5}}><span>{lang==="ar"?ar:en}</span><input inputMode="decimal" value={assets[k]} onChange={e=>setAssets(v=>({...v,[k]:e.target.value}))} style={{...btn,minWidth:0,textAlign:"center"}}/></label>)}</div><div style={{marginTop:16,padding:18,borderRadius:22,background:"linear-gradient(145deg,#173B57,#0C293E)",color:"white"}}><div style={{fontSize:10,opacity:.65}}>{lang==="ar"?"صافي المال الزكوي":"Net zakatable wealth"}</div><div style={{fontSize:28,fontWeight:700,marginTop:5}}>{total.toLocaleString()}</div><div style={{height:1,background:"rgba(255,255,255,.14)",margin:"14px 0"}}/><div style={{fontSize:10,opacity:.65}}>{lang==="ar"?"الزكاة التقديرية 2.5% عند بلوغ النصاب":"Estimated zakat at 2.5% when nisab is reached"}</div><div style={{fontSize:28,fontWeight:700,color:"#E7D29B",marginTop:5}}>{due.toLocaleString(undefined,{maximumFractionDigits:2})}</div></div><div style={{marginTop:18,fontSize:15,fontWeight:700}}>{lang==="ar"?"زكاة الفطر":"Zakat al-Fitr"}</div><div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:8,marginTop:9}}><input inputMode="numeric" value={fitr.people} onChange={e=>setFitr(v=>({...v,people:e.target.value}))} placeholder={lang==="ar"?"عدد الأشخاص":"People"} style={btn}/><input inputMode="decimal" value={fitr.perPerson} onChange={e=>setFitr(v=>({...v,perPerson:e.target.value}))} placeholder={lang==="ar"?"المبلغ للشخص":"Amount/person"} style={btn}/></div><div style={{...btn,marginTop:8,textAlign:"center",fontSize:18,fontWeight:700}}>{fitrDue.toLocaleString(undefined,{maximumFractionDigits:2})}</div><div style={{fontSize:9.5,opacity:.45,lineHeight:1.7,marginTop:10}}>{lang==="ar"?"هذه أداة حساب وليست فتوى. مسائل الديون والنصاب ونوع المال ومقدار زكاة الفطر قد تختلف باختلاف الحالة والبلد؛ راجع جهة شرعية موثوقة عند الشك.":"This is a calculation aid, not a fatwa. Debt treatment, nisab, asset rules and fitr amounts can vary by situation and locality; consult a trusted authority when uncertain."}</div></Shell>}

export function ManasikCenter({lang,go}){
 const [tab,setTab]=useState("umrah");
 const umrah=["الإحرام والنية والتلبية من الميقات","الطواف حول الكعبة سبعة أشواط","الصلاة بعد الطواف عند التيسّر","السعي بين الصفا والمروة سبعة أشواط","الحلق أو التقصير والتحلل"];
 const hajj=["الاستعداد والإحرام بحسب نوع النسك","يوم التروية: التوجه إلى منى","يوم عرفة: الوقوف بعرفة","بعد الغروب: التوجه إلى مزدلفة","يوم النحر: رمي جمرة العقبة ثم أعمال يوم النحر بحسب النسك","طواف الإفاضة والسعي عند وجوبه","أيام التشريق: المبيت والرمي وفق الترتيب والتعليمات","طواف الوداع عند وجوبه قبل مغادرة مكة"];
 const rows=tab==="umrah"?umrah:hajj;
 return <Shell lang={lang} go={go} titleAr="مناسك الحج والعمرة" titleEn="Hajj & Umrah" subAr="مسار إرشادي مرتب للمناسك مع تذكير باتباع تعليمات الجهات الرسمية والسؤال عن التفاصيل الفقهية الخاصة بحالتك" subEn="An ordered rites guide with reminders to follow official instructions and ask about case-specific jurisprudential details"><div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:8,marginTop:18}}><button onClick={()=>setTab("umrah")} style={{...btn,background:tab==="umrah"?C.lapis:"rgba(255,255,255,.52)",color:tab==="umrah"?"white":C.ink}}>{lang==="ar"?"العمرة":"Umrah"}</button><button onClick={()=>setTab("hajj")} style={{...btn,background:tab==="hajj"?C.lapis:"rgba(255,255,255,.52)",color:tab==="hajj"?"white":C.ink}}>{lang==="ar"?"الحج":"Hajj"}</button></div><div style={{marginTop:14}}>{rows.map((x,i)=><div key={x} style={{display:"grid",gridTemplateColumns:"42px 1fr",gap:11,alignItems:"start",padding:"15px 0",borderTop:"1px solid rgba(16,16,15,.07)"}}><div style={{width:36,height:36,borderRadius:13,display:"grid",placeItems:"center",background:"rgba(181,154,98,.13)",color:C.lapis,fontWeight:800}}>{i+1}</div><div style={{fontSize:12.5,lineHeight:1.8}}>{lang==="ar"?x:(tab==="umrah"?["Ihram, intention and Talbiyah from the miqat","Seven circuits of Tawaf around the Kaaba","Prayer after Tawaf when feasible","Seven laps of Sa'i between Safa and Marwah","Shaving or trimming the hair and exiting Ihram"]:["Prepare and enter Ihram according to your Hajj type","Day of Tarwiyah: proceed to Mina","Day of Arafah: stand at Arafat","After sunset: proceed to Muzdalifah","Day of Sacrifice: stone Jamrat al-Aqabah, then complete the day's rites according to your Hajj type","Tawaf al-Ifadah and Sa'i when applicable","Days of Tashreeq: stay and stone according to the prescribed order and official instructions","Farewell Tawaf when required before leaving Makkah"])[i]}</div></div>)}</div><div style={{marginTop:14,padding:14,borderRadius:18,background:"rgba(181,154,98,.08)",fontSize:10.5,lineHeight:1.8}}>{lang==="ar"?"المحتوى هنا ملخص إرشادي. في التطبيق النهائي تُربط الأدلة الرسمية المحدثة من وزارة الحج والعمرة/نسك، لأن تفاصيل الحج تختلف بحسب نوع النسك والحالة.":"This is a concise guide. The production app should link the latest official Ministry of Hajj and Umrah/Nusuk guidance because details vary by Hajj type and individual circumstances."}</div></Shell>}
